if (! document.localization) document.localization = [];

document.localization ['ar_AE'] = {
	"login.username": 'اسم المستخدم أو البريد الإلكترون',
    "login.username.placeholder":'أدخل اسم المستخدم أو البريد الإلكتروني',
    'login.password': 'كلمة المرور:',
    "login.password.placeholder": 'أدخل كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.password.incorrect': 'اسم المستخدم أو كلمة المرور غير صالحة',

    'header.label.username': 'اسم المستخدم',

    "devices.group.options.all": 'كل المجموعات',
    'devices.configuration.options.all': 'جميع الاعدادات',
    'devices.permissions.all': 'يتم منح جميع الأذونات',
    'devices.permissions.not.as.device.admin': '- التطبيق غير مثبت كمسؤول الجهاز',
    'devices.permissions.window.overlap.prohibited': '- لا يتوفرخاصية الضهورر أعلى النوافذ الأخرى',
    'devices.permissions.history.access.prohibited': '- لم يتم اعداد الوصول إلى محفوظات الاستخدام',
    'devices.unknown': 'مجهول',
    'devices.model.unknown': 'مجهول',
    "devices.date.unknown": 'غير معروف',
    'devices.date.format': 'dd/MM HH:mm',
    'devices.app.installed': '.تم التثبيت :${applicationName}-',
    'devices.app.not.installed': '.غير مثبت :${applicationName}-',
    'devices.app.version.available': 'متاح ,${applicationVersion}',
    'devices.app.installed.and.version.available': '${applicationVersionAvailable} متوفر ,${applicationInstalledVersion}-تم تثبيت :${applicationName}',
    'devices.app.needs.removal': 'الإزالة مطلوبة ,${applicationVersion}',
    "devices.no.data": 'الجهاز لم يرسل البيانات',
    'devices.settings.conformance.broken': '(${serverData}): عدم تطابق مع الإعدادات',
    'devices.file.installed': 'تثبيت :${file}-',
    'devices.file.not.installed': 'غير مثبت :${file}-',
    'devices.file.lastUpdate.differs': 'min ${diff} الاختلاف في وقت التعديل :${file}-',

    "button.apply": 'تطبيق',
    "button.gps.on": 'GPS تفعيل',
    "button.wifi.on": 'Wi-Fi تفعيل',
    "button.notify.update": 'إعلام عند التحديث',
    "button.app.settings": 'إعدادات التطبيق',
    "button.ok": 'موافق',
    "button.help": 'مساعدة',
    "button.new.app": 'تطبيق جديد',
    "button.new.app.version": 'إصدار جديد',
    "button.upgrade": 'ترقية',
    "button.renew.config": 'تحديث على الأجهزة',
    "button.common": 'تطبيق مشترك',
    "button.close": 'إغلاق',
    "button.yes": 'نعم',
    "button.cancel": 'إلغاء',
    "button.save": 'حفظ',
    "button.save.and.close": 'حفظ وإغلاق',
	'button.more': '... المزيد',
    "button.cleanup": 'مسح',
    "button.add": 'إضافة',
    "button.add.icon": 'أيقونة جديدة',
    "button.search": 'بحث',
    "button.export": 'تصدير',
    "button.change": 'تعديل',
    'button.copy': 'نسخ',
    "button.qrcode": 'QR رمز',
    "button.application": 'تطبيق',
    "button.change.password": 'تغيير كلمة المرور',
    "button.set.configuration": 'ضبط الاعدادات',
    'button.group.action': 'عمل جماعي',
    "button.delete": 'حذف',
    'button.login': 'تسجيل الدخول',
    "button.renew.code": 'تجديد',
    "button.configurations": 'الاعدادات',
    'button.set.configurations': 'تحديد الاعدادات' ,
    "button.edit.versions": 'إصدارات',
    'button.edit': 'تعديل' ,
    "button.change.common.app": 'تعديل التطبيق المشترك',
    "button.delete.common.app": 'حذف التطبيق المشترك',
    "button.turn.common.app": 'جعله مشتركًا',
    "button.hints.enable": 'إظهار تلميحات الأدوات',
    "button.hints.disable": 'إخفاء تلميحات الأدوات',
    'button.show.password': 'عرض كلمة المرور',
    'button.hide.password': 'اخفاء كلمة المرور',

    'question.impersonate.user': '؟ "${customerName}" قم بتسجيل الدخول إلى التطبيق كمسؤول عن المؤسسة',
    'question.change.user': '؟ "${customerName}" قم بتسجيل الدخول إلى التطبيق باسم المستخدم',
    'question.delete.file': '؟ "${fileName}" حذف الملف',
    'question.delete.customer': '؟ "${customerName}" هل تريد حذف المؤسسة',
    'question.delete.user': '؟ "${username}" حذف المستخدم',
    'question.delete.application': '؟ "${applicationName}" هل تريد حذف التطبيق',
    'question.delete.application.version': '؟ "${applicationVersion}" حذف الإصدار',
    'question.delete.configuration': '؟؟ "${configurationName}" حذف الاعداد',
    'question.delete.group': '؟ "${groupName}" هل تريد حذف المجموعة',
    'question.delete.device': '؟ "${deviceNumber}" هل تريد حذف الجهاز الذي يحمل الرقم',
    'question.exit.without.saving': 'لا يتم حفظ التغييرات. على أي حال مغادرة هذه الصفحة؟ ',
    'question.turn2common.application': '؟ "${applicationName}" مشاركة التطبيق',
    'question.app.upgrade': '؟ "${v2}" إلى أحدث إصدار للتهيئة "${v1}" هل تريد تحديث التطبيق ',

    'error.application.setting.empty.app': 'حدد التطبيق',
    'error.application.setting.empty.name': 'أدخل اسمًا' ,
    'error.application.setting.empty.value': 'حدد قيمة',

    'error.icon.dimension.invalid': 'يجب أن يكون الرمز مربعًا' ,
    'error.icon.empty.name': 'أدخل اسم الأيقونة' ,
    'error.icon.empty.file': 'تحميل أيقونة الملف',
    'error.application.version.pkg.mismatch': '(${expected}) لا يتوافق مع التطبيق (${actual}) ID حزمة الملف',
    'error.empty.user': 'حدد مستخدم' ,
	'error.empty.user.name': 'أدخل اسم المستخدم' ,
    'error.empty.user.login': 'املأ تسجيل دخول المستخدم', 
    'error.empty.user.role': 'حدد دور المستخدم',
    "error.empty.password": 'أدخل كلمة مرور جديدة',
    "error.empty.password.confirm": 'أدخل تأكيد كلمة المرور',
    'error.empty.group.name': 'املأ اسم المجموعة',
    'error.empty.configuration': 'حدد الاعداد' ,
    'error.empty.configuration.name': 'املأ اسم اللاعداد',
    'error.empty.configuration.password': 'أدخل كلمة المرور',
    "error.empty.configuration.contentApp": 'لم يتم تحديد تطبيق محتوى',
    'error.invalid.configuration.mainApp': 'MDM يتم استخدام التطبيق الرئيسي الخاطئ في إعدادات' ,
    "error.invalid.configuration.contentApp": 'MDM تطبيق محتوى غير صالح مستخدم في إعدادات',
    'error.mismatch.password': 'يجب أن تتطابق كلمة المرور وتأكيد كلمة المرور' ,
    "error.empty.customer.name": 'املأ اسم المؤسسة',
    'error.empty.customer.prefix': 'املأ بادئة رقم الجهاز',
    "error.empty.customer.device.configuration": 'حدد اعداد الجهاز',
    "error.empty.customer.duplicate.prefix": 'البادئة قيد الاستخدام بالفعل',
    'error.duplicate.customer.name': 'المؤسسة التي تحمل الاسم المدخل موجودة بالفعل. جرب اسما مختلفا. ',
    'error.duplicate.group.name': 'المجموعة ذات الاسم المدخل موجودة بالفعل. جرب اسما مختلفا. ',
    'error.duplicate.configuration.name': 'الاعداد بالاسم المدخل موجود بالفعل. جرب اسما مختلفا. ',
    'error.duplicate.device.number': 'يوجد بالفعل جهاز بهذا الرقم',
    "error.internal.server": 'خطأ داخلي في الخادم',
    "error.permission.denied": 'لا توجد حقوق للتنفيذ',
    'error.request.failure': 'فشل الطلب',
    'error.configuration.device.use': 'لا يمكن حذف هذا الاعداد , يتم استخدامه على الأجهزة. انتقل أولاً إلى "الأجهزة, وابحث عن الأجهزة التي تستخدم هذا الاعداد وغيّر إعداداتها. ',
    'error.invalid.system.update.time': 'الفاصل الزمني للتثبيت غير صالح',

    'error.configuration.file.empty.name': 'أدخل اسم ملف' ,
    'error.configuration.file.empty.desc': 'حدد وصف الملف' ,
    'error.configuration.file.empty.path': 'حدد المسار على الجهاز',
    'error.configuration.file.empty.file': 'أو قم بتحميل ملف URL أدخل عنوان',
    
    'error.notfound.device': 'الجهاز غير موجود',
    'error.duplicate.device': 'جهاز بنفس الرقم موجود بالفعل',
    'error.duplicate.login': 'مثل هذا تسجيل الدخول قيد الاستخدام بالفعل' ,
    'error.duplicate.group': 'توجد بالفعل مجموعة بنفس الاسم' ,
    'error.duplicate.application': 'الحزمة هذا والإصدار ID يوجد بالفعل تطبيق يحمل' ,
    'error.recent.application.version.exists': 'يوجد أحدث إصدار للتطبيق' ,
    "error.common.application.access.prohibited": 'فقط Super-Administrator يُسمح بإدارة التطبيقات الشائعة بواسطة',
    'error.application.config.reference.exists': 'التطبيق مستخدم في الاعدادات ولا يمكن حذفه',
    'error.application.version.deletion.prohibited': 'الإصدار إما فريد أو مستخدم في الاعدادات ولا يمكن حذفه' ,
    'error.duplicate.file': 'ملف بنفس الاسم موجود بالفعل' ,
    'error.used.file': 'هذا الملف مستخدم',
    'error.version.exists': 'الإصدار نفسه من هذا التطبيق موجود بالفعل' ,
    'error.duplicate.configuration': 'يوجد اعداد بهذا الاسم بالفعل' ,
    'error.notfound.customer.admin': 'حساب المسؤول غير موجود' ,
    'error.apk.file.required': '.apk أو .xapk حدد الملف بملحق' ,
    'error.apk.parse': 'حدث خطأ أثناء تحليل الملف',
    'error.empty.app.name': 'أدخل اسم التطبيق' ,
    "error.empty.app.pkg": 'أدخل معرف الحزمة',
    "error.empty.app.url": 'أدخل عنوان URL',
    "error.empty.app.iconText": 'أدخل نص الرمز',
    'error.empty.app.version': 'أدخل إصدار التطبيق' ,
	'error.notempty.group': 'تتضمن هذه المجموعة جهاز واحد أو أكثر. لا يمكنك إزالته. ',
    'error.file.empty':' تحميل ملف جديد ',
    'error.file.deletion': 'خطأ في حذف الملف على الخادم' ,
    'error.file.save': 'خطأ أثناء حفظ الملف على الخادم',
    'error.password.wrong': 'كلمة مرور غير صالحة',
    "error.password.empty": 'كلمة المرور غير محددة',
    'error.params.missing': 'معلمات مفقودة:',
    "error.empty.push.options": 'الرجاء تحديد خيارات التنبيهات الفورية',

    "table.filtering.check.all": 'تحديد الكل',
    "table.filtering.uncheck.all": 'إلغاء الكل',
    'table.filtering.suffix.configuration': 'الاعدادات',
    "table.filtering.suffix.group": 'مجموعات',
    "table.filtering.no.selected.configuration": 'لم يتم تحديد أي اعدادات',
    "table.filtering.no.selected.group": 'لا توجد مجموعات محددة',

    'Success.admin.created': 'إنشاء حساب المسؤول:\n ${adminCredentials}',
    'Success.uploading.file': '... يتم رفع الملف إلى الخادم',
    'Success.loading.devices': '... جارٍ تحميل قائمة الأجهزة',
    "Success.loading.customer": '... جارٍ تحميل تفاصيل العميل',
    'Success.file.uploaded': 'تم رفع الملف بنجاح.',
    'Success.file.uploaded.need.save': 'تم رفع الملف بنجاح. أدخل المسار ذي الصلة وانقر على "حفظ',
    "Success.settings.design.saved": 'تم حفظ إعدادات التصميم بنجاح',
    "Success.settings.common.saved": 'تم حفظ إعدادات جدول الجهاز بنجاح',
    "Success.settings.saved": 'تم حفظ الإعدادات بنجاح',
    "Success.settings.apiKey.saved": 'بنجاح API تم حفظ مفتاح',
    "Success.settings.hints.enabled": 'تم تفعيل التلميحات',
    "Success.settings.hints.disabled": 'تم تعطيل التلميحات',
    'Success.configuration.saved': 'تم حفظ الاعداد بنجاح' ,
    "Success.operation.completed": 'اكتملت العملية بنجاح',
    "Success.plugins.disabled": 'تم حفظ الإعدادات بنجاح',
    'Success.config.update.notification': 'تم إرسال أمر تحديث الاعداد إلى الأجهزة' ,
    'Success.config.update.device.app.settings.notification': 'تم إرسال أمر تحديث إعدادات التطبيق إلى الجهاز.',

    'form.icon.title': 'أيقونة',
    "form.icon.name": 'الاسم',
    'form.icon.file': 'ملف',

    'configuration.add.warning': 'هل أنت متأكد أنك تريد إنشاء تكوين فارغ؟ ستحتاج إلى إضافة جميع تطبيقات النظام المطلوبة يدويًا. ضع في اعتبارك نسخ التكوين الحالي وتعديله بدلاً من ذلك.',
    'configuration.remove.warning': 'هل أنت متأكد أنك تريد إزالة التكوين الأخير؟ ستفقد المعلومات المتعلقة بتطبيقات النظام المطلوبة.',
	'form.configuration.title': 'الاعداد' ,
    'form.configuration.title.typical': 'اعداد نموذجي' ,
    "form.configuration.settings.auto.update": 'تحديث تلقائي',
    'form.configuration.settings.system.update': 'تحديث النظام',
    'form.configuration.settings.system.update.default': 'افتراضي',
    'form.configuration.settings.system.update.immediate': 'فورًا',
    "form.configuration.settings.system.update.scheduled": 'مجدول',
    'form.configuration.settings.system.update.postponed': 'مؤجل',
    "form.configuration.settings.system.update.time": 'وقت التثبيت',
    'form.configuration.settings.system.update.time.from': 'من:',
    'form.configuration.settings.system.update.time.to': 'إلى:',
    "form.configuration.settings.block.status.bar": 'قفل شريط الحالة',
    'form.configuration.settings.block.status.bar.hint': 'هذا الإعداد مهمل ويعمل على Android 6 والإصدارات الأقدم. لقفل شريط الحالة في إصدارات Android الأحدث ، استخدم وضع الكشك (إعدادات MDM).',
    "form.configuration.settings.mdm.kiosk.mode": 'Kiosk وضعية',
    "form.configuration.settings.mdm.app.main": 'التطبيق الرئيسي',
    'form.configuration.settings.mdm.component.event.receiver': 'عنصر - مستلم الحدث',
    "form.configuration.settings.mdm.component.event.receiver.placeholder": 'أدخل اسم العنصر',
    "form.configuration.settings.mdm.component.wifi.ssid": 'WiFi SSID',
    "form.configuration.settings.mdm.component.wifi.ssid.placeholder": 'اتركه فارغًا للدخول يدويًا - WiFi SSID تسجيل',
    "form.configuration.settings.mdm.component.wifi.password": 'WiFi كلمة مرور',
    "form.configuration.settings.mdm.component.wifi.password.placeholder": 'اتركه فارغًا للدخول يدويًا - WiFi تسجيل مرور',
    "form.configuration.settings.mdm.component.wifi.security": 'WiFi نوع أمان',
    'form.configuration.settings.mdm.component.wifi.notice': 'ملاحظة: يتم تطبيق إعدادات WiFi هذه على التسجيل الأولي فقط!',
    "form.configuration.settings.mdm.component.server.url": 'للخادم الجديد URL عنوان',
    "form.configuration.settings.mdm.component.server.url.placeholder": 'جديد MDM يُستخدم للترحيل إلى خادم',
    "form.configuration.settings.mdm.app.content": 'تطبيق المحتوى',
    "form.configuration.settings.mdm.kiosk.home": 'تفعيل زر الصفحة الرئيسية',
    'form.configuration.settings.mdm.kiosk.recents': 'تفعيل الزر ااحديث',
    "form.configuration.settings.mdm.kiosk.notifications": 'تفعيل الإشعارات',
    "form.configuration.settings.mdm.kiosk.system.info": 'تفعيل معلومات شريط الحالة',
    "form.configuration.settings.mdm.kiosk.keyguard": 'تفعيل قفل الشاشة',
    'form.configuration.settings.mdm.mobile.enrollment': 'التسجيل باستخدام بيانات الجوال',
    "form.configuration.settings.mdm.lock.safe.settings": '(..., WiFi , GPS) قفل الإعدادات الآمنة',
    'form.configuration.settings.mdm.allowed.classes': 'الأنشطة المسموح بها',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'com.android.settings.homepage.SettingsHomepageActivity: فئات مفصولة بفواصل , على سبيل المثال',
    'form.configuration.settings.mdm.restrictions': 'قيود',
    'form.configuration.settings.mdm.restrictions.placeholder': 'قيود MDM ، مفصولة بفواصل ، على سبيل المثال: no_sms,no_outgoing_calls,no_usb_file_transfer',
    "form.configuration.settings.mdm.qrcode.url": 'لرمز الاستجابة السريعة URL عنوان',
    'form.configuration.settings.mdm.hint': 'حدد التطبيق والاعداد الرئيسيين',
    'form.configuration.apps.search.label': 'ابحث عن:',
    'form.configuration.apps.sort.label': 'فرز:',
    "form.configuration.apps.sort.byname": 'بالاسم',
    "form.configuration.apps.sort.bypkg": 'بالمعرف',
    'form.configuration.apps.no.apk': 'لا أحد',
    "form.configuration.apps.show.systeam.apps": 'إظهار تطبيقات النظام',
    'form.configuration.apps.action.install': 'تثبيت',
    'form.configuration.apps.action.prohibit': 'منع',
    "form.configuration.apps.action.not.install": 'عدم التثبيت',
    "form.configuration.apps.action.delete": 'حذف',
    'form.configuration.apps.action.permit': 'السماح',
    "form.configuration.apps.label.inherit": 'موروث',
    'form.configuration.apps.label.show': 'إظهار' ,
    'form.configuration.apps.label.not.show': 'إخفاء',
    'form.configuration.apps.edit.details': 'معلومات إضافية' ,
    "form.configuration.apps.keycode": 'رمز المفتاح',
    'form.configuration.apps.bottom': 'العرض في الخلاصة',
    'form.configuration.apps.hint': 'تلميح: لإلغاء ربط التطبيق بالاعداد , حدد الإجراء "حظر" أو "عدم التثبيت".',
    'form.configuration.settings.design.use.default': 'استخدام التصميم الافتراضي' ,
    "form.configuration.settings.design.color.background": 'لون الخلفية',
    'form.configuration.settings.design.color.background.placeholder': 'حدد لونًا' ,
    'form.configuration.settings.design.color.app.names': 'لون أسماء التطبيقات',
    'form.configuration.settings.design.color.app.names.placeholder': 'حدد لونًا' ,
    "form.configuration.settings.design.background.image.url": 'لصورة الخلفية url عنوان',
    'form.configuration.settings.design.background.image.url.placeholder': 'لصورة الخلفية url أدخل عنوان' ,
    "form.configuration.settings.design.icon": 'حجم الرمز',
    "form.configuration.settings.design.icon.small": 'صغير',
    "form.configuration.settings.design.icon.medium": '(متوسط ​​ (+ %20',
	"form.configuration.settings.design.icon.large": '(كبير (+ %40',
    "form.configuration.settings.design.desktop.header": 'عنوان سطح المكتب',
    "form.configuration.settings.design.desktop.header.no": 'لا',
    "form.configuration.settings.design.desktop.header.deviceid": 'معرف الجهاز',
    'form.configuration.settings.design.upload': 'تحميل',
    "form.configuration.settings.common.name": 'الاسم',
    "form.configuration.settings.common.name.placeholder": 'أدخل اسم الاعداد',
    "form.configuration.settings.common.desc": 'الوصف',
    "form.configuration.settings.common.desc.placeholder": 'أدخل وصف الاعداد',
    "form.configuration.settings.common.admin.pwd": 'كلمة مرور المسؤول',
    "form.configuration.settings.common.admin.pwd.placeholder": 'أدخل كلمة مرور المسؤول',
    "form.configuration.settings.common.gps": 'GPS',
    "form.configuration.settings.common.gps.any": 'أي',
    "form.configuration.settings.common.gps.off": 'معطل',
    "form.configuration.settings.common.gps.on": 'ممكّن',
    "form.configuration.settings.common.bluetooth": 'Bluetooth',
    "form.configuration.settings.common.wifi": 'Wi-Fi',
    "form.configuration.settings.common.mobile.data": 'بيانات الجوال',
    "form.configuration.settings.common.usb.storage": 'USB حظر تخزين',
    "form.configuration.settings.common.brightness": 'إدارة السطوع',
    "form.configuration.settings.common.brightness.none": 'بلا',
    "form.configuration.settings.common.brightness.auto": 'تلقائي',
    "form.configuration.settings.common.brightness.manual": 'القيمة',
    "form.configuration.settings.common.brightness.value": 'سطوع الشاشة',
    "form.configuration.settings.common.timeout": 'إدارة مهلة الشاشة',
    "form.configuration.settings.common.timeout.value": 'مهلة (فترات) الشاشة',
    "form.configuration.settings.common.volume.block": 'قفل حجم االصوت',
    'form.configuration.settings.common.volume.manage': 'إدارة حجم الجهاز',
    'form.configuration.settings.common.volume.value': 'حجم الجهاز',
    "form.configuration.settings.common.timezone.mode": 'إدارة المنطقة الزمنية',
    "form.configuration.settings.common.timezone.mode.default": 'بدون اعداد',
    "form.configuration.settings.common.timezone.mode.auto": 'تلقائي',
    "form.configuration.settings.common.timezone.mode.manual": 'يدوي',
    "form.configuration.settings.common.timezone": 'المنطقة الزمنية',
    'form.configuration.settings.common.timezone.placeholder': 'على سبيل المثال أمريكا/لوس أنجليس' ,
    "form.configuration.settings.common.timezone.link": 'قائمة المناطق الزمنية',
    'form.configuration.settings.common.no.network.warning': 'تحذير! لا تغلق جميع قنوات الاتصال ، وإلا فلن تتمكن من إدارة الأجهزة بعد الآن!',
    'form.configuration.settings.request.updates': 'تحديث الموقع',
    "form.configuration.settings.request.updates.donottrack": 'عدم التعقب',
    "form.configuration.settings.request.updates.gps": 'GPS بواسطة',
    "form.configuration.settings.request.updates.wifi": 'Wi-Fi بواسطة',
    'form.configuration.settings.request.updates.prompt.gps': 'GPS تحتاج إلى تفعيل GPS لتتبع إحداثيات' ,
    "form.configuration.settings.request.updates.prompt.wifi": 'Wi-Fi تحتاج إلى تفعيل Wi-Fi لتتبع إحداثيات',
    "form.configuration.settings.push.options": 'دفع الإخطارات',
    'form.configuration.settings.push.options.mqtt.worker': '(حفظ البطارية) MQTT بروتوكول' ,
    'form.configuration.settings.push.options.mqtt.alarm': '(التسليم الفوري) MQTT بروتوكول' ,
    'form.configuration.settings.push.options.polling': 'HTTP استطلاع',
    'form.configuration.settings.push.options.mqtt.worker.hint' : 'يسلم رسائل الدفع على الفور عندما يكون الجهاز نشطًا. ولكن قد تتأخر الرسائل لمدة تصل إلى بضع ساعات في وضع السكون. لا تستخدم هذا الخيار على الأجهزة المستقلة. يستخدم MQTT منفذ TCP 31000 ، قم بتمكينه على جدار الحماية الخاص بك.',
    'form.configuration.settings.push.options.mqtt.alarm.hint' : 'يسلم رسائل Push على الفور ولكن قد ينفق المزيد من الطاقة عندما يكون الجهاز في وضع السكون. أفضل خيار للأجهزة التي تعمل بالطاقة المستقلة. يستخدم MQTT منفذ TCP 31000 ، قم بتمكينه على جدار الحماية الخاص بك.',
    'form.configuration.settings.push.options.polling.hint' : 'يسلم رسائل Push بشكل موثوق مع تأخير أقصاه 15 دقيقة. لا يتطلب أي منافذ TCP بخلاف HTTPS. لا تستخدم هذا الخيار مع البرنامج المساعد للتحكم عن بعد.',
    'form.configuration.settings.push.options.keepalive' : 'وقت البقاء على قيد الحياة',
    'form.configuration.settings.minute.1' : '1 دقيقة',
    'form.configuration.settings.minutes.2' : '2 دقيقة',
    'form.configuration.settings.minutes.3' : '3 دقيقة',
    'form.configuration.settings.minutes.5' : '5 دقائق',
    'form.configuration.settings.minutes.10' : '10 دقائق',
    'form.configuration.settings.minutes.15' : '15 دقائق',
    "form.configuration.settings.password.mode": 'متطلبات كلمة الممنوح',
    'form.configuration.settings.password.mode.any': 'لا شيء',
    "form.configuration.settings.password.mode.present": 'كلمة المرور تقدم',
    "form.configuration.settings.password.mode.easy": 'سهل (6 رموز على الأقل)',
    "form.configuration.settings.password.mode.moderate": 'معتدل (أكثر من 8 رموز وحروف وأرقام)',
    "form.configuration.settings.password.mode.strong": 'قوي (8+ , أحرف كبيرة وصغيرة , أرقام , علامات)',
    'form.configuration.settings.show.wifi': 'إعدادات WiFi عند حدوث خطأ في الاتصال',
    'form.configuration.settings.use.default.launcher': 'استخدم مع المشغل الافتراضي' ,
    'form.configuration.settings.disable.screenshots': 'تعطيل التقاط الشاشة',
    "form.configuration.settings.orientation": 'قفل التوجيه',
    "form.configuration.settings.orientation.none": 'لا تغلق',
    'form.configuration.settings.orientation.portrait': 'تنسيق عمودي',
    'form.configuration.settings.orientation.landscape': 'تنسيق افقي',
    'form.configuration.settings.files.default.path': 'المسار الافتراضي على الجهاز',
    'form.configuration.files.search.label': 'بحث:',
    'form.configuration.files.action.upload': 'تحميل',
    'form.configuration.files.action.remove': 'إزالة' ,
    'form.configuration.files.variables': 'محتوى متغير',
    'form.configuration.files.variables.hint': 'سيتم استبدال السلاسل DEVICE_NUMBER و IMEI و CUSTOM* بقيمها',

	'form.configuration.file.name': 'اسم الملف' ,
    'form.configuration.file.description': 'وصف الملف',
    'form.configuration.file.description.placeholder': 'اختياري ، لراحتك',
    'form.configuration.file.path': 'مسار على الجهاز',
    'form.configuration.file.path.placeholder': 'استبعاد المسار إلى محرك الأقراص: /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'إذا تم استضافة ملف فقط على مورد خارجي',
    'form.configuration.file.file': 'ملف',
    'form.configuration.file.action': 'إجراء',
    'form.configuration.file.action.prompt.1': 'تحميل',
    'form.configuration.file.action.prompt.2': 'إزالة' ,
    "form.configuration.file.remove.prompt.1": 'لن تتم مزامنة هذا الملف مع الأجهزة بعد الآن',
    'form.configuration.file.remove.prompt.2': 'إزالة الملف من الخادم' ,

    "form.password.title": 'تغيير كلمة المرور',
    'form.password.label.user': 'المستخدم',
    "form.password.label.password.new": 'كلمة مرور جديدة',
    "form.password.label.password.new.placeholder": 'أدخل كلمة مرور جديدة',
    "form.password.label.password.confirm": 'تحقق',
    "form.password.label.password.confirm.placeholder": 'أدخل كلمة المرور الجديدة مرة أخرى',

    'form.application.type': 'نوع',
    "form.application.type.option.web": 'صفحة ويب',
    "form.application.type.option.app": 'التطبيق',
    'form.application.pkg': ' الحزمة ID',
    'form.application.from.file': 'محدد من ملف',
    'form.application.pkg.title': 'يتم تحديد معرف الحزمة تلقائيًا عند تحميل ملف APK. معرف الحزمة الذي تم إدخاله يدويًا مطلوب لتطبيقات النظام فقط.',
    'form.application.pkg.placeholder': 'على سبيل المثال ، com.android.camera',
    'form.application.disabled.arch': 'خاص بالإصدار',
    'form.application.disabled.arch.title': 'لإضافة ملفات APK لبنيات مختلفة لوحدة المعالجة المركزية ، انقر على "إضافة" أو افتح قائمة إصدارات التطبيق',
    'form.application.arch': 'الكود المحلي',
    'form.application.arch.title': 'تحتوي بعض التطبيقات على تعليمات برمجية محسّنة لبنية معينة لوحدة المعالجة المركزية. في هذه الحالة ، تحتاج إلى تحميل ملفي APK (لهيكل armeabi-v7a و arm64-v8a)',
    'form.application.arch.universal': 'لا شيء (APK عالمي)',
    'form.application.arch.armeabi': 'الكود الأصلي لـ armeabi-v7a',
    'form.application.arch.arm64': 'الكود الأصلي لـ arm64-v8a',
    'form.application.arch.no.split': 'ملف APK عالمي',
    'form.application.arch.split': 'تقسيم APK',
    'form.application.arch.warning': 'ملف APK هذا مخصص لـ ${arch} فقط. لا تنس تحميل ملفات APK لبنيات وحدة المعالجة المركزية الأخرى!',
    'form.application.arch.success': 'يحتوي هذا التطبيق على ملفات APK لكل من بنيات وحدة المعالجة المركزية',
    'form.application.version.exists': 'APK لهذا الإصدار موجود بالفعل',
    'form.application.url.armeabi': 'URL الخاص بـ armeabi-v7a',
    'form.application.url.arm64': 'URL الخاص بـ arm64-v8a',
    "form.application.name": 'اسم التطبيق',
    'form.application.name.title': 'سترى اسم التطبيق في القائمة. نوصي باستخدام أسماء فريدة وغنية بالمعلومات.',
    'form.application.name.placeholder': 'على سبيل المثال ، الكاميرا (Android)',
    'form.application.version': 'الإصدار',
    'form.application.version.placeholder': '0 لتطبيقات النظام',
    'form.application.version.title': 'يتم تحديد إصدار الحزمة تلقائيًا عند تحميل ملف APK. اضبطه على 0 لتطبيقات النظام.',
    'form.application.system': 'النظام',
    'form.application.system.title': 'تطبيقات النظام مثبتة مسبقًا على جهاز ولا تتطلب عنوان URL أو ملفًا. قم بتعيين هذه العلامة فقط إذا كنت بحاجة إلى تمكين حزمة نظام معينة.',
    "form.application.run.after.install": 'تشغيل بعد التثبيت',
    'form.application.run.after.install.title': 'يجب أن تبدأ التطبيقات ذات الخدمات الخلفية في المقدمة مرة واحدة على الأقل.',
    'form.application.run.at.boot': 'تشغيل في الاقلاع',
    'form.application.run.at.boot.title': 'عيّن هذه العلامة إذا كنت بحاجة إلى تشغيل التطبيق في المقدمة بعد التمهيد. هذا العلم لا يؤثر على عمليات الخلفية.',
    'form.application.url': 'URL',
    'form.application.url.title': 'يجب كتابة عنوان URL فقط إذا كان تطبيقك مستضافًا على مورد خارجي. يوصى بتحميل ملف APK باستخدام حقل أدناه.',
    'form.application.url.disabled': 'تم إعداد URL لكل إصدار. لتغيير عنوان URL ، أغلق هذه النافذة وانقر على رمز "الإصدارات".',
    'form.application.file': 'ملف',
    "form.application.showLabel": 'إظهار الرمز',
    'form.application.showLabel.title': 'تشير هذه العلامة إلى ما إذا كان يجب عرض رمز التطبيق في المشغل. قد يتم تجاوز هذا الخيار في التكوين.',
    'form.application.use.kiosk': 'افتح في Kiosk-Browser',
    'form.application.use.kiosk.title': 'عيّن هذه العلامة إذا كنت ترغب في فتح صفحة ويب في Kiosk-Browser دون أي إمكانية لتغيير العنوان',
    'form.application.iconText': 'نص أيقونة',
    'form.application.iconText.placeholder': '(افتراضي)',
    "form.application.versions.title": 'إصدارات التطبيق',
    'form.application.icon': 'أيقونة',
    'form.application.icon.default': '(افتراضي)',
    "form.application.icon.add": 'إضافة رمز',

    'form.application.setting.app': 'تطبيق',
    "form.application.setting.app.placeholder": 'حدد تطبيقًا',
    'form.application.setting.name': 'ينسب',
    'form.application.setting.value': 'القيمة',
    'form.application.setting.comment': 'تعليق',
    'form.application.setting.type': 'نوع',
    "form.application.setting.readonly": 'لا يتغير على الجهاز',
    
    'form.application.configurations.app': 'تطبيق',
    "form.application.configurations.configs": 'الاعدادات',

    "form.configuration.copy.new.name": 'اسم جديد',
    "form.configuration.copy.new.name.placeholder": 'أدخل اسم الاعداد الجديد',

	"form.customer.name": 'الاسم',
    "form.customer.name.placeholder": 'أدخل اسم المؤسسة',
    "form.customer.apiKey": 'API مفتاح',
    "form.customer.apiKey.placeholder": 'API أدخل مفتاح',
    "form.customer.prefix": 'بادئة',
    "form.customer.prefix.placeholder": 'أدخل بادئة رقم الجهاز',
    "form.customer.device.configuration": 'اعداد الجهاز',
    "form.customer.desc": 'الوصف',
    "form.customer.desc.placeholder": 'أدخل وصفًا للمؤسسة',
    "form.customer.copy.configuration": 'نسخ الاعدادات',
    "form.customer.copy.design": 'نسخ التصميم',
    'form.customer.type': 'نوع العميل',
    'form.customer.status': 'حالة العميل',
    'form.customer.expiry.time': 'تاريخ الانتهاء',
    'form.customer.device.limit': 'حد الأجهزة',

    'form.device.number': 'رقم',
    'form.device.number.locked': 'لا يمكن تغيير الرقم لأنه لم يكتمل تغيير الرقم السابق.',
    'form.device.migration.warning': 'سيتم تغيير رقم الجهاز. تأكد من أن الجهاز قيد التشغيل ومتصل بالإنترنت.',
    "form.device.number.hint": 'لا تستخدم أحرفًا خاصة',
    'form.device.desc': 'الوصف',
    "form.device.groups": 'المجموعات',
    'form.device.config': 'الاعداد' ,
    "form.device.imei": 'IMEI',
    "form.device.phone.number": 'رقم الهاتف',

    "form.update.device.config": 'الاعداد',

    'form.file.file': 'ملف',
    'form.file.path': 'مسار',
    'form.file.path.placeholder': '/"أدخل مسارًا نسبيًا , على سبيل المثال "/الملفات',

    'form.file.apps.name': 'اسم التطبيق' ,
    "form.file.apps.pkg": 'معرف الحزمة',
    'form.file.apps.version': 'الإصدار',

    "form.group.name": 'الاسم',
    "form.group.name.placeholder": 'أدخل اسم المجموعة',

    'form.user.login': 'تسجيل الدخول',
    "form.user.login.placeholder": 'أدخل تسجيل دخول المستخدم',
    "form.user.name": 'الاسم',
    "form.user.name.placeholder": 'أدخل اسم المستخدم الخاص بك',
    "form.user.role": 'الدور',
    "form.user.all.devices.available": 'جميع الأجهزة متوفرة',
    "form.user.available.groups": 'مجموعات الأجهزة المتاحة',
    "form.user.password.new": 'كلمة مرور جديدة',
    "form.user.password": 'كلمة المرور',
    "form.user.password.new.placeholder": 'أدخل كلمة مرور جديدة',
    "form.user.password.confirm": 'تحقق',
    "form.user.password.confirm.placeholder": 'أدخل كلمة المرور الجديدة مرة أخرى',

    'form.settings.hints.title': 'تلميحات',

    'form.settings.plugins.title': 'الاعدادات الإضافية المستخدمة',

	"form.settings.common.title": 'عرض جدول الجهاز',
    "form.settings.common.visible.columns":' "أعمدة مرئية في جدول" الأجهزة "',
    "form.settings.common.status": 'الحالة',
    "form.settings.common.role": 'دور المستخدمين',
    "form.settings.common.date": 'التاريخ',
    "form.settings.common.device.number": 'رقم الجهاز',
    "form.settings.common.imei": 'IMEI',
    "form.settings.common.phone.number": 'رقم الهاتف',
    "form.settings.common.phone.model": 'طراز الهاتف',
    "form.settings.common.status.permissions": 'حالة الاذونات',
    "form.settings.common.status.installation": 'حالة التثبيت',
    'form.settings.common.status.files': 'حالة الملفات' ,
    "form.settings.common.config": 'الاعداد',
    "form.settings.common.desc": 'الوصف',
    "form.settings.common.group": 'مجموعة',
    "form.settings.common.launcher.version": 'إصدار المشغل',
    "form.settings.common.battery.level": 'مستوى البطارية',
    'form.settings.common.default.launcher': 'مشغل افتراضية' ,

    'form.settings.design.title': 'التصميم الافتراضي',
    'form.settings.design.color.font': 'لون الخلفية',
    "form.settings.design.color.font.placeholder": 'حدد لونًا',
    "form.settings.design.color.app.names": 'لون أسماء التطبيقات',
    'form.settings.design.color.app.names.placeholder': 'حدد لونًا',
    "form.settings.design.url.background.image": 'لصورة الخلفية URL  عنوان',
    "form.settings.design.url.background.image.placeholder": 'لصورة الخلفية URL أدخل عنوان',
    "form.settings.design.size.icon": 'حجم الرمز',
    "form.settings.design.size.icon.small": 'صغير',
    "form.settings.design.size.icon.medium": '(متوسط ​​(+ %20',
    "form.settings.design.size.icon.large": '(كبير (+ %40',
    "form.settings.design.desktop.header": 'عنوان سطح المكتب',
    "form.settings.design.desktop.header.no": 'لا',
    "form.settings.design.desktop.header.device.id": 'الجهاز ID',

    "form.settings.lang.title": 'إعدادات اللغة',
    "form.settings.lang.use.default": 'استخدام اللغة الافتراضية',
    "form.settings.lang.use": 'استخدام اللغة',
    'form.settings.lang.en': 'English',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',

	"form.settings.misc.title": 'إعدادات متنوعة',
    "form.settings.misc.phone.format": 'تنسيق رقم الهاتف',
    "form.settings.misc.phone.format.placeholder": '+9 (999) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'الخاصية المخصصة #1',
    'form.settings.misc.custom.property.name.2': 'الخاصية المخصصة #2',
    'form.settings.misc.custom.property.name.3': 'الخاصية المخصصة #3',
    'form.settings.misc.custom.property.multiline': 'متعدد الأسطر',
    'form.settings.misc.custom.property.send': 'أرسل إلى الجهاز',
    'form.settings.misc.custom.property.name.placeholder': 'أدخل اسمًا لخاصية مخصصة',
    "form.settings.misc.create.new.devices": 'إضافة جهاز عند الوصول الأول',
    "form.settings.misc.new.device.config": 'اعداد جهاز جديد',
    "form.settings.misc.new.device.group": 'مجموعة أجهزة جديدة',

    "form.settings.groups.title": 'مجموعات',
    "form.settings.groups.search.placeholder": 'بحث المجموعة',

    'form.settings.users.title': 'المستخدمون',
    "form.settings.users.search.placeholder": 'بحث عن المستخدم',

    'form.qr.device.number': 'رقم الجهاز',
    'form.qr.auto.create': 'أضف إلى قائمة الأجهزة إذا لم يكن موجودًا',
    'form.qr.number.use': 'تخصيص رقم الجهاز',
    'form.qr.number.use.request': 'قيمة المستخدم',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'رقم سري',
    'form.qr.groups': 'أضف إلى المجموعات',
    'form.qr.button.json': 'احصل على JSON',
    'form.qr.device.number.placeholder': '... الجهاز ID أدخل',
    "form.qr.code.image.alt": 'QR رمز',

    "form.profile.title": 'تغيير كلمة المرور',
    "form.profile.password.old": 'كلمة المرور القديمة',
    "form.profile.password.old.placeholder": 'أدخل كلمة المرور القديمة',
    "form.profile.password.new": 'كلمة مرور جديدة',
    "form.profile.password.new.placeholder": 'أدخل كلمة مرور جديدة',
    "form.profile.password.confirm": 'تحقق',
    "form.profile.password.confirm.placeholder": 'أدخل كلمة المرور الجديدة مرة أخرى',

    "tab.customers": 'المنظمات',
    "tab.common.applications": 'التطبيقات المشتركة',

    "tab.devices": 'الأجهزة',
    "tab.applications": 'التطبيقات',
    "tab.configurations": 'الاعدادات',
    "tab.files": 'الملفات',
    "tab.default.design": 'التصميم الافتراضي',
    "tab.common.settings": 'عرض جدول الجهاز',
    "tab.users": 'المستخدمون',
    "tab.groups": 'المجموعات',
    "tab.language": 'اللغة والإعدادات الأخرى',
    'tab.license': 'رخصة',
    "tab.hints": 'تلميحات',
    "tab.plugins": 'الاعدادات الإضافية',
    
 	"tab.configeditor.common.settings": 'الإعدادات العامة',
    "tab.configeditor.design.settings": 'إعدادات التصميم',
    "tab.configeditor.applications": 'التطبيقات',
    "tab.configeditor.mdm.settings": 'MDM إعدادات',
    "tab.configeditor.app.settings": 'إعدادات التطبيقات',
    'tab.configeditor.files': 'الملفات' ,
    
    'search.placeholder.file': 'ملف البحث',
    'search.placeholder.configuration': 'البحث عن الاعداد',
    'search.placeholder.customer': 'ابحث عن منظمة',
    'search.placeholder.application': 'ابحث عن تطبيق' ,
    'search.placeholder.application.setting': 'ابحث عن إعداد تطبيق' ,
    'search.placeholder.device': 'ابحث عن جهاز' ,
    'search.placeholder.address': 'البحث عن العنوان',
    'search.placeholder.point': 'بحث الموقع',
    'search.placeholder.message': 'البحث عن الرسائل',
    'search.placeholder': '... بحث',
    'search.placeholder.from': '... من',
    'search.placeholder.to': '... إلى',
    'search.placeholder.user': 'اكتب اسم المستخدم',

    "table.heading.customer.name": 'الاسم',
    "table.heading.customer.desc": 'الوصف',
    "table.heading.customer.registration.time": 'مسجل',
    "table.heading.customer.last.login.time": 'آخر تسجيل دخول',
    "table.heading.customer.actions": 'الإجراءات',
    'table.heading.customer.type': 'نوع',
    'table.heading.customer.expiry.time': 'تنتهي',
    'table.heading.customer.device.limit': 'حد',
    'table.heading.customer.status': 'الحالة',

    'customer.new': 'جديد',
    'customer.active': 'نشيط',
    'customer.need.followup': 'بحاجة الى متابعة',
    'customer.followup.sent': 'تم إرسال المتابعة',
    'customer.internal.test': 'اختبار داخلي',
    'customer.developer': 'مطور',
    'customer.difficult': 'صعب',
    'customer.pause': 'وقفة',
    'customer.denial': 'إنكار',
    'customer.client': 'زبون',

    'table.heading.configuration.name': 'اسم',
    'table.heading.configuration.desc': 'الوصف',
    "table.heading.configuration.actions": 'الإجراءات',

    'table.heading.application.setting.app.pkg': 'الحزمة ID',
    'table.heading.application.setting.app.name': 'اسم التطبيق',
    'table.heading.application.setting.name': 'سمة',
    "table.heading.application.setting.value": 'القيمة',
    "table.heading.application.setting.comment": 'تعليق',
    "table.heading.application.setting.lastUpdate": 'تاريخ الإنشاء',

    'table.heading.file.url': 'URL',
    "table.heading.file.devicepath": 'مسار على الجهاز',
    'table.heading.file.description': 'وصف الملف',
    "table.heading.file.action": 'إجراء',
    "table.heading.file.lastUpdate": 'تاريخ الإنشاء',
    
    'table.heading.application.pkg': 'الحزمة ID',
    'table.heading.application.name': 'اسم التطبيق',
    "table.heading.application.version": 'الإصدار',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'أيقونة',
    "table.heading.application.actions": 'الإجراءات',
    'table.heading.application.order': 'ترتيب',

    "table.heading.device.status": 'الحالة',
    "table.heading.device.date": 'التاريخ',
    "table.heading.device.device.number": 'رقم الجهاز',
    "table.heading.device.imei": 'IMEI',
    "table.heading.device.phone.number": 'رقم الهاتف',
    "table.heading.device.phone.model": 'طراز الهاتف',
    "table.heading.device.status.permissions": 'حالة الإذن',
    "table.heading.device.status.installation": 'حالة التثبيت',
    'table.heading.device.status.files': 'حالة الملفات',
    "table.heading.device.configuration": 'الاعداد',
    "table.heading.device.desc": 'الوصف',
    "table.heading.device.group": 'مجموعة',
    'table.heading.device.launcher.version': 'إصدار المشغل' ,
    "table.heading.device.battery.level": 'مستوى البطارية',
    'table.heading.device.default.launcher': 'تعيين كافتراضي' ,
    "table.heading.device.actions": 'الإجراءات',

    "table.heading.group.name": 'الاسم',
    "table.heading.group.actions": 'الإجراءات',

	'table.heading.file.name': 'اسم الملف',
    'table.heading.file.path': 'مسار',
    "table.heading.file.address": 'العنوان',
    "table.heading.file.actions": 'الإجراءات',

    'table.heading.users.login': 'تسجيل الدخول',
    'table.heading.users.name': 'اسم',
    "table.heading.users.role": 'الدور',
    "table.heading.users.actions": 'الإجراءات',

    "table.heading.common.apps.customer": 'منظمة',
    "table.heading.common.apps.pkg": 'معرف الحزمة',
    "table.heading.common.apps.name": 'اسم التطبيق',
    "table.heading.common.apps.version": 'إصدار',
    "table.heading.common.apps.url": 'URL',
    "table.heading.common.apps.label": 'أيقونة',
    "table.heading.common.apps.actions": 'الإجراءات',

    'notfound.devices': 'لا توجد أجهزة لعرضها.',
    'notfound.files': 'قائمة الملفات فارغة.',
    'notfound.configurations': 'لم يتم العثور على اعدادات.',
    'notfound.customers': 'لم يتم العثور على المنظمات.',
    'notfound.common.apps':' لا توجد تطبيقات لعرضها. ',
    'notfound.applications':' لم يتم العثور على التطبيقات ',
    'notfound.groups': 'لم يتم العثور على مجموعات. جرب استعلامًا مختلفًا. ',
    'notfound.users': 'لم يتم العثور على المستخدمين. جرب طلب بحث مختلف. ',
    'notfound.apps.for.display': 'لا توجد تطبيقات لعرضها.',
    'notfound.app.versions.for.display': 'لا توجد إصدارات لعرضها.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    "menu.about": 'حول',
    "menu.profile": 'الملف الشخصي',
    "menu.panel.master": 'لوحة خبير',
    "menu.panel.main": 'اللوحة الرئيسية',
    "menu.logout": 'تسجيل الخروج',
    "menu.functions": 'وظائف',
    "menu.settings": 'الخصائص',
    "menu.show.hints": 'إظهار التلميحات',

    'plugin.name.not.specified': '<< اسم الوظيفة غير محدد >>',
    
	"breadcrumb.devices": 'الأجهزة',
    "breadcrumb.applications": 'التطبيقات',
    "breadcrumb.configurations": 'الاعدادات',
    "breadcrumb.files": 'الملفات',
    'breadcrumb.default.design': 'التصميم افتراضيًا',
    "breadcrumb.common.settings": 'عرض جدول الجهاز',
    "breadcrumb.language.settings": 'اللغة وإعدادات أخرى',
    "breadcrumb.license.settings": 'رخصة',
    "breadcrumb.users": 'المستخدمون',
    "breadcrumb.groups": 'المجموعات',
    "breadcrumb.hints": 'تلميحات',
    "breadcrumb.plugins": 'الإضافات',
    'breadcrumb.config.details': 'تفاصيل',
    "breadcrumb.application.versions": 'إصدارات',

    "app.name": 'Headwind MDM',
    'app.vendor.name':"h-mdm.com",
    'app.vendor.link':"https://h-mdm.com",
    "app.description": 'هو نظام إدارة الأجهزة المحمولة مفتوح المصدر',
    "app.title": '${appName} لوحة ويب',

    "box.show.my.apps.only": 'عرض تطبيقاتي فقط',
    'config.app.version.upgrade.message': '${installVersion} الإصدار المثبت , ${latestVersion} الإصدار المتاح ',

    "about.line.1": '${appName} لوحة تحكم',
    'about.line.2': 'Android مشغل المؤسسة لـ',
    'about.line.3': '${versionNumber} الإصدار',
    'about.line.4': 'الاعدادات الإضافية المثبتة',

    'common.app.clarification': 'هذا التطبيق عام وغير متاح للتعديل. لإضافة إصدار آخر من هذا التطبيق , يرجى الاتصال بالمسؤول. ',

    "qrcode.help.line1": 'لإعداد جهاز الأندرويد (الإصدار 7 أو أعلى) في وضع مُدار (الشركة):',
    "qrcode.help.line2": 'إعادة ضبط الجهاز على إعدادات المصنع',
    "qrcode.help.line3": 'مخفي (QR انقر 7 مرات في أي مكان من شاشة البداية (يجب عليك إدخال وضع مسح رمز الاستجابة السريعة',
    "qrcode.help.line4": 'هذا QR اتبع إرشادات الجهاز: قبول الشروط , والاتصال بشبكة واي فاي , وامسح رمز الاستجابة السريعة',
    'qrcode.help.line5': '(لذا لا تحتاج إلى إدخاله على جهاز محمول). لتضمين معرف الجهاز في رمز رمز الاستجابة السريعة ،أدخل معرف الجهاز على هذه الشاشة وانقر  على تجديد) ${appName} قد يحتوي رمز الاستجابة السريعة على معرف الجهاز',
    
    'form.configuration.app.version.select.select.title': 'حدد الإصدار المراد تثبيته' ,
    'form.configuration.app.version.select.version.check.off': 'تعطيل فحص الإصدار',
    'form.configuration.app.version.select.upgrade.warning': '؟ "${v2}" من النسخة "${v3}" إلى الإصدار "${v1}" ترقية التطبيق',
    'form.configuration.app.version.select.downgrade.warning': '؟ "${v2}" إلى الإصدار "${v1}" الرجوع إلى إصدار أقدم احذف جميع هذه التطبيقات على جميع الأجهزة! هل تريد الرجوع إلى إصدار أقدم من إصدار التطبيق',

    "hint.step.1": 'انقر هنا لبدء تسجيل الجهاز',
    "hint.step.2": 'QR انقر هنا لفتح رمز الاستجابة السريعة',
    "hint.step.3": 'QR انقر هنا لمعرفة كيفية فتح ماسح رمز الاستجابة السريعة',
    'hint.step.4': 'الجهاز المتاح في علامة التبويب «الأجهزة». انقر فوق "تجديد" لتضمينه في رمز الاستجابة السريعة ID ابحث عن',

    'ie.browser.notice.1': ' , Internet Explorer للأسف غير مدعوم.',
    'ie.browser.notice.2': '<a href="https://support.google.com/chrome/answer/95346؟co=GENIE.Platform٪3DDesktop">Chrome</a> - ${appName} المتصفح الموصى به لاستخدام',

    'form.resolved.duplicate.pkg.text1': '. مستخدم بالفعل بواسطة التطبيقات المدرجة أدناه "${pkg}" الحزمة ID',
    'form.resolved.duplicate.pkg.text2': 'هل تريد إضافة تطبيق جديد أم إصدار جديد من تطبيق موجود؟',
    'form.resolved.duplicate.pkg.text3': 'إصدار جديد لـ',
    'form.resolved.duplicate.pkg.text4': 'مُعرّف الحزمة "${pkg}" مستخدم بالفعل في التطبيقات ${apps}',
    'form.resolved.duplicate.pkg.text5': 'هل أنت متأكد أنك تريد تغيير معرف الحزمة؟',

    "tooltip.usage.byconfigurations": 'مستخدمة بواسطة الاعدادات',
    "tooltip.usage.byapps": 'مستخدمة بواسطة التطبيقات',
    "tooltip.usage.byicons": 'مستخدمة بواسطة الرموز',

    'form.devices.label.params.more': 'المزيد من المعلمات',
    'form.devices.label.params.less': 'معلمات أقل',
    "form.devices.label.installation.status": 'حالة التثبيت',
    "format.devices.date.createTime": 'dd/MM/yyyy HH:mm:ss',
    "format.devices.date.datePicker": 'dd-MM-yyyy',

    'form.devices.selection.install.status.default': '... حالة التثبيت',
    'form.devices.selection.install.status.all': 'الكل',
    "form.devices.selection.install.status.success": 'نجاح',
    'form.devices.selection.install.status.version.mismatch': 'عدم تطابق الإصدار',
    'form.devices.selection.install.status.failure': 'فشل',
    "form.devices.selection.imei.changed": 'مؤخرًا IMEI تم تغيير',

    'search.placeholder.launcher.version': 'إصدار المشغل' ,
    'error.date.range.invalid': 'فاصل تاريخ غير صالح',

    'customer.type.demo': 'محاكمة',
    'customer.type.small': 'أعمال صغيرة',
    'customer.type.corporate': 'مشروع - مغامرة',
    'customer.type.master': 'ابتدائي',

    'customer.type.options.all': 'كل الانواع',
    'customer.status.options.all': 'كل الحالات',

    'account.expiring': 'ستنتهي صلاحية حسابك في ${days} أيام. يرجى الاتصال بالبائع لتجديد حسابك.',
    'account.expired.short': 'انتهت صلاحية حسابك!',
    'account.expired': 'انتهت صلاحية حسابك. يرجى الاتصال بالبائع لتجديد حسابك.',
    'device.limit.achieved': 'لا يمكن إضافة جهاز لأنك وصلت إلى الحد الأقصى. الرجاء إزالة بعض الأجهزة أو الاتصال بالبائع لتوسيع حد جهازك.',

    'yes':' نعم',
    'no': 'لا'
};
