if (! document.localization) document.localization = [];

document.localization ['ar_AE'] = {
	"login.username": 'اسم المستخدم أو البريد الإلكترون',
    "login.username.placeholder":'أدخل اسم المستخدم أو البريد الإلكتروني',
    'login.password': 'كلمة المرور:',
    "login.password.placeholder": 'أدخل كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.password.incorrect': 'اسم المستخدم أو كلمة المرور غير صالحة',

    'header.label.username': 'اسم المستخدم',

    "devices.group.options.all": 'كل المجموعات',
    'devices.configuration.options.all': 'جميع الاعدادات',
    'devices.permissions.all': 'يتم منح جميع الأذونات',
    'devices.permissions.not.as.device.admin': '- التطبيق غير مثبت كمسؤول الجهاز',
    'devices.permissions.window.overlap.prohibited': '- لا يتوفرخاصية الضهورر أعلى النوافذ الأخرى',
    'devices.permissions.history.access.prohibited': '- لم يتم اعداد الوصول إلى محفوظات الاستخدام',
    'devices.unknown': 'مجهول',
    'devices.model.unknown': 'مجهول',
    "devices.date.unknown": 'غير معروف',
    'devices.date.format': 'dd/MM HH:mm',
    'devices.app.installed': '- ${applicationName}: تم التثبيت.',
    'devices.app.not.installed': '- ${applicationName}: غير مثبت.',
    'devices.app.version.available': ', متاح ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: تم تثبيت ${applicationInstalledVersion} , متوفر ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion} , الإزالة مطلوبة',
    "devices.no.data": 'الجهاز لم يرسل البيانات',
    'devices.settings.conformance.broken': 'عدم تطابق مع الإعدادات: (${serverData})',
    'devices.file.installed': '- ${file}: تثبيت',
    'devices.file.not.installed': '- ${file}: غير مثبت.',
    'devices.file.lastUpdate.differs': '- ${file}: الاختلاف في وقت التعديل ${diff} min',

    "button.apply": 'تطبيق',
    "button.gps.on": 'تفعيل GPS',
    "button.wifi.on": 'تفعيل Wi-Fi',
    "button.notify.update": 'إعلام عند التحديث',
    "button.app.settings": 'إعدادات التطبيق',
    "button.ok": 'موافق',
    "button.help": 'مساعدة',
    "button.new.app": 'تطبيق جديد',
    "button.new.app.version": 'إصدار جديد',
    "button.upgrade": 'ترقية',
    "button.renew.config": 'تحديث على الأجهزة',
    "button.common": 'تطبيق مشترك',
    "button.close": 'إغلاق',
    "button.yes": 'نعم',
    "button.cancel": 'إلغاء',
    "button.save": 'حفظ',
    "button.save.and.close": 'حفظ وإغلاق',
	'button.more': 'المزيد ...',
    "button.cleanup": 'مسح',
    "button.add": 'إضافة',
    "button.add.icon": 'أيقونة جديدة',
    "button.search": 'بحث',
    "button.export": 'تصدير',
    "button.change": 'تحرير',
    'button.copy': 'نسخ',
    "button.qrcode": 'رمز الاستجابة السريعة',
    "button.application": 'تطبيق',
    "button.change.password": 'تغيير كلمة المرور',
    "button.set.configuration": 'ضبط الاعدادات',
    "button.delete": 'حذف',
    'button.login': 'تسجيل الدخول',
    "button.renew.code": 'تجديد',
    "button.configurations": 'الاعدادات',
    'button.set.configurations': 'تحديد الاعدادات' ,
    "button.edit.versions": 'إصدارات',
    'button.edit': 'تحرير' ,
    "button.change.common.app": 'تعديل التطبيق المشترك',
    "button.delete.common.app": 'حذف التطبيق المشترك',
    "button.turn.common.app": 'جعله مشتركًا',
    "button.hints.enable": 'إظهار تلميحات الأدوات',
    "button.hints.disable": 'إخفاء تلميحات الأدوات',

    'question.impersonate.user': 'قم بتسجيل الدخول إلى التطبيق كمسؤول عن المؤسسة "${customerName}"؟',
    'question.delete.file': 'حذف الملف "${fileName}"؟',
    'question.delete.customer': 'هل تريد حذف المؤسسة "${customerName}"؟',
    'question.delete.user': 'حذف المستخدم "${username}"؟',
    'question.delete.application': 'هل تريد حذف التطبيق "${applicationName}"؟',
    'question.delete.application.version': 'حذف الإصدار "${applicationVersion}"؟',
    'question.delete.configuration': 'حذف الاعداد "${configurationName}" ؟؟',
    'question.delete.group': 'هل تريد حذف المجموعة "${groupName}"؟',
    'question.delete.device': 'هل تريد حذف الجهاز الذي يحمل الرقم "${deviceNumber}"؟',
    'question.exit.without.saving': 'لا يتم حفظ التغييرات. على أي حال مغادرة هذه الصفحة؟ ',
    'question.turn2common.application': 'مشاركة التطبيق "${applicationName}"؟',
    'question.app.upgrade': 'هل تريد تحديث التطبيق "${v1}" إلى أحدث إصدار للتهيئة "${v2}"؟',

    'error.application.setting.empty.app': 'حدد التطبيق',
    'error.application.setting.empty.name': 'أدخل اسمًا' ,
    'error.application.setting.empty.value': 'حدد قيمة',

    'error.icon.dimension.invalid': 'يجب أن يكون الرمز مربعًا' ,
    'error.icon.empty.name': 'أدخل اسم الأيقونة' ,
    'error.icon.empty.file': 'تحميل أيقونة الملف',
    'error.application.version.pkg.mismatch': 'ID حزمة الملف (${actual}) لا يتوافق مع التطبيق (${expected})',
    'error.empty.user': 'حدد مستخدم' ,
	'error.empty.user.name': 'أدخل اسم المستخدم' ,
    'error.empty.user.login': 'املأ تسجيل دخول المستخدم', 
    'error.empty.user.role': 'حدد دور المستخدم',
    "error.empty.password": 'أدخل كلمة مرور جديدة',
    "error.empty.password.confirm": 'أدخل تأكيد كلمة المرور',
    'error.empty.group.name': 'املأ اسم المجموعة',
    'error.empty.configuration': 'حدد الاعداد' ,
    'error.empty.configuration.name': 'املأ اسم اللاعداد',
    'error.empty.configuration.password': 'أدخل كلمة المرور',
    "error.empty.configuration.contentApp": 'لم يتم تحديد تطبيق محتوى',
    'error.invalid.configuration.mainApp': 'في إعدادات MDM , يتم استخدام التطبيق الرئيسي الخاطئ' ,
    "error.invalid.configuration.contentApp": 'تطبيق محتوى غير صالح مستخدم في إعدادات MDM',
    'error.mismatch.password': 'يجب أن تتطابق كلمة المرور وتأكيد كلمة المرور' ,
    "error.empty.customer.name": 'املأ اسم المؤسسة',
    'error.empty.customer.prefix': 'املأ بادئة رقم الجهاز',
    "error.empty.customer.device.configuration": 'حدد اعداد الجهاز',
    "error.empty.customer.duplicate.prefix": 'البادئة قيد الاستخدام بالفعل',
    'error.duplicate.customer.name': 'المؤسسة التي تحمل الاسم المدخل موجودة بالفعل. جرب اسما مختلفا. ',
    'error.duplicate.group.name': 'المجموعة ذات الاسم المدخل موجودة بالفعل. جرب اسما مختلفا. ',
    'error.duplicate.configuration.name': 'الاعداد بالاسم المدخل موجود بالفعل. جرب اسما مختلفا. ',
    'error.duplicate.device.number': 'يوجد بالفعل جهاز بهذا الرقم',
    "error.internal.server": 'خطأ داخلي في الخادم',
    "error.permission.denied": 'لا توجد حقوق للتنفيذ',
    'error.request.failure': 'فشل الطلب',
    'error.configuration.device.use': 'لا يمكن حذف هذا الاعداد , يتم استخدامه على الأجهزة. انتقل أولاً إلى "الأجهزة, وابحث عن الأجهزة التي تستخدم هذا الاعداد وغيّر إعداداتها. ',
    'error.invalid.system.update.time': 'الفاصل الزمني للتثبيت غير صالح',

    'error.configuration.file.empty.name': 'أدخل اسم ملف' ,
    'error.configuration.file.empty.desc': 'حدد وصف الملف' ,
    'error.configuration.file.empty.path': 'حدد المسار على الجهاز',
    'error.configuration.file.empty.file': 'أدخل عنوان URL أو قم بتحميل ملف',
    
    'error.notfound.device': 'الجهاز غير موجود',
    'error.duplicate.device': 'جهاز بنفس الرقم موجود بالفعل',
    'error.duplicate.login': 'مثل هذا تسجيل الدخول قيد الاستخدام بالفعل' ,
    'error.duplicate.group': 'توجد بالفعل مجموعة بنفس الاسم' ,
    'error.duplicate.application': 'يوجد بالفعل تطبيق يحمل ID الحزمة هذا والإصدار' ,
    'error.recent.application.version.exists': 'يوجد أحدث إصدار للتطبيق' ,
    "error.common.application.access.prohibited": 'يُسمح بإدارة التطبيقات الشائعة بواسطة Super-Administrator فقط',
    'error.application.config.reference.exists': 'التطبيق مستخدم في الاعدادات ولا يمكن حذفه',
    'error.application.version.deletion.prohibited': 'الإصدار إما فريد أو مستخدم في الاعدادات ولا يمكن حذفه' ,
    'error.duplicate.file': 'ملف بنفس الاسم موجود بالفعل' ,
    'error.used.file': 'هذا الملف مستخدم',
    'error.version.exists': 'الإصدار نفسه من هذا التطبيق موجود بالفعل' ,
    'error.duplicate.configuration': 'يوجد اعداد بهذا الاسم بالفعل' ,
    'error.notfound.customer.admin': 'حساب المسؤول غير موجود' ,
    'error.apk.file.required': 'حدد الملف بملحق .apk أو .xapk' ,
    'error.apk.parse': 'حدث خطأ أثناء تحليل الملف',
    'error.empty.app.name': 'أدخل اسم التطبيق' ,
    "error.empty.app.pkg": 'أدخل معرف الحزمة',
    "error.empty.app.url": 'أدخل عنوان URL',
    "error.empty.app.iconText": 'أدخل نص الرمز',
    'error.empty.app.version': 'أدخل إصدار التطبيق' ,
	'error.notempty.group': 'تتضمن هذه المجموعة جهاز واحد أو أكثر. لا يمكنك إزالته. ',
    'error.file.empty':' تحميل ملف جديد ',
    'error.file.deletion': 'خطأ في حذف الملف على الخادم' ,
    'error.file.save': 'خطأ أثناء حفظ الملف على الخادم',
    'error.password.wrong': 'كلمة مرور غير صالحة',
    "error.password.empty": 'كلمة المرور غير محددة',
    'error.params.missing': 'معلمات مفقودة:',
    "error.empty.push.options": 'الرجاء تحديد خيارات التنبيهات الفورية',

    "table.filtering.check.all": 'تحديد الكل',
    "table.filtering.uncheck.all": 'إلغاء الكل',
    'table.filtering.suffix.configuration': 'الاعدادات',
    "table.filtering.suffix.group": 'مجموعات',
    "table.filtering.no.selected.configuration": 'لم يتم تحديد أي اعدادات',
    "table.filtering.no.selected.group": 'لا توجد مجموعات محددة',

    'Success.admin.created': 'إنشاء حساب المسؤول:\n ${adminCredentials}',
    'Success.uploading.file': 'يتم رفع الملف إلى الخادم ...',
    'Success.loading.devices': 'جارٍ تحميل قائمة الأجهزة ...',
    "Success.loading.customer": 'جارٍ تحميل تفاصيل العميل ...',
    'Success.file.uploaded': 'تم رفع الملف بنجاح.',
    'Success.file.uploaded.need.save': 'تم رفع الملف بنجاح. أدخل المسار ذي الصلة وانقر على "حفظ',
    "Success.settings.design.saved": 'تم حفظ إعدادات التصميم بنجاح',
    "Success.settings.common.saved": 'تم حفظ إعدادات جدول الجهاز بنجاح',
    "Success.settings.saved": 'تم حفظ الإعدادات بنجاح',
    "Success.settings.apiKey.saved": 'تم حفظ مفتاح API بنجاح',
    "Success.settings.hints.enabled": 'تم تفعيل التلميحات',
    "Success.settings.hints.disabled": 'تم تعطيل التلميحات',
    'Success.configuration.saved': 'تم حفظ الاعداد بنجاح' ,
    "Success.operation.completed": 'اكتملت العملية بنجاح',
    "Success.plugins.disabled": 'تم حفظ الإعدادات بنجاح',
    'Success.config.update.notification': 'تم إرسال أمر تحديث الاعداد إلى الأجهزة' ,
    'Success.config.update.device.app.settings.notification': 'تم إرسال أمر تحديث إعدادات التطبيق إلى الجهاز.',

    'form.icon.title': 'أيقونة',
    "form.icon.name": 'الاسم',
    'form.icon.file': 'ملف',
    
	'form.configuration.title': 'الاعداد' ,
    'form.configuration.title.typical': 'اعداد نموذجي' ,
    "form.configuration.settings.auto.update": 'تحديث تلقائي',
    'form.configuration.settings.system.update': 'تحديث النظام',
    'form.configuration.settings.system.update.default': 'افتراضي',
    'form.configuration.settings.system.update.immediate': 'فورًا',
    "form.configuration.settings.system.update.scheduled": 'مجدول',
    'form.configuration.settings.system.update.postponed': 'مؤجل',
    "form.configuration.settings.system.update.time": 'وقت التثبيت',
    'form.configuration.settings.system.update.time.from': 'من:',
    'form.configuration.settings.system.update.time.to': 'إلى:',
    "form.configuration.settings.block.status.bar": 'قفل شريط الحالة',
    "form.configuration.settings.mdm.kiosk.mode": 'وضع Kiosk',
    "form.configuration.settings.mdm.app.main": 'التطبيق الرئيسي',
    'form.configuration.settings.mdm.component.event.receiver': 'عنصر - مستلم الحدث',
    "form.configuration.settings.mdm.component.event.receiver.placeholder": 'أدخل اسم العنصر',
    "form.configuration.settings.mdm.component.wifi.ssid": 'WiFi SSID',
    "form.configuration.settings.mdm.component.wifi.ssid.placeholder": 'تسجيل WiFi SSID - اتركه فارغًا للدخول يدويًا',
    "form.configuration.settings.mdm.component.wifi.password": 'كلمة مرور WiFi',
    "form.configuration.settings.mdm.component.wifi.password.placeholder": 'تسجيل مرور WiFi - اتركه فارغًا للدخول يدويًا',
    "form.configuration.settings.mdm.component.wifi.security": 'نوع أمان WiFi',
    "form.configuration.settings.mdm.component.server.url": 'عنوان URL للخادم الجديد',
    "form.configuration.settings.mdm.component.server.url.placeholder": 'يُستخدم للترحيل إلى خادم MDM جديد',
    "form.configuration.settings.mdm.app.content": 'تطبيق المحتوى',
    "form.configuration.settings.mdm.kiosk.home": 'تفعيل زر الصفحة الرئيسية',
    'form.configuration.settings.mdm.kiosk.recents': 'تفعيل الزر ااحديث',
    "form.configuration.settings.mdm.kiosk.notifications": 'تفعيل الإشعارات',
    "form.configuration.settings.mdm.kiosk.system.info": 'تفعيل معلومات شريط الحالة',
    "form.configuration.settings.mdm.kiosk.keyguard": 'تفعيل قفل الشاشة',
    "form.configuration.settings.mdm.lock.safe.settings": 'قفل الإعدادات الآمنة (WiFi , GPS , إلخ)',
    'form.configuration.settings.mdm.allowed.classes': 'الأنشطة المسموح بها',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'فئات مفصولة بفواصل , على سبيل المثال: com.android.settings.homepage.SettingsHomepageActivity',
    "form.configuration.settings.mdm.qrcode.url": 'عنوان URL لرمز الاستجابة السريعة',
    'form.configuration.settings.mdm.hint': 'حدد التطبيق والمكون الرئيسيين',
    'form.configuration.apps.search.label': 'ابحث عن:',
    'form.configuration.apps.sort.label': 'فرز:',
    "form.configuration.apps.sort.byname": 'بالاسم',
    "form.configuration.apps.sort.bypkg": 'بالمعرف',
    "form.configuration.apps.show.systeam.apps": 'إظهار تطبيقات النظام',
    'form.configuration.apps.action.install': 'تثبيت',
    'form.configuration.apps.action.prohibit': 'منع',
    "form.configuration.apps.action.not.install": 'عدم التثبيت',
    "form.configuration.apps.action.delete": 'حذف',
    'form.configuration.apps.action.permit': 'السماح',
    "form.configuration.apps.label.inherit": 'موروث',
    'form.configuration.apps.label.show': 'إظهار' ,
    'form.configuration.apps.label.not.show': 'إخفاء',
    'form.configuration.apps.edit.details': 'معلومات إضافية' ,
    "form.configuration.apps.keycode": 'رمز المفتاح',
    'form.configuration.apps.hint': 'تلميح: لإلغاء ربط التطبيق بالاعداد , حدد الإجراء "حظر" أو "عدم التثبيت".',
    'form.configuration.settings.design.use.default': 'استخدام التصميم الافتراضي' ,
    "form.configuration.settings.design.color.background": 'لون الخلفية',
    'form.configuration.settings.design.color.background.placeholder': 'حدد لونًا' ,
    'form.configuration.settings.design.color.app.names': 'لون أسماء التطبيقات',
    'form.configuration.settings.design.color.app.names.placeholder': 'حدد لونًا' ,
    "form.configuration.settings.design.background.image.url": 'عنوان URL لصورة الخلفية',
    'form.configuration.settings.design.background.image.url.placeholder': 'أدخل عنوان url لصورة الخلفية' ,
    "form.configuration.settings.design.icon": 'حجم الرمز',
    "form.configuration.settings.design.icon.small": 'صغير',
    "form.configuration.settings.design.icon.medium": 'متوسط ​​(+ 20%)',
	"form.configuration.settings.design.icon.large": 'كبير (+ 40%)',
    "form.configuration.settings.design.desktop.header": 'عنوان سطح المكتب',
    "form.configuration.settings.design.desktop.header.no": 'لا',
    "form.configuration.settings.design.desktop.header.deviceid": 'معرف الجهاز',
    "form.configuration.settings.common.name": 'الاسم',
    "form.configuration.settings.common.name.placeholder": 'أدخل اسم الاعداد',
    "form.configuration.settings.common.desc": 'الوصف',
    "form.configuration.settings.common.desc.placeholder": 'أدخل وصف الاعداد',
    "form.configuration.settings.common.admin.pwd": 'كلمة مرور المسؤول',
    "form.configuration.settings.common.admin.pwd.placeholder": 'أدخل كلمة مرور المسؤول',
    "form.configuration.settings.common.gps": 'GPS',
    "form.configuration.settings.common.gps.any": 'أي',
    "form.configuration.settings.common.gps.off": 'معطل',
    "form.configuration.settings.common.gps.on": 'ممكّن',
    "form.configuration.settings.common.bluetooth": 'Bluetooth',
    "form.configuration.settings.common.wifi": 'Wi-Fi',
    "form.configuration.settings.common.mobile.data": 'بيانات الجوال',
    "form.configuration.settings.common.usb.storage": 'حظر تخزين USB',
    "form.configuration.settings.common.brightness": 'إدارة السطوع',
    "form.configuration.settings.common.brightness.none": 'بلا',
    "form.configuration.settings.common.brightness.auto": 'تلقائي',
    "form.configuration.settings.common.brightness.manual": 'القيمة',
    "form.configuration.settings.common.brightness.value": 'سطوع الشاشة',
    "form.configuration.settings.common.timeout": 'إدارة مهلة الشاشة',
    "form.configuration.settings.common.timeout.value": 'مهلة (فترات) الشاشة',
    "form.configuration.settings.common.volume.block": 'تأمين الحجم',
    "form.configuration.settings.common.timezone.mode": 'إدارة المنطقة الزمنية',
    "form.configuration.settings.common.timezone.mode.default": 'بدون اعداد',
    "form.configuration.settings.common.timezone.mode.auto": 'تلقائي',
    "form.configuration.settings.common.timezone.mode.manual": 'يدوي',
    "form.configuration.settings.common.timezone": 'المنطقة الزمنية',
    'form.configuration.settings.common.timezone.placeholder': 'على سبيل المثال أمريكا / لوس أنجليس' ,
    "form.configuration.settings.common.timezone.link": 'قائمة المناطق الزمنية',
    'form.configuration.settings.request.updates': 'تحديث الموقع',
    "form.configuration.settings.request.updates.donottrack": 'عدم التعقب',
    "form.configuration.settings.request.updates.gps": 'بواسطة GPS',
    "form.configuration.settings.request.updates.wifi": 'عبر Wi-Fi',
    'form.configuration.settings.request.updates.prompt.gps': 'لتتبع إحداثيات GPS تحتاج إلى تفعيل GPS' ,
    "form.configuration.settings.request.updates.prompt.wifi": 'لتتبع إحداثيات Wi-Fi , تحتاج إلى تفعيل Wi-Fi',
    "form.configuration.settings.push.options": 'دفع الإخطارات',
    'form.configuration.settings.push.options.mqtt.worker': 'بروتوكول MQTT (حفظ البطارية)' ,
    'form.configuration.settings.push.options.mqtt.alarm': 'بروتوكول MQTT (التسليم الفوري)' ,
    'form.configuration.settings.push.options.polling': 'استطلاع HTTP',
    "form.configuration.settings.password.mode": 'متطلبات كلمة المرور',
    'form.configuration.settings.password.mode.any': 'لا شيء',
    "form.configuration.settings.password.mode.present": 'كلمة المرور تقدم',
    "form.configuration.settings.password.mode.easy": 'سهل (6 رموز على الأقل)',
    "form.configuration.settings.password.mode.moderate": 'معتدل (أكثر من 8 رموز وحروف وأرقام)',
    "form.configuration.settings.password.mode.strong": 'قوي (8+ , أحرف كبيرة وصغيرة , أرقام , علامات)',
    'form.configuration.settings.use.default.launcher': 'استخدم مع المشغل الافتراضي' ,
    "form.configuration.settings.orientation": 'قفل التوجيه',
    "form.configuration.settings.orientation.none": 'لا تغلق',
    'form.configuration.settings.orientation.portrait': 'تنسيق عمودي',
    'form.configuration.settings.orientation.landscape': 'تنسيق افقي',
    'form.configuration.files.search.label': 'بحث:',
    'form.configuration.files.action.upload': 'تحميل',
    'form.configuration.files.action.remove': 'إزالة' ,

	'form.configuration.file.name': 'اسم الملف' ,
    'form.configuration.file.description': 'وصف الملف',
    'form.configuration.file.path': 'مسار على الجهاز',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.file': 'ملف',
    'form.configuration.file.action': 'إجراء',
    'form.configuration.file.action.prompt.1': 'تحميل',
    'form.configuration.file.action.prompt.2': 'إزالة' ,
    "form.configuration.file.remove.prompt.1": 'لن تتم مزامنة هذا الملف مع الأجهزة بعد الآن',
    'form.configuration.file.remove.prompt.2': 'إزالة الملف من الخادم' ,

    "form.password.title": 'تغيير كلمة المرور',
    'form.password.label.user': 'المستخدم',
    "form.password.label.password.new": 'كلمة مرور جديدة',
    "form.password.label.password.new.placeholder": 'أدخل كلمة مرور جديدة',
    "form.password.label.password.confirm": 'تحقق',
    "form.password.label.password.confirm.placeholder": 'أدخل كلمة المرور الجديدة مرة أخرى',

    'form.application.type': 'نوع',
    "form.application.type.option.web": 'صفحة ويب',
    "form.application.type.option.app": 'التطبيق',
    'form.application.pkg': ' الحزمة ID',
    'form.application.from.file': 'محدد من ملف',
    "form.application.name": 'اسم التطبيق',
    'form.application.version': 'الإصدار',
    'form.application.system': 'النظام',
    "form.application.run.after.install": 'تشغيل بعد التثبيت',
    'form.application.run.at.boot': 'تشغيل في الاقلاع',
    'form.application.url': 'URL',
    'form.application.file': 'ملف',
    "form.application.showLabel": 'إظهار الرمز',
    'form.application.iconText': 'نص أيقونة',
    'form.application.iconText.placeholder': '(افتراضي)',
    "form.application.versions.title": 'إصدارات التطبيق',
    'form.application.icon': 'أيقونة',
    'form.application.icon.default': '(افتراضي)',
    "form.application.icon.add": 'إضافة رمز',

    'form.application.setting.app': 'تطبيق',
    "form.application.setting.app.placeholder": 'حدد تطبيقًا',
    'form.application.setting.name': 'ينسب',
    'form.application.setting.value': 'القيمة',
    'form.application.setting.comment': 'تعليق',
    'form.application.setting.type': 'نوع',
    "form.application.setting.readonly": 'لا يتغير على الجهاز',
    
    'form.application.configurations.app': 'تطبيق',
    "form.application.configurations.configs": 'الاعدادات',

    "form.configuration.copy.new.name": 'اسم جديد',
    "form.configuration.copy.new.name.placeholder": 'أدخل اسم الاعداد الجديد',

	"form.customer.name": 'الاسم',
    "form.customer.name.placeholder": 'أدخل اسم المؤسسة',
    "form.customer.apiKey": 'مفتاح API',
    "form.customer.apiKey.placeholder": 'أدخل مفتاح API',
    "form.customer.prefix": 'بادئة',
    "form.customer.prefix.placeholder": 'أدخل بادئة رقم الجهاز',
    "form.customer.device.configuration": 'اعداد الجهاز',
    "form.customer.desc": 'الوصف',
    "form.customer.desc.placeholder": 'أدخل وصفًا للمؤسسة',
    "form.customer.copy.configuration": 'نسخ الاعدادات',
    "form.customer.copy.design": 'نسخ التصميم',

    'form.device.number': 'رقم',
    "form.device.number.hint": 'لا تستخدم أحرفًا خاصة',
    'form.device.desc': 'الوصف',
    "form.device.groups": 'المجموعات',
    'form.device.config': 'الاعداد' ,
    "form.device.imei": 'IMEI',
    "form.device.phone.number": 'رقم الهاتف',

    "form.update.device.config": 'الاعداد',

    'form.file.file': 'ملف',
    'form.file.path': 'مسار',
    'form.file.path.placeholder': 'أدخل مسارًا نسبيًا , على سبيل المثال "/الملفات /"',

    'form.file.apps.name': 'اسم التطبيق' ,
    "form.file.apps.pkg": 'معرف الحزمة',
    'form.file.apps.version': 'الإصدار',

    "form.group.name": 'الاسم',
    "form.group.name.placeholder": 'أدخل اسم المجموعة',

    'form.user.login': 'تسجيل الدخول',
    "form.user.login.placeholder": 'أدخل تسجيل دخول المستخدم',
    "form.user.name": 'الاسم',
    "form.user.name.placeholder": 'أدخل اسم المستخدم الخاص بك',
    "form.user.role": 'الدور',
    "form.user.all.devices.available": 'جميع الأجهزة متوفرة',
    "form.user.available.groups": 'مجموعات الأجهزة المتاحة',
    "form.user.password.new": 'كلمة مرور جديدة',
    "form.user.password": 'كلمة المرور',
    "form.user.password.new.placeholder": 'أدخل كلمة مرور جديدة',
    "form.user.password.confirm": 'تحقق',
    "form.user.password.confirm.placeholder": 'أدخل كلمة المرور الجديدة مرة أخرى',

    'form.settings.hints.title': 'تلميحات',

    'form.settings.plugins.title': 'المكونات الإضافية المستخدمة',

	"form.settings.common.title": 'عرض جدول الجهاز',
    "form.settings.common.visible.columns":' "أعمدة مرئية في جدول" الأجهزة "',
    "form.settings.common.status": 'الحالة',
    "form.settings.common.role": 'دور المستخدمين',
    "form.settings.common.date": 'التاريخ',
    "form.settings.common.device.number": 'رقم الجهاز',
    "form.settings.common.imei": 'IMEI',
    "form.settings.common.phone.number": 'رقم الهاتف',
    "form.settings.common.phone.model": 'طراز الهاتف',
    "form.settings.common.status.permissions": 'حالة الإذن',
    "form.settings.common.status.installation": 'حالة التثبيت',
    'form.settings.common.status.files': 'حالة الملفات' ,
    "form.settings.common.config": 'الاعداد',
    "form.settings.common.desc": 'الوصف',
    "form.settings.common.group": 'مجموعة',
    "form.settings.common.launcher.version": 'إصدار المشغل',
    "form.settings.common.battery.level": 'مستوى البطارية',
    'form.settings.common.default.launcher': 'قاذفة افتراضية' ,

    'form.settings.design.title': 'التصميم الافتراضي',
    'form.settings.design.color.font': 'لون الخلفية',
    "form.settings.design.color.font.placeholder": 'حدد لونًا',
    "form.settings.design.color.app.names": 'لون أسماء التطبيقات',
    'form.settings.design.color.app.names.placeholder': 'حدد لونًا',
    "form.settings.design.url.background.image": 'عنوان URL لصورة الخلفية',
    "form.settings.design.url.background.image.placeholder": 'أدخل عنوان URL لصورة الخلفية',
    "form.settings.design.size.icon": 'حجم الرمز',
    "form.settings.design.size.icon.small": 'صغير',
    "form.settings.design.size.icon.medium": 'متوسط ​​(+ 20%)',
    "form.settings.design.size.icon.large": 'كبير (+ 40%)',
    "form.settings.design.desktop.header": 'عنوان سطح المكتب',
    "form.settings.design.desktop.header.no": 'لا',
    "form.settings.design.desktop.header.device.id": 'معرف الجهاز',

    "form.settings.lang.title": 'إعدادات اللغة',
    "form.settings.lang.use.default": 'استخدام اللغة الافتراضية',
    "form.settings.lang.use": 'استخدام اللغة',
    'form.settings.lang.en': 'English',
    'form.settings.lang.ru': 'الروسية',
    'form.settings.lang.fr': 'فرنسي',
    'form.settings.lang.ar': 'عربي',

	"form.settings.misc.title": 'إعدادات متنوعة',
    "form.settings.misc.phone.format": 'تنسيق رقم الهاتف',
    "form.settings.misc.phone.format.placeholder": '+9 (999) 999-99-99',
    "form.settings.misc.create.new.devices": 'إضافة جهاز عند الوصول الأول',
    "form.settings.misc.new.device.config": 'اعداد جهاز جديد',
    "form.settings.misc.new.device.group": 'مجموعة أجهزة جديدة',

    "form.settings.groups.title": 'مجموعات',
    "form.settings.groups.search.placeholder": 'بحث المجموعة',

    'form.settings.users.title': 'المستخدمون',
    "form.settings.users.search.placeholder": 'بحث عن المستخدم',

    'form.qr.device.number.placeholder': 'أدخل ID الجهاز ...',
    "form.qr.code.image.alt": 'رمز QR',

    "form.profile.title": 'تغيير كلمة المرور',
    "form.profile.password.old": 'كلمة المرور القديمة',
    "form.profile.password.old.placeholder": 'أدخل كلمة المرور القديمة',
    "form.profile.password.new": 'كلمة مرور جديدة',
    "form.profile.password.new.placeholder": 'أدخل كلمة مرور جديدة',
    "form.profile.password.confirm": 'تحقق',
    "form.profile.password.confirm.placeholder": 'أدخل كلمة المرور الجديدة مرة أخرى',

    "tab.customers": 'المنظمات',
    "tab.common.applications": 'التطبيقات المشتركة',

    "tab.devices": 'الأجهزة',
    "tab.applications": 'التطبيقات',
    "tab.configurations": 'الاعدادات',
    "tab.files": 'الملفات',
    "tab.default.design": 'التصميم الافتراضي',
    "tab.common.settings": 'عرض جدول الجهاز',
    "tab.users": 'المستخدمون',
    "tab.groups": 'المجموعات',
    "tab.language": 'اللغة والإعدادات الأخرى',
    'tab.license': 'رخصة',
    "tab.hints": 'تلميحات',
    "tab.plugins": 'المكونات الإضافية',
    
 	"tab.configeditor.common.settings": 'الإعدادات العامة',
    "tab.configeditor.design.settings": 'إعدادات التصميم',
    "tab.configeditor.applications": 'التطبيقات',
    "tab.configeditor.mdm.settings": 'إعدادات MDM',
    "tab.configeditor.app.settings": 'إعدادات التطبيقات',
    'tab.configeditor.files': 'الملفات' ,
    
    'search.placeholder.file': 'ملف البحث',
    'search.placeholder.configuration': 'البحث عن الاعداد',
    'search.placeholder.customer': 'ابحث عن منظمة',
    'search.placeholder.application': 'ابحث عن تطبيق' ,
    'search.placeholder.application.setting': 'ابحث عن إعداد تطبيق' ,
    'search.placeholder.device': 'ابحث عن جهاز' ,
    'search.placeholder.address': 'البحث عن العنوان',
    'search.placeholder.point': 'بحث الموقع',
    'search.placeholder.message': 'البحث عن الرسائل',
    'search.placeholder': 'بحث ...',
    'search.placeholder.from': 'من ...',
    'search.placeholder.to': 'إلى ...',

    "table.heading.customer.name": 'الاسم',
    "table.heading.customer.desc": 'الوصف',
    "table.heading.customer.registration.time": 'مسجل',
    "table.heading.customer.last.login.time": 'آخر تسجيل دخول',
    "table.heading.customer.actions": 'الإجراءات',

    'table.heading.configuration.name': 'اسم',
    'table.heading.configuration.desc': 'الوصف',
    "table.heading.configuration.actions": 'الإجراءات',

    'table.heading.application.setting.app.pkg': 'الحزمة ID',
    'table.heading.application.setting.app.name': 'اسم التطبيق',
    'table.heading.application.setting.name': 'سمة',
    "table.heading.application.setting.value": 'القيمة',
    "table.heading.application.setting.comment": 'تعليق',
    "table.heading.application.setting.lastUpdate": 'تاريخ الإنشاء',

    'table.heading.file.url': 'URL',
    "table.heading.file.devicepath": 'مسار على الجهاز',
    'table.heading.file.description': 'وصف الملف',
    "table.heading.file.action": 'إجراء',
    "table.heading.file.lastUpdate": 'تاريخ الإنشاء',
    
    'table.heading.application.pkg': 'الحزمة ID',
    'table.heading.application.name': 'اسم التطبيق',
    "table.heading.application.version": 'الإصدار',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'أيقونة',
    "table.heading.application.actions": 'الإجراءات',
    'table.heading.application.order': 'ترتيب',

    "table.heading.device.status": 'الحالة',
    "table.heading.device.date": 'التاريخ',
    "table.heading.device.device.number": 'رقم الجهاز',
    "table.heading.device.imei": 'IMEI',
    "table.heading.device.phone.number": 'رقم الهاتف',
    "table.heading.device.phone.model": 'طراز الهاتف',
    "table.heading.device.status.permissions": 'حالة الإذن',
    "table.heading.device.status.installation": 'حالة التثبيت',
    'table.heading.device.status.files': 'حالة الملفات',
    "table.heading.device.configuration": 'الاعداد',
    "table.heading.device.desc": 'الوصف',
    "table.heading.device.group": 'مجموعة',
    'table.heading.device.launcher.version': 'إصدار المشغل' ,
    "table.heading.device.battery.level": 'مستوى البطارية',
    'table.heading.device.default.launcher': 'تعيين كافتراضي' ,
    "table.heading.device.actions": 'الإجراءات',

    "table.heading.group.name": 'الاسم',
    "table.heading.group.actions": 'الإجراءات',

	'table.heading.file.name': 'اسم الملف',
    'table.heading.file.path': 'مسار',
    "table.heading.file.address": 'العنوان',
    "table.heading.file.actions": 'الإجراءات',

    'table.heading.users.login': 'تسجيل الدخول',
    'table.heading.users.name': 'اسم',
    "table.heading.users.role": 'الدور',
    "table.heading.users.actions": 'الإجراءات',

    "table.heading.common.apps.customer": 'منظمة',
    "table.heading.common.apps.pkg": 'معرف الحزمة',
    "table.heading.common.apps.name": 'اسم التطبيق',
    "table.heading.common.apps.version": 'إصدار',
    "table.heading.common.apps.url": 'URL',
    "table.heading.common.apps.label": 'أيقونة',
    "table.heading.common.apps.actions": 'الإجراءات',

    'notfound.devices': 'لا توجد أجهزة لعرضها.',
    'notfound.files': 'قائمة الملفات فارغة.',
    'notfound.configurations': 'لم يتم العثور على اعدادات.',
    'notfound.customers': 'لم يتم العثور على المنظمات.',
    'notfound.common.apps':' لا توجد تطبيقات لعرضها. ',
    'notfound.applications':' لم يتم العثور على التطبيقات ',
    'notfound.groups': 'لم يتم العثور على مجموعات. جرب استعلامًا مختلفًا. ',
    'notfound.users': 'لم يتم العثور على المستخدمين. جرب طلب بحث مختلف. ',
    'notfound.apps.for.display': 'لا توجد تطبيقات لعرضها.',
    'notfound.app.versions.for.display': 'لا توجد إصدارات لعرضها.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    "menu.about": 'حول',
    "menu.profile": 'الملف الشخصي',
    "menu.panel.master": 'لوحة رئيسية',
    "menu.panel.main": 'اللوحة الرئيسية',
    "menu.logout": 'تسجيل الخروج',
    "menu.functions": 'وظائف',
    "menu.settings": 'الإعدادات',
    "menu.show.hints": 'إظهار التلميحات',

    'plugin.name.not.specified': '<< اسم الوظيفة غير محدد >>',
    
	"breadcrumb.devices": 'الأجهزة',
    "breadcrumb.applications": 'التطبيقات',
    "breadcrumb.configurations": 'الاعدادات',
    "breadcrumb.files": 'الملفات',
    'breadcrumb.default.design': 'التصميم افتراضيًا',
    "breadcrumb.common.settings": 'عرض جدول الجهاز',
    "breadcrumb.language.settings": 'اللغة وإعدادات أخرى',
    "breadcrumb.license.settings": 'رخصة',
    "breadcrumb.users": 'المستخدمون',
    "breadcrumb.groups": 'المجموعات',
    "breadcrumb.hints": 'تلميحات',
    "breadcrumb.plugins": 'الإضافات',
    'breadcrumb.config.details': 'تفاصيل',
    "breadcrumb.application.versions": 'إصدارات',

    "app.name": 'Headwind MDM',
    "app.description": 'هو نظام إدارة الأجهزة المحمولة مفتوح المصدر',
    "app.title": 'لوحة ويب Headwind MDM',

    "box.show.my.apps.only": 'عرض تطبيقاتي فقط',
    'config.app.version.upgrade.message': 'الإصدار المثبت ${installVersion} , الإصدار المتاح ${latestVersion}',

    "about.line.1": 'لوحة تحكم Headwind MDM',
    'about.line.2': 'مشغل المؤسسة لـ Android',
    'about.line.3': 'الإصدار ${versionNumber}',
    'about.line.4': 'المكونات الإضافية المثبتة',

    'common.app.clarification': 'هذا التطبيق عام وغير متاح للتحرير. لإضافة إصدار آخر من هذا التطبيق , يرجى الاتصال بالمسؤول. ',

    "qrcode.help.line1": 'لإعداد جهاز Android (الإصدار 7 أو أعلى) في وضع (شركة) مُدار:',
    "qrcode.help.line2": 'إعادة ضبط الجهاز على إعدادات المصنع',
    "qrcode.help.line3": 'انقر 7 مرات في أي مكان من شاشة البداية (يجب عليك إدخال وضع مسح رمز QR مخفي)',
    "qrcode.help.line4": 'اتبع إرشادات الجهاز: قبول الشروط , والاتصال بشبكة Wi-Fi , ومسح رمز الاستجابة QR السريعة هذا',

    'qrcode.help.line5': 'Tقد يحتوي رمز QR على ID الجهاز لـ Headwind MDM (لذا لا تحتاج إلى إدخاله على جهاز محمول). لتضمين ID الجهاز في رمز QR ، أدخل ID الجهاز على هذه الشاشة وانقر على "تجديد".',
    
    'form.configuration.app.version.select.select.title': 'حدد الإصدار المراد تثبيته' ,
    'form.configuration.app.version.select.version.check.off': 'تعطيل فحص الإصدار',
    'form.configuration.app.version.select.upgrade.warning': 'ترقية التطبيق "${v1}" إلى الإصدار "${v3}" للتهيئة "${v2}"؟',
    'form.configuration.app.version.select.downgrade.warning': 'الرجوع إلى إصدار أقدم احذف جميع هذه التطبيقات على جميع الأجهزة! هل تريد الرجوع إلى إصدار أقدم من إصدار التطبيق "${v1}" إلى الإصدار "${v2}"؟ "',

    "hint.step.1": 'انقر هنا لبدء تسجيل الجهاز',
    "hint.step.2": 'انقر هنا لفتح رمز الاستجابة السريعة QR',
    "hint.step.3": 'انقر هنا لمعرفة كيفية فتح ماسح رمز الاستجابة السريعة QR  على الجهاز',
    'hint.step.4': ' QR ابحث عن ID الجهاز المتاح في علامة التبويب «الأجهزة». انقر فوق "تجديد" لتضمينه في رمز الاستجابة السريعة. "',

    'ie.browser.notice.1': 'للأسف , Internet Explorer غير مدعوم.',
    'ie.browser.notice.2': 'المتصفح الموصى به لاستخدام Headwind MDM - <a href="https://support.google.com/chrome/answer/95346؟co=GENIE.Platform٪3DDesktop"> Chrome < / أ>. ',

    'form.resolved.duplicate.pkg.text1': 'ID الحزمة "${pkg}" مستخدم بالفعل بواسطة التطبيقات المدرجة أدناه.',
    'form.resolved.duplicate.pkg.text2': 'هل تريد إضافة تطبيق جديد أم إصدار جديد من تطبيق موجود؟',
    'form.resolved.duplicate.pkg.text3': 'إصدار جديد لـ',
    
    "tooltip.usage.byconfigurations": 'مستخدمة بواسطة الاعدادات',
    "tooltip.usage.byapps": 'مستخدمة بواسطة التطبيقات',
    "tooltip.usage.byicons": 'مستخدمة بواسطة الرموز',

    'form.devices.label.params.more': 'المزيد من المعلمات',
    'form.devices.label.params.less': 'معلمات أقل',
    "form.devices.label.installation.status": 'حالة التثبيت',
    "format.devices.date.createTime": 'dd/MM/yyyy HH: mm:ss',
    "format.devices.date.datePicker": 'dd-MM-yyyy',

    'form.devices.selection.install.status.default': 'حالة التثبيت ...',
    'form.devices.selection.install.status.all': 'الكل',
    "form.devices.selection.install.status.success": 'نجاح',
    'form.devices.selection.install.status.version.mismatch': 'عدم تطابق الإصدار',
    'form.devices.selection.install.status.failure': 'فشل',
    "form.devices.selection.imei.changed": 'تم تغيير IMEI مؤخرًا',

    'search.placeholder.launcher.version': 'إصدار المشغل' ,
    'error.date.range.invalid': 'فاصل تاريخ غير صالح',

    'yes':' نعم',
    'no': 'لا'
};
