if (! document.localization) document.localization = [];

document.localization ['en_US'] = {
    'login.username': 'Username or email',
    'login.username.placeholder': 'Enter your username or email',
    'login.password': 'Password:',
    'login.password.placeholder': 'Enter password',
    'login.submit': 'Login',
    'login.password.incorrect': 'Invalid username or password',

    'header.label.username': 'Username',

    'devices.group.options.all': 'All groups',
    'devices.configuration.options.all': 'All configurations',
    'devices.permissions.all': 'All permissions are granted',
    'devices.permissions.not.as.device.admin': '- The application is not installed as a device administrator',
    'devices.permissions.window.overlap.prohibited': '- Overlay on top of other windows is not available',
    'devices.permissions.history.access.prohibited': '- Access to usage history is not configured',
    'devices.unknown': 'Unknown',
    'devices.model.unknown': 'Unknown',
    'devices.date.unknown': 'unknown',
    'devices.date.format': 'dd/MM HH:mm',
    'devices.app.installed': '- ${applicationName}: Installed.',
    'devices.app.not.installed': '- ${applicationName}: not installed.',
    'devices.app.version.available': ', available ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: installed ${applicationInstalledVersion}, available ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, removal is required',
    'devices.no.data': 'The device has not transmitted data',
    'devices.settings.conformance.broken': 'Mismatch with settings: (${serverData})',

    'button.apply': 'Apply',
    'button.gps.on': 'Enable GPS',
    'button.wifi.on': 'Enable Wi-Fi',
    'button.notify.update': 'Notify on update',
    'button.app.settings': 'Application settings',
    'button.ok': 'OK',
    'button.help': 'Help',
    'button.new.app': 'New application',
    'button.new.app.version': 'New version',
    'button.upgrade': 'Upgrade',
    'button.renew.config': 'Update on devices',
    'button.common': 'Common application',
    'button.close': 'Close',
    'button.yes': 'Yes',
    'button.cancel': 'Cancel',
    'button.save': 'Save',
    'button.save.and.close': 'Save and close',
    'button.more': 'More ...',
    'button.cleanup': 'Clear',
    'button.add': 'Add',
    'button.add.icon': 'New Icon',
    'button.search': 'Search',
    'button.export': 'Export',
    'button.change': 'Edit',
    'button.copy': 'Copy',
    'button.qrcode': 'QR code',
    'button.application': 'Application',
    'button.change.password': 'Change password',
    'button.set.configuration': 'Set configuration',
    'button.delete': 'Delete',
    'button.login': 'Login',
    'button.renew.code': 'Renew',
    'button.configurations': 'Configurations',
    'button.set.configurations': 'Specify Configurations',
    'button.edit.versions': 'Versions',
    'button.edit': 'Edit',
    'button.change.common.app': 'Edit Shared Application',
    'button.delete.common.app': 'Delete Shared Application',
    'button.turn.common.app': 'Make Common',
    'button.hints.enable': 'Show tooltips',
    'button.hints.disable': 'Hide tooltips',
    'button.plugin.deviceimport.import': 'Import',
    'button.plugin.deviceimport.newimport': 'New Import',
    'button.plugin.deviceimport.back': 'Back',
    'button.plugin.deviceexport.export': 'Export',
    'button.plugin.deviceinfo.export': 'Export',
    'button.plugin.deviceinfo.view': 'View',
    'button.plugin.deviceinfo.dynamic': 'Dynamic data',
    
    'question.impersonate.user': 'Log in to the application as the administrator of the organization "${customerName}"?',
    'question.delete.file': 'Delete file "${fileName}"?',
    'question.delete.customer': 'Delete organization "${customerName}"?',
    'question.delete.user': 'Delete user "${username}"?',
    'question.delete.application': 'Delete application "${applicationName}"?',
    'question.delete.application.version': 'Delete version "${applicationVersion}"?',
    'question.delete.configuration': 'Delete configuration "${configurationName}"??',
    'question.delete.group': 'Delete group "${groupName}"?',
    'question.delete.device': 'Delete the device with the number "${deviceNumber}"?',
    'question.exit.without.saving': 'Changes are not saved. Anyway leave this page?',
    'question.turn2common.application': 'Share the application "${applicationName}"?',
    'question.app.upgrade': 'Update application "${v1}" to latest version for configuration "${v2}"?',

    'error.application.setting.empty.app': 'Specify application',
    'error.application.setting.empty.name': 'Enter a name',
    'error.application.setting.empty.value': 'Specify a value',

    'error.icon.dimension.invalid': 'Icon must be square',
    'error.icon.empty.name': 'Enter the name of the icon',
    'error.icon.empty.file': 'Upload icon file',
    'error.application.version.pkg.mismatch': 'Package ID of the file (${actual}) does not correspond to the application (${expected})',
    'error.empty.user': 'Select a user',
    'error.empty.user.name': 'Fill in the username',
    'error.empty.user.login': 'Fill in the user login',
    'error.empty.user.role': 'Select a user role',
    'error.empty.password': 'Enter new password',
    'error.empty.password.confirm': 'Enter password confirmation',
    'error.empty.group.name': 'Fill in the group name',
    'error.empty.configuration': 'Specify the configuration',
    'error.empty.configuration.name': 'Fill in the configuration name',
    'error.empty.configuration.password': 'Fill in the password',
    'error.empty.configuration.contentApp': 'No content application specified',
    'error.invalid.configuration.mainApp': 'In the MDM settings, the wrong main application is used',
    'error.invalid.configuration.contentApp': 'Invalid content application used in MDM settings',
    'error.mismatch.password': 'Password and password confirmation must match',
    'error.empty.customer.name': 'Fill in the name of the organization',
    'error.empty.customer.prefix': 'Fill in the device number prefix',
    'error.empty.customer.device.configuration': 'Select device configuration',
    'error.empty.customer.duplicate.prefix': 'Prefix already in use',
    'error.duplicate.customer.name': 'The organization with the entered name already exists. Try a different name.',
    'error.duplicate.group.name': 'The group with the entered name already exists. Try a different name.',
    'error.duplicate.configuration.name': 'The configuration with the entered name already exists. Try a different name.',
    'error.duplicate.device.number': 'A device with this number already exists',
    'error.plugin.devicelog.date.range.invalid': 'Invalid date interval',
    'error.plugin.audit.date.range.invalid': 'Invalid date interval',
    'error.plugin.deviceinfo.date.range.invalid': 'Invalid date interval',
    'error.internal.server': 'Internal server error',
    'error.permission.denied': 'No rights to execute',
    'error.request.failure': 'Request failure',
    'error.configuration.device.use': 'Cannot delete this configuration, it is used on devices. First go to "Devices", find the devices using this configuration and change their settings.',
    'error.invalid.system.update.time': 'Invalid installation interval',

    'error.notfound.device': 'Device not found',
    'error.duplicate.login': 'Such a login is already in use',
    'error.duplicate.group': 'A group with the same name already exists',
    'error.duplicate.application': 'An application with this package ID and version already exists',
    'error.recent.application.version.exists': 'More recent application version exists',
    'error.common.application.access.prohibited': 'Managing of the common applications is allowed by Super-Administrator only',
    'error.application.config.reference.exists': 'The application is used in configurations and cannot be deleted',
    'error.application.version.deletion.prohibited': 'The version is either unique or used in configurations and cannot be deleted',
    'error.duplicate.file': 'A file with the same name already exists',
    'error.duplicate.configuration': 'A configuration with this name already exists',
    'error.notfound.customer.admin': 'Administrator account not found',
    'error.apk.file.required': 'Select the file with the .apk extension',
    'error.empty.app.name': 'Enter application name',
    'error.empty.app.pkg': 'Enter the package ID',
    'error.empty.app.url': 'Enter the URL',
    'error.empty.app.iconText': 'Enter the icon text',
    'error.empty.app.version': 'Enter the version of the application',
    'error.notempty.group': 'This group includes one or more devices. You cannot remove it.',
    'error.file.empty': 'Upload a new file',
    'error.file.deletion': 'Error deleting file on server',
    'error.file.save': 'Error while saving file on server',
    'error.password.wrong': 'Invalid password',
    'error.password.empty': 'Password not specified',
    'error.params.missing': 'Missing parameters:',
    'error.empty.push.options': 'Please select the Push notifications options',

    'table.filtering.check.all': 'Select All',
    'table.filtering.uncheck.all': 'Cancel All',
    'table.filtering.suffix.configuration': 'configurations',
    'table.filtering.suffix.group': 'groups',
    'table.filtering.no.selected.configuration': 'No configurations selected',
    'table.filtering.no.selected.group': 'No selected groups',

    'success.admin.created': 'Administrator account created:\n ${adminCredentials}',
    'success.plugin.devicelog.settings.saved': 'Settings saved successfully',
    'success.plugin.deviceinfo.settings.saved': 'Settings saved successfully',
    'success.uploading.file': 'The file is uploaded to the server ...',
    'success.loading.devices': 'Loading device list ...',
    'success.loading.customer': 'Loading customer details ...',
    'success.file.uploaded': 'File uploaded successfully.',
    'success.file.uploaded.need.save': 'File uploaded successfully. Enter the relative path and click "Save".',
    'success.settings.design.saved': 'Design settings saved successfully',
    'success.settings.common.saved': 'General settings saved successfully',
    'success.settings.language.saved': 'Language settings saved successfully',
    'success.settings.apiKey.saved': 'API key saved successfully',
    'success.settings.hints.enabled': 'Hints enabled',
    'success.settings.hints.disabled': 'Hints disabled',
    'success.configuration.saved': 'Configuration saved successfully',
    'success.operation.completed': 'Operation completed successfully',
    'success.plugins.disabled': 'Settings saved successfully',
    'success.config.update.notification': 'Configuration update command has been sent to devices',
    'success.config.update.device.app.settings.notification': 'The command to update application settings has been sent to the device.',

    'form.icon.title': 'Icon',
    'form.icon.name': 'Name',
    'form.icon.file': 'File',

    'form.configuration.title': 'Configuration',
    'form.configuration.title.typical': 'Typical configuration',
    'form.configuration.settings.auto.update': 'Auto-Update',
    'form.configuration.settings.system.update': 'System Update',
    'form.configuration.settings.system.update.default': 'Default',
    'form.configuration.settings.system.update.immediate': 'Immediately',
    'form.configuration.settings.system.update.scheduled': 'Scheduled',
    'form.configuration.settings.system.update.postponed': 'Postponed',
    'form.configuration.settings.system.update.time': 'Installation time',
    'form.configuration.settings.system.update.time.from': 'from:',
    'form.configuration.settings.system.update.time.to': 'to:',
    'form.configuration.settings.block.status.bar': 'Status bar lock',
    'form.configuration.settings.mdm.kiosk.mode': 'Kiosk Mode',
    'form.configuration.settings.mdm.app.main': 'Main Application',
    'form.configuration.settings.mdm.component.event.receiver': 'Component - event recipient',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Enter the name of the component',
    'form.configuration.settings.mdm.app.content': 'Content Application',
    'form.configuration.settings.mdm.qrcode.url': 'QR code URL',
    'form.configuration.settings.mdm.hint': 'Select the main application and component',
    'form.configuration.apps.search.label': 'Search for:',
    'form.configuration.apps.sort.label': 'Sort:',
    'form.configuration.apps.sort.byname': 'By name',
    'form.configuration.apps.sort.bypkg': 'By ID',
    'form.configuration.apps.show.systeam.apps': 'Show System Applications',
    'form.configuration.apps.action.install': 'Install',
    'form.configuration.apps.action.prohibit': 'Prohibit',
    'form.configuration.app.versions.action.prohibit': 'Do not install',
    'form.configuration.apps.action.delete': 'Delete',
    'form.configuration.apps.action.permit': 'Permit',
    'form.configuration.apps.label.inherit': 'Inherited',
    'form.configuration.apps.label.show': 'Show',
    'form.configuration.apps.label.not.show': 'Hide',
    'form.configuration.settings.design.use.default': 'Use default design',
    'form.configuration.settings.design.color.background': 'Background Color',
    'form.configuration.settings.design.color.background.placeholder': 'Select a color',
    'form.configuration.settings.design.color.app.names': 'Application Names Color',
    'form.configuration.settings.design.color.app.names.placeholder': 'Select a color',
    'form.configuration.settings.design.background.image.url': 'URL of the background image',
    'form.configuration.settings.design.background.image.url.placeholder': 'Enter the url of the background image',
    'form.configuration.settings.design.icon': 'Icon size',
    'form.configuration.settings.design.icon.small': 'Small',
    'form.configuration.settings.design.icon.medium': 'Average (+ 20%)',
    'form.configuration.settings.design.icon.large': 'Large (+ 40%)',
    'form.configuration.settings.design.desktop.header': 'Desktop title',
    'form.configuration.settings.design.desktop.header.no': 'No',
    'form.configuration.settings.design.desktop.header.deviceid': 'Device ID',
    'form.configuration.settings.common.name': 'Name',
    'form.configuration.settings.common.name.placeholder': 'Enter the configuration name',
    'form.configuration.settings.common.desc': 'Description',
    'form.configuration.settings.common.desc.placeholder': 'Enter the configuration description',
    'form.configuration.settings.common.admin.pwd': 'Administrator Password',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Enter the administrator password',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Any',
    'form.configuration.settings.common.gps.off': 'Disabled',
    'form.configuration.settings.common.gps.on': 'Enabled',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Mobile data',
    'form.configuration.settings.common.usb.storage': 'USB storage',
    'form.configuration.settings.request.updates': 'Update Location',
    'form.configuration.settings.request.updates.donottrack': 'Do Not Track',
    'form.configuration.settings.request.updates.gps': 'By GPS',
    'form.configuration.settings.request.updates.wifi': 'Over Wi-Fi',
    'form.configuration.settings.request.updates.prompt.gps': 'To track GPS coordinates you need to enable GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'To track Wi-Fi coordinates you need to enable Wi-Fi',
    'form.configuration.settings.push.options' : 'Push notifications',
    'form.configuration.settings.push.options.mqtt.worker' : 'MQTT protocol (save battery)',
    'form.configuration.settings.push.options.mqtt.alarm' : 'MQTT protocol (instant delivery)',
    'form.configuration.settings.push.options.polling' : 'HTTP polling',

    'form.password.title': 'Change Password',
    'form.password.label.user': 'User',
    'form.password.label.password.new': 'New password',
    'form.password.label.password.new.placeholder': 'Enter a new password',
    'form.password.label.password.confirm': 'Verify',
    'form.password.label.password.confirm.placeholder': 'Enter the new password again',

    'form.application.type': 'Type',
    'form.application.type.option.web': 'Web-page',
    'form.application.type.option.app': 'Application',
    'form.application.pkg': 'Package ID',
    'form.application.from.file': 'Determined from file',
    'form.application.name': 'Application Name',
    'form.application.version': 'Version',
    'form.application.system': 'System',
    'form.application.run.after.install': 'Run after installation',
    'form.application.url': 'URL',
    'form.application.file': 'File',
    'form.application.showLabel': 'Show Icon',
    'form.application.iconText': 'Icon Text',
    'form.application.iconText.placeholder': '(default)',
    'form.application.versions.title': 'Versions of application',
    'form.application.icon': 'Icon',
    'form.application.icon.default': '(default)',
    'form.application.icon.add': 'Add icon',

    'form.application.setting.app': 'Application',
    'form.application.setting.app.placeholder': 'Select an application',
    'form.application.setting.name': 'Title',
    'form.application.setting.value': 'Value',
    'form.application.setting.comment': 'Comment',
    'form.application.setting.type': 'Type',
    'form.application.setting.readonly': 'Does not change on the device',
    
    'form.application.configurations.app': 'Application',
    'form.application.configurations.configs': 'Configurations',

    'form.configuration.copy.new.name': 'New name',
    'form.configuration.copy.new.name.placeholder': 'Enter the new configuration name',

    'form.customer.name': 'Name',
    'form.customer.name.placeholder': 'Enter the name of the organization',
    'form.customer.apiKey': 'API key',
    'form.customer.apiKey.placeholder': 'Enter the API key',
    'form.customer.prefix': 'Prefix',
    'form.customer.prefix.placeholder': 'Enter the device number prefix',
    'form.customer.device.configuration': 'Device configuration',
    'form.customer.desc': 'Description',
    'form.customer.desc.placeholder': 'Enter a description of the organization',
    'form.customer.copy.configuration': 'Copy configurations',
    'form.customer.copy.design': 'Copy design',

    'form.device.number': 'Number',
    'form.device.desc': 'Description',
    'form.device.groups': 'Groups',
    'form.device.config': 'Configuration',
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Phone Number',

    'form.update.device.config': 'Configuration',

    'form.file.file': 'File',
    'form.file.path': 'Path',
    'form.file.path.placeholder': 'Enter a relative path, for example "/ files /"',

    'form.file.apps.name': 'Application Name',
    'form.file.apps.pkg': 'Package ID',
    'form.file.apps.version': 'Version',

    'form.group.name': 'Name',
    'form.group.name.placeholder': 'Enter the name of the group',

    'form.user.login': 'Login',
    'form.user.login.placeholder': 'Enter user login',
    'form.user.name': 'Name',
    'form.user.name.placeholder': 'Enter your username',
    'form.user.role': 'Role',
    'form.user.all.devices.available': 'All devices are available',
    'form.user.available.groups': 'Available device groups',
    'form.user.password.new': 'New Password',
    'form.user.password': 'Password',
    'form.user.password.new.placeholder': 'Enter a new password',
    'form.user.password.confirm': 'Verify',
    'form.user.password.confirm.placeholder': 'Enter the new password again',

    'form.settings.hints.title': 'Hints',

    'form.settings.plugins.title': 'Used Plugins',

    'form.settings.common.title': 'General Settings',
    'form.settings.common.visible.columns': 'Visible columns in the "Devices" table',
    'form.settings.common.status': 'Status',
    'form.settings.common.role': 'Users role',
    'form.settings.common.date': 'Date',
    'form.settings.common.device.number': 'Device number',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Phone Number',
    'form.settings.common.phone.model': 'Phone Model',
    'form.settings.common.status.permissions': 'Permission Status',
    'form.settings.common.status.installation': 'Installation Status',
    'form.settings.common.config': 'Configuration',
    'form.settings.common.desc': 'Description',
    'form.settings.common.group': 'Group',
    'form.settings.common.launcher.version': 'Launcher version',
    'form.settings.common.battery.level': 'Battery level',

    'form.settings.design.title': 'Default Design',
    'form.settings.design.color.font': 'Background Color',
    'form.settings.design.color.font.placeholder': 'Select a color',
    'form.settings.design.color.app.names': 'Application Names Color',
    'form.settings.design.color.app.names.placeholder': 'Select a color',
    'form.settings.design.url.background.image': 'URL of the background image',
    'form.settings.design.url.background.image.placeholder': 'Enter the background image URL',
    'form.settings.design.size.icon': 'Icon size',
    'form.settings.design.size.icon.small': 'Small',
    'form.settings.design.size.icon.medium': 'Average (+ 20%)',
    'form.settings.design.size.icon.large': 'Large (+ 40%)',
    'form.settings.design.desktop.header': 'Desktop title',
    'form.settings.design.desktop.header.no': 'No',
    'form.settings.design.desktop.header.device.id': 'Device ID',

    'form.settings.lang.title': 'Language Settings',
    'form.settings.lang.use.default': 'Use default language',
    'form.settings.lang.use': 'Use language',
    'form.settings.lang.en': 'English',
    'form.settings.lang.ru': 'Russian',

    'form.settings.groups.title': 'Groups',
    'form.settings.groups.search.placeholder': 'Group search',

    'form.settings.users.title': 'Users',
    'form.settings.users.search.placeholder': 'Search user',

    'form.qr.device.number.placeholder': 'Enter the device ID ...',
    'form.qr.code.image.alt': 'QR code',

    'form.profile.title': 'Change password',
    'form.profile.password.old': 'Old Password',
    'form.profile.password.old.placeholder': 'Enter old password',
    'form.profile.password.new': 'New Password',
    'form.profile.password.new.placeholder': 'Enter a new password',
    'form.profile.password.confirm': 'Verify',
    'form.profile.password.confirm.placeholder': 'Enter the new password again',

    'tab.customers': 'Organizations',
    'tab.common.applications': 'Shared Applications',

    'tab.devices': 'Devices',
    'tab.applications': 'Applications',
    'tab.configurations': 'Configurations',
    'tab.files': 'Files',
    'tab.default.design': 'Default Design',
    'tab.common.settings': 'General Settings',
    'tab.users': 'Users',
    'tab.groups': 'Groups',
    'tab.language': 'Language Settings',
    'tab.license': 'License',
    'tab.hints': 'Hints',
    'tab.plugins': 'Plugins',
    
    'tab.configeditor.common.settings': 'General Settings',
    'tab.configeditor.design.settings': 'Design Settings',
    'tab.configeditor.applications': 'Applications',
    'tab.configeditor.mdm.settings': 'MDM Settings',
    'tab.configeditor.app.settings': 'Applications Settings',

    'search.placeholder.file': 'search file',
    'search.placeholder.configuration': 'Search for configuration',
    'search.placeholder.customer': 'Search for an organization',
    'search.placeholder.application': 'Search for an application',
    'search.placeholder.application.setting': 'Search for an application setting',
    'search.placeholder.device': 'Search for a device',
    'search.placeholder.address': 'Address search',
    'search.placeholder.point': 'Site search',
    'search.placeholder.message': 'Message search',
    'search.placeholder': 'Search ...',
    'search.placeholder.from': 'From ...',
    'search.placeholder.to': 'To ...',

    'table.heading.customer.name': 'Name',
    'table.heading.customer.desc': 'Description',
    'table.heading.customer.registration.time': 'Registered',
    'table.heading.customer.last.login.time': 'Last login',
    'table.heading.customer.actions': 'Actions',

    'table.heading.configuration.name': 'Name',
    'table.heading.configuration.desc': 'Description',
    'table.heading.configuration.actions': 'Actions',

    'table.heading.application.setting.app.pkg': 'Package ID',
    'table.heading.application.setting.app.name': 'Application Name',
    'table.heading.application.setting.name': 'Customization name',
    'table.heading.application.setting.value': 'Value',
    'table.heading.application.setting.comment': 'Comment',
    'table.heading.application.setting.lastUpdate': 'Last Modified Date',

    'table.heading.application.pkg': 'Package ID',
    'table.heading.application.name': 'Application Name',
    'table.heading.application.version': 'Version',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Icon',
    'table.heading.application.actions': 'Actions',

    'table.heading.device.status': 'Status',
    'table.heading.device.date': 'Date',
    'table.heading.device.device.number': 'Device Number',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Phone Number',
    'table.heading.device.phone.model': 'Phone Model',
    'table.heading.device.status.permissions': 'Permission Status',
    'table.heading.device.status.installation': 'Installation Status',
    'table.heading.device.configuration': 'Configuration',
    'table.heading.device.desc': 'Description',
    'table.heading.device.group': 'Group',
    'table.heading.device.launcher.version': 'Launcher version',
    'table.heading.device.battery.level': 'Battery level',
    'table.heading.device.actions': 'Actions',

    'table.heading.group.name': 'Name',
    'table.heading.group.actions': 'Actions',

    'table.heading.file.name': 'Filename',
    'table.heading.file.path': 'Path',
    'table.heading.file.address': 'Address',
    'table.heading.file.actions': 'Actions',

    'table.heading.users.login': 'Login',
    'table.heading.users.name': 'Name',
    'table.heading.users.role': 'Role',
    'table.heading.users.actions': 'Actions',

    'table.heading.common.apps.customer': 'Organization',
    'table.heading.common.apps.pkg': 'Package ID',
    'table.heading.common.apps.name': 'Application Name',
    'table.heading.common.apps.version': 'Version',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Icon',
    'table.heading.common.apps.actions': 'Actions',


    'table.heading.plugin.devicelog.deviceNumber': 'Device number',
    'table.heading.plugin.devicelog.dateTime': 'Date and Time',
    'table.heading.plugin.devicelog.app': 'Application',
    'table.heading.plugin.devicelog.severity': 'Severity',
    'table.heading.plugin.devicelog.message': 'Message',

    'table.heading.plugin.audit.dateTime': 'Date and Time',
    'table.heading.plugin.audit.user': 'User login',
    'table.heading.plugin.audit.ipAddress': 'IP-address',
    'table.heading.plugin.audit.action': 'Action',

    'table.heading.plugin.deviceimport.deviceNumber': 'Device number',
    'table.heading.plugin.deviceimport.imei': 'IMEI',
    'table.heading.plugin.deviceimport.phoneNumber': 'Phone #',
    'table.heading.plugin.deviceimport.status': 'Status',
    'table.heading.plugin.deviceimport.newDevicesCount': 'Imported new devices',
    'table.heading.plugin.deviceimport.existingDevicesUpdated': 'Updated existing devices',
    'table.heading.plugin.deviceimport.existingDevicesSkipped': 'Skipped existing devices',
    'table.heading.plugin.deviceimport.repeatedRecordsSkipped': 'Missing duplicate devices',
    
    'notfound.devices': 'There are no devices to display.',
    'notfound.files':' The file list is empty. Use the "Add" button to upload a new file.',
    'notfound.configurations': 'No configurations were found.',
    'notfound.customers': 'Organizations not found.',
    'notfound.common.apps': 'There are no applications to display.',
    'notfound.common.plugin.devicelog.logs': 'No log records found. Try a different query.',
    'notfound.common.plugin.audit.logs': 'No audit log records found. Try a different query.',
    'notfound.applications': 'Applications not found',
    'notfound.groups':' No groups found. Try a different query.',
    'notfound.users':' Users not found. Try a different query.',
    'notfound.apps.for.display': 'There are no applications to display.',
    'notfound.app.versions.for.display': 'There are no versions to display.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    'format.date.plugin.devicelog.createTime': 'dd/MM/yyyy HH:mm:ss',
    'format.date.plugin.devicelog.datePicker': 'dd-MM-yyyy',

    'format.date.plugin.audit.createTime': 'dd/MM/yyyy HH:mm:ss',
    'format.date.plugin.audit.datePicker': 'dd-MM-yyyy',

    'format.date.plugin.deviceinfo.createTime': 'dd/MM/yyyy HH:mm:ss',
    'format.date.plugin.deviceinfo.datePicker': 'dd-MM-yyyy',

    'menu.about': 'About',
    'menu.profile': 'Profile',
    'menu.panel.master': 'Master Panel',
    'menu.panel.main': 'Main panel',
    'menu.logout': 'Log out',
    'menu.functions': 'Functions',
    'menu.settings': 'Settings',
    'menu.show.hints': 'Show hints',


    'plugin.name.not.specified': '<< The function name is not specified >>',

    'plugin.licensing.localization.key.name': 'License',
    'plugin.licensing.title': 'License',
    'plugin.licensing.apiKey': 'API Key',
    'plugin.licensing.apiKey.placeholder': 'Enter API key',

    'plugin.deviceexport.localization.key.name': 'Export devices',
    'plugin.deviceexport.tab.title': 'Export devices',
    'plugin.deviceexport.selection': 'Export',
    'plugin.deviceexport.group.selection': 'Select a group',
    'plugin.deviceexport.configuration.selection': 'Select configuration',
    'plugin.deviceexport.selection.all': 'All',
    'plugin.deviceexport.selection.group': 'Group',
    'plugin.deviceexport.selection.configuration': 'Configuration',
    'plugin.deviceexport.exporting': 'Export file is generated ...',

    'plugin.deviceimport.localization.key.name': 'Import devices',
    'plugin.deviceimport.tab.title': 'Import devices',
    'plugin.deviceimport.group.selection': 'Select a group',
    'plugin.deviceimport.file.selection': 'Select file ',
    'plugin.deviceimport.configuration.selection': 'Select configuration',
    'plugin.deviceimport.devicenumber.selection': 'Device number',
    'plugin.deviceimport.imei.selection': 'IMEI',
    'plugin.deviceimport.phonenumber.selection': 'Phone number',
    'plugin.deviceimport.column.0': 'No',
    'plugin.deviceimport.column.1': 'Column A',
    'plugin.deviceimport.column.2': 'Column B',
    'plugin.deviceimport.column.3': 'Column C',
    'plugin.deviceimport.column.4': 'Column D',
    'plugin.deviceimport.column.5': ' Column E',
    'plugin.deviceimport.column.6': ' Column F',
    'plugin.deviceimport.column.7': ' Column G',
    'plugin.deviceimport.column.8': ' Column H',
    'plugin.deviceimport.column.9': ' Column I',
    'plugin.deviceimport.column.10': 'Column J',
    'plugin.deviceimport.column.11': 'Column K',
    'plugin.deviceimport.column.12': 'Column L',
    'plugin.deviceimport.column.13': 'Column M',
    'plugin.deviceimport.column.14': 'Column N',
    'plugin.deviceimport.column.15': 'Column O',
    'plugin.deviceimport.column.16': 'Column P',
    'plugin.deviceimport.column.17': 'Column Q',
    'plugin.deviceimport.column.18': 'Column R',
    'plugin.deviceimport.column.19': 'Column S',
    'plugin.deviceimport.column.20': 'Column T',
    'plugin.deviceimport.column.21': 'Column U',
    'plugin.deviceimport.column.22': 'Column V',
    'plugin.deviceimport.column.23': 'Column W',
    'plugin.deviceimport.column.24': 'Column X',
    'plugin.deviceimport.column.25': 'Column Y',
    'plugin.deviceimport.column.26': 'Column Z',
    'plugin.deviceimport.error.xls.file.required': 'Select a file with the extension. xls or .xslx',
    'plugin.deviceimport.error.file.expired': 'Please, upload file again',
    'plugin.deviceimport.error.configuration.required': 'Specify the configuration',
    'plugin.deviceimport.error.devicenumber.required': 'Specify a column for the device number',
    'plugin.deviceimport.error.file.required': 'Select file',
    'plugin.deviceimport.error.group.invalid': 'Invalid group',
    'plugin.deviceimport.error.configuration.invalid': 'Invalid configuration',
    'plugin.deviceimport.parsing': 'Parsing file...',
    'plugin.deviceimport.importing': 'Importing devices...',
    'plugin.deviceimport.device.status.ok': 'OK',
    'plugin.deviceimport.device.status.exists': 'Already exists',
    'plugin.deviceimport.device.status.repeating': 'Repeating',
    'plugin.deviceimport.label.existingdevices': 'Existing devices',
    'plugin.deviceimport.label.existingdevices.override': 'Override',
    'plugin.deviceimport.label.existingdevices.ignore': 'Ignore',

    'plugin.devicelog.localization.key.name': 'Logs',
    'plugin.devicelog.tab.title': 'Logs',
    'plugin.devicelog.settings.title': '"Logs" plugin settings',
    'plugin.devicelog.option.severyty.default': 'Severity search...',
    'plugin.devicelog.settings.log.preserve.period': 'Log storage time (days)',
    'plugin.devicelog.setting.rules.title': 'Rules',
    'plugin.devicelog.settings.rules.heading.name': 'Rule name',
    'plugin.devicelog.settings.rules.heading.active': 'Active?',
    'plugin.devicelog.settings.rules.heading.filter': 'Filter',
    'plugin.devicelog.settings.rules.heading.application': 'Application',
    'plugin.devicelog.settings.rules.heading.configuration': 'Configuration',
    'plugin.devicelog.settings.rules.heading.group': 'Group',
    'plugin.devicelog.settings.rules.heading.severity': 'Severity',

    'plugin.devicelog.settings.form.rule.name': 'Name',
    'plugin.devicelog.settings.form.rule.name.placeholder': 'Enter the rule name',
    'plugin.devicelog.settings.form.rule.active': 'Active?',
    'plugin.devicelog.settings.form.rule.severity': 'Level',
    'plugin.devicelog.settings.form.rule.severity.placeholder': 'Select the log level',
    'plugin.devicelog.settings.form.rule.filter': 'Filter',
    'plugin.devicelog.settings.form.rule.filter.placeholder': 'Enter filter',
    'plugin.devicelog.settings.form.rule.application': 'Application',
    'plugin.devicelog.settings.form.rule.application.placeholder': 'Select an application',
    'plugin.devicelog.settings.form.rule.group': 'Group',
    'plugin.devicelog.settings.form.rule.group.placeholder': 'Select a group',
    'plugin.devicelog.settings.form.rule.device': 'Device',
    'plugin.devicelog.settings.form.rule.device.placeholder': 'Select a device',
    'plugin.devicelog.settings.form.rule.configuration': 'Configuration',
    'plugin.devicelog.settings.form.rule.configuration.placeholder': 'Select a configuration',

    'plugin.devicelog.settings.error.empty.rule.name': 'Specify the name',
    'plugin.devicelog.settings.error.empty.rule.app.pkg': 'Specify the application',
    'plugin.devicelog.settings.error.empty.rule.severity': 'Specify the severity',
    'plugin.devicelog.settings.error.invalid.app': 'Invalid application',
    'plugin.devicelog.settings.error.invalid.group': 'Invalid group',
    'plugin.devicelog.settings.error.invalid.configuration': 'Invalid configuration',
    'plugin.devicelog.settings.error.invalid.device': 'Invalid device',
    'plugin.devicelog.settings.question.delete.rule': 'Delete rule "${rulename}"?',
    'plugin.devicelog.settings.button.devices': 'Devices',
    'plugin.devicelog.settings.label.rule': 'Rule',
    'plugin.devicelog.settings.form.rule.devices': 'Devices',

    'plugin.audit.localization.key.name': 'Audit',
    'plugin.audit.action.user.login': 'Successful login of user',
    'plugin.audit.action.jwt.login': 'Successful login of API client',
    'plugin.audit.tab.title': 'Audit',

    'plugin.deviceinfo.localization.key.name': 'Detailed information',
    'plugin.deviceinfo.title': 'Detailed information',
    'plugin.deviceinfo.settings.data.preserve.period': 'Storage time (days)',
    'plugin.deviceinfo.settings.interval.mins': 'Data collection interval',
    'plugin.deviceinfo.settings.send.data': 'Transmit detailed information',
    
    'plugin.deviceinfo.state.wifiState.inactive': 'Wi-Fi disabled',
    'plugin.deviceinfo.state.wifiState.scanning': 'Network Search',
    'plugin.deviceinfo.state.wifiState.disconnected': 'Connection failed',
    'plugin.deviceinfo.state.wifiState.connecting': 'A connection is being established',
    'plugin.deviceinfo.state.wifiState.connected': 'Connection established',

    'plugin.deviceinfo.state.gpsState.inactive': 'GPS is disabled',
    'plugin.deviceinfo.state.gpsState.lost': 'GPS is on, but there is no signal from satellites',
    'plugin.deviceinfo.state.gpsState.active': 'GPS is on, there is a signal from satellites',

    'plugin.deviceinfo.state.mobile1State.inactive': 'Data transmission via the mobile network is disabled',
    'plugin.deviceinfo.state.mobile1State.disconnected': 'Data transfer is allowed, but no connection',
    'plugin.deviceinfo.state.mobile1State.connected': 'Mobile data transfer enabled',

    'plugin.deviceinfo.state.mobile2State.inactive': 'Data transmission via the mobile network is disabled',
    'plugin.deviceinfo.state.mobile2State.disconnected': 'Data transfer is allowed, but no connection',
    'plugin.deviceinfo.state.mobile2State.connected': 'Mobile data transfer enabled',

    'plugin.deviceinfo.state.mobile1SimState.unknown': 'Status unknown',
    'plugin.deviceinfo.state.mobile1SimState.absent': 'No SIM card',
    'plugin.deviceinfo.state.mobile1SimState.pinRequired': 'PIN is required',
    'plugin.deviceinfo.state.mobile1SimState.pukRequired': 'Requires PUK code',
    'plugin.deviceinfo.state.mobile1SimState.locked': 'SIM card locked',
    'plugin.deviceinfo.state.mobile1SimState.ready': 'Ready',
    'plugin.deviceinfo.state.mobile1SimState.notReady': 'Not ready',
    'plugin.deviceinfo.state.mobile1SimState.disabled': 'SIM card locked forever',
    'plugin.deviceinfo.state.mobile1SimState.error': 'Error reading SIM card',
    'plugin.deviceinfo.state.mobile1SimState.restricted': 'Limited use',

    'plugin.deviceinfo.state.mobile2SimState.unknown': 'Status unknown',
    'plugin.deviceinfo.state.mobile2SimState.absent': 'No SIM card',
    'plugin.deviceinfo.state.mobile2SimState.pinRequired': 'PIN is required',
    'plugin.deviceinfo.state.mobile2SimState.pukRequired': 'PUK code required',
    'plugin.deviceinfo.state.mobile2SimState.locked': 'SIM card locked',
    'plugin.deviceinfo.state.mobile2SimState.ready': 'Ready',
    'plugin.deviceinfo.state.mobile2SimState.notReady': 'Not ready',
    'plugin.deviceinfo.state.mobile2SimState.disabled': 'SIM card locked forever',
    'plugin.deviceinfo.state.mobile2SimState.error': 'Error reading SIM card',
    'plugin.deviceinfo.state.mobile2SimState.restricted': 'Limited use',

    'plugin.deviceinfo.tab.title': 'Detailed Information',
    'plugin.deviceinfo.enum.time.min': 'min ago',
    'plugin.deviceinfo.enum.time.hour': 'hours ago',
    'plugin.deviceinfo.enum.time.day': 'days ago',
    'plugin.deviceinfo.title.time': 'Time',
    'plugin.deviceinfo.title.deviceNumber': 'Device number',
    'plugin.deviceinfo.title.description': 'Description',
    'plugin.deviceinfo.title.groups': 'Groups',
    'plugin.deviceinfo.title.imei.required': 'IMEI (required)',
    'plugin.deviceinfo.title.imei': 'IMEI',
    'plugin.deviceinfo.title.phone.required': 'Phone (required)',
    'plugin.deviceinfo.title.phone': 'Phone',
    'plugin.deviceinfo.title.model': 'Model',
    'plugin.deviceinfo.title.os.version': 'OS version',
    'plugin.deviceinfo.title.mdm.mode': 'MDM mode',
    'plugin.deviceinfo.title.launcher.type': 'Launcher variant',
    'plugin.deviceinfo.title.battery.level': 'Battery charge',
    'plugin.deviceinfo.title.permission.1': 'Permission to install as device administrator',
    'plugin.deviceinfo.title.permission.2': 'Permission to overlay on top of other windows',
    'plugin.deviceinfo.title.permission.3': 'Permission to access the use of history',
    'plugin.deviceinfo.title.permission.true': 'yes',
    'plugin.deviceinfo.title.permission.false': 'no',

    'plugin.deviceinfo.boolean.true': 'yes',
    'plugin.deviceinfo.boolean.false': 'no',

    'plugin.deviceinfo.title.group.device': 'General parameters',
    'plugin.deviceinfo.title.group.deviceBatteryLevel': 'Battery charge',
    'plugin.deviceinfo.title.group.deviceBatteryCharging': 'Charging type',
    'plugin.deviceinfo.title.group.deviceIpAddress': 'IP Address Used',
    'plugin.deviceinfo.title.group.deviceKeyguard': 'Device protection is enabled',
    'plugin.deviceinfo.title.group.deviceRingVolume': 'Ring volume',
    'plugin.deviceinfo.title.group.deviceWifiEnabled': 'Wi-Fi enabled',
    'plugin.deviceinfo.title.group.deviceMobileDataEnabled': 'Mobile data enabled',
    'plugin.deviceinfo.title.group.deviceGpsEnabled': 'GPS enabled',
    'plugin.deviceinfo.title.group.deviceBluetoothEnabled': 'Bluetooth is on',

    'plugin.deviceinfo.title.group.wifi': 'Wi-Fi settings',
    'plugin.deviceinfo.title.group.wifiRssi': 'Wi-Fi signal strength',
    'plugin.deviceinfo.title.group.wifiSsid': 'SSID',
    'plugin.deviceinfo.title.group.wifiSecurity': 'Network protection is enabled',
    'plugin.deviceinfo.title.group.wifiState': 'Connection status',
    'plugin.deviceinfo.title.group.wifiIpAddress': 'IP address of the Wi-Fi connection',
    'plugin.deviceinfo.title.group.wifiTx': 'Bytes transferred',
    'plugin.deviceinfo.title.group.wifiRx': 'Bytes received',

    'plugin.deviceinfo.title.group.gps': 'GPS options',
    'plugin.deviceinfo.title.group.gpsState': 'Satellite communication status',
    'plugin.deviceinfo.title.group.gpsLat': 'Latitude',
    'plugin.deviceinfo.title.group.gpsLon': 'Longitude',
    'plugin.deviceinfo.title.group.gpsAlt': 'Height',
    'plugin.deviceinfo.title.group.gpsSpeed': 'Speed ​​(km / h)',
    'plugin.deviceinfo.title.group.gpsCourse': 'Direction',

    'plugin.deviceinfo.title.group.mobile1': 'SIM card settings # 1',
    'plugin.deviceinfo.title.group.mobile1Rssi': 'Cellular signal strength',
    'plugin.deviceinfo.title.group.mobile1Carrier': 'Name of mobile operator',
    'plugin.deviceinfo.title.group.mobile1DataEnabled': 'Data transfer enabled',
    'plugin.deviceinfo.title.group.mobile1IpAddress': 'IP address of the mobile connection',
    'plugin.deviceinfo.title.group.mobile1State': 'Mobile connection status',
    'plugin.deviceinfo.title.group.mobile1SimState': 'SIM card status',
    'plugin.deviceinfo.title.group.mobile1Tx': 'Bytes transferred',
    'plugin.deviceinfo.title.group.mobile1Rx': 'Bytes received',

    'plugin.deviceinfo.title.group.mobile2': 'SIM card settings # 2',
    'plugin.deviceinfo.title.group.mobile2Rssi': 'Cellular signal strength',
    'plugin.deviceinfo.title.group.mobile2Carrier': 'Name of mobile operator',
    'plugin.deviceinfo.title.group.mobile2DataEnabled': 'Data transfer enabled',
    'plugin.deviceinfo.title.group.mobile2IpAddress': 'IP address of the mobile connection',
    'plugin.deviceinfo.title.group.mobile2State': 'Mobile connection status',
    'plugin.deviceinfo.title.group.mobile2SimState': 'SIM card status',
    'plugin.deviceinfo.title.group.mobile2Tx': 'Bytes transferred',
    'plugin.deviceinfo.title.group.mobile2Rx': 'Bytes received',

    'plugin.deviceinfo.title.apps.status': 'Installation status',
    'plugin.deviceinfo.title.apps.name': 'Title',
    'plugin.deviceinfo.title.apps.pkg': 'Package ID',
    'plugin.deviceinfo.title.apps.ver1': 'Installed version',
    'plugin.deviceinfo.title.apps.ver2': 'Required version',

    'plugin.deviceinfo.dynamic.tab.title': 'Dynamic Information',
    'plugin.deviceinfo.dynamic.period': 'Interval',
    'plugin.deviceinfo.dynamic.period.1': '1 hour',
    'plugin.deviceinfo.dynamic.period.6': '6 hours',
    'plugin.deviceinfo.dynamic.period.24': '24 hours',
    'plugin.deviceinfo.dynamic.period.48': '48 hours',
    'plugin.deviceinfo.dynamic.period.any': 'Any',

    'plugin.deviceinfo.dynamic.params.all': 'Settings',

    'plugin.deviceinfo.exporting': 'Export file is generated ...',

    'plugin.deviceinfo.intervalMins.option.1': '15 minutes',
    'plugin.deviceinfo.intervalMins.option.2': '30 minutes',
    'plugin.deviceinfo.intervalMins.option.3': '1 hour',
    'plugin.deviceinfo.intervalMins.option.4': '2 hours',
    'plugin.deviceinfo.intervalMins.option.5': '6 hours',
    'plugin.deviceinfo.intervalMins.option.6': '12 hours',
    'plugin.deviceinfo.intervalMins.option.7': '24 hours',

    'breadcrumb.devices': 'Devices',
    'breadcrumb.applications': 'Applications',
    'breadcrumb.configurations': 'Configurations',
    'breadcrumb.files': 'Files',
    'breadcrumb.default.design': 'Design by default',
    'breadcrumb.common.settings': 'General Settings',
    'breadcrumb.language.settings': 'Language Settings',
    'breadcrumb.license.settings': 'License',
    'breadcrumb.users': 'Users',
    'breadcrumb.groups': 'Groups',
    'breadcrumb.hints': 'Hints',
    'breadcrumb.plugins': 'Plugins',
    'breadcrumb.config.details': 'Details',
    'breadcrumb.plugin.licensing.main': 'Licensing',
    'breadcrumb.plugin.devicelog.main': 'Logs',
    'breadcrumb.plugin.deviceimport.main': 'Import devices',
    'breadcrumb.plugin.audit.main': 'Audit',
    'breadcrumb.plugin.deviceinfo.main': 'Detailed info',
    'breadcrumb.plugin.devicereset.main': 'Reset settings',
    'breadcrumb.plugin.deviceinfo.dynamic.main': 'Dynamic Information',
    'breadcrumb.application.versions': 'Versions',

    'app.title': 'Headwind MDM Server',

    'box.show.my.apps.only': 'Display my applications only',
    'configuration.app.version.upgrade.message': 'Installed version ${installedVersion}, available version ${latestVersion}',

    'about.line.1': 'Headwind MDM control panel',
    'about.line.2': 'Enterprise launcher for Android',
    'about.line.3': 'Version ${versionNumber}',
    'about.line.4': 'Installed plugins',

    'common.app.clarification': 'This application is public and not available for editing. To add another version of this app, please contact the administrator.',

    'qrcode.help.line1': 'To setup the Android device (version 7 or higher) in a managed (corporate) mode:',
    'qrcode.help.line2': 'Reset the device to factory settings',
    'qrcode.help.line3': 'Tap 7 times on any place of the start screen (you must enter a hidden QR code scanning mode)',
    'qrcode.help.line4': 'Follow the device instructions: accept the terms, connect to Wi-Fi, scan this QR-code',
    'qrcode.help.line5': 'The QR code may contain the device ID for Headwind MDM (so you don\'t need to enter it on a mobile device). To embed the device ID into the QR code, enter the device ID on this screen and click "Renew".',

    'form.configuration.app.version.select.select.title': 'Select the version to install',
    'form.configuration.app.version.select.version.check.off': 'Disable version checking',
    'form.configuration.app.version.select.upgrade.warning': 'Upgrade application "${v1}" to version "${v3}" for configuration "${v2}"?',
    'form.configuration.app.version.select.downgrade.warning': 'Downgrade version DELETE ALL THESE APPLICATIONS on all devices! Downgrade the application version "${v1}" to version "${v2}"? ',

    'hint.step.1': 'Click here to start the device enrollment',
    'hint.step.2': 'Click here to open the QR code',
    'hint.step.3': 'Click here to see how to open the QR code scanner on the device',
    'hint.step.4': 'Find an available device ID in the «Devices» tab. Click «Renew» to include it in the QR code.',

    'ie.browser.notice.1': 'Unfortunately, Internet Explorer is not supported.',
    'ie.browser.notice.2': 'Recommended Browser for Using Headwind MDM - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a>.',

    'form.resolved.duplicate.pkg.text1': 'Package ID "${pkg}" is already used by the applications listed below.',
    'form.resolved.duplicate.pkg.text2': 'Do you want to add a new application or a new version of an existing application?',
    'form.resolved.duplicate.pkg.text3': 'New version for',

};