if (! document.localization) document.localization = [];

document.localization ['es_ES'] = {
    'login.username': 'Usuario o Email',
    'login.username.placeholder': 'Ingrese su usuario o email',
    'login.password': 'Contraseña:',
    'login.password.placeholder': 'Ingrese contraseña',
    'login.submit': 'Ingresar',
    'login.password.incorrect': 'Usuario o contrseña invalidos.',

    'header.label.username': 'Usuario',

    'devices.group.options.all': 'Todos los Grupos',
    'devices.configuration.options.all': 'Toda las Configuraciónes',
    'devices.permissions.all': 'Todos los permisos fueron concedidos',
    'devices.permissions.not.as.device.admin': '- La aplicacion no esta instalada como Administrador del Dispositivo',
    'devices.permissions.window.overlap.prohibited': '- Sobreponerse sobre ventanas no esta activo',
    'devices.permissions.history.access.prohibited': '- El acceso al historial de uso no esta configurado',
    'devices.unknown': 'Desconocido',
    'devices.model.unknown': 'Desconocido',
    'devices.date.unknown': 'desconocido',
    'devices.date.format': 'dd/MM HH:mm',
    'devices.app.installed': '- ${applicationName}: Instalada.',
    'devices.app.not.installed': '- ${applicationName}: no instalada.',
    'devices.app.version.available': ', disponible ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: instalada ${applicationInstalledVersion}, disponible ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, requiere eliminar',
    'devices.no.data': 'El dispositivo no ha trasmitido ningun dato',
    'devices.settings.conformance.broken': 'Problema de configuración: (${serverData})',
    'devices.file.installed': '- ${file}: instalado',
    'devices.file.not.installed': '- ${file}: no instalado.',
    'devices.file.lastUpdate.differs': '- ${file}: diferencia en tiempo de modificacion de ${diff} minutos',

    'button.apply': 'Aplicar',
    'button.gps.on': 'Activar GPS',
    'button.wifi.on': 'Activar Wi-Fi',
    'button.notify.update': 'Notificar en Actualizacion',
    'button.app.settings': 'Configuración de la Aplicacion',
    'button.ok': 'OK',
    'button.help': 'Ayuda',
    'button.new.app': 'Nueva aplicacion',
    'button.new.app.version': 'Nueva version',
    'button.upgrade': 'Actualizar',
    'button.renew.config': 'Actualizar en dipositivos',
    'button.common': 'Aplicacion comun',
    'button.close': 'Cerrar',
    'button.yes': 'Si',
    'button.cancel': 'Cancelar',
    'button.save': 'Guardar',
    'button.save.and.close': 'Guardar and Cerrar',
    'button.more': 'Mas ...',
    'button.cleanup': 'Limpiar',
    'button.add': 'Añadir',
    'button.add.icon': 'Nuevo Icono',
    'button.search': 'Buscar',
    'button.export': 'Exportar',
    'button.change': 'Editar',
    'button.copy': 'Copiar',
    'button.qrcode': 'Codigo QR',
    'button.application': 'Aplicacion',
    'button.change.password': 'Cambiar contraseña',
    'button.set.configuration': 'Definir configuración',
    'button.group.action': 'Acción de grupo',
    'button.delete': 'Eliminar',
    'button.login': 'Ingresar',
    'button.renew.code': 'Actualizar',
    'button.configurations': 'Configuraciónes',
    'button.set.configurations': 'Especificar Configuraciónes',
    'button.edit.versions': 'Versiones',
    'button.edit': 'Editar',
    'button.change.common.app': 'Editar Aplicacion Compartida',
    'button.delete.common.app': 'Eliminar Aplicacion Compartida',
    'button.turn.common.app': 'Convertir en Comun',
    'button.hints.enable': 'Mostrar Pistas',
    'button.hints.disable': 'Ocultar Pistas',
    'button.show.password': 'Mostrar contraseña',
    'button.hide.password': 'Ocultar Contraseña',

    'question.impersonate.user': 'Ingresar como el administrador de la aplicacion "${customerName}"?',
    'question.change.user': '¿Iniciar sesión en la aplicación como usuario "${userName}"?',
    'question.delete.file': 'Eliminar archivo "${fileName}"?',
    'question.delete.customer': 'Eliminar organizacion "${customerName}"?',
    'question.delete.user': 'Eliminar usuario "${username}"?',
    'question.delete.application': 'Eliminar aplicacion"${applicationName}"?',
    'question.delete.application.version': 'Eliminar version "${applicationVersion}"?',
    'question.delete.configuration': 'Elminar configuración "${configurationName}"??',
    'question.delete.group': 'Eliminar grupo "${groupName}"?',
    'question.delete.device': 'Elminar dispositivo con número "${deviceNumber}"?',
    'question.exit.without.saving': 'Los cambios no fueron guardados. Desea salir de esta pagina de todos modos?',
    'question.turn2common.application': 'Compartir aplicacion "${applicationName}"?',
    'question.app.upgrade': 'Actualizar aplicacion "${v1}" a la ultima version "${v2}"?',

    'error.application.setting.empty.app': 'Especificar aplicacion',
    'error.application.setting.empty.name': 'Ingrese un nombre',
    'error.application.setting.empty.value': 'Ingrese un valor',

    'error.icon.dimension.invalid': 'El Icono debe ser cuadrado',
    'error.icon.empty.name': 'Ingrese el nombre del icono',
    'error.icon.empty.file': 'Subir icono',
    'error.application.version.pkg.mismatch': 'La ID del paquete (${actual}), no corresponde a la aplicacion (${expected})',
    'error.empty.user': 'Seleccione usuario',
    'error.empty.user.name': 'Ingrese el nombre de usuario',
    'error.empty.user.login': 'Ingrese el usuario para ingreso',
    'error.empty.user.role': 'Seleccione el rol',
    'error.empty.password': 'Ingrese nueva contraseña',
    'error.empty.password.confirm': 'Ingrese confirmacion de contraseña',
    'error.empty.group.name': 'Ingrese el nombre del grupo',
    'error.empty.configuration': 'Especifique la configuración',
    'error.empty.configuration.name': 'Ingrese el nombre de la configuración',
    'error.empty.configuration.password': 'Ingrese la contraseña',
    'error.empty.configuration.contentApp': 'No hay contenido para aplicacion especificada',
    'error.invalid.configuration.mainApp': 'En las opciones del MDM, se uso la aplicacion incorrecta',
    'error.invalid.configuration.contentApp': 'Aplicacion de contenido especificada invalida',
    'error.mismatch.password': 'Las contraseñas deben coincidir',
    'error.empty.customer.name': 'Ingrese el nombre de la organizacion',
    'error.empty.customer.prefix': 'Ingrese el encabezado del nombre',
    'error.empty.customer.device.configuration': 'Seleccione una configuración',
    'error.empty.customer.duplicate.prefix': 'Encabezado ya esta en uso',
    'error.duplicate.customer.name': 'La organizacion con el nombre elegido ya existe. Intente un nombre diferente.',
    'error.duplicate.group.name': 'El grupo con el nombre elegido ya existe. Intente un nombre diferente.',
    'error.duplicate.configuration.name': 'La configuración con el nombre elegido ya existe. Intente un nombre diferente.',
    'error.duplicate.device.number': 'Ya existe un dispositivo con este número',
    'error.internal.server': 'Error interno del servidor',
    'error.permission.denied': 'No posee permisos para ejecutar',
    'error.request.failure': 'Fallo el pedido',
    'error.configuration.device.use': 'No puede eliminar esta configuración, esta en uso en dispositivos. Primero dirijase a "Dispositivos" y cambie su configuración',
    'error.invalid.system.update.time': 'Intervalo de instalación invalido',

    'error.configuration.file.empty.name': 'Ingrese nombre del archivo',
    'error.configuration.file.empty.desc': 'Ingrese descripcion',
    'error.configuration.file.empty.path': 'Ingrese la ruta local del dispositivo',
    'error.configuration.file.empty.file': 'Ingrese una URL o suba un archivo',
    
    'error.notfound.device': 'No se encontro dispositivo',
    'error.duplicate.device': 'Ya existe un dispositivo con el mismo número',
    'error.duplicate.login': 'El usuario para ingreso ya existe',
    'error.duplicate.group': 'Ya existe un grupo con el mismo nombre',
    'error.duplicate.application': 'Ya existe una aplicacion con la misma ID',
    'error.recent.application.version.exists': 'Ya existe una version superior de la aplicacion',
    'error.common.application.access.prohibited': 'El manejo de aplicaciones comunes solo puede ser realizado por el Super-Administrador',
    'error.application.config.reference.exists': 'La aplicacion esta siendo usada en configuraciónes y no puede eliminarse',
    'error.application.version.deletion.prohibited': 'La version es unica o bien esta siendo usada en confituraciones y no puede eliminarse',
    'error.duplicate.file': 'Ya existe un archivo con el mismo nombre',
    'error.used.file': 'Este archivo esta en uso',
    'error.version.exists': 'Ya existe una version igual de la aplicacion',
    'error.duplicate.configuration': 'Ya existe una configuración con este nombre',
    'error.notfound.customer.admin': 'No se encontro la cuenta de Administrador',
    'error.apk.file.required': 'Seleccione un archivo con extension .apk o .xapk',
    'error.apk.parse': 'Ha ocurrido un error al procesar el archivo',
    'error.empty.app.name': 'Ingrese el nombre de la aplicacion',
    'error.empty.app.pkg': 'Ingrese la ID del paquete',
    'error.empty.app.url': 'Ingrese la URL',
    'error.empty.app.iconText': 'Ingrese el texto del icono',
    'error.empty.app.version': 'Ingrese la version de la aplicacion',
    'error.notempty.group': 'Este grupo incluye uno o mas dispositivos. No puede ser removido.',
    'error.file.empty': 'Subir un nuevo archivo',
    'error.file.deletion': 'Error eliminando archivo en el servidor',
    'error.file.save': 'Error guardando archivo en el servidor',
    'error.password.wrong': 'Contraseña invalida',
    'error.password.empty': 'Contraseña no especificada',
    'error.params.missing': 'Parametros faltantes:',
    'error.empty.push.options': 'Por favor, seleccione las opciones de notificaciones "Push"',

    'table.filtering.check.all': 'Seleccionar Todo',
    'table.filtering.uncheck.all': 'Cancelar Todo',
    'table.filtering.suffix.configuration': 'configuraciónes',
    'table.filtering.suffix.group': 'grupos',
    'table.filtering.no.selected.configuration': 'No se seleccionaron configuraciónes',
    'table.filtering.no.selected.group': 'No se seleccionaron grupos',

    'success.admin.created': 'Cuenta de Administrador creada:\n ${adminCredentials}',
    'success.uploading.file': 'El archivo fue subido al servidor ...',
    'success.loading.devices': 'Cargado lista de dispositivos ...',
    'success.loading.customer': 'Cargando detalles del cliente ...',
    'success.file.uploaded': 'Archivo subido satisfactoriamente.',
    'success.file.uploaded.need.save': 'Archivo subido satisfactoriamente. Ingrese la ruta relativa y presione "Guardar".',
    'success.settings.design.saved': 'Configuración de diseño guardada satisfactoriamente',
    'success.settings.common.saved': 'Configuración de tabla de dispositivos guardada satisfactoriamente',
    'success.settings.saved': 'Configuraciónes guardadas satisfactoriamente',
    'success.settings.apiKey.saved': 'Clave API guardada satisfactoriamente',
    'success.settings.hints.enabled': 'Pistas habilitadas',
    'success.settings.hints.disabled': 'Pistas deshabilitadas',
    'success.configuration.saved': 'Configuración guardada satisfactoriamente',
    'success.operation.completed': 'Operacion completada satisfactoriamente',
    'success.plugins.disabled': 'Configuración guardada satisfactoriamente',
    'success.config.update.notification': 'La actualizacion de configuración fue enviada a los dispositivos.',
    'success.config.update.device.app.settings.notification': 'La actualizacion de configuración fue enviada al dispositivo',

    'form.icon.title': 'Icono',
    'form.icon.name': 'Nombre',
    'form.icon.file': 'Archivo',

    'configuration.add.warning': '¿Está seguro de que desea crear una configuración vacía? Deberá agregar todas las aplicaciones del sistema necesarias manualmente. En su lugar, considere copiar y modificar una configuración existente.',
    'configuration.remove.warning': '¿Está seguro de que desea eliminar la última configuración? Perderá información sobre las aplicaciones del sistema necesarias.',
    'form.configuration.title': 'Configuración',
    'form.configuration.title.typical': 'Configuración tipica',
    'form.configuration.settings.auto.update': 'Auto-Actualizar',
    'form.configuration.settings.system.update': 'Actualizacion del Sistema',
    'form.configuration.settings.system.update.default': 'Por Defecto',
    'form.configuration.settings.system.update.immediate': 'Inmediatamente',
    'form.configuration.settings.system.update.scheduled': 'Programada',
    'form.configuration.settings.system.update.postponed': 'Postpuesta',
    'form.configuration.settings.system.update.time': 'Tiempo de instalación',
    'form.configuration.settings.system.update.time.from': 'de:',
    'form.configuration.settings.system.update.time.to': 'para:',
    'form.configuration.settings.block.status.bar': 'Bloqueo de Barra de Estado',
    'form.configuration.settings.block.status.bar.hint': 'Esta configuración está obsoleta y funciona en Android 6 y versiones anteriores. Para bloquear la barra de estado en las versiones más recientes de Android, use el modo quiosco (configuración de MDM).',
    'form.configuration.settings.mdm.kiosk.mode': 'Modo "Kiosk"',
    'form.configuration.settings.mdm.app.main': 'Aplicacion Principal',
    'form.configuration.settings.mdm.component.event.receiver': 'Componente - receptor de evento',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Ingrese el nombre del componente',
    'form.configuration.settings.mdm.component.wifi.ssid': 'WiFi SSID',
    'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'WiFi SSID de provisionamiento - dejar en blanco para ingresar manualmente',
    'form.configuration.settings.mdm.component.wifi.password': 'Contraseña WiFi',
    'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Contraseña WiFi de provisionamiento - dejar en blanco para ingresar manualmente',
    'form.configuration.settings.mdm.component.wifi.security': 'Tipo de seguridad WiFi',
    'form.configuration.settings.mdm.component.wifi.notice': 'Aviso: ¡estas configuraciónes de WiFi se aplican solo a la inscripción inicial!',
    'form.configuration.settings.mdm.component.server.url': 'URL del servidor',
    'form.configuration.settings.mdm.component.server.url.placeholder': 'Usado para la migracion a un nuevo servidor MDM',
    'form.configuration.settings.mdm.app.content': 'Aplicacion de Contenido',
    'form.configuration.settings.mdm.kiosk.home': 'Habilitar Boton Inicio',
    'form.configuration.settings.mdm.kiosk.recents': 'Habilitar Boton Recientes',
    'form.configuration.settings.mdm.kiosk.notifications': 'Habilitar Notificaciones',
    'form.configuration.settings.mdm.kiosk.system.info': 'Habilitar informacion de barra de estado',
    'form.configuration.settings.mdm.kiosk.keyguard': 'Activar bloqueo de pantalla',
    'form.configuration.settings.mdm.mobile.enrollment': 'Inscríbase usando datos móviles',
    'form.configuration.settings.mdm.lock.safe.settings': 'Bloquear opciones seguras (WiFi, GPS, etc)',
    'form.configuration.settings.mdm.allowed.classes': 'Actividades permitidas',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'Clases separadas por comas, e.j.: com.android.settings.homepage.SettingsHomepageActivity',
    'form.configuration.settings.mdm.restrictions': 'Restricciones',
    'form.configuration.settings.mdm.restrictions.placeholder': 'Restricciones de MDM, separadas por comas, e.j.: no_sms,no_outgoing_calls,no_usb_file_transfer',
    'form.configuration.settings.mdm.qrcode.url': 'URL del codigo QR',
    'form.configuration.settings.mdm.hint': 'Seleccione la aplicacion principal y componente',
    'form.configuration.apps.search.label': 'Buscar por:',
    'form.configuration.apps.sort.label': 'Ordenar:',
    'form.configuration.apps.sort.byname': 'Por nombre',
    'form.configuration.apps.sort.bypkg': 'Por ID',
    'form.configuration.apps.no.apk': 'ninguno',
    'form.configuration.apps.show.systeam.apps': 'Mostrar aplicaciones del sistema',
    'form.configuration.apps.action.install': 'Instalar',
    'form.configuration.apps.action.prohibit': 'Bloquear',
    'form.configuration.apps.action.not.install': 'No instalar',
    'form.configuration.apps.action.delete': 'Eliminar',
    'form.configuration.apps.action.permit': 'Permitir',
    'form.configuration.apps.label.inherit': 'Hederada',
    'form.configuration.apps.label.show': 'Mostrar',
    'form.configuration.apps.label.not.show': 'Ocultar',
    'form.configuration.apps.edit.details': 'Parametros adicionales',
    'form.configuration.apps.keycode': 'Codigo Key',
    'form.configuration.apps.bottom': 'Mostrar en la línea inferior',
    'form.configuration.apps.hint': 'Pista: para desvincular la aplicacion de la configuración, seleccione la accion "Bloquear" o "No instalar".',
    'form.configuration.settings.design.use.default': 'Usar diseño por defecto',
    'form.configuration.settings.design.color.background': 'Color de Fondo',
    'form.configuration.settings.design.color.background.placeholder': 'Seleccione un color',
    'form.configuration.settings.design.color.app.names': 'Color del nombre de aplicaciones',
    'form.configuration.settings.design.color.app.names.placeholder': 'Seleccione un color',
    'form.configuration.settings.design.background.image.url': 'URL para la imagen de fondo',
    'form.configuration.settings.design.background.image.url.placeholder': 'Ingrese una URL para la imagen de fondo',
    'form.configuration.settings.design.icon': 'Tamaño de Icono',
    'form.configuration.settings.design.icon.small': 'Pequeño',
    'form.configuration.settings.design.icon.medium': 'Normal (+ 20%)',
    'form.configuration.settings.design.icon.large': 'Grandes (+ 40%)',
    'form.configuration.settings.design.desktop.header': 'Titulo de escritorio',
    'form.configuration.settings.design.desktop.header.no': 'No',
    'form.configuration.settings.design.desktop.header.deviceid': 'ID del Dispositivo',
    'form.configuration.settings.design.upload': 'Subir',
    'form.configuration.settings.common.name': 'Nombre',
    'form.configuration.settings.common.name.placeholder': 'Ingrese el nombre de la configuración',
    'form.configuration.settings.common.desc': 'Descripcion',
    'form.configuration.settings.common.desc.placeholder': 'Ingrese la descripcion de la configuración',
    'form.configuration.settings.common.admin.pwd': 'Contraseña Administrador',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Ingrese la contraseña de Administrador',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Cualquiera',
    'form.configuration.settings.common.gps.off': 'Deshabilitado',
    'form.configuration.settings.common.gps.on': 'Habilitado',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Datos Mobiles',
    'form.configuration.settings.common.usb.storage': 'Bloquear almacenamiento USB',
    'form.configuration.settings.common.brightness': 'Administrar brillo',
    'form.configuration.settings.common.brightness.none': 'Ninguno',
    'form.configuration.settings.common.brightness.auto': 'Automatico',
    'form.configuration.settings.common.brightness.manual': 'Valor',
    'form.configuration.settings.common.brightness.value': 'Brillo de pantalla',
    'form.configuration.settings.common.timeout': 'Tiempo de espera en pantalla',
    'form.configuration.settings.common.timeout.value': 'Espera en pantalla (s)',
    'form.configuration.settings.common.volume.block': 'Bloquear volumen',
    'form.configuration.settings.common.volume.manage': 'Administrar volumen',
    'form.configuration.settings.common.volume.value': 'Volumen',
    'form.configuration.settings.common.timezone.mode': 'Administrar Zona',
    'form.configuration.settings.common.timezone.mode.default': 'No administrar',
    'form.configuration.settings.common.timezone.mode.auto': 'Automatico',
    'form.configuration.settings.common.timezone.mode.manual': 'Manual',
    'form.configuration.settings.common.timezone': 'Zona',
    'form.configuration.settings.common.timezone.placeholder': 'e.j. America/Los_Angeles',
    'form.configuration.settings.common.timezone.link': 'Lista de zonas',
    'form.configuration.settings.common.no.network.warning': '¡ADVERTENCIA! ¡No apague todos los canales de conexión, de lo contrario ya no podrá administrar dispositivos!',
    'form.configuration.settings.request.updates': 'Actualizar Localizacion',
    'form.configuration.settings.request.updates.donottrack': 'No seguir',
    'form.configuration.settings.request.updates.gps': 'Con GPS',
    'form.configuration.settings.request.updates.wifi': 'Con Wi-Fi',
    'form.configuration.settings.request.updates.prompt.gps': 'Para seguir coordenadas debes habilitar el GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'Para seguir coordenadas debes habilitar el Wi-Fi',
    'form.configuration.settings.push.options' : 'Notificaciones Emergentes',
    'form.configuration.settings.push.options.mqtt.worker' : 'Protocolo MQTT (ahorra bateria)',
    'form.configuration.settings.push.options.mqtt.alarm' : 'Protocolo MQTT (envio instantaneo)',
    'form.configuration.settings.push.options.polling' : 'HTTP polling',
    'form.configuration.settings.push.options.mqtt.worker.hint' : 'Entrega mensajes Push instantáneamente cuando el dispositivo está activo. Pero los mensajes pueden demorarse hasta algunas horas en el modo de suspensión. No utilice esta opción en dispositivos independientes. MQTT usa el puerto TCP 31000, habilítelo en su firewall.',
    'form.configuration.settings.push.options.mqtt.alarm.hint' : 'Envía mensajes Push al instante, pero puede gastar más energía cuando un dispositivo está inactivo. La mejor opción para dispositivos autónomos. MQTT usa el puerto TCP 31000, habilítelo en su firewall.',
    'form.configuration.settings.push.options.polling.hint' : 'Entrega de manera confiable mensajes Push con un retraso máximo de 15 minutos. No requiere ningún puerto TCP que no sea HTTP (S). No utilice esta opción junto con el complemento de control remoto.',
    'form.configuration.settings.push.options.keepalive' : 'Mantener vivo el tiempo',
    'form.configuration.settings.minute.1' : '1 minuto',
    'form.configuration.settings.minutes.2' : '2 minutos',
    'form.configuration.settings.minutes.3' : '3 minutos',
    'form.configuration.settings.minutes.5' : '5 minutos',
    'form.configuration.settings.minutes.10' : '10 minutos',
    'form.configuration.settings.minutes.15' : '15 minutos',
    'form.configuration.settings.password.mode' : 'Requerimientos de contraseña',
    'form.configuration.settings.password.mode.any' : 'Ninguno',
    'form.configuration.settings.password.mode.present' : 'Presente Contraseña',
    'form.configuration.settings.password.mode.easy' : 'Facil (al menos 6 simbolos)',
    'form.configuration.settings.password.mode.moderate' : 'Moderada (8+ simbolos, letras y digitos)',
    'form.configuration.settings.password.mode.strong' : 'Fuerte (8+, mayusculas & minusculas, digitos, simbolos)',
    'form.configuration.settings.show.wifi': 'Configuración de WiFi en error de conexión',
    'form.configuration.settings.use.default.launcher': 'Usar con el launcher estándar',
    'form.configuration.settings.disable.screenshots': 'Deshabilitar la captura de pantalla',
    'form.configuration.settings.orientation': 'Bloquear orientacion',
    'form.configuration.settings.orientation.none': 'No bloquear',
    'form.configuration.settings.orientation.portrait': 'Vertical',
    'form.configuration.settings.orientation.landscape': 'Horizontal',
    'form.configuration.settings.files.default.path': 'Ruta predeterminada en el dispositivo',
    'form.configuration.files.search.label': 'Buscar:',
    'form.configuration.files.action.upload': 'Subir',
    'form.configuration.files.action.remove': 'Remover',
    'form.configuration.files.variables': 'Contenido variable',
    'form.configuration.files.variables.hint': 'Las cadenas DEVICE_NUMBER, IMEI, CUSTOM* se reemplazarán por sus valores',

    'form.configuration.file.name': 'Nombre archivo',
    'form.configuration.file.description': 'Descripcion archivo',
    'form.configuration.file.description.placeholder': 'Opcional, para su conveniencia',
    'form.configuration.file.path': 'Ruta al archivo',
    'form.configuration.file.path.placeholder': 'Sin ruta a una unidad, p. Ej. /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'Si un archivo está alojado en un recurso externo',
    'form.configuration.file.file': 'Archivo',
    'form.configuration.file.action': 'Accion',
    'form.configuration.file.action.prompt.1': 'Subir',
    'form.configuration.file.action.prompt.2': 'Remover',
    'form.configuration.file.remove.prompt.1': 'Este archivo no sera sincronizado con los dipositivos nunca mas',
    'form.configuration.file.remove.prompt.2': 'Eliminar este archivo del servidor',

    'form.password.title': 'Cambiar contraseña',
    'form.password.label.user': 'Usuario',
    'form.password.label.password.new': 'Nueva contraseña',
    'form.password.label.password.new.placeholder': 'Ingresa una nueva contraseña',
    'form.password.label.password.confirm': 'Verificar',
    'form.password.label.password.confirm.placeholder': 'Ingresa la contraseña nuevamente',

    'form.application.type': 'Tipo',
    'form.application.type.option.web': 'Pagina Web',
    'form.application.type.option.app': 'Aplicacion',
    'form.application.pkg': 'ID Paquete',
    'form.application.from.file': 'determinada por el archivo',
    'form.application.pkg.title': 'El ID del paquete se determina automáticamente cuando carga el archivo APK. El ID de paquete ingresado manualmente solo es necesario para las aplicaciones del sistema.',
    'form.application.pkg.placeholder': 'Por ejemplo, com.android.camera',
    'form.application.disabled.arch': 'Específico de la versión',
    'form.application.disabled.arch.title': 'Para agregar APK para diferentes arquitecturas de CPU, haga clic en "Agregar" o abra la lista de versiones de la aplicación',
    'form.application.arch': 'Código nativo',
    'form.application.arch.title': 'Algunas aplicaciones contienen código optimizado para cierta arquitectura de CPU. En este caso, debe cargar dos APK (para las arquitecturas armeabi-v7a y arm64-v8a)',
    'form.application.arch.universal': 'Ninguno (APK universal)',
    'form.application.arch.armeabi': 'Código nativo para armeabi-v7a',
    'form.application.arch.arm64': 'Código nativo para arm64-v8a',
    'form.application.arch.no.split': 'APK universal',
    'form.application.arch.split': 'APK dividido',
    'form.application.arch.warning': 'Este APK es solo para ${arch}. ¡No olvide cargar APK de otras arquitecturas de CPU!',
    'form.application.arch.success': 'Esta aplicación contiene APK para ambas arquitecturas de CPU',
    'form.application.version.exists': 'El APK para esta versión ya existe',
    'form.application.url.armeabi': 'URL de armeabi-v7a',
    'form.application.url.arm64': 'URL de arm64-v8a',
    'form.application.name': 'Nombre Aplicacion',
    'form.application.name.title': 'Verá el nombre de la aplicación en la lista. Recomendamos utilizar nombres únicos e informativos.',
    'form.application.name.placeholder': 'Por ejemplo, Cámara (Android)',
    'form.application.version': 'Version',
    'form.application.version.placeholder': '0 para aplicaciones del sistema',
    'form.application.version.title': 'La versión del paquete se determina automáticamente cuando carga el archivo APK. Póngalo en 0 para las aplicaciones del sistema.',
    'form.application.system': 'Sistema',
    'form.application.system.title': 'Las aplicaciones del sistema están preinstaladas en un dispositivo y no requieren URL ni archivo. Establezca este indicador solo si necesita habilitar un determinado paquete del sistema.',
    'form.application.run.after.install': 'Correr luego de la instalación',
    'form.application.run.after.install.title': 'Las aplicaciones con servicios en segundo plano deben iniciarse en primer plano al menos una vez.',
    'form.application.run.at.boot': 'Correr al inicio',
    'form.application.run.at.boot.title': 'Establezca esta marca si necesita ejecutar la aplicación en primer plano después del arranque. Esta bandera no afecta los procesos en segundo plano.',
    'form.application.url': 'URL',
    'form.application.url.title': 'La URL solo debe escribirse si su aplicación está alojada en un recurso externo. Se recomienda cargar un archivo APK utilizando un campo a continuación.',
    'form.application.url.disabled': 'La URL se configura para cada versión. Para cambiar la URL, cierre esta ventana y haga clic en el icono "Versiones".',
    'form.application.file': 'Archivo',
    'form.application.showLabel': 'Mostrar Icono',
    'form.application.showLabel.title': 'Esta bandera indica si el icono de la aplicación debe mostrarse en el lanzador. Esta opción puede anularse en la configuración.',
    'form.application.use.kiosk': 'Abierto en Kiosk Browser',
    'form.application.use.kiosk.title': 'Establezca esta bandera si desea abrir una página web en Kiosk-Browser sin posibilidad de cambiar la URL',
    'form.application.iconText': 'Texto del Icono',
    'form.application.iconText.placeholder': '(por defecto)',
    'form.application.versions.title': 'Versiones de Aplicacion',
    'form.application.icon': 'Icono',
    'form.application.icon.default': '(por defecto)',
    'form.application.icon.add': 'Añadir Icono',

    'form.application.setting.app': 'Aplicacion',
    'form.application.setting.app.placeholder': 'Seleccione una aplicacion',
    'form.application.setting.name': 'Atributo',
    'form.application.setting.value': 'Valor',
    'form.application.setting.comment': 'Comentario',
    'form.application.setting.type': 'Tipo',
    'form.application.setting.readonly': 'No cambia en el dispositivo',
    
    'form.application.configurations.app': 'Aplicacion',
    'form.application.configurations.configs': 'Configuración',

    'form.configuration.copy.new.name': 'Nuevo nombre',
    'form.configuration.copy.new.name.placeholder': 'Ingrese el nuevo nombre de configuración',

    'form.customer.name': 'Nombre',
    'form.customer.name.placeholder': 'Ingrese el nombre de la organizacion',
    'form.customer.apiKey': 'Clave API',
    'form.customer.apiKey.placeholder': 'Ingrese la clave API',
    'form.customer.prefix': 'Prefijo',
    'form.customer.prefix.placeholder': 'Ingrese el prefijo de número de dispositivo',
    'form.customer.device.configuration': 'Configuración del Dispositivo',
    'form.customer.desc': 'Descripcion',
    'form.customer.desc.placeholder': 'Ingrese una descripcion de la organizacion',
    'form.customer.copy.configuration': 'Copiar configuraciónes',
    'form.customer.copy.design': 'Copiar diseño',
    'form.customer.type': 'Tipo de cliente',
    'form.customer.status': 'Estado de cliente',
    'form.customer.expiry.time': 'Fecha de caducidad',
    'form.customer.device.limit': 'Límite de dispositivos',

    'form.device.number': 'Número',
    'form.device.number.locked': 'No se puede cambiar el número porque no se completó el cambio de número anterior.',
    'form.device.migration.warning': 'Se cambiará el número de dispositivo. Asegúrese de que el dispositivo esté encendido y en línea.',
    'form.device.number.hint': 'No utilice caracteres especiales',
    'form.device.desc': 'Descripcion',
    'form.device.groups': 'Grupos',
    'form.device.config': 'Configuración',
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Número Telefonico',

    'form.update.device.config': 'Configuración',

    'form.file.file': 'Archivo',
    'form.file.path': 'Ruta',
    'form.file.path.placeholder': 'Ingrese una ruta relativa, por ejemplo "/ archivos /"',

    'form.file.apps.name': 'Nombre de Aplicacion',
    'form.file.apps.pkg': 'ID del Paquete',
    'form.file.apps.version': 'Version',

    'form.group.name': 'Nombre',
    'form.group.name.placeholder': 'Ingrese el nombre del grupo',

    'form.user.login': 'Ingresar',
    'form.user.login.placeholder': 'Ingrese el usuario para ingreso',
    'form.user.name': 'Nombre',
    'form.user.name.placeholder': 'Ingrese su nombre de usuario',
    'form.user.role': 'Rol',
    'form.user.all.devices.available': 'Todos los dipositivos estan diposnibles',
    'form.user.available.groups': 'Grupos de dispositivos disponibles',
    'form.user.password.new': 'Nueva Contraseña',
    'form.user.password': 'Contraseña',
    'form.user.password.new.placeholder': 'Ingrese una nueva contraseña',
    'form.user.password.confirm': 'Verificar',
    'form.user.password.confirm.placeholder': 'Ingrese la nueva contraseña otra vez',

    'form.settings.hints.title': 'Pistas',

    'form.settings.plugins.title': 'Plugins Utilizados',

    'form.settings.common.title': 'Vista de Tabla Dispositivos',
    'form.settings.common.visible.columns': 'Columnas visibles en la tabla de "Dispositivos"',
    'form.settings.common.status': 'Estado',
    'form.settings.common.role': 'Rol de usuarios',
    'form.settings.common.date': 'Fecha',
    'form.settings.common.device.number': 'Número Dispositivo',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Número Telefonico',
    'form.settings.common.phone.model': 'Modelo del Telefono',
    'form.settings.common.status.permissions': 'Estado de Permisos',
    'form.settings.common.status.installation': 'Estado de Instalación',
    'form.settings.common.status.files': 'Estado de Archivos',
    'form.settings.common.config': 'Configuración',
    'form.settings.common.desc': 'Descripcion',
    'form.settings.common.group': 'Grupo',
    'form.settings.common.launcher.version': 'Version del Launcher',
    'form.settings.common.battery.level': 'Nivel de Bateria',
    'form.settings.common.default.launcher': 'Launcher por defecto',

    'form.settings.design.title': 'Diseño por Defecto',
    'form.settings.design.color.font': 'Color de Fondo',
    'form.settings.design.color.font.placeholder': 'Seleccione un color',
    'form.settings.design.color.app.names': 'Color de Nombre de Apliacaciones',
    'form.settings.design.color.app.names.placeholder': 'Seleccione un color',
    'form.settings.design.url.background.image': 'URL para la imagen de fondo',
    'form.settings.design.url.background.image.placeholder': 'Ingrese una URL para la imagen de fondo',
    'form.settings.design.size.icon': 'Tamaño de Iconos',
    'form.settings.design.size.icon.small': 'Pequeño',
    'form.settings.design.size.icon.medium': 'Normal (+ 20%)',
    'form.settings.design.size.icon.large': 'Grande (+ 40%)',
    'form.settings.design.desktop.header': 'Titulo del Escritorio',
    'form.settings.design.desktop.header.no': 'No',
    'form.settings.design.desktop.header.device.id': 'ID Dispositivo',

    'form.settings.lang.title': 'Opciones de Lenguaje',
    'form.settings.lang.use.default': 'Usar el lenguaje por defecto',
    'form.settings.lang.use': 'Usar lenguaje',
    'form.settings.lang.en': 'English',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',

    'form.settings.misc.title': 'Opciones Varias',
    'form.settings.misc.phone.format': 'Formato del número telefonico',
    'form.settings.misc.phone.format.placeholder': '+9 (999) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'Propiedad personalizada #1',
    'form.settings.misc.custom.property.name.2': 'Propiedad personalizada #2',
    'form.settings.misc.custom.property.name.3': 'Propiedad personalizada #3',
    'form.settings.misc.custom.property.multiline': 'Multilínea',
    'form.settings.misc.custom.property.send': 'Enviar a dispositivo',
    'form.settings.misc.custom.property.name.placeholder': 'Ingrese un nombre para la propiedad personalizada',
    'form.settings.misc.create.new.devices': 'Añadir dipositivo en el primer acceso',
    'form.settings.misc.new.device.config': 'Nuevo configuración de dispositivo',
    'form.settings.misc.new.device.group': 'Nuevo grupo de dispositivos',

    'form.settings.groups.title': 'Grupos',
    'form.settings.groups.search.placeholder': 'Buscar grupo',

    'form.settings.users.title': 'Usuarios',
    'form.settings.users.search.placeholder': 'Buscar usuario',

    'form.qr.device.number': 'ID del dispositivo',
    'form.qr.auto.create': 'Agregar a la lista de dispositivos si no existe',
    'form.qr.number.use': 'Asignación de ID de dispositivo',
    'form.qr.number.use.request': 'Valor de usuario',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'Número de serie',
    'form.qr.groups': 'Agregar a grupos',
    'form.qr.button.json': 'Obtener JSON',
    'form.qr.device.number.placeholder': 'Ingrese la ID del dispositivo ...',
    'form.qr.code.image.alt': 'Codigo QR',

    'form.profile.title': 'Cambiar contraseña',
    'form.profile.password.old': 'Contraseña Anterior',
    'form.profile.password.old.placeholder': 'Ingrese la contraseña anterior',
    'form.profile.password.new': 'Nueva contraseña',
    'form.profile.password.new.placeholder': 'Ingrese una nueva contraseña',
    'form.profile.password.confirm': 'Verificar',
    'form.profile.password.confirm.placeholder': 'Ingrese nuevamente la nueva contraseña',

    'tab.customers': 'Organizaciones',
    'tab.common.applications': 'Aplicaciones Compartidas',

    'tab.devices': 'Dispositivos',
    'tab.applications': 'Aplicaciones',
    'tab.configurations': 'Configuraciónes',
    'tab.files': 'Archivos',
    'tab.default.design': 'Diseño por Defecto',
    'tab.common.settings': 'Tabla de Dispositivos',
    'tab.users': 'Usuarios',
    'tab.groups': 'Grupos',
    'tab.language': 'Lenguaje y Otras Opciones',
    'tab.license': 'Licencia',
    'tab.hints': 'Pistas',
    'tab.plugins': 'Plugins',
    
    'tab.configeditor.common.settings': 'Opciones Comunes',
    'tab.configeditor.design.settings': 'Opciones de Diseño',
    'tab.configeditor.applications': 'Aplicaciones',
    'tab.configeditor.mdm.settings': 'Opciones MDM',
    'tab.configeditor.app.settings': 'Opciones de Aplicaciones',
    'tab.configeditor.files': 'Archivos',

    'search.placeholder.file': 'buscar archivo',
    'search.placeholder.configuration': 'Buscar configuración',
    'search.placeholder.customer': 'Buscar una organizacion',
    'search.placeholder.application': 'Buscar una aplicacion',
    'search.placeholder.application.setting': 'Buscar por una opcion de aplicacion',
    'search.placeholder.device': 'Buscar un dispositivo',
    'search.placeholder.address': 'Buscar direccion',
    'search.placeholder.point': 'Buscar sitio',
    'search.placeholder.message': 'Buscar mensaje',
    'search.placeholder': 'Buscar ...',
    'search.placeholder.from': 'De ...',
    'search.placeholder.to': 'Para ...',
    'search.placeholder.user': 'Ingrese el nombre de usuario',

    'table.heading.customer.name': 'Nombre',
    'table.heading.customer.desc': 'Descripcion',
    'table.heading.customer.registration.time': 'Registrado',
    'table.heading.customer.last.login.time': 'Ultimo ingreso',
    'table.heading.customer.actions': 'Acciones',
    'table.heading.customer.type': 'Tipo',
    'table.heading.customer.expiry.time': 'Expira',
    'table.heading.customer.device.limit': 'Límite',
    'table.heading.customer.status': 'Estado',

    'customer.new': 'Nuevo',
    'customer.active': 'Activo',
    'customer.need.followup': 'Necesita seguimiento',
    'customer.followup.sent': 'Seguimiento enviado',
    'customer.internal.test': 'Prueba interna',
    'customer.developer': 'Elaborador',
    'customer.difficult': 'Difícil',
    'customer.pause': 'Pausa',
    'customer.denial': 'Negación',
    'customer.client': 'Cliente',

    'table.heading.configuration.name': 'Nombre',
    'table.heading.configuration.desc': 'Descripcion',
    'table.heading.configuration.actions': 'Acciones',

    'table.heading.application.setting.app.pkg': 'ID de Paquete',
    'table.heading.application.setting.app.name': 'Nombre Aplicacion',
    'table.heading.application.setting.name': 'Atributo',
    'table.heading.application.setting.value': 'Valor',
    'table.heading.application.setting.comment': 'Comentario',
    'table.heading.application.setting.lastUpdate': 'Fecha de Creacion',

    'table.heading.file.url': 'URL',
    'table.heading.file.devicepath': 'Ruta en Dispositivo',
    'table.heading.file.description': 'Descripcion del archivo',
    'table.heading.file.action': 'Accion',
    'table.heading.file.lastUpdate': 'Fecha de Creacion',
    
    'table.heading.application.pkg': 'ID del Paquete',
    'table.heading.application.name': 'Nombre Aplicacion',
    'table.heading.application.version': 'Version',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Icono',
    'table.heading.application.actions': 'Acciones',
    'table.heading.application.order': 'Orden',

    'table.heading.device.status': 'Estado',
    'table.heading.device.date': 'Fecha',
    'table.heading.device.device.number': 'Número Dispositivo',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Número Telefonico',
    'table.heading.device.phone.model': 'Modelo Telefono',
    'table.heading.device.status.permissions': 'Estado Permisos',
    'table.heading.device.status.installation': 'Estado Instalación',
    'table.heading.device.status.files': 'Estado Archivos',
    'table.heading.device.configuration': 'Confituracion',
    'table.heading.device.desc': 'Descripcion',
    'table.heading.device.group': 'Grupo',
    'table.heading.device.launcher.version': 'Version del Launcher',
    'table.heading.device.battery.level': 'Nivel de Bateria',
    'table.heading.device.default.launcher': 'Por Defecto',
    'table.heading.device.actions': 'Acciones',

    'table.heading.group.name': 'Nombre',
    'table.heading.group.actions': 'Acciones',

    'table.heading.file.name': 'Nombre Archivo',
    'table.heading.file.path': 'Ruta',
    'table.heading.file.address': 'Direccion',
    'table.heading.file.actions': 'Acciones',

    'table.heading.users.login': 'Ingreso',
    'table.heading.users.name': 'Nombre',
    'table.heading.users.role': 'Rol',
    'table.heading.users.actions': 'Acciones',

    'table.heading.common.apps.customer': 'Organizacion',
    'table.heading.common.apps.pkg': 'ID del Paquete',
    'table.heading.common.apps.name': 'Nombre Aplicacion',
    'table.heading.common.apps.version': 'Version',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Icono',
    'table.heading.common.apps.actions': 'Acciones',

    'notfound.devices': 'No hay dispositivos para mostrar.',
    'notfound.files':' La lista de archivos esta vacia',
    'notfound.configurations': 'No se encontraron configuraciónes.',
    'notfound.customers': 'No se encontraron organizaciones.',
    'notfound.common.apps': 'No hay aplicaciones para mostrar.',
    'notfound.applications': 'No se encontraron aplicaciones.',
    'notfound.groups':' No se encontraron grupos. Prueba una consulta diferente',
    'notfound.users':' No se encontraron usuarios. Prueba una consulta diferente',
    'notfound.apps.for.display': 'No hay aplicaciones para mostrar.',
    'notfound.app.versions.for.display': 'No hay versiones para mostrar.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    'menu.about': 'Informacion',
    'menu.profile': 'Perfil',
    'menu.panel.master': 'Panel Maestro',
    'menu.panel.main': 'Panel Principal',
    'menu.logout': 'Salir',
    'menu.functions': 'Funciones',
    'menu.settings': 'Opciones',
    'menu.show.hints': 'Mostrar pistas',

    'plugin.name.not.specified': '<< El nombre de la funcion no esta especificado >>',

    'breadcrumb.devices': 'Dispositivos',
    'breadcrumb.applications': 'Aplicaciones',
    'breadcrumb.configurations': 'Configuraciónes',
    'breadcrumb.files': 'Archivos',
    'breadcrumb.default.design': 'Diseño por defecto',
    'breadcrumb.common.settings': 'Tabla de Dispositivos',
    'breadcrumb.language.settings': 'Lenguaje y Otras Opciones',
    'breadcrumb.license.settings': 'Licencia',
    'breadcrumb.users': 'Usuarios',
    'breadcrumb.groups': 'Grupos',
    'breadcrumb.hints': 'Pistas',
    'breadcrumb.plugins': 'Plugins',
    'breadcrumb.config.details': 'Detalles',
    'breadcrumb.application.versions': 'Versiones',

    'app.name': 'Headwind MDM',
    'app.vendor.name':"h-mdm.com",
    'app.vendor.link':"https://h-mdm.com",
    'app.description': 'es la solucion MDM open-source',
    'app.title': '${appName} Panel Web',

    'box.show.my.apps.only': 'Mostrar mis aplicaciones solamente',
    'configuration.app.version.upgrade.message': 'Version instalada ${installedVersion}, version disponible ${latestVersion}',

    'about.line.1': '${appName} panel de control',
    'about.line.2': 'Launcher Enterprise para Android',
    'about.line.3': 'Version ${versionNumber}',
    'about.line.4': 'Plugins Instalados',

    'common.app.clarification': 'Esta aplicacion es publica y no esta disponible para editar, por favor, contacte al administrador',

    'qrcode.help.line1': 'Para configurar un dispositivo Android (version 7 or mayor) en un modo adminsitrado:',
    'qrcode.help.line2': 'Restaurar el dispositivo a su estado de fabrica',
    'qrcode.help.line3': 'Presiona 7 veces en la pantalla de inicio (debes entrar a el modo de escaneo QR)',
    'qrcode.help.line4': 'Sigue las instrucciones del dispositivo: acepta los terminos, conecta el Wi-Fi, y escanea este codigo QR',
    'qrcode.help.line5': 'Este QR debe contener el ID del dispositivo de ${appName} (no necesitas ingresarlo en el dispositivo). Para agregar la ID del dispositivo al QR, ingresa la ID del dispositvo y presiona "Renovar".',

    'form.configuration.app.version.select.select.title': 'Selecciona la version a instalar',
    'form.configuration.app.version.select.version.check.off': 'Deshabilitar la verificacion de version',
    'form.configuration.app.version.select.upgrade.warning': 'Actualizar aplicacion "${v1}" a la version version "${v3}" para configuración "${v2}"?',
    'form.configuration.app.version.select.downgrade.warning': 'Downgrade version DELETE ALL THESE APPLICATIONS on all devices! Downgrade the application version "${v1}" to version "${v2}"? ',

    'hint.step.1': 'Haz click aqui para comenzar el provisionamiento del dispositivo',
    'hint.step.2': 'Haz click aqui para mostrar el codigo QR',
    'hint.step.3': 'Haz click aqui para ingresar al lector QR del dispositivo',
    'hint.step.4': 'Ingresa una ID disponible en la pestaña «Dispositivos». Haz click en «Recargar» para incluirla en el codigo QR.',

    'ie.browser.notice.1': 'Desafortunadamente, Internet Explorer no es soportado.',
    'ie.browser.notice.2': 'Recomendamos el explorador web - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a>.',

    'form.resolved.duplicate.pkg.text1': 'ID del paquete "${pkg}" ya esta siendo usada.',
    'form.resolved.duplicate.pkg.text2': 'Deseas añadir una nueva aplicacion o una nueva version de la aplicacion?',
    'form.resolved.duplicate.pkg.text3': 'Nueva version para',
    'form.resolved.duplicate.pkg.text4': 'Las aplicaciones ${apps} ya utilizan el ID de paquete "${pkg}"',
    'form.resolved.duplicate.pkg.text5': '¿Está seguro de que desea cambiar el ID del paquete?',

    'tooltip.usage.byconfigurations': 'Usada por configuraciónes',
    'tooltip.usage.byapps': 'Usada por aplicaciones',
    'tooltip.usage.byicons': 'Usada por inconos',

    'form.devices.label.params.more': 'Mas parametros',
    'form.devices.label.params.less': 'Menos parametros',
    'form.devices.label.installation.status': 'Estado de Instalación',
    "format.devices.date.createTime": "dd/MM/yyyy HH:mm:ss",
    "format.devices.date.datePicker": "dd-MM-yyyy",

    'form.devices.selection.install.status.default': 'Estado de instalación ...',
    'form.devices.selection.install.status.all': 'Todos',
    'form.devices.selection.install.status.success': 'Satisfactorio',
    'form.devices.selection.install.status.version.mismatch': 'Error de Version',
    'form.devices.selection.install.status.failure': 'Fallo',
    'form.devices.selection.imei.changed': 'IMEI cambio recientemente',

    'search.placeholder.launcher.version': 'Version del Launcher',
    'error.date.range.invalid': 'Rango de fechas invalido',

    'customer.type.demo': 'Demo',
    'customer.type.small': 'Profesional',
    'customer.type.corporate': 'Empresa',
    'customer.type.master': 'Primaria',

    'customer.type.options.all': 'Todos los tipos',
    'customer.status.options.all': 'Todos los estados',

    'account.expiring': 'Su cuenta caducará en $ {days} días. Comuníquese con el vendedor para renovar su cuenta.',
    'account.expired': 'Su cuenta ha caducado. Comuníquese con el vendedor para renovar su cuenta.',
    'account.expired.short': 'Su cuenta ha caducado.',
    'device.limit.achieved': 'No se puede agregar un dispositivo porque alcanzó su límite. Quite algunos dispositivos o comuníquese con el vendedor para ampliar el límite de dispositivos.',

    'yes': 'si',
    'no': 'no'
};
