if (! document.localization) document.localization = [];

document.localization ['fr_FR'] = {
    'login.username': 'Identifiant ou email',
    'login.username.placeholder': 'Entrez votre identifiant ou email',
    'login.password': 'Mot de passe :',
    'login.password.placeholder': 'Entrez le mot de passe',
    'login.submit': 'S\'identifier',
    'login.password.incorrect': 'Identifiant ou mot de passe invalide',

    'header.label.username': 'Identifiant',

    'devices.group.options.all': 'Tous les groupes',
    'devices.configuration.options.all': 'Toutes les configurations',
    'devices.permissions.all': 'Toutes les autorisations sont accordées',
    'devices.permissions.not.as.device.admin': '- L\'application n\'est pas installée comme administrateur de l\'appareil',
    'devices.permissions.window.overlap.prohibited': '- La superposition sur d\'autres fenêtres non disponibles.',
    'devices.permissions.history.access.prohibited': '- Accès à l\'historique des usages non configuré.',
    'devices.unknown': 'Inconnue',
    'devices.model.unknown': 'Inconnue',
    'devices.date.unknown': 'Inconnue',
    'devices.date.format': 'dd/MM HH:mm',
    'devices.app.installed': '- ${applicationName}: Installée.',
    'devices.app.not.installed': '- ${applicationName}: pas installé.',
    'devices.app.version.available': ', disponible ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: installée ${applicationInstalledVersion}, disponible ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, suppression est requise',
    'devices.no.data': 'L\'appareil n\'a pas transmis de données',
    'devices.settings.conformance.broken': 'Incohérence avec les paramètres: (${serverData})',
    'devices.file.installed': '- ${file}: installé',
    'devices.file.not.installed': '- ${file}: pas installé.',
    'devices.file.lastUpdate.differs': '- ${file}: différence dans le temps de modification ${diff} min',

	'button.apply': 'Appliquer',
    'button.gps.on': 'Activer GPS',
    'button.wifi.on': 'Activer Wi-Fi',
    'button.notify.update': 'Notifier lors de la mise à jour',
    'button.app.settings': 'Paramètres de l\'application',
    'button.ok': 'D\'accord',
    'button.help': 'Aide',
    'button.new.app': 'Nouvelle application',
    'button.new.app.version': 'Nouvelle version',
    'button.upgrade': 'Mettre à jour',
    'button.renew.config': 'Mise à jour sur les appareils',
    'button.common': 'Application commune',
    'button.close': 'Fermer',
    'button.yes': 'Oui',
    'button.cancel': 'Annuler',
    'button.save': 'Enregistrer',
    'button.save.and.close': 'Enregistrer et fermer',
    'button.more': 'Plus ...',
    'button.cleanup': 'Effacer',
    'button.add': 'Ajouter',
    'button.add.icon': 'Nouvelle icône',
    'button.search': 'Rechercher',
    'button.export': 'Exporter',
    'button.change': 'Modifier',
    'button.copy': 'Copier',
    'button.qrcode': 'Code QR',
    'button.application': 'Application',
    'button.change.password': 'Changer le mot de passe',
    'button.set.configuration': 'Définir la configuration',
    'button.group.action': 'Action de groupe',
    'button.delete': 'Supprimer',
    'button.login': 'S\'identifier',
    'button.renew.code': 'Renouveler',
    'button.configurations': 'Configurations',
    'button.set.configurations': 'Spécifier les configurations',
    'button.edit.versions': 'Versions',
    'button.edit': 'Modifier',
    'button.change.common.app': 'Modifier l\'application partagée',
    'button.delete.common.app': 'Supprimer l\'application partagée',
    'button.turn.common.app': 'Rendre commun',
    'button.hints.enable': 'Afficher les info-bulles',
    'button.hints.disable': 'Masquer les info-bulles',
    'button.show.password': 'Afficher le mot de passe',
    'button.hide.password': 'Masquer le mot de passe',

	'question.impersonate.user': 'Connectez-vous à l\'application comme administrateur de l\'organisation "${customerName}"?',
    'question.change.user': 'Connectez-vous à l\'application en tant qu\'utilisateur "${userName}"?',
    'question.delete.file': 'Supprimer le fichier "${fileName}"?',
    'question.delete.customer': 'Supprimer l\'organisation "${customerName}"?',
    'question.delete.user': 'Supprimer l\'utilisateur "${username}"?',
    'question.delete.application': 'Supprimer l\'application "${applicationName}"?',
    'question.delete.application.version': 'Supprimer la version "${applicationVersion}"?',
    'question.delete.configuration': 'Supprimer la configuration "${configurationName}"??',
    'question.delete.group': 'Supprimer le groupe "${groupName}"?',
    'question.delete.device': 'Supprimer l\'appareil avec le numéro "${deviceNumber}"?',
    'question.exit.without.saving': 'Aucune modification est conservée. Bref, quittez la page.?',
    'question.turn2common.application': 'Partager l\'application "${applicationName}"?',
    'question.app.upgrade': 'Actualiser l\'application "${v1}" vers la dernière version pour la configuration "${v2}"?',
     
    'error.application.setting.empty.app': 'Spécifiez l\'application',
    'error.application.setting.empty.name': 'Entrez un nom',
    'error.application.setting.empty.value': 'Spécifiez une valeur',

    'error.icon.dimension.invalid': 'L\'icône doit être carrée',
    'error.icon.empty.name': 'Entrez le nom de l\'icône',
    'error.icon.empty.file': 'Télécharger le fichier d\'icône',
    'error.application.version.pkg.mismatch': 'Le package ID du fichier (${réel}) ne correspond pas à l\'application (${expected})',
	'error.empty.user': 'Sélectionnez un utilisateur',
    'error.empty.user.name': 'Remplissez l\'identifiant',
    'error.empty.user.login': 'Remplir l\'identifiant de l\'utilisateur',
    'error.empty.user.role': 'Sélectionnez un rôle utilisateur',
    'error.empty.password': 'Entrez un nouveau mot de passe',
    'error.empty.password.confirm': 'Entrez la confirmation du mot de passe',
    'error.empty.group.name': 'Remplissez le nom du groupe',
    'error.empty.configuration': 'Spécifiez la configuration',
    'error.empty.configuration.name': 'Remplissez le nom de la configuration',
    'error.empty.configuration.password': 'Remplissez le mot de passe',
    'error.empty.configuration.contentApp': 'Aucune application de contenu est spécifiée',
    'error.invalid.configuration.mainApp': 'Dans les paramètres MDM, la mauvaise application principale est utilisée',
    'error.invalid.configuration.contentApp': 'Invalide contenu utilisé de l\'application dans les paramètres MDM',
    'error.mismatch.password': 'Mot de passe et sa confirmation doivent correspondre',
    'error.empty.customer.name': 'Remplissez le nom de l\'organisation',
    'error.empty.customer.prefix': 'Remplissez le préfixe du numéro de l\'appareil',
    'error.empty.customer.device.configuration': 'Sélectionnez la configuration de l\'appareil',
    'error.empty.customer.duplicate.prefix': 'Préfixe déjà utilisé',
    'error.duplicate.customer.name': 'Nom de l\'organisation saisi existe, essayez un autre nom.',								  
    'error.duplicate.group.name': 'Nom de groupe saisi existe, essayez un autre nom.',
    'error.duplicate.configuration.name': 'Nom de configuration saisi existe, essayez un autre nom.',
    'error.duplicate.device.number': 'Un appareil avec ce numéro existe',
    'error.internal.server': 'Erreur interne du serveur',
    'error.permission.denied': 'Aucun droit à exécuter',
    'error.request.failure': 'Échec de la demande',
    'error.configuration.device.use': 'Suppression impossible de cette configuration, déjà utilisée sur appareils. Allez sur " Appareils ", trouvez les appareils ayant cette configuration et modifiez ses paramètres.',
    'error.invalid.system.update.time': 'Invalide intervalle d\'installation',
    
	'error.configuration.file.empty.name': 'Entrez nom de fichier',
    'error.configuration.file.empty.desc': 'Spécifiez description de fichier',
    'error.configuration.file.empty.path': 'Spécifiez chemin sur l\'appareil',
    'error.configuration.file.empty.file': 'Entrez URL ou téléchargez un fichier',
    
	'error.notfound.device': 'Appareil non trouvé',
    'error.duplicate.device': 'Un appareil avec le même numéro existe déjà',
    'error.duplicate.login': 'Un tel identifiant est déjà utilisé',
    'error.duplicate.group': 'Un groupe ayant le même nom existe',
    'error.duplicate.application': 'Une application avec ce package ID et version existe déjà',
    'error.recent.application.version.exists': 'Une version plus récente de l\'application existe',
    'error.common.application.access.prohibited': 'Seule le super-administrateur est autorisé à gérer les applications communes',
    'error.application.config.reference.exists': 'L\'application est utilisée dans des configurations et impossible à supprimer.',
    'error.application.version.deletion.prohibited': 'Soit la version est unique, ou utilisée dans des configurations, et ne peut être supprimée',
    'error.duplicate.file': 'Un fichier du même nom existe',
    'error.used.file': 'Ce fichier est utilisé',
    'error.version.exists': 'La même version de cette application existe',
    'error.duplicate.configuration': 'Une configuration avec ce nom existe',
    'error.notfound.customer.admin': 'Compte administrateur introuvable',
    'error.apk.file.required': 'Sélectionnez le fichier avec l\'extension .apk ou .xapk',
    'error.apk.parse': 'Une erreur s\'est produite lors de l\'analyse du fichier',
    'error.empty.app.name': 'Entrez le nom de l\'application',
    'error.empty.app.pkg': 'Entrez ID du package',
    'error.empty.app.url': 'Entrez URL',
    'error.empty.app.iconText': 'Entrez le texte de l\'icône',
    'error.empty.app.version': 'Entrez la version de l\'application',
    'error.notempty.group': 'Ce groupe comprend un ou plusieurs appareils. Impossible de supprimer.',
    'error.file.empty': 'Télécharger un nouveau fichier',
    'error.file.deletion': 'Erreur lors de la suppression du fichier sur le serveur',
    'error.file.save': 'Erreur lors de l\'enregistrement du fichier sur le serveur',
    'error.password.wrong': 'Mot de passe invalide',
    'error.password.empty': 'Mot de passe non spécifié',
    'error.params.missing': 'Paramètres manquants:',
    'error.empty.push.options': 'Veuillez sélectionner les options de notifications push',

	'table.filtering.check.all': 'Tout sélectionner',
    'table.filtering.uncheck.all': 'Tout annuler',
    'table.filtering.suffix.configuration': 'configurations',
    'table.filtering.suffix.group': 'groupes',
    'table.filtering.no.selected.configuration': 'Aucune configuration sélectionnée',
    'table.filtering.no.selected.group': 'Aucun groupe sélectionné',

	'success.admin.created': 'Compte administrateur créé:\n ${adminCredentials}',
    'success.uploading.file': 'Le fichier est téléchargé sur le serveur ...',
    'success.loading.devices': 'Chargement de la liste des appareils ...',
    'success.loading.customer': 'Chargement des données client ...',
    'success.file.uploaded': 'Fichier téléchargé avec succès.',
    'success.file.uploaded.need.save': 'Fichier téléchargé avec succès. Entrez le chemin relatif et cliquez sur "Enregistrer".',
    'success.settings.design.saved': 'Paramètres de conception enregistrés avec succès',
    'success.settings.common.saved': 'Paramètres généraux enregistrés avec succès',
    'success.settings.saved': 'Paramètres enregistrés avec succès',
    'success.settings.apiKey.saved': 'Clé API enregistrée avec succès',
    'success.settings.hints.enabled': 'Indications activées',
    'success.settings.hints.disabled': 'Indications désactivées',
    'success.configuration.saved': 'Configuration enregistrée avec succès',
    'success.operation.completed': 'Opération terminée avec succès',
    'success.plugins.disabled': 'Paramètres enregistrés avec succès',
    'success.config.update.notification': 'Commande de mise à jour de la configuration a été envoyée aux appareils',
    'success.config.update.device.app.settings.notification': 'Commande de mise à jour des paramètres de l\'application a été envoyée à l\'appareil.',

	'form.icon.title': 'Icône',
    'form.icon.name': 'Nom',
    'form.icon.file': 'Fichier',

    'configuration.add.warning': 'Voulez-vous vraiment créer une configuration vide? Vous devrez ajouter manuellement toutes les applications système requises. Envisagez plutôt de copier et de modifier une configuration existante.',
    'configuration.remove.warning': 'Voulez-vous vraiment supprimer la dernière configuration? Vous perdrez des informations sur les applications système requises.',
	'form.configuration.title': 'Configuration',
    'form.configuration.title.typical': 'Configuration typique',
    'form.configuration.settings.auto.update': 'Mise à jour automatique',
    'form.configuration.settings.system.update': 'Mise à jour du système',
    'form.configuration.settings.system.update.default': 'Par défaut',
    'form.configuration.settings.system.update.immediate': 'Immédiatement',
    'form.configuration.settings.system.update.scheduled': 'Programmé',
    'form.configuration.settings.system.update.postponed': 'Reporté',
    'form.configuration.settings.system.update.time': 'Heure d\'installation',
    'form.configuration.settings.system.update.time.from': 'de:',
    'form.configuration.settings.system.update.time.to': 'à:',
    'form.configuration.settings.block.status.bar': 'Verrouillage de la barre d\'état',
    'form.configuration.settings.block.status.bar.hint': 'Ce paramètre est obsolète et fonctionne sur Android 6 et versions antérieures. Pour verrouiller la barre d\'état sur les nouvelles versions d\'Android, utilisez le mode kiosque (paramètres MDM).',
    'form.configuration.settings.mdm.kiosk.mode': 'Mode kiosk',
    'form.configuration.settings.mdm.app.main': 'Application principale',
    'form.configuration.settings.mdm.component.event.receiver': 'Composant - destinataire de l\'événement',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Entrez le nom du composant',
    'form.configuration.settings.mdm.component.wifi.ssid': 'SSID WiFi',
    'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'Inscription WiFi SSID - laissez vide pour entrer manuellement',
    'form.configuration.settings.mdm.component.wifi.password': 'Mot de passe WiFi',
    'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Inscription passe de WiFi - laissez vide pour entrer manuellement',
    'form.configuration.settings.mdm.component.wifi.security': 'Type de sécurité WiFi',
    'form.configuration.settings.mdm.component.wifi.notice': 'Remarque: ces paramètres WiFi ne sont appliqués qu\'à l\'inscription initiale!',
    'form.configuration.settings.mdm.component.server.url': 'Nouveaux server URL',
    'form.configuration.settings.mdm.component.server.url.placeholder': 'Utilisé pour la migration vers un nouveau serveur MDM',
    'form.configuration.settings.mdm.app.content': 'Application de contenu',
    'form.configuration.settings.mdm.kiosk.home': 'Activer le bouton Accueil',
    'form.configuration.settings.mdm.kiosk.recents': 'Activer le bouton Récents',
    'form.configuration.settings.mdm.kiosk.notifications': 'Activer les notifications',
    'form.configuration.settings.mdm.kiosk.system.info': 'Activer les informations de la barre d\'état',
    'form.configuration.settings.mdm.kiosk.keyguard': 'Activer le verrouillage de l\'écran',
    'form.configuration.settings.mdm.mobile.enrollment': 'S\'inscrire en utilisant les données mobiles',
    'form.configuration.settings.mdm.lock.safe.settings': 'Verrouiller les paramètres de sécurité (WiFi, GPS, etc.)',
    'form.configuration.settings.mdm.allowed.classes': 'Activités autorisées',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'Classes séparées par des virgules, p.e.: com.android.settings.homepage.SettingsHomepageActivity',
    'form.configuration.settings.mdm.restrictions': 'Restrictions',
    'form.configuration.settings.mdm.restrictions.placeholder': 'Restrictions MDM, séparées par des virgules, p.e.: no_sms,no_outgoing_calls,no_usb_file_transfer',
    'form.configuration.settings.mdm.qrcode.url': 'Adresse URL du code QR',
    'form.configuration.settings.mdm.hint': 'Sélectionnez l\'application principale et le composant',
    'form.configuration.apps.search.label': 'Rechercher:',
    'form.configuration.apps.sort.label': 'Trier:',
    'form.configuration.apps.sort.byname': 'Par nom',
    'form.configuration.apps.sort.bypkg': 'Par ID',
    'form.configuration.apps.no.apk': 'rien',
    'form.configuration.apps.show.systeam.apps': 'Afficher les applications système',
    'form.configuration.apps.action.install': 'Installer',
    'form.configuration.apps.action.prohibit': 'Interdire',
    'form.configuration.apps.action.not.install': 'Ne pas installer',
    'form.configuration.apps.action.delete': 'Supprimer',
    'form.configuration.apps.action.permit': 'Permettre',
    'form.configuration.apps.label.inherit': 'Hérité',
    'form.configuration.apps.label.show': 'Afficher',
    'form.configuration.apps.label.not.show': 'Cacher',
    'form.configuration.apps.edit.details': 'Paramètres supplémentaires',
    'form.configuration.apps.keycode': 'Code clé',
    'form.configuration.apps.bottom': 'Affichage en bas',
    'form.configuration.apps.hint': 'Astuce: pour dissocier l\'application de la configuration, sélectionnez l\'action "Bloquer" ou "Ne pas installer".',
    'form.configuration.settings.design.use.default': 'Utiliser la conception par défaut',
    'form.configuration.settings.design.color.background': 'Couleur d\'arrière-plan',
    'form.configuration.settings.design.color.background.placeholder': 'Sélectionnez une couleur',
    'form.configuration.settings.design.color.app.names': 'Couleur des noms d\'application',
    'form.configuration.settings.design.color.app.names.placeholder': 'Sélectionnez une couleur',
    'form.configuration.settings.design.background.image.url': 'Adress URL de l\'image d\'arrière-plan',
    'form.configuration.settings.design.background.image.url.placeholder': 'Entrez url de l\'image d\'arrière-plan',
    'form.configuration.settings.design.icon': 'Taille de l\'icône',
    'form.configuration.settings.design.icon.small': 'Petit',
    'form.configuration.settings.design.icon.medium': 'Moyenne (+20%)',
    'form.configuration.settings.design.icon.large': 'Grand (+40%)',
    'form.configuration.settings.design.desktop.header': 'Titre du bureau',
    'form.configuration.settings.design.desktop.header.no': 'Non',
    'form.configuration.settings.design.desktop.header.deviceid': 'ID de l\'appareil',
    'form.configuration.settings.design.upload': 'Télécharger',
    'form.configuration.settings.common.name': 'Nom',
    'form.configuration.settings.common.name.placeholder': 'Entrez le nom de la configuration',
    'form.configuration.settings.common.desc': 'Description',
    'form.configuration.settings.common.desc.placeholder': 'Entrez la description de la configuration',
    'form.configuration.settings.common.admin.pwd': 'Mot de passe administrateur',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Entrez le mot de passe administrateur',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Tout',
    'form.configuration.settings.common.gps.off': 'Désactivé',
    'form.configuration.settings.common.gps.on': 'Activé',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Données mobiles',
    'form.configuration.settings.common.usb.storage': 'Bloquer le stockage USB',
    'form.configuration.settings.common.brightness': 'Gérer la luminosité',
    'form.configuration.settings.common.brightness.none': 'Aucun',
    'form.configuration.settings.common.brightness.auto': 'Auto',
    'form.configuration.settings.common.brightness.manual': 'Valeur',
    'form.configuration.settings.common.brightness.value': 'Luminosité de l\'écran',
    'form.configuration.settings.common.timeout': 'Gérer le mise en veille de l\'écran',
    'form.configuration.settings.common.timeout.value': 'Veille de l\'écran (s)',
    'form.configuration.settings.common.volume.block': 'Verrouiller le volume',
    'form.configuration.settings.common.volume.manage': 'Gérer le volume',
    'form.configuration.settings.common.volume.value': 'Volume',
    'form.configuration.settings.common.timezone.mode': 'Gérer le fuseau horaire',
    'form.configuration.settings.common.timezone.mode.default': 'Ne gère pas',
    'form.configuration.settings.common.timezone.mode.auto': 'Auto',
    'form.configuration.settings.common.timezone.mode.manual': 'Valeur',
    'form.configuration.settings.common.timezone': 'Fuseau horaire',
    'form.configuration.settings.common.timezone.placeholder': 'p.e. America/Los_Angeles',
    'form.configuration.settings.common.timezone.link': 'Liste des fuseaux horaires',
    'form.configuration.settings.common.no.network.warning': 'ATTENTION! Ne désactivez pas tous les canaux de connexion, sinon vous ne pourrez plus gérer les appareils!',
    'form.configuration.settings.request.updates': 'Mettre à jour la localisation',
    'form.configuration.settings.request.updates.donottrack': 'Ne pas suivre',
    'form.configuration.settings.request.updates.gps': 'Par GPS',
    'form.configuration.settings.request.updates.wifi': 'Par Wi-Fi',
    'form.configuration.settings.request.updates.prompt.gps': 'Pour suivre les coordonnées GPS, vous devez activer le GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'Pour suivre les coordonnées Wi-Fi, vous devez activer le Wi-Fi',
    'form.configuration.settings.push.options': 'Notifications push',
    'form.configuration.settings.push.options.mqtt.worker': 'Protocole MQTT (économiser la batterie)',
    'form.configuration.settings.push.options.mqtt.alarm': 'Protocole MQTT (livraison instantanée)',
    'form.configuration.settings.push.options.polling': 'interrogation HTTP',
    'form.configuration.settings.push.options.mqtt.worker.hint' : 'Fournit des messages Push instantanément lorsque l\'appareil est actif. Mais les messages peuvent être retardés jusqu\'à quelques heures en mode veille. N\'utilisez pas cette option sur les appareils autonomes. MQTT utilise le port TCP 31000, activez-le sur votre pare-feu.',
    'form.configuration.settings.push.options.mqtt.alarm.hint' : 'Fournit des messages Push instantanément, mais peut dépenser plus d\'énergie lorsqu\'un appareil est en veille. Meilleure option pour les appareils alimentés autonomes. MQTT utilise le port TCP 31000, activez-le sur votre pare-feu.',
    'form.configuration.settings.push.options.polling.hint' : 'Délivre de manière fiable les messages Push avec un délai maximum de 15 minutes. Ne nécessite aucun port TCP autre que HTTP (S). N\'utilisez pas cette option avec le plugin de contrôle à distance.',
    'form.configuration.settings.push.options.keepalive' : 'Temps de Keep-Alive',
    'form.configuration.settings.minute.1' : '1 minute',
    'form.configuration.settings.minutes.2' : '2 minutes',
    'form.configuration.settings.minutes.3' : '3 minutes',
    'form.configuration.settings.minutes.5' : '5 minutes',
    'form.configuration.settings.minutes.10' : '10 minutes',
    'form.configuration.settings.minutes.15' : '15 minutes',
    'form.configuration.settings.password.mode' : 'Exigences relatives au mot de passe',
    'form.configuration.settings.password.mode.any' : 'Aucune',
    'form.configuration.settings.password.mode.present' : 'Mot de passe présente',
    'form.configuration.settings.password.mode.easy' : 'Facile (au moins 6 symboles)',
    'form.configuration.settings.password.mode.moderate' : 'Modéré (8+ symboles, lettres et chiffres)',
    'form.configuration.settings.password.mode.strong' : 'Fort (8+, majuscules et minuscules, chiffres, signes)',
    'form.configuration.settings.show.wifi': 'Paramètres WiFi en cas d\'erreur de connexion',
    'form.configuration.settings.use.default.launcher': 'Utiliser avec le lanceur par défaut',
    'form.configuration.settings.disable.screenshots': 'Désactiver la capture d\'écran',
    'form.configuration.settings.orientation': 'Verrouiller l\'orientation',
    'form.configuration.settings.orientation.none': 'Ne pas verrouiller',
    'form.configuration.settings.orientation.portrait': 'Portrait',
    'form.configuration.settings.orientation.landscape': 'Paysage',
    'form.configuration.settings.files.default.path': 'Chemin par défaut sur l\'appareil',
    'form.configuration.files.search.label': 'Rechercher:',
    'form.configuration.files.action.upload': 'Télécharger',
    'form.configuration.files.action.remove': 'Supprimer',
    'form.configuration.files.variables': 'Contenu variable',
    'form.configuration.files.variables.hint': 'Les chaînes DEVICE_NUMBER, IMEI, CUSTOM* seront remplacées par leurs valeurs',

	'form.configuration.file.name': 'Nom du fichier',
    'form.configuration.file.description': 'Description',
    'form.configuration.file.description.placeholder': 'En option, pour votre commodité',
    'form.configuration.file.path': 'Chemin sur l\'appareil',
    'form.configuration.file.path.placeholder': 'Pas de chemin vers un lecteur: /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'Si un fichier est hébergé sur une ressource externe',
    'form.configuration.file.file': 'Fichier',
    'form.configuration.file.action': 'Action',
    'form.configuration.file.action.prompt.1': 'Upload',
    'form.configuration.file.action.prompt.2': 'Supprimer',
    'form.configuration.file.remove.prompt.1': 'Ce fichier ne sera plus synchronisé avec les appareils',
    'form.configuration.file.remove.prompt.2': 'Supprimer le fichier depuis le serveur',

	'form.password.title': 'Changer le mot de passe',
     'form.password.label.user': 'Utilisateur',
     'form.password.label.password.new': 'Nouveau mot de passe',
     'form.password.label.password.new.placeholder': 'Entrez un nouveau mot de passe',
     'form.password.label.password.confirm': 'Vérifier',
     'form.password.label.password.confirm.placeholder': 'Entrez à nouveau le nouveau mot de passe',

	'form.application.type': 'Type',
    'form.application.type.option.web': 'Page Web',
    'form.application.type.option.app': 'Application',
    'form.application.pkg': 'ID du package',
    'form.application.from.file': 'déterminé à partir du fichier',
    'form.application.pkg.title': 'L\'ID du package est automatiquement déterminé lorsque vous téléchargez le fichier APK. L\'ID du package saisi manuellement est requis pour les applications système uniquement.',
    'form.application.pkg.placeholder': 'Par exemple, com.android.camera',
    'form.application.disabled.arch': 'Spécifique à la version',
    'form.application.disabled.arch.title': 'Pour ajouter des APK pour différentes architectures de processeur, cliquez sur "Ajouter" ou ouvrez la liste des versions de l\'application',
    'form.application.arch': 'Code natif',
    'form.application.arch.title': 'Certaines applications contiennent du code optimisé pour certaines architectures de processeur. Dans ce cas, vous devez télécharger deux APK (pour les architectures armeabi-v7a et arm64-v8a)',
    'form.application.arch.universal': 'Aucun (APK universel)',
    'form.application.arch.armeabi': 'Code natif pour armeabi-v7a',
    'form.application.arch.arm64': 'Code natif pour arm64-v8a',
    'form.application.arch.no.split': 'APK universel',
    'form.application.arch.split': 'APK divisé',
    'form.application.arch.warning': 'Ce fichier APK est pour ${arch} uniquement. N\'oubliez pas de télécharger des APK d\'autres architectures de processeurs !',
    'form.application.arch.success': 'Cette application contient des fichiers APK pour les deux architectures de processeur',
    'form.application.version.exists': 'L\'APK pour cette version existe déjà',
    'form.application.url.armeabi': 'URL pour armeabi-v7a',
    'form.application.url.arm64': 'URL pour arm64-v8a',
    'form.application.name': 'Nom de l\'application',
    'form.application.name.title': 'Vous verrez le nom de l\'application dans la liste. Nous vous recommandons d\'utiliser des noms uniques et informatifs.',
    'form.application.name.placeholder': 'Par exemple, Photo (Android)',
    'form.application.version': 'Version',
    'form.application.version.placeholder': '0 pour les applications système',
    'form.application.version.title': 'La version du package est automatiquement déterminée lorsque vous téléchargez le fichier APK. Réglez-le sur 0 pour les applications système.',
    'form.application.system': 'Système',
    'form.application.system.title': 'Les applications système sont préinstallées sur un appareil et ne nécessitent ni URL ni fichier. Définissez cet indicateur uniquement si vous devez activer un certain package système.',
    'form.application.run.after.install': 'Exécuter après l\'installation',
    'form.application.run.after.install.title': 'Les applications avec des services d\'arrière-plan doivent être lancées au premier plan au moins une fois.',
    'form.application.run.at.boot': 'Exécuter au démarrage',
    'form.application.run.at.boot.title': 'Définissez cet indicateur si vous devez exécuter l\'application au premier plan après le démarrage. Cet indicateur n\'affecte pas les processus d\'arrière-plan.',
    'form.application.url': 'URL',
    'form.application.url.title': 'L\'URL ne doit être saisie que si votre application est hébergée sur une ressource externe. Il est recommandé de télécharger un fichier APK en utilisant un champ ci-dessous.',
    'form.application.url.disabled': 'L\'URL est configurée pour chaque version. Pour modifier l\'URL, fermez cette fenêtre et cliquez sur l\'icône "Versions".',
    'form.application.file': 'Fichier',
    'form.application.showLabel': 'Afficher l\'icône',
    'form.application.showLabel.title': 'Cet indicateur indique si l\'icône de l\'application doit être affichée dans le lanceur. Cette option peut être remplacée dans la configuration.',
    'form.application.use.kiosk': 'Ouvrir dans Kiosk-Browser',
    'form.application.use.kiosk.title': 'Définissez cet indicateur si vous souhaitez ouvrir une page Web dans le navigateur de kiosque sans aucune possibilité de modifier l\'adresse',
    'form.application.iconText': 'Texte de l\'icône',
    'form.application.iconText.placeholder': '(par défaut)',
    'form.application.versions.title': 'Versions de l\'application',
    'form.application.icon': 'Icône',
    'form.application.icon.default': '(par défaut)',
    'form.application.icon.add': 'Ajouter une icône',

'form.application.setting.app': 'Application',
     'form.application.setting.app.placeholder': 'Sélectionnez une application',
     'form.application.setting.name': 'Attribut',
     'form.application.setting.value': 'Valeur',
     'form.application.setting.comment': 'Commentaire',
     'form.application.setting.type': 'Type',
     'form.application.setting.readonly': 'Ne change pas sur l\'appareil',
    
     'form.application.configurations.app': 'Application',
     'form.application.configurations.configs': 'Configurations',

     'form.configuration.copy.new.name': 'Nouveau nom',
     'form.configuration.copy.new.name.placeholder': 'Entrez le nouveau nom de configuration',

    'form.customer.name': 'Nom',
    'form.customer.name.placeholder': 'Entrez le nom de l\'organisation',
    'form.customer.apiKey': 'Clé API',
    'form.customer.apiKey.placeholder': 'Entrez la clé API',
    'form.customer.prefix': 'Préfixe',
    'form.customer.prefix.placeholder': 'Entrez le préfixe du numéro de l\'appareil',
    'form.customer.device.configuration': 'Configuration de l\'appareil',
    'form.customer.desc': 'Description',
    'form.customer.desc.placeholder': 'Entrez une description de l\'organisation',
    'form.customer.copy.configuration': 'Copier les configurations',
    'form.customer.copy.design': 'Copier la conception',
    'form.customer.type': 'Type de client',
    'form.customer.status': 'Statut de client',
    'form.customer.expiry.time': 'Date d\'expiration',
    'form.customer.device.limit': 'Limite d\'appareils',

    'form.device.number': 'Numéro',
    'form.device.number.locked': 'Impossible de modifier le numéro car le changement de numéro précédent n\'a pas été effectué.',
    'form.device.migration.warning': 'Le numéro de l\'appareil sera modifié. Assurez-vous que l\'appareil est allumé et en ligne.',
    'form.device.number.hint': 'N\'utilisez pas de caractères spéciaux',
    'form.device.desc': 'Description',
    'form.device.groups': 'Groupes',
    'form.device.config': 'Configuration',
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Numéro de téléphone',

    'form.update.device.config': 'Configuration',

    'form.file.file': 'Fichier',
    'form.file.path': 'Chemin',
    'form.file.path.placeholder': 'Entrez un chemin relatif, par exemple "/files/"',

    'form.file.apps.name': 'Nom de l\'application',
    'form.file.apps.pkg': 'ID du package',
    'form.file.apps.version': 'Version',

    'form.group.name': 'Nom de groupe',
    'form.group.name.placeholder': 'Enter le nom de groupe',

    'form.user.login': 'Connexion',
    'form.user.login.placeholder': 'Entrez la session de l\'utilisateur',
    'form.user.name': 'Nom',
    'form.user.name.placeholder': 'Saisir l\'identifiant de l\'utilisateur',
    'form.user.role': 'Rôle',
    'form.user.all.devices.available': 'Tous les appareils sont disponibles',
    'form.user.available.groups': 'Groupes de appareils disponibles',
    'form.user.password.new': 'Nouveau mot de passe',
    'form.user.password': 'Mot de passe',
    'form.user.password.new.placeholder': 'Entrez un nouveau mot de passe',
    'form.user.password.confirm': 'Vérifier',
    'form.user.password.confirm.placeholder': 'Entrez à nouveau le nouveau mot de passe',

    'form.settings.hints.title': 'Conseils',

    'form.settings.plugins.title': 'Plugins utilisés',

    'form.settings.common.title': 'Paramètres généraux',
    'form.settings.common.visible.columns': 'Colonnes visibles dans le tableau "Appareils"',
    'form.settings.common.status': 'Statut',
    'form.settings.common.role': 'Rôle des utilisateurs',
    'form.settings.common.date': 'Date',
    'form.settings.common.device.number': 'Numéro de l\'appareils',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Numéro de téléphone',
    'form.settings.common.phone.model': 'Modèle de téléphone',
    'form.settings.common.status.permissions': 'Statut de l\'autorisation',
    'form.settings.common.status.installation': 'État de l\'installation',
    'form.settings.common.status.files': 'État des fichiers',
    'form.settings.common.config': 'Configuration',
    'form.settings.common.desc': 'Description',
    'form.settings.common.group': 'Groupe',
    'form.settings.common.launcher.version': 'Version du lanceur',
    'form.settings.common.battery.level': 'Niveau de la batterie',
    'form.settings.common.default.launcher': 'Lanceur par défaut',

	'form.settings.design.title': 'Conception par défaut',
    'form.settings.design.color.font': 'Couleur d\'arrière-plan',
    'form.settings.design.color.font.placeholder': 'Sélectionnez une couleur',
    'form.settings.design.color.app.names': 'Couleur des noms d\'application',
    'form.settings.design.color.app.names.placeholder': 'Sélectionnez une couleur',
    'form.settings.design.url.background.image': 'URL de l\'image d\'arrière-plan',
    'form.settings.design.url.background.image.placeholder': 'Entrez URL de l\'image d\'arrière-plan',
    'form.settings.design.size.icon': 'Taille de l\'icône',
    'form.settings.design.size.icon.small': 'Petit',
    'form.settings.design.size.icon.medium': 'Moyenne (+ 20%)',
    'form.settings.design.size.icon.large': 'Large (+ 40%)',
    'form.settings.design.desktop.header': 'Titre du bureau',
    'form.settings.design.desktop.header.no': 'Non',
    'form.settings.design.desktop.header.device.id': 'ID de l\'appareil',

    'form.settings.lang.title': 'Paramètres de langue',
    'form.settings.lang.use.default': 'Utiliser la langue par défaut',
    'form.settings.lang.use': 'Utiliser la langue',
    'form.settings.lang.en': 'English',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',

    'form.settings.misc.title': 'Paramètres divers',
    'form.settings.misc.phone.format': 'Format du numéro de téléphone',
    'form.settings.misc.phone.format.placeholder': '+9 (999) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'Propriété personnalisée #1',
    'form.settings.misc.custom.property.name.2': 'Propriété personnalisée #2',
    'form.settings.misc.custom.property.name.3': 'Propriété personnalisée #3',
    'form.settings.misc.custom.property.multiline': 'Multiligne',
    'form.settings.misc.custom.property.send': 'Envoyer à l\'appareil',
    'form.settings.misc.custom.property.name.placeholder': 'Entrez le nom d\'une propriété personnalisée',
    'form.settings.misc.create.new.devices': 'Ajouter un appareil lors du premier accès',
    'form.settings.misc.new.device.config': 'Nouvelle configuration d\'appareil',
    'form.settings.misc.new.device.group': 'Nouveau groupe d\'appareils',

    'form.settings.groups.title': 'Groupes',
    'form.settings.groups.search.placeholder': 'Recherche de groupe',

    'form.settings.users.title': 'Utilisateurs',
    'form.settings.users.search.placeholder': 'Rechercher un utilisateur',

    'form.qr.device.number': 'ID d\'appareil',
    'form.qr.auto.create': 'Ajouter à la liste des appareils s\'il n\'existe pas',
    'form.qr.number.use': 'Attribution d\'ID d\'appareil',
    'form.qr.number.use.request': 'Valeur utilisateur',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'Numéro de série',
    'form.qr.groups': 'Ajouter aux groupes',
    'form.qr.button.json': 'Obtenez JSON',
    'form.qr.device.number.placeholder': 'Entrez ID de l\'appareil ...',
    'form.qr.code.image.alt': 'Code QR',

'form.profile.title': 'Changer le mot de passe',
     'form.profile.password.old': 'Ancien mot de passe',
     'form.profile.password.old.placeholder': 'Entrez l\'ancien mot de passe',
     'form.profile.password.new': 'Nouveau mot de passe',
     'form.profile.password.new.placeholder': 'Entrez un nouveau mot de passe',
     'form.profile.password.confirm': 'Vérifier',
     'form.profile.password.confirm.placeholder': 'Entrez à nouveau le nouveau mot de passe',

     'tab.customers': 'Organisations',
     'tab.common.applications': 'Applications partagées',

     'tab.devices': 'Appareils',
     'tab.applications': 'Applications',
     'tab.configurations': 'Configurations',
     'tab.files': 'Fichiers',
     'tab.default.design': 'Conception par défaut',
     'tab.common.settings': 'Paramètres généraux',
     'tab.users': 'Utilisateurs',
     'tab.groups': 'Groupes',
     'tab.language': 'Paramètres de langue',
     'tab.license': 'Licence',
     'tab.hints': 'Indications',
     'tab.plugins': 'Plugins',
    
	'tab.configeditor.common.settings': 'Paramètres généraux',
    'tab.configeditor.design.settings': 'Paramètres de conception',
    'tab.configeditor.applications': 'Applications',
    'tab.configeditor.mdm.settings': 'Paramètres MDM',
    'tab.configeditor.app.settings': 'Paramètres des applications',
    'tab.configeditor.files': 'Fichiers',

    'search.placeholder.file': 'rechercher un fichier',
    'search.placeholder.configuration': 'Rechercher la configuration',
    'search.placeholder.customer': 'Rechercher une organisation',
    'search.placeholder.application': 'Rechercher une application',
    'search.placeholder.application.setting': 'Rechercher un paramètre d\'application',
    'search.placeholder.device': 'Rechercher un appareil',
    'search.placeholder.address': 'Recherche d\'adresse',
    'search.placeholder.point': 'Recherche sur site',
    'search.placeholder.message': 'Recherche de message',
    'search.placeholder': 'Rechercher ...',
    'search.placeholder.from': 'De ...',
    'search.placeholder.to': 'À ...',
    'search.placeholder.user': 'Tapez le nom d\'utilisateur',

    'table.heading.customer.name': 'Nom',
    'table.heading.customer.desc': 'Description',
    'table.heading.customer.registration.time': 'Enregistré',
    'table.heading.customer.last.login.time': 'Dernière connexion',
    'table.heading.customer.actions': 'Actions',
    'table.heading.customer.type': 'Type',
    'table.heading.customer.expiry.time': 'Expire',
    'table.heading.customer.device.limit': 'Limite',
    'table.heading.customer.status': 'Statut',

    'customer.new': 'Nouveau',
    'customer.active': 'Actif',
    'customer.need.followup': 'Besoin d\'un suivi',
    'customer.followup.sent': 'Suivi envoyé',
    'customer.internal.test': 'Test interne',
    'customer.developer': 'Développeur',
    'customer.difficult': 'Difficile',
    'customer.pause': 'Pause',
    'customer.denial': 'Rejet',
    'customer.client': 'Client',

    'table.heading.configuration.name': 'Nom',
    'table.heading.configuration.desc': 'Description',
    'table.heading.configuration.actions': 'Actions',

    'table.heading.application.setting.app.pkg': 'ID du package',
    'table.heading.application.setting.app.name': 'Nom de l\'application',
    'table.heading.application.setting.name': 'Nom de personnalisation',
    'table.heading.application.setting.value': 'Valeur',
    'table.heading.application.setting.comment': 'Commentaire',
    'table.heading.application.setting.lastUpdate': 'Date de la dernière modification',

	'table.heading.file.url': 'URL',
    'table.heading.file.devicepath': 'Chemin sur l\'appareil',
    'table.heading.file.description': 'Description',
    'table.heading.file.action': 'Action',
    'table.heading.file.lastUpdate': 'Date de la dernière modification',
    
    'table.heading.application.pkg': 'ID du package',
    'table.heading.application.name': 'Nom de l\'application',
    'table.heading.application.version': 'Version',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Icône',
    'table.heading.application.actions': 'Actions',
    'table.heading.application.order': 'Ordre',

    'table.heading.device.status': 'Statut',
    'table.heading.device.date': 'Date',
    'table.heading.device.device.number': 'Numéro de l\'appareil',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Numéro de téléphone',
    'table.heading.device.phone.model': 'Modèle de téléphone',
    'table.heading.device.status.permissions': 'Statut de l\'autorisation',
    'table.heading.device.status.installation': 'État de l\'installation',
    'table.heading.device.status.files': 'État des fichiers',
    'table.heading.device.configuration': 'Configuration',
    'table.heading.device.desc': 'Description',
    'table.heading.device.group': 'Groupe',
    'table.heading.device.launcher.version': 'Version du lanceur',
    'table.heading.device.battery.level': 'Niveau de batterie',
    'table.heading.device.default.launcher': 'Définir par défaut',
    'table.heading.device.actions': 'Actions',

    'table.heading.group.name': 'Nom',
    'table.heading.group.actions': 'Actions',

    'table.heading.file.name': 'Nom de fichier',
    'table.heading.file.path': 'Chemin',
    'table.heading.file.address': 'Adresse',
    'table.heading.file.actions': 'Actions',

    'table.heading.users.login': 'Identifiant :',
    'table.heading.users.name': 'Nom',
    'table.heading.users.role': 'Rôle',
    'table.heading.users.actions': 'Actions',

    'table.heading.common.apps.customer': 'Organisation',
    'table.heading.common.apps.pkg': 'ID du package',
    'table.heading.common.apps.name': 'Nom de l\'application',
    'table.heading.common.apps.version': 'Version',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Icône',
    'table.heading.common.apps.actions': 'Actions',
    
	'notfound.devices': 'Il n\'y a aucun appareil à afficher.',
    'notfound.files': 'La liste des fichiers est vide. Utilisez le bouton "Ajouter" pour télécharger un nouveau fichier.',
    'notfound.configurations': 'Aucune configuration n\'a été trouvée.',
    'notfound.customers': 'Organisations non trouvées.',
    'notfound.common.apps': 'Il n\'y a aucune application à afficher.',
    'notfound.applications': 'Applications introuvables',
    'notfound.groups': 'Aucun groupe trouvé. Essayez une autre requête.',
    'notfound.users': 'Utilisateurs non trouvés. Essayez une autre requête.',
    'notfound.apps.for.display': 'Il n\'y a aucune application à afficher.',
    'notfound.app.versions.for.display': 'Il n\'y a aucune version à afficher.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

	'menu.about': 'À propos de',
    'menu.profile': 'Profil',
    'menu.panel.master': 'Panneau principal',
    'menu.panel.main': 'Panneau principal',
    'menu.logout': 'Déconnexion',
    'menu.functions': 'Fonctions',
    'menu.settings': 'Paramètres',
    'menu.show.hints': 'Afficher les indices',

    'plugin.name.not.specified': '<< Le nom de la fonction n\'est pas spécifié >>',

    'breadcrumb.devices': 'Appareils',
    'breadcrumb.applications': 'Applications',
    'breadcrumb.configurations': 'Configurations',
    'breadcrumb.files': 'Fichiers',
    'breadcrumb.default.design': 'Conception par défaut',
    'breadcrumb.common.settings': 'Paramètres généraux',
    'breadcrumb.language.settings': 'Paramètres de langue',
    'breadcrumb.license.settings': 'Licence',
    'breadcrumb.users': 'Utilisateurs',
    'breadcrumb.groups': 'Groupes',
    'breadcrumb.hints': 'Indications',
    'breadcrumb.plugins': 'Plugins',
    'breadcrumb.config.details': 'Détails',
    'breadcrumb.application.versions': 'Versions',

    'app.name': 'Headwind MDM',
    'app.vendor.name':"h-mdm.com",
    'app.vendor.link':"https://h-mdm.com",
    'app.description': 'est le système de gestion des appareils mobiles open source',
    'app.title': 'Serveur ${appName}',
     
	'box.show.my.apps.only': 'Afficher uniquement mes applications',
    'configuration.app.version.upgrade.message': 'Version installée ${installedVersion}, version disponible ${latestVersion}',

    'about.line.1': 'Panneau de configuration ${appName}',
    'about.line.2': 'Lanceur d\'entreprise pour Android',
    'about.line.3': 'Version ${versionNumber}',
    'about.line.4': 'Plugins installés',

    'common.app.clarification': 'Cette application est publique et ne peut pas être modifiée. Pour ajouter une autre version de cette application, veuillez contacter l\'administrateur.',

    'qrcode.help.line1': 'Pour configurer l\'appareil Android (version 7 ou plus) en mode géré (entreprise):',
    'qrcode.help.line2': 'Réinitialiser l\'appareil aux paramètres d\'usine',
    'qrcode.help.line3': 'Appuyez 7 fois sur n\'importe quel endroit de l\'écran de démarrage (vous devez entrer dans un mode de numérisation de code QR caché)',
    'qrcode.help.line4': 'Suivez les instructions de l\'appareil: acceptez les conditions, connectez-vous au Wi-Fi, scannez ce QR-code',
    'qrcode.help.line5': 'Le code QR peut contenir ID de l\'appareil pour ${appName} (pas besoin de le saisir sur un appareil mobile). Pour intégrer ID de l\'appareil dans le code QR, saisissez ID de l\'appareil sur cet écran et cliquez sur "Renouveler".',

	'form.configuration.app.version.select.select.title': 'Sélectionnez la version à installer',
    'form.configuration.app.version.select.version.check.off': 'Désactiver la vérification de version',
    'form.configuration.app.version.select.upgrade.warning': 'Mettre à niveau l\'application "${v1}" vers la version "${v3}" pour la configuration "${v2}"?',
    'form.configuration.app.version.select.downgrade.warning': 'Version dégradée EFFACER TOUTES CES APPLICATIONS sur tous les appareils ! Dégrader la version de l\'application "${v1}" à la version "${v2}"?',

    'hint.step.1': 'Cliquez ici pour démarrer l\'inscription de l\'appareil',
    'hint.step.2': 'Cliquez ici pour ouvrir le code QR',
    'hint.step.3': 'Cliquez ici pour voir comment ouvrir le scanner de code QR sur l\'appareil',
    'hint.step.4': 'Trouvez un identifiant d\'appareil disponible dans l\'onglet «Appareils». Cliquez sur «Renouveler» pour l\'inclure dans le code QR.',

    'ie.browser.notice.1': 'Malheureusement, Internet Explorer n\'est pas pris en charge.',
    'ie.browser.notice.2': 'Navigateur recommandé pour l\'utilisation de ${appName} - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop"> Chrome < / a>.',

    'form.resolved.duplicate.pkg.text1': 'ID de package "${pkg}" est déjà utilisé par les applications répertoriées ci-dessous.',
    'form.resolved.duplicate.pkg.text2': 'Voulez-vous ajouter une nouvelle application ou une nouvelle version d\'une application existante?',
    'form.resolved.duplicate.pkg.text3': 'Nouvelle version pour',
    'form.resolved.duplicate.pkg.text4': 'L\'ID de package "${pkg}" est déjà utilisé par les applications ${apps}',
    'form.resolved.duplicate.pkg.text5': 'Voulez-vous vraiment modifier l\'ID du package?',

    'tooltip.usage.byconfigurations': 'Utilisé par les configurations',
    'tooltip.usage.byapps': 'Utilisé par les applications',
    'tooltip.usage.byicons': 'Utilisé par les icônes',

    'form.devices.label.params.more': 'Plus de paramètres',
    'form.devices.label.params.less': 'Moins de paramètres',
    'form.devices.label.installation.status': 'État de l\'installation',
    "format.devices.date.createTime": "dd/MM/yyyy HH:mm:ss",
    "format.devices.date.datePicker": "dd-MM-yyyy",

    'form.devices.selection.install.status.default': 'État de l\'installation ...',
    'form.devices.selection.install.status.all': 'Toute',
    'form.devices.selection.install.status.success': 'Succès',
    'form.devices.selection.install.status.version.mismatch': 'Incompatibilite de version',
    'form.devices.selection.install.status.failure': 'Échec',
    'form.devices.selection.imei.changed': 'IMEI a récemment changé',

    'search.placeholder.launcher.version': 'Version du lanceur',
    'error.date.range.invalid': 'L\'intervalle de date n\'est pas valide',

    'customer.type.demo': 'Démo',
    'customer.type.small': 'Petite entreprise',
    'customer.type.corporate': 'Entreprise',
    'customer.type.master': 'Primaire',

    'customer.type.options.all': 'Tous les types',
    'customer.status.options.all': 'Tous les statuts',

    'account.expiring': 'Votre compte expirera dans $ {days} jours. Veuillez contacter le vendeur pour renouveler votre compte.',
    'account.expired': 'Votre compte a expiré. Veuillez contacter le vendeur pour renouveler votre compte.',
    'account.expired.short': 'Votre compte a expiré!',
    'device.limit.achieved': 'Impossible d\'ajouter un appareil car vous avez atteint votre limite. Veuillez supprimer certains appareils ou contacter le vendeur pour étendre la limite de votre appareil.',

    'yes': 'oui',
    'no': 'non'
};
