if (! document.localization) document.localization = [];

document.localization ['hu_HU'] = {
    'login.username': 'Felhasználónév vagy e-mail',
    'login.username.placeholder': 'Adja meg a felhasználónevet vagy e-mail-címet',
    'login.password': 'Jelszó:',
    'login.password.placeholder': 'Adja meg a jelszót',
    'login.submit': 'Bejelentkezés',
    'login.password.incorrect': 'Érvénytelen felhasználónév vagy jelszó',
    'login.password.recovery': 'Elfelejtetted a jelszavad?',
    'recovery.password': 'Jelszó helyreállítása',
    'recovery.password.success': 'A jelszó-helyreállítási útmutatót elküldtük e-mailben',
    'login.no.account': 'Nincs fiókja?',
    'login.signup': 'Regisztráció',

    'signup.title': 'Kezdés',
    'signup.email': 'E-mail-címed',
    'signup.email.placeholder': 'Adjon meg érvényes e-mail-címet',
    'signup.email.invalid': 'Adjon meg érvényes e-mail-címet',
    'signup.terms.agree': 'Elfogadom a',
    'signup.terms.terms': 'felhasználási feltételeket',
    'signup.submit': 'Regisztráció',
    'signup.progress': 'Regisztráció folyamatban...',
    'signup.email.used': 'Az ezzel az e-mail-címmel rendelkező ügyfél már regisztrált',
    'signup.name.used': 'Egy ügyfél ezzel a felhasználónévvel már regisztrálva van',
    'signup.complete': 'Köszönjük a feliratkozást!',
    'signup.email.check': 'Kérjük, ellenőrizze e-mailjeit, és kattintson a linkre a regisztráció befejezéséhez!',
    'signup.complete.title': 'A ${appName} fiókja majdnem kész!',
    'signup.ready.title': 'A ${appName} fiókja készen áll!',
    'signup.customer.id': 'Felhasználónév',
    'signup.customer.id.placeholder': 'Csak betűket és számjegyeket használjon',
    'signup.customer.id.invalid': 'Kérjük, csak 6 vagy több karaktert, betűt és számjegyet használjon',
    'signup.first.name': 'Keresztnév',
    'signup.first.name.placeholder': 'Az Ön keresztneve (kötelező)',
    'signup.last.name': 'Vezetéknév',
    'signup.last.name.placeholder': 'Az Ön vezetékneve (kötelező)',
    'signup.company': 'Cégnév',
    'signup.company.placeholder': 'Vállalkozásának neve (nem kötelező)',
    'signup.description': 'Hogyan fogja használni a MDM-t?',
    'signup.description.placeholder': 'Ez segít csapatunknak abban, hogy segítsen Önnek',
    'signup.password': 'Jelszó',
    'signup.password.repeat': 'Jelszó ismétlése',
    'signup.password.placeholder': '6+ karakter',
    'signup.password.short': 'Kérjük, adjon meg legalább 6 karaktert',
    'signup.password.not.match': 'A jelszavak nem egyeznek',
    'signup.finalized.title': 'Fiókja készen áll!',
    'signup.finalized.description': 'Rövid időn belül meg kell kapnia a hasznos utasításokat tartalmazó e-mailt. Kérjük, tekintse át ezt az e-mailt, és jelentkezzen be a webpanelre felhasználónevével és jelszavával.',
    'signup.token.invalid.title': 'A token érvénytelen vagy már használt',
    'signup.token.invalid.description': 'Kérjük, próbálja meg újra a regisztrációt új fiók létrehozásához!',

    'header.label.username': 'Felhasználónév',

    'summary.devices.status': 'Eszközállapot',
    'summary.devices.active': 'Aktív',
    'summary.devices.idle': 'Tétlen',
    'summary.devices.offline': 'Kapcsolat nélkül',
    'summary.devices.enrollment': 'Regisztrációs összegzés',
    'summary.devices.enrolled.total': 'Összes regisztrált',
    'summary.devices.enrolled.earlier': 'Korábban beiratkozott',
    'summary.devices.enrolled.monthly': 'Utolsó 30 nap',
    'summary.devices.installation.status': 'Alkalmazás állapota',
    'summary.devices.installation.completed': 'Kész',
    'summary.devices.version.mismatch': 'Verzióeltérés',
    'summary.devices.installation.failed': 'Sikertelen telepítés',
    'summary.devices.enrolled.lastyear': 'Utolsó 12 hónap',

    'devices.group.options.all': 'Minden csoport',
    'devices.configuration.options.all': 'Minden konfiguráció',
    'devices.permissions.all': 'Minden engedély megadva',
    'devices.permissions.not.as.device.admin': '- Az alkalmazás nincs telepítve eszközrendszergazdaként',
    'devices.permissions.window.overlap.prohibited': '- Más ablakok feletti átfedés nem érhető el',
    'devices.permissions.history.access.prohibited': '- A használati előzményekhez való hozzáférés nincs konfigurálva',
    'devices.unknown': 'Ismeretlen',
    'devices.model.unknown': 'Ismeretlen',
    'devices.date.unknown': 'ismeretlen',
    'devices.date.format': 'yy/MM/dd HH:mm',
    'devices.app.installed': '- ${applicationName}: Telepítve.',
    'devices.app.not.installed': '- ${applicationName}: nincs telepítve.',
    'devices.app.version.available': ', kapható ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: telepítve ${applicationInstalledVersion}, elérhető ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, eltávolítás szükséges',
    'devices.no.data': 'A készülék nem továbbított adatokat',
    'devices.settings.conformance.broken': 'Nem egyezik a beállításokkal: (${serverData})',
    'devices.file.installed': '- ${file}: telepítve',
    'devices.file.not.installed': '- ${file}: nincs telepítve.',
    'devices.file.lastUpdate.differs': '- ${file}: különbség a módosítási időben ${diff} min',

    'button.apply': 'Alkalmaz',
    'button.gps.on': 'GPS bekapcsolása',
    'button.wifi.on': 'Wi-Fi bekapcsolása',
    'button.notify.update': 'Értesítés frissítéskor',
    'button.app.settings': 'Alkalmazásbeállítások',
    'button.ok': 'OK',
    'button.help': 'Segítség',
    'button.new.app': 'Új alkalmazás',
    'button.new.app.version': 'Új verzió',
    'button.upgrade': 'Frissítés',
    'button.renew.config': 'Frissítés az eszközökön',
    'button.common': 'Közös alkalmazás',
    'button.close': 'Bezárás',
    'button.yes': 'Igen',
    'button.cancel': 'Mégse',
    'button.save': 'Mentés',
    'button.save.and.close': 'Mentés és bezárás',
    'button.more': 'Továbbiak ...',
    'button.cleanup': 'Törlés',
    'button.add': 'Hozzáadás',
    'button.add.icon': 'Új ikon',
    'button.search': 'Keresés',
    'button.export': 'Exportálás',
    'button.change': 'Szerkesztés',
    'button.copy': 'Másolás',
    'button.qrcode': 'QR-kód',
    'button.application': 'Alkalmazás',
    'button.change.password': 'Jelszó módosítása',
    'button.set.configuration': 'Konfiguráció beállítása',
    'button.set.group': 'Csoport beállítása',
    'button.group.action': 'Csoportművelet',
    'button.delete': 'Törlés',
    'button.login': 'Bejelentkezés',
    'button.renew.code': 'Megújítás',
    'button.configurations': 'Konfigurációk',
    'button.set.configurations': 'Konfigurációk megadása',
    'button.edit.versions': 'Verziók',
    'button.edit': 'Szerkesztés',
    'button.change.common.app': 'Megosztott alkalmazás szerkesztése',
    'button.delete.common.app': 'Törölje a megosztott alkalmazást',
    'button.turn.common.app': 'Tedd közössé',
    'button.hints.enable': 'Súgóbuborékok megjelenítése',
    'button.hints.disable': 'Súgóbuborékok elrejtése',
    'button.show.password': 'Jelszó mutatása',
    'button.hide.password': 'Jelszó elrejtése',

    'question.impersonate.user': 'Jelentkezzen be az alkalmazásba a "${customerName}" szervezet adminisztrátoraként?',
    'question.change.user': 'Jelentkezzen be az alkalmazásba "${userName}" felhasználóként?',
    'question.delete.file': 'Törli a "${fileName}" fájlt?',
    'question.delete.customer': 'Törli a "${customerName}" szervezetet?',
    'question.delete.user': 'Törli a "${username}" felhasználót?',
    'question.delete.application': 'Törli a „${applicationName}” alkalmazást?',
    'question.delete.application.version': 'Törli a „${applicationVersion}” verziót?',
    'question.delete.configuration': 'Törli a "${configurationName}" konfigurációt?',
    'question.delete.group': 'Törli a "${groupName}" csoportot?',
    'question.delete.role': 'Törli a „${roleName}” szerepet?',
    'question.delete.icon': 'Törli a „${iconName}” ikont?',
    'question.delete.device.bulk': 'Törli a kiválasztott eszközöket?',
    'question.delete.device': 'Törli a „${deviceNumber}” számú eszközt?',
    'question.exit.without.saving': 'A változtatások nem kerülnek mentésre. Egyébként elhagyja ezt az oldalt?',
    'question.turn2common.application': 'Megosztja a „${applicationName}” alkalmazást?',
    'question.app.upgrade': 'Frissíti a „${v1}” alkalmazást a legújabb verzióra a „${v2}” konfigurációhoz?',

    'error.application.setting.empty.app': 'Adja meg az alkalmazást',
    'error.application.setting.empty.name': 'Adjon meg egy nevet',
    'error.application.setting.empty.value': 'Adjon meg egy értéket',

    'error.icon.dimension.invalid': 'Az ikonnak négyzet alakúnak kell lennie',
    'error.icon.empty.name': 'Írja be az ikon nevét',
    'error.icon.empty.file': 'Ikonfájl feltöltése',
    'error.application.version.pkg.mismatch': 'A fájl csomagazonosítója (${actual}) nem egyezik az alkalmazáséval (${expected})',
    'error.empty.user': 'Válassz felhasználót',
    'error.empty.user.name': 'Töltsd ki a felhasználónevet',
    'error.empty.user.login': 'Töltse ki a felhasználói bejelentkezési adatokat',
    'error.empty.user.role': 'Válassz felhasználói szerepkört',
    'error.empty.password': 'Adja meg az új jelszót',
    'error.empty.password.confirm': 'Adja meg a jelszó megerősítését',
    'error.user.not.found': 'A felhasználó nem található',
    'error.email.not.configured': 'Az e-mail nincs beállítva',
    'error.email.not.found': 'Felhasználói e-mail nincs beállítva',
    'error.empty.group.name': 'Adja meg a csoport nevét',
    'error.empty.configuration': 'Adja meg a konfigurációt',
    'error.empty.configuration.name': 'Adja meg a konfiguráció nevét',
    'error.empty.configuration.password': 'Adja meg a jelszót',
    'error.empty.configuration.contentApp': 'Nincs tartalomalkalmazás megadva',
    'error.empty.group': 'Adjon hozzá egy eszközt egy vagy több csoporthoz',
    'error.invalid.character': 'Az eszközszám nem tartalmazhat / ? &',
    'error.invalid.configuration.mainApp': 'A MDM beállításokban rossz fő alkalmazást használnak',
    'error.invalid.configuration.contentApp': 'Érvénytelen tartalomalkalmazás a MDM beállításaiban',
    'error.mismatch.password': 'A jelszónak és a jelszó megerősítésének egyeznie kell',
    'error.empty.customer.name': 'Írja be a szervezet nevét',
    'error.empty.customer.prefix': 'Töltse ki az eszközszám előtagját',
    'error.empty.customer.device.configuration': 'Válassza ki az eszköz konfigurációját',
    'error.empty.customer.duplicate.prefix': 'Az előtag már használatban van',
    'error.duplicate.customer.name': 'A megadott nevű szervezet már létezik. Próbálkozzon másik névvel.',
    'error.duplicate.group.name': 'A megadott nevű csoport már létezik. Próbálkozzon másik névvel.',
    'error.duplicate.configuration.name': 'A megadott névvel rendelkező konfiguráció már létezik. Próbálkozzon másik névvel.',
    'error.duplicate.device.number': 'Már létezik ilyen számú eszköz',
    'error.internal.server': 'Belső szerverhiba',
    'error.permission.denied': 'Nincs jogosultság a végrehajtáshoz',
    'error.request.failure': 'Sikertelen kérés',
    'error.configuration.device.use': 'Ez a konfiguráció nem törölhető, eszközökön használják. Először lépjen az "Eszközök" elemre, keresse meg az ezt a konfigurációt használó eszközöket, és módosítsa a beállításaikat.',
    'error.invalid.system.update.time': 'Érvénytelen telepítési időszak',
    'error.size.limit.exceeded': 'Tárhelykorlát túllépve',

    'error.configuration.file.empty.name': 'Adjon meg egy fájlnevet',
    'error.configuration.file.empty.desc': 'Adja meg a fájl leírását',
    'error.configuration.file.empty.path': 'Adja meg az elérési utat az eszközön',
    'error.configuration.file.empty.file': 'Kérjük, töltsön fel egy fájlt',
    'error.configuration.file.empty.url': 'Adja meg a fájl URL-címét',

    'error.notfound.device': 'Az eszköz nem található',
    'error.duplicate.device': 'Már létezik eszköz ezzel a számmal',
    'error.duplicate.login': 'Ez a bejelentkezési név már használatban van',
    'error.duplicate.email': 'Már létezik felhasználó ezzel az e-mail címmel',
    'error.duplicate.group': 'Már létezik csoport ezzel a névvel',
    'error.duplicate.application': 'Már létezik egy alkalmazás ezzel a csomagazonosítóval és verzióval',
    'error.recent.application.version.exists': 'Az alkalmazás újabb verziója létezik',
    'error.common.application.access.prohibited': 'A közös alkalmazásokat csak a főadminisztrátor kezelheti',
    'error.application.config.reference.exists': 'Az alkalmazás konfigurációkban használatos, és nem törölhető',
    'error.application.version.deletion.prohibited': 'A verzió vagy egyedi, vagy konfigurációkban használatos, és nem törölhető',
    'error.duplicate.file': 'Már létezik ilyen nevű fájl',
    'error.used.file': 'Ezt a fájlt használják',
    'error.version.exists': 'Az alkalmazás ugyanazon verziója már létezik',
    'error.duplicate.configuration': 'Már létezik ilyen nevű konfiguráció',
    'error.duplicate.role.name': 'Már létezik azonos nevű szerepkör',
    'error.empty.role.name': 'Kérjük, adja meg a szerepkör nevét',
    'error.duplicate.icon.name': 'Már létezik ilyen nevű ikon',
    'error.notfound.customer.admin': 'A rendszergazdai fiók nem található',
    'error.apk.file.required': 'Válasszon .apk vagy .xapk kiterjesztésű fájlt',
    'error.apk.parse': 'Hiba történt a fájl elemzése közben',
    'error.package.not.match': 'A csomagazonosító nem egyezik',
    'error.empty.app.name': 'Adja meg az alkalmazás nevét',
    'error.empty.app.pkg': 'Adja meg a csomagazonosítót',
    'error.empty.app.url': 'Adja meg az URL-címet',
    'error.empty.app.iconText': 'Írja be az ikon szövegét',
    'error.empty.app.version': 'Adja meg az alkalmazás verzióját',
    'error.notempty.group': 'Ez a csoport egy vagy több eszközt tartalmaz. Nem távolíthatja el.',
    'error.file.empty': 'Új fájl feltöltése',
    'error.file.deletion': 'Hiba történt a fájl törlésekor a szerveren',
    'error.file.save': 'Hiba a fájl szerverre mentésekor',
    'error.password.wrong': 'Érvénytelen jelszó',
    'error.password.empty': 'Nincs jelszó megadva',
    'error.password.weak': 'Gyenge jelszó',
    'error.params.missing': 'Hiányzó paraméterek:',
    'error.empty.push.options': 'Kérjük, válassza a Push értesítések opciókat',
    'error.app.name.exists': 'Már létezik egy másik alkalmazás ezzel a névvel. Kérjük, adjon meg egyedi nevet.',

    'table.filtering.check.all': 'Összes kijélőlese',
    'table.filtering.uncheck.all': 'Kijélőles törlése',
    'table.filtering.suffix.configuration': 'konfigurációk',
    'table.filtering.suffix.group': 'csoportok',
    'table.filtering.suffix.permission': 'engedélyeket',
    'table.filtering.no.selected.configuration': 'Nincs konfiguráció kijélőlve',
    'table.filtering.no.selected.group': 'Nincs csoport kijélőlve',
    'table.filtering.no.selected.permission': 'Nincsenek kiválasztva engedélyek',

    'success.admin.created': 'Rendszergazdai fiók létrehozva:\n ${adminCredentials}',
    'success.uploading.file': 'A fájl feltöltése folyamatban van a szerverre…',
    'success.loading.devices': 'Eszközlista betöltése…',
    'success.loading.customer': 'Ügyféladatok betöltése…',
    'success.file.uploaded': 'A fájl sikeresen feltöltve.',
    'success.file.uploaded.need.save': 'A fájl sikeresen feltöltve. Adja meg a relatív elérési utat, és kattintson a "Mentés" gombra.',
    'success.settings.design.saved': 'A tervezési beállítások mentése sikerült',
    'success.settings.common.saved': 'Az eszköztáblázat beállításai sikeresen mentve',
    'success.settings.saved': 'A beállítások sikeresen mentve',
    'success.settings.apiKey.saved': 'Az API-kulcs mentése sikerült',
    'success.settings.hints.enabled': 'Tippek engedélyezve',
    'success.settings.hints.disabled': 'Tippek letiltva',
    'success.configuration.saved': 'A konfiguráció sikeresen mentve',
    'success.operation.completed': 'A művelet sikeresen befejezodott',
    'success.plugins.disabled': 'A beállítások sikeresen mentve',
    'success.config.update.notification': 'A konfiguráció frissítési parancsát elküldtük az eszközöknek',
    'success.config.update.device.app.settings.notification': 'Az alkalmazás beállításainak frissítésére vonatkozó parancs el lett küldve az eszközre.',

    'form.icon.title': 'Ikon',
    'form.icon.name': 'Név',
    'form.icon.file': 'Fájl',

    'configuration.add.warning': 'Biztosan üres konfigurációt szeretne létrehozni? Az összes szükséges rendszeralkalmazást manuálisan kell hozzáadnia. Ehelyett fontolja meg egy meglévő konfiguráció másolását és módosítását.',
    'configuration.remove.warning': 'Biztosan eltávolítja az utolsó konfigurációt? Elveszíti az információkat, hogy mely rendszeralkalmazásokra van szükség.',
    'form.configuration.title': 'Konfiguráció',
    'form.configuration.title.typical': 'Tipikus konfiguráció',
    'form.configuration.settings.auto.update': 'Automatikus frissítés',
    'form.configuration.settings.system.update': 'Rendszerfrissítés',
    'form.configuration.settings.system.update.default': 'Alapértelmezett',
    'form.configuration.settings.system.update.immediate': 'Azonnal',
    'form.configuration.settings.system.update.scheduled': 'Ütemezett',
    'form.configuration.settings.system.update.postponed': 'Elhalasztott',
    'form.configuration.settings.system.update.time': 'Telepítési idő',
    'form.configuration.settings.system.update.time.from': 'ettől:',
    'form.configuration.settings.system.update.time.to': 'eddig:',
    'form.configuration.settings.system.schedule.app.update': 'Alkalmazásfrissítés ütemezése',
    'form.configuration.settings.system.app.update.time': 'Az alkalmazás frissítési ideje',
    'form.configuration.settings.download.updates': 'Tartalom letöltése',
    'form.configuration.settings.download.updates.unlimited': 'Korlátozás nélkül',
    'form.configuration.settings.download.updates.limited': '3 próbálkozás a mobilhálózaton',
    'form.configuration.settings.download.updates.wifi': 'Csak Wi-Fi-n',
    'form.configuration.settings.block.status.bar': 'Állapotsáv zárolása',
    'form.configuration.settings.block.status.bar.hint': 'Ez a beállítás elavult, és jól működik Android 6 és régebbi rendszereken. Az állapotsor zárolásához az újabb Android-verziókon használja a kioszk módot (MDM beállítások).',
    'form.configuration.settings.mdm.kiosk.mode': 'Kioszk mód',
    'form.configuration.settings.mdm.app.main': 'MDM alkalmazás',
    'form.configuration.settings.mdm.component.event.receiver': 'Admin fogadó osztály',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Az érték com.hmdm.launcher.AdminReceiver legyen',
    'form.configuration.settings.mdm.component.wifi.ssid': 'Wi-Fi SSID',
    'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'Regisztrációs Wi-Fi SSID – hagyd üresen kézi megadáshoz',
    'form.configuration.settings.mdm.component.wifi.password': 'Wi-Fi jelszó',
    'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Regisztrációs Wi-Fi-jelszó – hagyd üresen kézi megadáshoz',
    'form.configuration.settings.mdm.component.wifi.security': 'Wi-Fi biztonsági típus',
    'form.configuration.settings.mdm.component.wifi.notice': 'Megjegyzés: ezek a Wi-Fi-beállítások csak a kezdeti regisztrációra vonatkoznak!',
    'form.configuration.settings.mdm.component.server.url': 'Új szerver URL',
    'form.configuration.settings.mdm.component.server.url.placeholder': 'Új MDM kiszolgálóra való migrációhoz használják',
    'form.configuration.settings.mdm.app.content': 'Tartalomalkalmazás',
    'form.configuration.settings.mdm.kiosk.home': 'Home gomb engedélyezése',
    'form.configuration.settings.mdm.kiosk.recents': 'Legutóbbiak gomb engedélyezése',
    'form.configuration.settings.mdm.kiosk.notifications': 'Értesítések engedélyezése',
    'form.configuration.settings.mdm.kiosk.system.info': 'Állapotsáv információk engedélyezése',
    'form.configuration.settings.mdm.kiosk.keyguard': 'Képernyőzár engedélyezése',
    'form.configuration.settings.mdm.kiosk.lock.buttons': 'Bekapcsoló gomb zárolása',
    'form.configuration.settings.mdm.mobile.enrollment': 'Regisztráció mobiladattal',
    'form.configuration.settings.mdm.encrypt.device': 'Eszköz tárhely titkosítása',
    'form.configuration.settings.mdm.lock.safe.settings': 'Biztonságos beállítások zárolása (Wi-Fi, GPS stb.)',
    'form.configuration.settings.mdm.permissive': 'Engedékeny (féloldott) mód',
    'form.configuration.settings.mdm.kiosk.exit': 'Kioszk kilépés gomb',
    'form.configuration.settings.mdm.kiosk.screen': 'Képernyő mindig bekapcsolva',
    'form.configuration.settings.mdm.allowed.classes': 'Engedélyezett activity-k',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'Vesszővel elválasztott osztályok, pl.: com.android.settings.homepage.SettingsHomepageActivity',
    'form.configuration.settings.mdm.restrictions': 'Korlátozások',
    'form.configuration.settings.mdm.restrictions.placeholder': 'MDM korlátozások, vesszővel elválasztva, pl.: no_sms,no_outgoing_calls,no_usb_file_transfer',
    'form.configuration.settings.mdm.launcher': 'Indító URL felülírása',
    'form.configuration.settings.mdm.launcher.placeholder': 'Alternatív launcher URL zárt hálózatokba való beiratkozáshoz',
    'form.configuration.settings.mdm.misc': 'Egyéb QR-kód-bejegyzések',
    'form.configuration.settings.mdm.misc.placeholder': 'vesszővel elválasztott bejegyzések, pl.:\n"android.app.extra.PROVISIONING_LOCALE": "de_DE"',
    'form.configuration.settings.mdm.extras': 'Admin extra beállítások',
    'form.configuration.settings.mdm.extras.placeholder': 'Vesszővel elválasztott további MDM-beállítások, például:\n"com.hmdm.OPEN_WIFI": true',
    'form.configuration.settings.mdm.permissive.locked': 'Az engedélyező mód bekapcsolásához kapcsolja ki a kioszk módot',
    'form.configuration.settings.mdm.qrcode.url': 'QR-kód URL-címe',
    'form.configuration.settings.mdm.hint': 'Válaszd ki a fo alkalmazást es komponenst',
    'form.configuration.apps.search.label': 'Keresés:',
    'form.configuration.apps.sort.label': 'Rendezés:',
    'form.configuration.apps.sort.byname': 'Név szerint',
    'form.configuration.apps.sort.bypkg': 'Azonosító szerint',
    'form.configuration.apps.no.apk': 'nincs',
    'form.configuration.apps.show.systeam.apps': 'Rendszeralkalmazások mutatása',
    'form.configuration.apps.action.select': '(válassz)',
    'form.configuration.apps.action.install': 'Telepítés',
    'form.configuration.apps.action.prohibit': 'Tiltás',
    'form.configuration.apps.action.not.install': 'Ne telepítse',
    'form.configuration.apps.action.delete': 'Törlés',
    'form.configuration.apps.action.permit': 'Engedélyezés',
    'form.configuration.apps.label.inherit': 'Örökölt',
    'form.configuration.apps.label.show': 'Mutat',
    'form.configuration.apps.label.not.show': 'Elrejt',
    'form.configuration.apps.edit.details': 'További paraméterek',
    'form.configuration.apps.keycode': 'Billentyűkód',
    'form.configuration.apps.bottom': 'Megjelenítés az alsó sorban',
    'form.configuration.apps.long.tap': 'Hosszú koppintás beállításokat nyit',
    'form.configuration.apps.hint': 'Tipp: az alkalmazás és a konfiguráció közötti kapcsolat leválasztásához válassza a "Block" vagy a "Ne telepítse" műveletet.',
    'form.configuration.settings.design.use.default': 'Alapértelmezett design használata',
    'form.configuration.settings.design.color.background': 'Háttér színe',
    'form.configuration.settings.design.color.background.placeholder': 'Válasszon színt',
    'form.configuration.settings.design.color.app.names': 'Alkalmazásnevek színe',
    'form.configuration.settings.design.color.app.names.placeholder': 'Válasszon színt',
    'form.configuration.settings.design.background.image.url': 'Háttérkép URL-je',
    'form.configuration.settings.design.background.image.url.placeholder': 'Adja meg a háttérkép URL-jét',
    'form.configuration.settings.design.icon': 'Ikonméret',
    'form.configuration.settings.design.icon.small': 'Kicsi',
    'form.configuration.settings.design.icon.medium': 'Közepes (+20%)',
    'form.configuration.settings.design.icon.large': 'Nagy (+40%)',
    'form.configuration.settings.design.desktop.header': 'Asztal címe',
    'form.configuration.settings.design.desktop.header.no': 'Nem',
    'form.configuration.settings.design.desktop.header.deviceid': 'Eszközazonosító',
    'form.configuration.settings.design.desktop.header.description': 'Leírás',
    'form.configuration.settings.design.desktop.header.custom': 'Egyedi sablon',
    'form.configuration.settings.design.desktop.header.hint': 'Győződjön meg arról, hogy ez a paraméter el lett küldve az eszközöknek (Beállítások - Általános és nyelvi beállítások)',
    'form.configuration.settings.design.desktop.header.template': 'Írja be a sablont',
    'form.configuration.settings.design.desktop.header.template.placeholder': 'Változók használata',
    'form.configuration.settings.design.display.status': 'Idő és akkumulátorszint megjelenítése',
    'form.configuration.settings.design.upload': 'Feltöltés',
    'form.configuration.settings.common.name': 'Név',
    'form.configuration.settings.common.name.placeholder': 'Adja meg a konfiguráció nevét',
    'form.configuration.settings.common.desc': 'Leírás',
    'form.configuration.settings.common.desc.placeholder': 'Adja meg a konfiguráció leírását',
    'form.configuration.settings.common.admin.pwd': 'Feloldási jelszó',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Adja meg az eszköz feloldó jelszavát',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Bármilyen',
    'form.configuration.settings.common.gps.off': 'Kikapcsolva',
    'form.configuration.settings.common.gps.on': 'Bekapcsolva',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Mobiladat',
    'form.configuration.settings.common.usb.storage': 'USB tároló tiltása',
    'form.configuration.settings.common.brightness': 'Fényerő kezelése',
    'form.configuration.settings.common.brightness.none': 'Egyik sem',
    'form.configuration.settings.common.brightness.auto': 'Automatikus',
    'form.configuration.settings.common.brightness.manual': 'Érték',
    'form.configuration.settings.common.brightness.value': 'Képernyő fényereje',
    'form.configuration.settings.common.timeout': 'Képernyő időletelte kezelése',
    'form.configuration.settings.common.timeout.value': 'Képernyő időtúllépése',
    'form.configuration.settings.common.volume.block': 'Hangerő zárolása',
    'form.configuration.settings.common.volume.manage': 'Hangerő kezelése',
    'form.configuration.settings.common.volume.value': 'Hangerő',
    'form.configuration.settings.common.timezone.mode': 'Időzóna kezelése',
    'form.configuration.settings.common.timezone.mode.default': 'Ne kezelje',
    'form.configuration.settings.common.timezone.mode.auto': 'Automatikus',
    'form.configuration.settings.common.timezone.mode.manual': 'Kézi',
    'form.configuration.settings.common.timezone': 'Időzóna',
    'form.configuration.settings.common.timezone.placeholder': 'például Amerika/Los_Angeles',
    'form.configuration.settings.common.timezone.link': 'Időzónák listája',
    'form.configuration.settings.common.no.network.warning': 'FIGYELEM! Ne kapcsoljon ki minden csatlakozási csatornát, különben nem tudja többé kezelni az eszközöket!',
    'form.configuration.settings.common.autostart.foreground': 'Alkalmazások automatikus indítása az előtérben',
    'form.configuration.settings.request.updates': 'Helyzetkövetés',
    'form.configuration.settings.request.updates.donottrack': 'Nincs aktív követés (használjon harmadik féltől származó alkalmazás helyadatait)',
    'form.configuration.settings.request.updates.gps': 'Kövesse nyomon a helyét a GPS segítségével',
    'form.configuration.settings.request.updates.wifi': 'Helyszín követése Wi-Fi-n keresztül (a Google-szolgáltatásokat engedélyezni kell)',
    'form.configuration.settings.request.updates.prompt.gps': 'A hely GPS alapján történő nyomon követéséhez engedélyeznie kell a GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'A hely Wi-Fi-n keresztüli nyomon követéséhez engedélyeznie kell a Wi-Fi-t',
    'form.configuration.settings.revoke.location.permission': 'Nincs helyengedély',
    'form.configuration.settings.revoke.location.permission.hint': 'Ha be van állítva, a helymeghatározási engedély nem lesz megadva a MDM ügynöknek, és nem tudja nyomon követni az eszköz helyét',
    'form.configuration.settings.apps.permissions': 'Engedélyek más alkalmazásokhoz',
    'form.configuration.settings.apps.permissions.grant': 'Minden engedély automatikus megadása',
    'form.configuration.settings.apps.permissions.ask.location': 'Az összes automatikus megadása, kérje a felhasználótól a hely engedélyét',
    'form.configuration.settings.apps.permissions.deny.location': 'Az összes automatikus megadása, ne adjon engedélyt a helyhez',
    'form.configuration.settings.apps.permissions.ask.all': 'Kérjen minden engedélyt a felhasználótól',
    'form.configuration.settings.push.options' : 'Push értesítések',
    'form.configuration.settings.push.options.mqtt.worker' : 'MQTT protokoll (az akkumulátor kímélése)',
    'form.configuration.settings.push.options.mqtt.alarm' : 'MQTT protokoll',
    'form.configuration.settings.push.options.polling' : 'HTTP szavazás',
    'form.configuration.settings.push.options.mqtt.worker.hint' : 'Azonnal kézbesíti a Push üzeneteket, ha az eszköz aktív. Az üzenetek azonban alvó üzemmódban akár néhány órát is késhetnek. Ne használja ezt az opciót önálló eszközökön. A MQTT a TCP 31000-es portot használja, engedélyezze a tűzfalon.',
    'form.configuration.settings.push.options.mqtt.alarm.hint' : 'A MQTT egy könnyű protokoll, amely minimális erőforrást fogyaszt. A MQTT a TCP 31000-es portot használja, engedélyezze a tűzfalon.',
    'form.configuration.settings.push.options.polling.hint' : 'A hosszú lekérdezés továbbra is fenntart egy HTTP kapcsolatot, amely több szervererőforrást fogyaszthat. Nem igényel más TCP portot, mint a HTTP(S).',
    'form.configuration.settings.push.options.keepalive' : 'Életben tartás ideje',
    'form.configuration.settings.minute.1' : '1 perc',
    'form.configuration.settings.minutes.2' : '2 perc',
    'form.configuration.settings.minutes.3' : '3 perc',
    'form.configuration.settings.minutes.5' : '5 perc',
    'form.configuration.settings.minutes.10' : '10 perc',
    'form.configuration.settings.minutes.15' : '15 perc',
    'form.configuration.settings.password.mode' : 'Jelszó követelmények',
    'form.configuration.settings.password.mode.any' : 'Egyik sem',
    'form.configuration.settings.password.mode.present' : 'Jelszó bemutatja',
    'form.configuration.settings.password.mode.easy' : 'Egyszerű (legalább 6 szimbólum)',
    'form.configuration.settings.password.mode.moderate' : 'Mérsékelt (8+ szimbólum, betű és számjegy)',
    'form.configuration.settings.password.mode.strong' : 'Erős (8+, nagy- és kisbetűk, számjegyek, jelek)',
    'form.configuration.settings.show.wifi': 'Wi-Fi-beállítások csatlakozási hiba esetén',
    'form.configuration.settings.use.default.launcher': 'Háttérmód',
    'form.configuration.settings.use.default.launcher.hint': 'Ne cserélje ki a rendszerlaunchert, csak futtassa a MDM háttérszolgáltatásokat. Kioszk móddal nem ajánlott.',
    'form.configuration.settings.disable.screenshots': 'Képernyőfelvétel letiltása',
    'form.configuration.settings.orientation': 'Zár tájolása',
    'form.configuration.settings.orientation.none': 'Ne zárja le',
    'form.configuration.settings.orientation.portrait': 'Portré',
    'form.configuration.settings.orientation.landscape': 'Táj',
    'form.configuration.settings.files.default.path': 'Alapértelmezett elérési út az eszközön',
    'form.configuration.files.search.label': 'Keresés:',
    'form.configuration.files.action.upload': 'Feltöltés',
    'form.configuration.files.action.remove': 'Eltávolítás',
    'form.configuration.files.variables': 'Változó tartalom',
    'form.configuration.files.variables.hint': 'A DEVICE_NUMBER, IMEI, CUSTOM* karakterláncok az értékükre kerülnek',

    'form.configuration.file.name': 'Fájlnév',
    'form.configuration.file.select': 'Válassz fájlt',
    'form.configuration.file.create': '(új fájl létrehozása)',
    'form.configuration.file.description': 'Fájl leírása',
    'form.configuration.file.description.placeholder': 'Opcionális, az Ön kényelme érdekében',
    'form.configuration.file.override.path': 'Útvonal felülírása',
    'form.configuration.file.override.path.title': 'Csak ehhez a konfigurációhoz adja meg az eszköz elérési útját',
    'form.configuration.file.path': 'Útvonal az eszközön',
    'form.configuration.file.path.placeholder': 'Egy meghajtó elérési útjának kizárása, pl. /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'Ha csak egy fájlt tárolnak külső erőforráson',
    'form.configuration.file.file': 'Fájl',
    'form.configuration.file.action': 'Művelet',
    'form.configuration.file.action.prompt.1': 'Feltöltés',
    'form.configuration.file.action.prompt.2': 'Eltávolítás',
    'form.configuration.file.remove.prompt.1': 'Ez a fájl többé nem lesz szinkronizálva az eszközökkel',
    'form.configuration.file.remove.prompt.2': 'Fájl eltávolítása a szerverről',

    'form.password.title': 'Jelszó módosítása',
    'form.password.label.user': 'Felhasználó',
    'form.password.label.password.new': 'Új jelszó',
    'form.password.label.password.new.placeholder': 'Adjon meg egy új jelszót',
    'form.password.label.password.confirm': 'Ellenőrizze',
    'form.password.label.password.confirm.placeholder': 'Írja be újra az új jelszót',
    'form.password.length': 'Minimális hossz: ${length}.',

    'form.application.type': 'Típus',
    'form.application.type.option.web': 'Weboldal',
    'form.application.type.option.app': 'Alkalmazás',
    'form.application.type.option.intent': 'Rendszerművelet',
    'form.application.intent': 'Művelet',
    'form.application.intent.placeholder': 'Válasszon egy műveletet',
    'form.application.url.hint': 'A file:///storage/emulated/0/... használatával helyi fájlokra és mappákra mutató hivatkozásokat hozhat létre',
    'form.application.pkg': 'Csomagazonosító',
    'form.application.from.file': 'fájlból határozták meg',
    'form.application.pkg.title': 'A ID csomag automatikusan meghatározásra kerül, amikor feltölti a APK fájlt. A manuálisan beírt ID csomag csak rendszeralkalmazásokhoz szükséges.',
    'form.application.pkg.placeholder': 'Például com.android.camera',
    'form.application.disabled.arch': 'Verzióspecifikus',
    'form.application.disabled.arch.title': 'A különböző CPU architektúrákhoz tartozó APK-k hozzáadásához kattintson a „Hozzáadás” gombra, vagy nyissa meg az alkalmazásverziók listáját.',
    'form.application.arch': 'Nativ kod',
    'form.application.arch.title': 'Egyes alkalmazások bizonyos CPU architektúrára optimalizált kódot tartalmaznak. Ebben az esetben két APK-t kell feltöltenie (armeabi-v7a és arm64-v8a architektúrákhoz)',
    'form.application.arch.universal': 'Nincs (univerzális APK)',
    'form.application.arch.armeabi': 'Natív kód az armeabi-v7a számára',
    'form.application.arch.arm64': 'Natív kód az arm64-v8a számára',
    'form.application.arch.no.split': 'Univerzalis APK',
    'form.application.arch.split': 'Osztott APK',
    'form.application.arch.warning': 'Ez a APK csak a ${arch}-hez van optimalizálva, és előfordulhat, hogy nem működik minden eszközön. Javasoljuk egy másik APK feltöltése egy másik CPU ívhez optimalizálva. A APK minden eszközön való használatához válassza az „Univerzális APK” lehetőséget.',
    'form.application.arch.success': 'Ez az alkalmazás mindkét CPU architektúrához APK-kat tartalmaz',
    'form.application.version.exists': 'A APK ehhez a verzióhoz már létezik',
    'form.application.generic.name': 'Általános nevek használata nem ajánlott. Használja a {name}-{version}.apk formátumot',
    'form.application.url.armeabi': 'URL az armeabi-v7a számára',
    'form.application.url.arm64': 'URL az arm64-v8a-hoz',
    'form.application.name': 'Alkalmazás neve',
    'form.application.name.title': 'Látni fogja az alkalmazás nevét a listában. Javasoljuk egyedi és informatív elnevezések használatát.',
    'form.application.name.placeholder': 'Például: Kamera (Android)',
    'form.application.version': 'Verzió',
    'form.application.version.placeholder': '0 az előre telepített alkalmazásokhoz',
    'form.application.version.title': 'A csomag verziószáma automatikusan megállapításra kerül a APK fájl feltöltésekor. Rendszeralkalmazások esetén állítsa 0-ra.',
    'form.application.version.code': 'Verziókod',
    'form.application.version.code.exists': 'Már létezik ugyanazzal a kóddal rendelkező verzió. Kérjük, jelentse ezt a problémát az alkalmazás fejlesztőinek.',
    'form.application.system': 'Előre telepített app',
    'form.application.system.title': 'A rendszeralkalmazások előre telepítve vannak az eszközön, és nem igényelnek URL-t vagy fájlt. Ezt a jelzőt csak akkor állítsa be, ha engedélyeznie kell egy bizonyos rendszercsomagot.',
    'form.application.run.after.install': 'Indítás telepítés után',
    'form.application.run.after.install.title': 'A háttérszolgáltatással rendelkező alkalmazásokat legalább egyszer el kell indítani az előtérben.',
    'form.application.run.at.boot': 'Indítás rendszerindításkor',
    'form.application.run.at.boot.title': 'Állítsa be ezt a jelzőt, ha az alkalmazást rendszerindítás után az előtérben kell futtatnia. Ez a jelző nincs hatással a háttérfolyamatokra.',
    'form.application.url': 'URL',
    'form.application.url.title': 'A URL kódot csak akkor kell beírni, ha az alkalmazást külső erőforrás tárolja. Javasoljuk, hogy egy APK fájlt töltsön fel az alábbi mező használatával.',
    'form.application.url.disabled': 'A URL mindegyik verzióhoz be van állítva. A URL módosításához zárja be ezt az ablakot, és kattintson a „Verziók” ikonra.',
    'form.application.file': 'Fájl',
    'form.application.auto.update': 'Automatikus frissítés',
    'form.application.auto.update.title': 'Állítsa be ezt a jelzőt az összes olyan konfiguráció frissítéséhez, ahol az alkalmazás telepítve van. Csak akkor használja, ha 100%-ig biztos abban, hogy az alkalmazás stabil.',
    'form.application.showLabel': 'Ikon megjelenítése',
    'form.application.showLabel.title': 'Ez a zászló jelzi, hogy az alkalmazás ikonja megjelenjen-e az launcherban. Ez az opció felülírható a konfigurációban.',
    'form.application.use.kiosk': 'Megnyitás Kioszk böngészőben',
    'form.application.use.kiosk.title': 'Állítsa be ezt a jelzőt, ha egy weboldalt szeretne megnyitni a Kiosk Browserben anélkül, hogy megváltoztatná a címet',
    'form.application.iconText': 'Ikon szövege',
    'form.application.iconText.placeholder': '(alapértelmezett)',
    'form.application.versions.title': 'Az alkalmazás verziói',
    'form.application.icon': 'Ikon',
    'form.application.icon.default': '(alapértelmezett)',
    'form.application.icon.add': 'Ikon hozzáadása',

    'form.application.setting.app': 'Alkalmazás',
    'form.application.setting.app.placeholder': 'Válasszon ki egy alkalmazást',
    'form.application.setting.name': 'Attribútum',
    'form.application.setting.value': 'Érték',
    'form.application.setting.comment': 'Megjegyzés',
    'form.application.setting.type': 'Típus',
    'form.application.setting.readonly': 'Nem változik a készüléken',
    
    'form.application.configurations.app': 'Alkalmazás',
    'form.application.configurations.configs': 'Konfigurációk',

    'form.configuration.copy.new.name': 'Új név',
    'form.configuration.copy.new.name.placeholder': 'Adja meg az új konfiguráció nevét',

    'form.customer.name': 'Ügyfél ID',
    'form.customer.name.placeholder': 'A bejelentkezéshez használt szervezeti azonosító',
    'form.customer.admin.name': 'Adminisztrátor neve',
    'form.customer.firstname.placeholder': 'Keresztnév',
    'form.customer.lastname.placeholder': 'Vezetéknév',
    'form.customer.language': 'Nyelv',
    'form.customer.language.placeholder': 'Üres az angolhoz vagy két kis betűhöz',
    'form.customer.apiKey': 'API kulcs',
    'form.customer.apiKey.placeholder': 'Írja be a API kulcsot',
    'form.customer.prefix': 'Előtag',
    'form.customer.prefix.placeholder': 'Írja be az eszközszám előtagját',
    'form.customer.device.configuration': 'Eszköz konfiguráció',
    'form.customer.desc': 'Leírás',
    'form.customer.desc.placeholder': 'Adja meg a szervezet leírását',
    'form.customer.copy.configuration': 'Konfigurációk másolása',
    'form.customer.copy.design': 'Tervezés másolása',
    'form.customer.type': 'Vevő típusa',
    'form.customer.status': 'Ügyfél állapota',
    'form.customer.expiry.time': 'Lejárati dátum',
    'form.customer.device.limit': 'Eszközkorlát',
    'form.customer.size.limit': 'Tárolási korlát',
    'form.customer.size.limit.placeholder': 'Méret (Mb)',

    'form.device.number': 'Szám',
    'form.device.number.locked': 'A szám nem módosítható, mert az előző számmódosítás nem fejeződött be.',
    'form.device.migration.warning': 'A készülék száma megváltozik. Győződjön meg arról, hogy a készülék be van kapcsolva és online.',
    'form.device.number.hint': 'Ne használjon speciális karaktereket',
    'form.device.desc': 'Leírás',
    'form.device.groups': 'Csoportok',
    'form.device.config': 'Konfiguráció',
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Telefonszám',

    'form.update.device.config': 'Konfiguráció',
    'form.update.device.action': 'Csoportművelet',
    'form.device.set.group': 'Hozzáadás csoportokhoz',
    'form.device.clear.group': 'Eltávolítás a csoportokból',

    'form.file.file': 'Fájl',
    'form.file.name': 'Fájlnév',
    'form.file.description': 'Leírás (nem kötelező)',
    'form.file.external': 'Külső',
    'form.file.external.title': 'A fájl feltöltése helyett külső erőforrás URL-címét is megadhatja',
    'form.file.external.url': 'URL',
    'form.file.external.url.placeholder': 'A fájl URL-címe a külső erőforráson',
    'form.file.path': 'Útvonal a szerveren',
    'form.file.device.path': 'Útvonal az eszközön',
    'form.file.device.path.placeholder': 'A /storage/emulated/0 fájlhoz viszonyított elérési út',
    'form.file.deleted': 'TÖRÖLVE',
    'form.file.copy.link': 'Link másolása: ${link}',
    'form.file.configurations.file': 'Fájl',
    'form.file.configurations.configs': 'Konfigurációk',
    'form.file.configurations.upload': 'Feltöltés',
    'form.file.path.placeholder': 'Adjon meg egy relatív elérési utat, például "/files/"',
    'form.file.available': 'Szabad hely: ${space} Mb',

    'form.file.apps.name': 'Alkalmazás neve',
    'form.file.apps.pkg': 'Csomagazonosító',
    'form.file.apps.version': 'Verzió',

    'form.group.name': 'Név',
    'form.group.name.placeholder': 'Írja be a csoport nevét',

    'form.role.name': 'Név',
    'form.role.name.placeholder': 'Írja be a szerep nevét',
    'form.role.permissions': 'Engedélyek',

    'form.user.login': 'Bejelentkezés',
    'form.user.login.placeholder': 'Adja meg a felhasználói bejelentkezést',
    'form.user.name': 'Név',
    'form.user.name.placeholder': 'Kereszt- és vezetéknév',
    'form.user.email': 'Email',
    'form.user.email.placeholder': 'Írja be az e-mail-címet',
    'form.user.role': 'Szerepkör',
    'form.user.all.devices.available': 'Minden eszköz elérhető',
    'form.user.available.groups': 'Elérhető eszközcsoportok',
    'form.user.all.configs.available': 'Minden konfiguráció elérhető',
    'form.user.available.configs': 'Elérhető konfigurációk',
    'form.user.password.new': 'Új jelszó',
    'form.user.password': 'Jelszó',
    'form.user.password.new.placeholder': 'Adjon meg egy új jelszót',
    'form.user.password.confirm': 'Ellenőrizze',
    'form.user.password.confirm.placeholder': 'Írja be újra az új jelszót',

    'form.settings.hints.title': 'Súgók',

    'form.settings.plugins.title': 'Használt pluginok',

    'form.settings.common.title': 'Eszköztabla nezet',
    'form.settings.common.visible.columns': 'Lathato oszlopok az "Eszközök" tablaban',
    'form.settings.common.status': 'Állapot',
    'form.settings.common.role': 'Felhasználói szerep',
    'form.settings.common.date': 'Utolsó online időpont',
    'form.settings.common.device.number': 'Eszközszám',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Telefonszám',
    'form.settings.common.phone.model': 'Telefonmodell',
    'form.settings.common.status.permissions': 'Engedélyállapot',
    'form.settings.common.status.installation': 'Telepítési állapot',
    'form.settings.common.status.files': 'Fájlok állapota',
    'form.settings.common.config': 'Konfiguráció',
    'form.settings.common.desc': 'Leírás',
    'form.settings.common.group': 'Csoport',
    'form.settings.common.launcher.version': 'Launcher verziója',
    'form.settings.common.battery.level': 'Akkumulatorszint',
    'form.settings.common.default.launcher': 'Háttérmód',
    'form.settings.common.mdm.mode': 'MDM mód',
    'form.settings.common.kiosk.mode': 'Kioszk mód',
    'form.settings.common.android.version': 'Android-verzió',
    'form.settings.common.enrollment.date': 'Beiratkozás dátuma',
    'form.settings.common.serial': 'Sorozatszám',
    'form.settings.common.publicip': 'IP-cím',

    'form.settings.design.title': 'Alapértelmezett design',
    'form.settings.design.color.font': 'Háttér színe',
    'form.settings.design.color.font.placeholder': 'Válassz szint',
    'form.settings.design.color.app.names': 'Alkalmazásnévek szine',
    'form.settings.design.color.app.names.placeholder': 'Válassz szint',
    'form.settings.design.url.background.image': 'Hattérkép URL-je',
    'form.settings.design.url.background.image.placeholder': 'Adja meg a háttérkép URL-címét',
    'form.settings.design.size.icon': 'Ikonmeret',
    'form.settings.design.size.icon.small': 'Kicsi',
    'form.settings.design.size.icon.medium': 'Közepes (+20%)',
    'form.settings.design.size.icon.large': 'Nagy (+40%)',
    'form.settings.design.desktop.header': 'Asztal címe',
    'form.settings.design.desktop.header.no': 'Nem',
    'form.settings.design.desktop.header.device.id': 'Eszközazonosító',

    'form.settings.lang.title': 'Nyelvi beállítások',
    'form.settings.lang.use.default': 'Alapértelmezett nyelv használata',
    'form.settings.lang.use': 'Nyelv hasznalata',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.en': 'English',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.it': 'Italiano',
    'form.settings.lang.hu': 'Magyar',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.vi': 'Tiếng Việt',
    'form.settings.lang.tr': 'Türkçe',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',
    'form.settings.lang.ja': '日本',

    'form.settings.misc.title': 'Különféle beállítások',
    'form.settings.misc.phone.format': 'Telefonszám formátum',
    'form.settings.misc.phone.format.placeholder': '+ (36) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'Egyedi tulajdonság #1',
    'form.settings.misc.custom.property.name.2': 'Egyedi tulajdonság #2',
    'form.settings.misc.custom.property.name.3': 'Egyedi tulajdonság #3',
    'form.settings.misc.custom.property.multiline': 'Többsoros',
    'form.settings.misc.custom.property.send': 'Küldés eszközre',
    'form.settings.misc.custom.property.name.placeholder': 'Adja meg az egyéni tulajdonság nevét',
    'form.settings.misc.create.new.devices': 'Eszköz hozzáadása az első hozzáféréskor',
    'form.settings.misc.new.device.config': 'Új eszközkonfiguráció',
    'form.settings.misc.new.device.group': 'Új eszközcsoport',
    'form.settings.misc.send.description': 'Leírás küldése az eszközöknek',
    'form.settings.misc.password.length': 'Minimális jelszóhossz',
    'form.settings.misc.password.strength': 'Jelszó erőssége',
    'form.settings.misc.password.none': 'Nincs megadva (bármely karakter)',
    'form.settings.misc.password.alphanumeric': 'Kis- és nagybetűk, számjegyek',
    'form.settings.misc.password.specialchar': 'Kis- és nagybetűk, számjegyek, speciális karakterek',
    'form.settings.misc.password.reset': 'A felhasználónak vissza kell állítania a jelszót',
    'form.settings.misc.idle.logout': 'Jelentkezzen ki üresjáratban',
    'form.settings.misc.idle.logout.never': 'Soha',
    'form.settings.misc.idle.logout.1': '5 perc',
    'form.settings.misc.idle.logout.2': '10 perc',
    'form.settings.misc.idle.logout.3': '30 perc',
    'form.settings.misc.idle.logout.4': '1 óra',
    'form.settings.security.title': 'Biztonsági beállítások',

    'idle.logout.message': 'Inaktivitás miatt ${sec} másodpercen belül kijelentkeztetjük',
    'idle.logout.resume': 'itt vagyok!',

    'form.settings.groups.title': 'Csoportok',
    'form.settings.groups.search.placeholder': 'Csoportos keresés',

    'form.settings.users.title': 'Felhasználók',
    'form.settings.users.search.placeholder': 'Felhasználó keresése',

    'form.settings.roles.title': 'Felhasználói szerepek',

    'form.settings.icons.title': 'Ikonok',
    'form.settings.icons.search.placeholder': 'Keresés ikonok',

    'form.qr.device.number': 'Eszközszám',
    'form.qr.auto.create': 'Ha nem létezik, adja hozzá az eszközlistához',
    'form.qr.number.use': 'Eszközszám hozzárendelés',
    'form.qr.number.use.request': 'Felhasználói érték',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'Sorozatszám',
    'form.qr.number.hint': 'Az automatikus eszközszám-hozzárendelés engedélyezéséhez törölje az eszközszámot',
    'form.qr.groups': 'Hozzáadás csoportokhoz',
    'form.qr.button.json': 'JSON lekerese',
    'form.qr.device.number.placeholder': 'Írja be a készüléket ID …',
    'form.qr.code.image.alt': 'QR-kód',

    'form.password.reset.title': 'Kérjük, állítson be új jelszót',
    'form.password.reset.invalid': 'Sajnáljuk, ez a jelszó-visszaállítási hivatkozás érvénytelen',
    'form.password.reset.submit': 'Jelszó beállítása',

    'form.two.factor.auth.title': 'Kéttényezős hitelesítés',
    'form.two.factor.auth.hint': 'A regisztráció befejezéséhez telepítse a hitelesítő alkalmazást mobileszközére, olvassa be a QR-kódot, majd hozza létre és írja be az ellenőrző kódot.',
    'form.two.factor.auth.code.invalid': 'Az ellenőrző kód érvénytelen!',
    'form.two.factor.auth.code': 'Ellenőrző kód',
    'form.two.factor.auth.code.hint': '6 számjegyű kód a hitelesítő alkalmazásból',
    'form.two.factor.auth.code.error': 'A kódnak 6 jegyű számnak kell lennie',
    'form.two.factor.auth.verify': 'Ellenőrizze',
    'form.two.factor.auth.settings.hint': 'A kéttényezős hitelesítés beállításához telepítse a hitelesítő alkalmazást mobileszközére, olvassa be a QR-kódot, majd hozza létre és írja be az ellenőrző kódot.',
    'form.two.factor.auth.set': 'A kéttényezős hitelesítés be van kapcsolva',
    'form.two.factor.auth.reset': 'A kéttényezős hitelesítés ki van kapcsolva',
    'form.two.factor.auth.off.confirm': 'Ki szeretné kapcsolni a kéttényezős hitelesítést? A visszakapcsolás után az összes hitelesítő érvénytelen lesz.',

    'form.profile.title': 'Jelszó módosítása',
    'form.profile.password.old': 'Régi jelszó',
    'form.profile.password.old.placeholder': 'Írja be a régi jelszót',
    'form.profile.password.new': 'Új jelszó',
    'form.profile.password.new.placeholder': 'Adjon meg egy új jelszót',
    'form.profile.password.confirm': 'Ellenőrizze',
    'form.profile.password.confirm.placeholder': 'Írja be újra az új jelszót',

    'tab.customers': 'Szervezetek',
    'tab.common.applications': 'Megosztott alkalmazások',

    'tab.devices': 'Eszközök',
    'tab.applications': 'Alkalmazások',
    'tab.configurations': 'Konfigurációk',
    'tab.files': 'Fájlok',
    'tab.default.design': 'Alapértelmezett design',
    'tab.common.settings': 'Eszköztabla nezet',
    'tab.users': 'Felhasználók',
    'tab.roles': 'Szerepkörök',
    'tab.groups': 'Csoportok',
    'tab.icons': 'Ikonok',
    'tab.language': 'Altalanos es nyelvi beállítások',
    'tab.license': 'Licenc',
    'tab.hints': 'Súgók',
    'tab.plugins': 'Bővítmények',
    
    'tab.configeditor.common.settings': 'Altalanos beállítások',
    'tab.configeditor.design.settings': 'Design beállítások',
    'tab.configeditor.applications': 'Alkalmazások',
    'tab.configeditor.mdm.settings': 'MDM beállítások',
    'tab.configeditor.app.settings': 'Alkalmazásbeállítások',
    'tab.configeditor.files': 'Fájlok',

    'search.placeholder.file': 'keresési fájl',
    'search.placeholder.configuration': 'Keresse meg a konfigurációt',
    'search.placeholder.customer': 'Keressen egy szervezetet',
    'search.placeholder.application': 'Keressen egy alkalmazást',
    'search.placeholder.application.setting': 'Keressen egy alkalmazásbeállítást',
    'search.placeholder.device': 'Keressen egy eszközt',
    'search.placeholder.address': 'Címkeresés',
    'search.placeholder.point': 'Webhelykeresés',
    'search.placeholder.message': 'Üzenetkeresés',
    'search.placeholder': 'Keresés…',
    'search.placeholder.from': '-tól…',
    'search.placeholder.to': 'Hogy…',
    'search.placeholder.user': 'Írja be a felhasználónevet',

    'table.heading.customer.name': 'Név',
    'table.heading.customer.desc': 'Leírás',
    'table.heading.customer.registration.time': 'Bejegyzett',
    'table.heading.customer.last.login.time': 'Utolsó bejelentkezés',
    'table.heading.customer.actions': 'Műveletek',
    'table.heading.customer.type': 'Típus',
    'table.heading.customer.expiry.time': 'Lejár',
    'table.heading.customer.device.limit': 'Határ',
    'table.heading.customer.status': 'Állapot',

    'customer.new': 'Új',
    'customer.active': 'Aktív',
    'customer.need.followup': 'Nyomon követés szükséges',
    'customer.followup.sent': 'Nyomon követés elküldve',
    'customer.internal.test': 'Belső teszt',
    'customer.developer': 'Fejlesztő',
    'customer.difficult': 'Nehéz',
    'customer.pause': 'Szünet',
    'customer.inactive': 'Nincs bejelentkezés',
    'customer.abandon': 'Hagyja el',
    'customer.onpremise': 'Helyszíni próba',
    'customer.denial': 'Tagadás',
    'customer.client': 'Ügyfél',

    'table.heading.configuration.name': 'Név',
    'table.heading.configuration.desc': 'Leírás',
    'table.heading.configuration.actions': 'Műveletek',

    'table.heading.application.setting.app.pkg': 'Csomagazonosító',
    'table.heading.application.setting.app.name': 'Alkalmazás neve',
    'table.heading.application.setting.name': 'Attribútum',
    'table.heading.application.setting.value': 'Érték',
    'table.heading.application.setting.comment': 'Megjegyzés',
    'table.heading.application.setting.lastUpdate': 'Létrehozás dátuma',

    'table.heading.file.url': 'URL',
    'table.heading.file.devicepath': 'Útvonal az eszközön',
    'table.heading.file.description': 'Fájl leírása',
    'table.heading.file.action': 'Művelet',
    'table.heading.file.lastUpdate': 'Létrehozás dátuma',
    
    'table.heading.application.pkg': 'Csomagazonosító',
    'table.heading.application.name': 'Alkalmazás neve',
    'table.heading.application.version': 'Verzió',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Ikon',
    'table.heading.application.actions': 'Műveletek',
    'table.heading.application.order': 'Sorrend',

    'table.heading.device.status': 'Állapot',
    'table.heading.device.date': 'Dátum',
    'table.heading.device.device.number': 'Eszközszám',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Telefonszám',
    'table.heading.device.phone.model': 'Telefonmodell',
    'table.heading.device.status.permissions': 'Engedélyállapot',
    'table.heading.device.status.installation': 'Telepítési állapot',
    'table.heading.device.status.files': 'Fájlok állapota',
    'table.heading.device.configuration': 'Konfiguráció',
    'table.heading.device.desc': 'Leírás',
    'table.heading.device.group': 'Csoport',
    'table.heading.device.launcher.version': 'Launcher verziója',
    'table.heading.device.battery.level': 'Akkumulatorszint',
    'table.heading.device.default.launcher': 'Háttérmód',
    'table.heading.device.mdm.mode': 'MDM mód',
    'table.heading.device.kiosk.mode': 'Kioszk mód',
    'table.heading.device.android.version': 'Android-verzió',
    'table.heading.device.enrollment.date': 'Regisztralva',
    'table.heading.device.serial': 'Sorozatszám',
    'table.heading.device.publicip': 'IP-cím',
    'table.heading.device.actions': 'Műveletek',

    'table.heading.group.name': 'Név',
    'table.heading.group.actions': 'Műveletek',

    'table.heading.role.name': 'Név',
    'table.heading.role.actions': 'Műveletek',

    'table.heading.file.name': 'Fájlnév',
    'table.heading.file.comment': 'Leírás',
    'table.heading.file.device.path': 'Útvonal az eszközön',
    'table.heading.file.update.time': 'Frissítve:',
    'table.heading.file.external': 'Külső',
    'table.heading.file.variable': 'Változó',
    'table.heading.file.remove': 'Eltávolítás',
    'table.heading.file.remove.hint': 'Kényszeríti a fájl eltávolítását az eszköz tárolójából',
    'table.heading.file.path': 'Útvonal',
    'table.heading.file.address': 'Cím',
    'table.heading.file.size': 'Méret',
    'table.heading.file.actions': 'Műveletek',

    'table.heading.users.login': 'Bejelentkezés',
    'table.heading.users.name': 'Név',
    'table.heading.users.role': 'Szerepkör',
    'table.heading.users.actions': 'Műveletek',

    'table.heading.common.apps.customer': 'Szervezet',
    'table.heading.common.apps.pkg': 'Csomagazonosító',
    'table.heading.common.apps.name': 'Alkalmazás neve',
    'table.heading.common.apps.version': 'Verzió',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Ikon',
    'table.heading.common.apps.actions': 'Műveletek',

    'notfound.devices': 'Nincsenek megjeleníthető eszközök.',
    'notfound.files':'A fájllista üres.',
    'notfound.configurations': 'Nem találhatók konfigurációk.',
    'notfound.customers': 'Nem található szervezetek.',
    'notfound.common.apps': 'Nincsenek megjeleníthető alkalmazások.',
    'notfound.applications': 'Az alkalmazások nem találhatók',
    'notfound.groups':'Nem található csoport. Próbálkozzon másik lekérdezéssel.',
    'notfound.users':'Felhasználók nem találhatók. Próbálkozzon másik lekérdezéssel.',
    'notfound.apps.for.display': 'Nincsenek megjeleníthető alkalmazások.',
    'notfound.app.versions.for.display': 'Nincs megjeleníthető verzió.',
    'notfound.roles':'A szereplista üres.',
    'notfound.icons':'Az ikonlista üres.',

    'format.date.header': 'yyyy/MM/dd HH:mm',

    'menu.about': 'Névjegy',
    'menu.profile': 'Profil',
    'menu.panel.master': 'Mester panel',
    'menu.panel.main': 'Fopanel',
    'menu.logout': 'Kijelentkezes',
    'menu.functions': 'Funkciok',
    'menu.settings': 'Beállítások',
    'menu.show.hints': 'Tippek megjelenítése',

    'plugin.name.not.specified': '<< A funkció neve nincs megadva >>',

    'breadcrumb.summary': 'Összegzés',
    'breadcrumb.devices': 'Eszközök',
    'breadcrumb.applications': 'Alkalmazások',
    'breadcrumb.configurations': 'Konfigurációk',
    'breadcrumb.files': 'Fájlok',
    'breadcrumb.default.design': 'Tervezés alapértelmezés szerint',
    'breadcrumb.common.settings': 'Eszköztabla nezet',
    'breadcrumb.language.settings': 'Nyelvi és egyéb beállítások',
    'breadcrumb.license.settings': 'Licenc',
    'breadcrumb.users': 'Felhasználók',
    'breadcrumb.groups': 'Csoportok',
    'breadcrumb.hints': 'Súgók',
    'breadcrumb.plugins': 'Bővítmények',
    'breadcrumb.config.details': 'Részletek',
    'breadcrumb.application.versions': 'Verziók',

    'app.name': 'Ellenszél MDM',
    'app.vendor.name':"h-mdm.com",
    'app.vendor.link':"https://h-mdm.com",
    'app.description': 'egy nyílt forráskódú mobileszköz-kezelő rendszer',
    'app.title': '${appName} webpanel',

    'box.show.my.apps.only': 'Csak az én alkalmazásaimat jelenítse meg',
    'configuration.app.version.upgrade.message': 'Telepített verzió ${installedVersion}, elérhető verzió ${latestVersion}',

    'about.line.1': '${appName} vezérlőpanel',
    'about.line.2': 'Nyílt forráskódú MDM Androidra',
    'about.line.3': '${versionNumber} verzió',
    'about.line.4': 'Telepített pluginok',

    'common.app.clarification': 'Ez az alkalmazás nyilvános és nem szerkeszthető. Az alkalmazás egy másik verziójának hozzáadásához forduljon a rendszergazdához.',

    'qrcode.help.line1': 'Az Android-eszköz (7-es vagy újabb verzió) felügyelt (vállalati) módban történő beállítása:',
    'qrcode.help.line2': 'Állítsa vissza a készüléket a gyári beállításokra',
    'qrcode.help.line3': 'Érintse meg hétszer a kezdőképernyő tetszőleges pontját (ezzel belép a rejtett QR-kód-beolvasási módba)',
    'qrcode.help.line4': 'Kövesse az eszköz utasításait: fogadja el a feltételeket, csatlakozzon Wi-Fi-hez, szkennelje be ezt a QR-kódot',
    'qrcode.help.line5': 'A QR-kód tartalmazhatja a ${appName} eszközazonosítóját, így azt nem kell megadni a mobileszközön. Az eszközazonosító QR-kódba ágyazásához adja meg az azonosítót ezen a képernyőn, majd kattintson a „Megújítás” gombra.',

    'form.configuration.app.version.select.select.title': 'Válassza ki a telepíteni kívánt verziót',
    'form.configuration.app.version.select.version.check.off': 'A verzióellenőrzés letiltása',
    'form.configuration.app.version.select.upgrade.warning': 'Frissítse a „${v1}” alkalmazást „${v3}” verzióra a „${v2}” konfigurációhoz?',
    'form.configuration.app.version.select.downgrade.warning': 'A régebbi verzió telepítése MINDEN ESZKÖZÖN TÖRLI EZEKET AZ ALKALMAZÁSOKAT! Biztosan visszaállítja az alkalmazást a(z) „${v1}” verzióról a(z) „${v2}” verzióra?',

    'hint.step.1': 'Kattintson ide az eszköz regisztrációjának elindításához',
    'hint.step.2': 'Kattintson ide a QR-kód megnyitásához',
    'hint.step.3': 'Kattintson ide annak megtekintéséhez, hogyan nyitható meg a QR-kód-olvasó az eszközön',
    'hint.step.4': 'Keressen egy elérhető eszközazonosítót az „Eszközök” lapon. Kattintson a „Megújítás” gombra az azonosító QR-kódba foglalásához.',

    'ie.browser.notice.1': 'Sajnos az Internet Explorer nem támogatott.',
    'ie.browser.notice.2': 'A ${appName} használatához a <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a> böngészőt javasoljuk.',

    'form.resolved.duplicate.pkg.text1': 'A ID "${pkg}" csomagot már használják az alább felsorolt ​​alkalmazások.',
    'form.resolved.duplicate.pkg.text2': 'Új alkalmazást szeretne hozzáadni, vagy egy meglévő alkalmazás új verzióját?',
    'form.resolved.duplicate.pkg.text3': 'Új verzió ehhez',
    'form.resolved.duplicate.pkg.text4': 'A ID "${pkg}" csomagot már használják a ${apps} alkalmazások',
    'form.resolved.duplicate.pkg.text5': 'Biztosan módosítani szeretné a ID csomagot?',

    'tooltip.usage.byconfigurations': 'Konfigurációk használják',
    'tooltip.usage.byapps': 'Alkalmazások használják',
    'tooltip.usage.byicons': 'Ikonok által használt',

    'form.devices.label.params.more': 'További parameterek',
    'form.devices.label.params.less': 'Kevesebb parameter',
    'form.devices.label.installation.status': 'Telepítési állapot',
    "format.devices.date.createTime": "yyyy/MM/dd HH:mm:ss",
    "format.devices.date.datePicker": "yyyy-MM-dd",
    'form.devices.fast.search': 'Gyors keresés szám szerint',

    'form.devices.selection.install.status.default': 'Telepítés állapota…',
    'form.devices.selection.install.status.all': 'Mind',
    'form.devices.selection.install.status.success': 'Sikeres',
    'form.devices.selection.install.status.version.mismatch': 'Verziós eltérés',
    'form.devices.selection.install.status.failure': 'Hiba',
    'form.devices.selection.imei.changed': 'A IMEI nemrég megváltozott',

    'search.placeholder.launcher.version': 'Launcher verziója',
    'error.date.range.invalid': 'Érvénytelen dátumintervallum',

    'form.selection.status.any': 'Bármilyen érték',
    'form.selection.status.all': 'Mind',
    'form.selection.status.yes': 'Igen',
    'form.selection.status.no': 'Nem',

    'form.devices.selection.status': 'Állapot…',
    'form.devices.selection.online': 'Online',
    'form.devices.selection.offline': 'Offline',
    'form.devices.selection.number': 'Adj meg egy számot',

    'form.devices.selection.online.status.custom': 'Adja meg az időt',
    'form.devices.selection.online.status.1': '15 perc',
    'form.devices.selection.online.status.2': '30 perc',
    'form.devices.selection.online.status.3': '1 óra',
    'form.devices.selection.online.status.4': '2 óra',
    'form.devices.selection.online.status.5': '6 óra',
    'form.devices.selection.online.status.6': '1 nap',
    'form.devices.selection.online.status.7': '2 nap',
    'form.devices.selection.online.status.8': '3 nap',
    'form.devices.selection.online.status.9': '1 hét',
    'form.devices.selection.online.status.10': '1 hónap',

    'form.devices.selection.online.status.label': 'jegyzőkönyv)',
    'form.devices.status.ago': 'ezelőtt',
    'form.devices.status.minutes': 'perc',
    'form.devices.status.hours': 'óra',
    'form.devices.status.days': 'nap',
    'form.devices.status.weeks': 'hét',
    'form.devices.status.months': 'hónap',
    'form.devices.status.years': 'év',

    'customer.type.demo': 'Demó',
    'customer.type.small': 'Szakmai',
    'customer.type.corporate': 'Vállalkozás',
    'customer.type.master': 'Elsődleges',

    'customer.type.options.all': 'Minden típus',
    'customer.status.options.all': 'Minden állapot',

    'account.expiring': 'Fiókja ${days} napon belül lejár. Kérjük, lépjen kapcsolatba az eladóval a fiók megújításához.',
    'account.expired.short': 'Fiókja lejárt!',
    'account.expired': 'Fiókja lejárt. Kérjük, lépjen kapcsolatba az eladóval a fiók megújításához.',
    'device.limit.achieved': 'Nem lehet eszközt hozzáadni, mert elérte a korlátot. Kérjük, távolítson el néhány eszközt, vagy lépjen kapcsolatba az eladóval az eszközkorlát meghosszabbítása érdekében.',

    'menu.updates': 'Frissítések keresése',
    'updates.title': 'Frissítések',
    'updates.disabled.custom': 'Egyedi verzió, kérjük, frissítse manuálisan',
    'updates.disabled.not_master': 'Kérje meg a tárhelyszolgáltatót, hogy frissítse',
    'updates.disabled.multiple': 'Több alkalmazásverzió, kérjük, frissítse manuálisan',
    'updates.disabled.error': 'Belső szerverhiba',
    'updates.disabled.download': 'Hiba a frissítés letöltése közben',
    'updates.application': 'Alkalmazás',
    'updates.current.version': 'Jelenlegi verzió',
    'updates.available.version': 'Elérhető verzió',
    'updates.downloaded': 'Letöltve',
    'updates.auto.update': 'A mobilalkalmazások automatikus frissítése (elővigyázatossággal használja a gyártás során!)',
    'updates.enable.stats': 'Használati statisztikák küldése a szolgáltatónak a rendszer teljesítményének javítása érdekében',
    'updates.get': 'Frissítések beszerzése',
    'updates.checking': 'Frissítések keresése…',
    'updates.getting': 'Frissítések lekérése…',
    'updates.success': 'Frissítés befejezve',
    'updates.web.hint': 'A webalkalmazás frissítésének befejezéséhez futtassa a „/opt/hmdm/update-web-app.sh” parancsfájlt az SSH-konzolon',

    'permission.edit_device_app_settings': 'Eszközspecifikus alkalmazásbeállítások kezelése',
    'permission.plugins_customer_access_management': 'Elérhető pluginok kezelése',
    'permission.plugin_audit_access': 'Auditnapló megtekintése',
    'permission.plugin_contacts_access': 'Névjegyek kezelése',
    'permission.plugin_deviceexport_access': 'Eszközök exportálása',
    'permission.plugin_deviceimport_access': 'Eszközök importálása',
    'permission.plugin_deviceinfo_access': 'Eszköz részletes adatainak megtekintése',
    'permission.plugin_devicelocations_access': 'Eszközök megtekintése a térképen',
    'permission.plugin_devicelocations_settings_access': 'Térképplugin konfigurálása',
    'permission.plugin_devicelog_access': 'Eszköznaplók megtekintése',
    'permission.plugin_devicereset_access': 'Eszközök visszaállítása és újraindítása',
    'permission.plugin_licensing_access': 'Hozzáférés a licenchez (elavult)',
    'permission.plugin_messaging_send': 'Üzenetek küldése',
    'permission.plugin_messaging_delete': 'Elküldött üzenetek törlése',
    'permission.plugin_photo_remove_photo': 'Fényképek törlése',
    'permission.settings': 'Beállítások kezelése',
    'permission.configurations': 'Konfigurációk megtekintése',
    'permission.edit_devices': 'Eszközadatok szerkesztése',
    'permission.edit_device_desc': 'Eszközleírás szerkesztése',
    'permission.enroll_devices': 'Eszközök regisztrálása QR-kóddal',
    'permission.plugin_apuppet_access': 'Távoli vezérlés',
    'permission.plugin_knox_access': 'Knox plugin',
    'permission.add_config': 'Konfigurációk hozzáadása',
    'permission.copy_config': 'Konfigurációk másolása',
    'permission.plugin_openvpn_access': 'OpenVPN plugin',
    'permission.plugin_photo_access': 'Fotó plugin',
    'permission.push_api': 'Hozzáférés a Push API-hez',
    'permission.plugin_urlfilter_access': 'URL-szűrés',
    'permission.plugin_push_send': 'Push üzenetek küldése',
    'permission.plugin_push_delete': 'Push üzenetek törlése',
    'permission.get_updates': 'Frissítések keresése',
    'permission.plugin_xtra_access': 'Prémium verzió kérése',
    'permission.applications': 'Alkalmazások megtekintése',
    'permission.edit_applications': 'Alkalmazások kezelése',
    'permission.edit_application_versions': 'Alkalmazásverziók kezelése',
    'permission.files': 'Fájlok megtekintése',
    'permission.edit_files': 'Fájlok kezelése',

    'yes': 'igen',
    'no': 'nem'
};
