if (! document.localization) document.localization = [];

document.localization ['pt_PT'] = {
    'login.username': 'Usuário ou Email',
    'login.username.placeholder': 'Insira o seu usuário ou email',
    'login.password': 'Senha:',
    'login.password.placeholder': 'Insira sua senha',
    'login.submit': 'Login',
    'login.password.incorrect': 'Usuário ou senha inválidos',

    'header.label.username': 'Usuário',

    'devices.group.options.all': 'Todos os Grupos',
    'devices.configuration.options.all': 'Todas as Configurações',
    'devices.permissions.all': 'Todas as permissões concedidas',
    'devices.permissions.not.as.device.admin': '- A Aplicação não está instalada como administrador do dispositivo',
    'devices.permissions.window.overlap.prohibited': '- A sobreposição sobre outras janelas não está disponível',
    'devices.permissions.history.access.prohibited': '- Acesso ao histórico de uso não configurado',
    'devices.unknown': 'Desconhecido',
    'devices.model.unknown': 'Desconhecido',
    'devices.date.unknown': 'desconhecido',
    'devices.date.format': 'dd/MM HH:mm',
    'devices.app.installed': '- ${applicationName}: Instalado.',
    'devices.app.not.installed': '- ${applicationName}: não instalado.',
    'devices.app.version.available': ', disponível ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: instalado ${applicationInstalledVersion}, disponível ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, remoção é necessária',
    'devices.no.data': 'O dispositivo não transmitiu dados',
    'devices.settings.conformance.broken': 'Incompatibilidade com as configurações: (${serverData})',
    'devices.file.installed': '- ${file}: instalado',
    'devices.file.not.installed': '- ${file}: não instalado.',
    'devices.file.lastUpdate.differs': '- ${file}: diferença de ${diff} min da última atualização',

    'button.apply': 'Aplicar',
    'button.gps.on': 'Ativar GPS',
    'button.wifi.on': 'Ativar Wi-Fi',
    'button.notify.update': 'Notificar na Atualização',
    'button.app.settings': 'Configurações do Aplicativo',
    'button.ok': 'OK',
    'button.help': 'Ajuda',
    'button.new.app': 'Novo Aplicativo',
    'button.new.app.version': 'Nova Versão',
    'button.upgrade': 'Atualizar',
    'button.renew.config': 'Atualizar Dispositivos',
    'button.common': 'Aplicação comum',
    'button.close': 'Fechar',
    'button.yes': 'Sim',
    'button.cancel': 'Cancelar',
    'button.save': 'Salvar',
    'button.save.and.close': 'Salvar e Fechar',
    'button.more': 'Mais ...',
    'button.cleanup': 'Limpar',
    'button.add': 'Adicionar',
    'button.add.icon': 'Novo ícone',
    'button.search': 'Buscar',
    'button.export': 'Exportar',
    'button.change': 'Editar',
    'button.copy': 'Copiar',
    'button.qrcode': 'QR code',
    'button.application': 'Aplicativo',
    'button.change.password': 'Alterar Senha',
    'button.set.configuration': 'Aplicar configuração',
    'button.delete': 'Remover',
    'button.login': 'Login',
    'button.renew.code': 'Renovar',
    'button.configurations': 'Configurações',
    'button.set.configurations': 'Especificar Confgurações',
    'button.edit.versions': 'Versões',
    'button.edit': 'Editar',
    'button.change.common.app': 'Editar Aplicativos Compartilhados',
    'button.delete.common.app': 'Remover Aplicativos Compartilhados',
    'button.turn.common.app': 'Tornar Comum',
    'button.hints.enable': 'Mostrar Dicas',
    'button.hints.disable': 'Ocultar Dicas',
    'button.show.password': 'Mostrar senha',
    'button.hide.password': 'Ocultar senha',

    'question.impersonate.user': 'Entrar no aplicativo como administrador da organização "${customerName}"?',
    'question.change.user': 'Entrar no aplicativo como usuário "${userName}"?',
    'question.delete.file': 'Excluir arquivo "${fileName}"?',
    'question.delete.customer': 'Excluir organização "${customerName}"?',
    'question.delete.user': 'Excluir usuário "${username}"?',
    'question.delete.application': 'Excluir aplicação "${applicationName}"?',
    'question.delete.application.version': 'Excluir versão "${applicationVersion}"?',
    'question.delete.configuration': 'Excluir configuração "${configurationName}"??',
    'question.delete.group': 'Excluir grupo "${groupName}"?',
    'question.delete.device': 'Excluir dispositivo com o número "${deviceNumber}"?',
    'question.exit.without.saving': 'Alterações não foram salvas. De qualquer forma deseja sair dessa página?',
    'question.turn2common.application': 'Compartilhar a aplicação "${applicationName}"?',
    'question.app.upgrade': 'Atualizar aplicação "${v1}" para a versão mais recente da configuração "${v2}"?',

    'error.application.setting.empty.app': 'Insira o aplicativo',
    'error.application.setting.empty.name': 'Insira o nome',
    'error.application.setting.empty.value': 'Insira o Valor',

    'error.icon.dimension.invalid': 'O ícone precisa ser quadrado',
    'error.icon.empty.name': 'Insira o nome do ícone',
    'error.icon.empty.file': 'Upload do ícone',
    'error.application.version.pkg.mismatch': 'O pacote de ID do arquivo (${actual}) não corresponde a aplicação (${expected})',
    'error.empty.user': 'Selecione um usuário',
    'error.empty.user.name': 'Insira o nome do usuário',
    'error.empty.user.login': 'Insira o login do usuário',
    'error.empty.user.role': 'Selecione o perfil do usuário',
    'error.empty.password': 'Insira a nova senha',
    'error.empty.password.confirm': 'Insira a confirmação de senha',
    'error.empty.group.name': 'Insira o nome do grupo',
    'error.empty.configuration': 'Selecione a configuração',
    'error.empty.configuration.name': 'Insira o nome da configuração',
    'error.empty.configuration.password': 'Insira a senha',
    'error.empty.configuration.contentApp': 'Nenhum conteúdo de aplicação especificado',
    'error.invalid.configuration.mainApp': 'Nas configurações do MDM, o aplicativo principal errado é usado',
    'error.invalid.configuration.contentApp': 'Aplicação de conteúdo inválido nas configurações do MDM',
    'error.mismatch.password': 'Senha e confirmação de senha devem corresponder',
    'error.empty.customer.name': 'Preencha o nome da organização',
    'error.empty.customer.prefix': 'Preencha o número do prefixo do dispositivo',
    'error.empty.customer.device.configuration': 'Selecione a configuração do dispositivo',
    'error.empty.customer.duplicate.prefix': 'Este prefixo já está em uso',
    'error.duplicate.customer.name': 'A organização com o nome digitado já existe. Tente um nome diferente.',
    'error.duplicate.group.name': 'O grupo que você digitou já existe. Tente um nome diferente',
    'error.duplicate.configuration.name': 'O nome de configuração que você digitou já existe. Tente um nome diferente.',
    'error.duplicate.device.number': 'Um dispositivo com esse número já existe',
    'error.internal.server': 'Erro interno do servidor',
    'error.permission.denied': 'Sem direitos de execução',
    'error.request.failure': 'Falha de solicitou',
    'error.configuration.device.use': 'Não é possível excluir essa configuração, ela está sendo usada em algum(ns) dispositivo(s). Primeiro vá para "Dispositivos", encontre o dispositivo usando esta configuração e altere sua configuração.',
    'error.invalid.system.update.time': 'Intervalo de instalação inválido',

    'error.configuration.file.empty.name': 'Insira um nome de arquivo',
    'error.configuration.file.empty.desc': 'Especifique uma descrição de arquivo',
    'error.configuration.file.empty.path': 'Especifique o caminho no dispositivo',
    'error.configuration.file.empty.file': 'Insira uma URL ou faça upload de um arquivo',
    
    'error.notfound.device': 'Dispositivo não encontrado',
    'error.duplicate.device': 'Um dispositivo com o mesmo número já existe',
    'error.duplicate.login': 'Esse login já está em uso',
    'error.duplicate.group': 'Um grupo com esse mesmo nome já existe',
    'error.duplicate.application': 'Já existe uma aplicação com esse ID de pacote e versão',
    'error.recent.application.version.exists': 'Existe uma versão mais recente da aplicação',
    'error.common.application.access.prohibited': 'O gerenciamento das aplicações comuns é permitido apenas pelo Super-Administrador',
    'error.application.config.reference.exists': 'A aplicação está sendo usada nas configurações e não pode ser excluída',
    'error.application.version.deletion.prohibited': 'A versão é única ou usada em configurações e não pode ser excluída',
    'error.duplicate.file': 'Um arquivo com o mesmo nome já existe',
    'error.used.file': 'Este arquivo está usado',
    'error.version.exists': 'A mesma versão deste app já existe',
    'error.duplicate.configuration': 'Uma configuração com este nome já existe',
    'error.notfound.customer.admin': 'Conta de administrador não encontrada',
    'error.apk.file.required': 'Selecione o arquivo com a extensão .apk ou .xapk',
    'error.apk.parse': 'Um erro ocorreu ao analisar o arquivo',
    'error.empty.app.name': 'Insira o nome da aplicação',
    'error.empty.app.pkg': 'Insira o ID do pacote',
    'error.empty.app.url': 'Insira a URL',
    'error.empty.app.iconText': 'Insira o texto do ícone',
    'error.empty.app.version': 'Insira a versão da aplicação',
    'error.notempty.group': 'Esse grupo inclui um ou mais dispositivos. Você não pode removê-lo.',
    'error.file.empty': 'Upload de um novo arquivo',
    'error.file.deletion': 'Erro ao excluir um arquivo do servidor',
    'error.file.save': 'Erro ao salvar o arquivo no servidor',
    'error.password.wrong': 'Senha inválida',
    'error.password.empty': 'Senha não especificado',
    'error.params.missing': 'Parâmetros ausentes:',
    'error.empty.push.options': 'Por favor, selecione as notificações de Push',

    'table.filtering.check.all': 'Selecionar Tudo',
    'table.filtering.uncheck.all': 'Cancelar Tudo',
    'table.filtering.suffix.configuration': 'Configurações',
    'table.filtering.suffix.group': 'Grupos',
    'table.filtering.no.selected.configuration': 'Nenhuma configuração selecionada',
    'table.filtering.no.selected.group': 'Nenhum grupo selecionado',

    'success.admin.created': 'Conta de administrador criada:\n ${adminCredentials}',
    'success.uploading.file': 'O arquivo está sendo enviado para o servidor ...',
    'success.loading.devices': 'Carregando a lista de dispositivos ...',
    'success.loading.customer': 'Carregando os detalhes do cliente ...',
    'success.file.uploaded': 'Arquivo carregado com sucesso.',
    'success.file.uploaded.need.save': 'Arquivo enviado com sucesso. Insira o caminho relativo e clique em "Salvar".',
    'success.settings.design.saved': 'Configurações de design salvas com sucesso',
    'success.settings.common.saved': 'Configurações de tabela de dispositivos salvas com sucesso',
    'success.settings.saved': 'Configurações salvas com sucesso',
    'success.settings.apiKey.saved': 'API key salva com sucesso',
    'success.settings.hints.enabled': 'Dicas habilitadas',
    'success.settings.hints.disabled': 'Dicas desabilitadas',
    'success.configuration.saved': 'Configuração salva com sucesso',
    'success.operation.completed': 'Operação completada com sucesso',
    'success.plugins.disabled': 'Configurações salvas com sucesso',
    'success.config.update.notification': 'O comando de atualização da configuração foi enviado aos dispositivos',
    'success.config.update.device.app.settings.notification': 'O comando para atualizar as configurações do aplicativo foi enviado ao dispositivo.',

    'form.icon.title': 'Ícone',
    'form.icon.name': 'Nome',
    'form.icon.file': 'Arquivo',

    'configuration.add.warning': 'Você tem certeza que quer criar uma configuração vazia? Você precisará adicionar todos os aplicativos de sistema necessários manualmente. Considere copiar e modificar uma configuração existente ao invés disso.',
    'configuration.remove.warning': 'Você tem certeza que quer remover a última configuração? Você perderá informações de quais aplicativos do sistema são necessários.',
    'form.configuration.title': 'Configuração',
    'form.configuration.title.typical': 'Configuração padrão',
    'form.configuration.settings.auto.update': 'Atualização automática',
    'form.configuration.settings.system.update': 'Atualização do sistema',
    'form.configuration.settings.system.update.default': 'Padrão',
    'form.configuration.settings.system.update.immediate': 'Imediatamente',
    'form.configuration.settings.system.update.scheduled': 'Agendado',
    'form.configuration.settings.system.update.postponed': 'Adiado',
    'form.configuration.settings.system.update.time': 'Hora de instalação',
    'form.configuration.settings.system.update.time.from': 'de:',
    'form.configuration.settings.system.update.time.to': 'a:',
    'form.configuration.settings.block.status.bar': 'Bloqueio da barra de status',
    'form.configuration.settings.block.status.bar.hint': 'Esta configuração está obsoleta e funciona no Android 6 e versões anteriores. Para bloquear a barra de status em versões mais recentes do Android, use o modo quiosque (configurações de MDM).',
    'form.configuration.settings.mdm.kiosk.mode': 'Modo Kiosk',
    'form.configuration.settings.mdm.app.main': 'Aplicação Principal',
    'form.configuration.settings.mdm.component.event.receiver': 'Componente - destinatário do evento',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Insira o nome do componente',
    'form.configuration.settings.mdm.component.wifi.ssid': 'WiFi SSID',
    'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'Insrição de WiFi SSID - deixe vazio para inserir manualmente',
    'form.configuration.settings.mdm.component.wifi.password': 'Senha do WiFi',
    'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Inscrição de WiFi pass - deixe vazio para inserir manualmente',
    'form.configuration.settings.mdm.component.wifi.security': 'Tipo de segurança do WiFi',
    'form.configuration.settings.mdm.component.wifi.notice': 'Aviso: algumas configurações de WiFi são aplicadas apenas à inscrição inicial!',
    'form.configuration.settings.mdm.component.server.url': 'Novo URL do servidor',
    'form.configuration.settings.mdm.component.server.url.placeholder': 'Usado para migração para um novo servidor de MDM',
    'form.configuration.settings.mdm.app.content': 'Aplicação de Conteúdo',
    'form.configuration.settings.mdm.kiosk.home': 'Habilitar botão Home',
    'form.configuration.settings.mdm.kiosk.recents': 'Habilitar botão Recentes',
    'form.configuration.settings.mdm.kiosk.notifications': 'Habilitar notificações',
    'form.configuration.settings.mdm.kiosk.system.info': 'Habilitar informações da barra de status',
    'form.configuration.settings.mdm.kiosk.keyguard': 'Habilitar bloqueio de tela',
    'form.configuration.settings.mdm.mobile.enrollment': 'Registre-se usando dados móveis',
    'form.configuration.settings.mdm.lock.safe.settings': 'Configurações de bloqueio de segurançå (WiFi, GPS, etc)',
    'form.configuration.settings.mdm.allowed.classes': 'Atividades permitidas',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'Classes separadas por vírgulas, por exemplo: com.android.settings.homepage.SettingsHomepageActivity',
    'form.configuration.settings.mdm.restrictions': 'Restrições',
    'form.configuration.settings.mdm.restrictions.placeholder': 'Restrições do MDM separadas por vírgula, por exemplo: no_sms,no_outgoing_calls,no_usb_file_transfer',
    'form.configuration.settings.mdm.qrcode.url': 'URL do QR code',
    'form.configuration.settings.mdm.hint': 'Selecione a aplicação principal e componente',
    'form.configuration.apps.search.label': 'Buscar por:',
    'form.configuration.apps.sort.label': 'Ordenar:',
    'form.configuration.apps.sort.byname': 'Por nome',
    'form.configuration.apps.sort.bypkg': 'Por ID',
    'form.configuration.apps.no.apk': 'Nenhum',
    'form.configuration.apps.show.systeam.apps': 'Mostrar Aplicações do Sistema',
    'form.configuration.apps.action.install': 'Instalar',
    'form.configuration.apps.action.prohibit': 'Bloquear',
    'form.configuration.apps.action.not.install': 'Não instalar',
    'form.configuration.apps.action.delete': 'Excluir',
    'form.configuration.apps.action.permit': 'Permitir',
    'form.configuration.apps.label.inherit': 'Herdado',
    'form.configuration.apps.label.show': 'Mostrar',
    'form.configuration.apps.label.not.show': 'Ocultar',
    'form.configuration.apps.edit.details': 'Parâmetros adicionais',
    'form.configuration.apps.keycode': 'Código chave',
    'form.configuration.apps.bottom': 'Exibir na linha abaixo',
    'form.configuration.apps.hint': 'Dica: para desvincular o aplicativo da configuração, selecione a ação "Bloquear" ou "Não instalar".',
    'form.configuration.settings.design.use.default': 'Use o design padrão',
    'form.configuration.settings.design.color.background': 'Cor de fundo',
    'form.configuration.settings.design.color.background.placeholder': 'Selecione uma cor',
    'form.configuration.settings.design.color.app.names': 'Cor dos nomes dos aplicativos',
    'form.configuration.settings.design.color.app.names.placeholder': 'Selecione uma cor',
    'form.configuration.settings.design.background.image.url': 'URL da imagem de fundo',
    'form.configuration.settings.design.background.image.url.placeholder': 'Insira a URL da imagem de fundo',
    'form.configuration.settings.design.icon': 'Tamanho do ícone',
    'form.configuration.settings.design.icon.small': 'Pequeno',
    'form.configuration.settings.design.icon.medium': 'Médio (+ 20%)',
    'form.configuration.settings.design.icon.large': 'Grande (+ 40%)',
    'form.configuration.settings.design.desktop.header': 'Título da área de Trabalho',
    'form.configuration.settings.design.desktop.header.no': 'Não',
    'form.configuration.settings.design.desktop.header.deviceid': 'ID do dispositivo',
    'form.configuration.settings.design.upload': 'Upload',
    'form.configuration.settings.common.name': 'Nome',
    'form.configuration.settings.common.name.placeholder': 'Insira o nome da configuração',
    'form.configuration.settings.common.desc': 'Descrição',
    'form.configuration.settings.common.desc.placeholder': 'Insira a descrição da configuração',
    'form.configuration.settings.common.admin.pwd': 'Senha de administrador',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Insira a senha do administrador',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Qualquer',
    'form.configuration.settings.common.gps.off': 'Desabilitado',
    'form.configuration.settings.common.gps.on': 'Habilitado',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Dados móveis',
    'form.configuration.settings.common.usb.storage': 'Bloquear armazenamento USB',
    'form.configuration.settings.common.brightness': 'Gerenciar brilho',
    'form.configuration.settings.common.brightness.none': 'Nenhum',
    'form.configuration.settings.common.brightness.auto': 'Automático',
    'form.configuration.settings.common.brightness.manual': 'Valor',
    'form.configuration.settings.common.brightness.value': 'Brilho da tela',
    'form.configuration.settings.common.timeout': 'Gerenciar tempo limite de tela',
    'form.configuration.settings.common.timeout.value': 'Tempo limite de tela',
    'form.configuration.settings.common.volume.block': 'Bloquear volume',
    'form.configuration.settings.common.volume.manage': 'Gerenciar volume',
    'form.configuration.settings.common.volume.value': 'Volume',
    'form.configuration.settings.common.timezone.mode': 'Gerenciar fuso horário',
    'form.configuration.settings.common.timezone.mode.default': 'Não gerenciar',
    'form.configuration.settings.common.timezone.mode.auto': 'Automático',
    'form.configuration.settings.common.timezone.mode.manual': 'Manual',
    'form.configuration.settings.common.timezone': 'Fuso horário',
    'form.configuration.settings.common.timezone.placeholder': 'por exemplo: America/Los_Angeles',
    'form.configuration.settings.common.timezone.link': 'Lista de fuso horários',
    'form.configuration.settings.common.no.network.warning': 'AVISO! Não desligue todos os canais de conexão, caso contrário você não será mais capaz de gerenciar mais os dispositivos!',
    'form.configuration.settings.request.updates': 'Atualizar localização',
    'form.configuration.settings.request.updates.donottrack': 'Não rastrear',
    'form.configuration.settings.request.updates.gps': 'Pelo GPS',
    'form.configuration.settings.request.updates.wifi': 'Por Wi-Fi',
    'form.configuration.settings.request.updates.prompt.gps': 'Para rastrear as coordenadas do GPS você precisa habilitar o GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'Para rastrear as coordenadas de Wi-Fi você precisa habilitar o Wi-Fi',
    'form.configuration.settings.push.options' : 'Notificações via Push',
    'form.configuration.settings.push.options.mqtt.worker' : 'Protocolo MQTT (economizar bateria)',
    'form.configuration.settings.push.options.mqtt.alarm' : 'Protocolo MQTT (entrega instantânea)',
    'form.configuration.settings.push.options.polling' : 'Sondagem HTTP',
    'form.configuration.settings.push.options.mqtt.worker.hint' : 'Envie mensagens instantaneamente quando o dispositivo estiver ativo. Mas as mensagens podem atrasar até algumas horas no modo de hibernação. Não use esta opção em dispositivos independentes. O MQTT usa a porta TCP 31000, habilite-o em seu firewall.',
    'form.configuration.settings.push.options.mqtt.alarm.hint' : 'Entrega mensagens via push instantaneamente, mas pode gastar mais energia quando um dispositivo está hibernando. Melhor opção para dispositivos autônomos alimentados. O MQTT usa a porta TCP 31000, habilite-o em seu firewall.',
    'form.configuration.settings.push.options.polling.hint' : 'Entrega confiável de mensagens via push com um atraso máximo de 15 minutos. Não requer nenhuma porta TCP diferente de HTTPS. Não use esta opção junto com o plugin de controle remoto.',
    'form.configuration.settings.push.options.keepalive' : 'Tempo Keep-Alive',
    'form.configuration.settings.minute.1' : '1 minuto',
    'form.configuration.settings.minutes.2' : '2 minutos',
    'form.configuration.settings.minutes.3' : '3 minutos',
    'form.configuration.settings.minutes.5' : '5 minutos',
    'form.configuration.settings.minutes.10' : '10 minutos',
    'form.configuration.settings.minutes.15' : '15 minutos',
    'form.configuration.settings.password.mode' : 'Requisitos de senha',
    'form.configuration.settings.password.mode.any' : 'Nenhum',
    'form.configuration.settings.password.mode.present' : 'Apresentar senha',
    'form.configuration.settings.password.mode.easy' : 'Fácil (ao menos 6 símbolos)',
    'form.configuration.settings.password.mode.moderate' : 'Moderado (mais de 8 letras e números)',
    'form.configuration.settings.password.mode.strong' : 'Forte (mais de 8, maiúsculas e minúsculas, números, símbolos)',
    'form.configuration.settings.show.wifi': 'Configurações de WiFi em erro de conexão',
    'form.configuration.settings.use.default.launcher': 'Use com o inicializador padrão',
    'form.configuration.settings.disable.screenshots': 'Desabilitar captura de tela',
    'form.configuration.settings.orientation': 'Bloquear orientação',
    'form.configuration.settings.orientation.none': 'Não bloquear',
    'form.configuration.settings.orientation.portrait': 'Retrato',
    'form.configuration.settings.orientation.landscape': 'Paisagem',
    'form.configuration.settings.files.default.path': 'Caminho padrão em um dispositivo',
    'form.configuration.files.search.label': 'Buscar:',
    'form.configuration.files.action.upload': 'Upload',
    'form.configuration.files.action.remove': 'Remover',
    'form.configuration.files.variables': 'Conteúdo variável',
    'form.configuration.files.variables.hint': 'Strings DEVICE_NUMBER, IMEI, CUSTOM* serão substituídos pelos seus valores',

    'form.configuration.file.name': 'Nome do arquivo',
    'form.configuration.file.description': 'Descrição do arquivo',
    'form.configuration.file.description.placeholder': 'Opcional, para sua conveniência',
    'form.configuration.file.path': 'Caminho no dispositivo',
    'form.configuration.file.path.placeholder': 'Excluindo caminho para um drive, por exemplo: /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'Se apenas um arquivos estiver hospedado no recurso externo',
    'form.configuration.file.file': 'Arquivo',
    'form.configuration.file.action': 'Ação',
    'form.configuration.file.action.prompt.1': 'Upload',
    'form.configuration.file.action.prompt.2': 'Remover',
    'form.configuration.file.remove.prompt.1': 'Este arquivo não será mais sincronizado com os dispositivos',
    'form.configuration.file.remove.prompt.2': 'Remover arquivos do servidor',

    'form.password.title': 'Alterar Senha',
    'form.password.label.user': 'Usuário',
    'form.password.label.password.new': 'Nova senha',
    'form.password.label.password.new.placeholder': 'Entre com uma nova senha',
    'form.password.label.password.confirm': 'Confirmar',
    'form.password.label.password.confirm.placeholder': 'Entre com a senha novamente',

    'form.application.type': 'Tipo',
    'form.application.type.option.web': 'Web-page',
    'form.application.type.option.app': 'Aplicativo',
    'form.application.pkg': 'ID do pacote',
    'form.application.from.file': 'determinado a partir do arquivo',
    'form.application.pkg.title': 'ID do pacote é automaticamente determinado quando você faz upload do arquivo APK. A ID do pacote inserida manulamente é necessária apenas para aplicativos do sistema.',
    'form.application.pkg.placeholder': 'Por exemplo: com.android.camera',
    'form.application.disabled.arch': 'Versão específica',
    'form.application.disabled.arch.title': 'Para adicionar APKs para diferente arquiteturas de CPU, clique em "Adicionar" ou abra a lista de versões do aplicativo',
    'form.application.arch': 'Código nativo',
    'form.application.arch.title': 'Alguns aplicativos contém código otimizados para determinadas arquiteturas de CPU. Neste caso, você precisa fazer upload de duas APKs (para arquitetura armeabi-v7a e arm64-v8a)',
    'form.application.arch.universal': 'Nenhum (APK universal)',
    'form.application.arch.armeabi': 'Código nativo para armeabi-v7a',
    'form.application.arch.arm64': 'Código nativo para arm64-v8a',
    'form.application.arch.no.split': 'Universal APK',
    'form.application.arch.split': 'APK de divisão',
    'form.application.arch.warning': 'Esta APK é apenas para ${arch}. Não esqueça de fazer upload da APK para outra arquitetura de CPU!',
    'form.application.arch.success': 'Este aplicativo contém APKs para ambas arquiteturas de CPU',
    'form.application.version.exists': 'O APK para esta versão já existe',
    'form.application.url.armeabi': 'URL para armeabi-v7a',
    'form.application.url.arm64': 'URL para arm64-v8a',
    'form.application.name': 'Nome da Aplicação',
    'form.application.name.title': 'Você verá o nome do aplicativo na lista. Nós recomendamos usar nomes únicos e informativos.',
    'form.application.name.placeholder': 'Por exemplo: Câmera (Android)',
    'form.application.version': 'Versão',
    'form.application.version.placeholder': '0 para aplicativos do sistema',
    'form.application.version.title': 'Package version is automatically determined when you upload the APK file. Set it to 0 for system apps.',
    'form.application.system': 'System',
    'form.application.system.title': 'Os aplicativos do sistema são pré-instaladas em um disposito e não requerem URL ou arquivo. Marque essa opção apenas se precisar habilitar um determinado pacote de sistema.',
    'form.application.run.after.install': 'Rodar após instalação',
    'form.application.run.after.install.title': 'Aplicações com serviços de segundo plano precisam ser iniciados em primeiro plano ao menos uma vez.',
    'form.application.run.at.boot': 'Executar na inicialização',
    'form.application.run.at.boot.title': 'Defina este sinalizador se precisar executar o aplicativo em primeiro plano após a inicialização. Este sinalizador não está afetando os processos em segundo plano.',
    'form.application.url': 'URL',
    'form.application.url.title': 'A URL deve ser digitado apenas se o seu aplicativo está hospedado em um recurso externo. Recomenda-se fazer upload de um arquivo APK usando um campo abaixo.',
    'form.application.url.disabled': 'URL é configurada para cada versão. Para alterar a URL, feche esta janela e clique no ícone "Versões".',
    'form.application.file': 'Arquivo',
    'form.application.showLabel': 'Mostrar Ícone',
    'form.application.showLabel.title': 'Este sinalizador indica se o ícone do aplicativo deve ser exibido no inicializador. Esta opção pode ser substituída na configuração.',
    'form.application.use.kiosk': 'Abrir no Kiosk Browser',
    'form.application.use.kiosk.title': 'Defina este sinalizador se desejar abrir uma página da web no Kiosk Browser sem qualquer possibilidade de alterar o endereço',
    'form.application.iconText': 'Texto do ícone',
    'form.application.iconText.placeholder': '(padrão)',
    'form.application.versions.title': 'Versões da aplicação',
    'form.application.icon': 'Ícone',
    'form.application.icon.default': '(padrão)',
    'form.application.icon.add': 'Adicionar ícone',

    'form.application.setting.app': 'Aplicativo',
    'form.application.setting.app.placeholder': 'Selecione uma aplicação',
    'form.application.setting.name': 'Atributo',
    'form.application.setting.value': 'Valor',
    'form.application.setting.comment': 'Comente',
    'form.application.setting.type': 'Tipo',
    'form.application.setting.readonly': 'Não muda no dispositivo',
    
    'form.application.configurations.app': 'Aplicativo',
    'form.application.configurations.configs': 'Configurações',

    'form.configuration.copy.new.name': 'Novo nome',
    'form.configuration.copy.new.name.placeholder': 'Insira o novo nome da configuração',

    'form.customer.name': 'Nome',
    'form.customer.name.placeholder': 'Insira o nome da organização',
    'form.customer.apiKey': 'Chave de API',
    'form.customer.apiKey.placeholder': 'Insria a chave de API',
    'form.customer.prefix': 'Prefixo',
    'form.customer.prefix.placeholder': 'Insira o prefixo do número do dispositivo',
    'form.customer.device.configuration': 'Configuração do dispositvo',
    'form.customer.desc': 'Descrição',
    'form.customer.desc.placeholder': 'Insira uma descrição da organização',
    'form.customer.copy.configuration': 'Copiar configurações',
    'form.customer.copy.design': 'Copiar design',
    'form.customer.type': 'Tipo de cliente',
    'form.customer.status': 'Status do cliente',
    'form.customer.expiry.time': 'Data de validade',
    'form.customer.device.limit': 'Dispositivo limite',

    'form.device.number': 'Número',
    'form.device.number.locked': 'Não é possível alterar o número, porque a alteração do número anterior não foi concluída.',
    'form.device.migration.warning': 'O número do dispositivo será alterado. Tenha certeza que o dispositivo está ligado e online.',
    'form.device.number.hint': 'Não use caracteres especiais',
    'form.device.desc': 'Descrição',
    'form.device.groups': 'Grupos',
    'form.device.config': 'Configuração',
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Número do telefone',

    'form.update.device.config': 'Configuração',

    'form.file.file': 'Arquivo',
    'form.file.path': 'Caminho',
    'form.file.path.placeholder': 'Insira um caminho relativo, por exemplo "/ arquivos /"',

    'form.file.apps.name': 'Nome da Aplicação',
    'form.file.apps.pkg': 'ID do pacote',
    'form.file.apps.version': 'Versão',

    'form.group.name': 'Nome',
    'form.group.name.placeholder': 'Insira o nome do grupo',

    'form.user.login': 'Login',
    'form.user.login.placeholder': 'Insira o login do usuário',
    'form.user.name': 'Nome',
    'form.user.name.placeholder': 'Entre com seu nome de usuário',
    'form.user.role': 'Função',
    'form.user.all.devices.available': 'Todos dispositivos estão disponíveis',
    'form.user.available.groups': 'Grupos de dispositivos disponíveis',
    'form.user.password.new': 'Nova senha',
    'form.user.password': 'Senha',
    'form.user.password.new.placeholder': 'Entre com uma nova senha',
    'form.user.password.confirm': 'Confirmar',
    'form.user.password.confirm.placeholder': 'Entre com a senha novamente',

    'form.settings.hints.title': 'Dicas',

    'form.settings.plugins.title': 'Plugins usados',

    'form.settings.common.title': 'Visualização da tabela de dispositivos',
    'form.settings.common.visible.columns': 'Colunas visíveis na tabela de "Dispositivos"',
    'form.settings.common.status': 'Status',
    'form.settings.common.role': 'Função do usuário',
    'form.settings.common.date': 'Data',
    'form.settings.common.device.number': 'Número do dispositivo',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Número do telefone',
    'form.settings.common.phone.model': 'Modelo do telefone',
    'form.settings.common.status.permissions': 'Status de permissão',
    'form.settings.common.status.installation': 'Status de instalação',
    'form.settings.common.status.files': 'Status dos arquivos',
    'form.settings.common.config': 'Configuração',
    'form.settings.common.desc': 'Descrição',
    'form.settings.common.group': 'Grupo',
    'form.settings.common.launcher.version': 'Versão do lançador',
    'form.settings.common.battery.level': 'Nível da bateria',
    'form.settings.common.default.launcher': 'Lançador padrão',

    'form.settings.design.title': 'Design padrão',
    'form.settings.design.color.font': 'Cor de fundo',
    'form.settings.design.color.font.placeholder': 'Selecione uma cor',
    'form.settings.design.color.app.names': 'Cor dos nomes dos aplicativos',
    'form.settings.design.color.app.names.placeholder': 'Selecione uma cor',
    'form.settings.design.url.background.image': 'URL da imagem de fundo',
    'form.settings.design.url.background.image.placeholder': 'Insira a URL da imagem de fundo',
    'form.settings.design.size.icon': 'Tamanho do ícone',
    'form.settings.design.size.icon.small': 'Pequeno',
    'form.settings.design.size.icon.medium': 'Médio (+ 20%)',
    'form.settings.design.size.icon.large': 'Grande (+ 40%)',
    'form.settings.design.desktop.header': 'Título da área de Trabalho',
    'form.settings.design.desktop.header.no': 'Não',
    'form.settings.design.desktop.header.device.id': 'ID do dispositivo',

    'form.settings.lang.title': 'Configurações de idioma',
    'form.settings.lang.use.default': 'Utilizar idioma padrão',
    'form.settings.lang.use': 'Selecione um idioma',
    'form.settings.lang.en': 'English',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',

    'form.settings.misc.title': 'Configurações diversas',
    'form.settings.misc.phone.format': 'Formato de número de telefone',
    'form.settings.misc.phone.format.placeholder': '+9 (999) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'Propriedade personalizada #1',
    'form.settings.misc.custom.property.name.2': 'Propriedade personalizada #2',
    'form.settings.misc.custom.property.name.3': 'Propriedade personalizada #3',
    'form.settings.misc.custom.property.multiline': 'Multilinha',
    'form.settings.misc.custom.property.send': 'Enviar para o dispositivo',
    'form.settings.misc.custom.property.name.placeholder': 'Insira o nome de uma propriedade personalizada',
    'form.settings.misc.create.new.devices': 'Adicionar dispositivo no primeiro acesso',
    'form.settings.misc.new.device.config': 'Nova configuração de dispositivos',
    'form.settings.misc.new.device.group': 'Novo grupo de dispositivos',

    'form.settings.groups.title': 'Grupos',
    'form.settings.groups.search.placeholder': 'Pesquisar Grupo',

    'form.settings.users.title': 'Usuários',
    'form.settings.users.search.placeholder': 'Pesquisar usuário',

    'form.qr.device.number': 'Número do dispositivo',
    'form.qr.auto.create': 'Adicionar a lista de dispositivos se não existir',
    'form.qr.number.use': 'Atribuição de número de dispositivo',
    'form.qr.number.use.request': 'Valor do usuário',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'Número de série',
    'form.qr.groups': 'Adicionar aos grupos',
    'form.qr.button.json': 'Get JSON',
    'form.qr.device.number.placeholder': 'Insira o ID do dispositivo ...',
    'form.qr.code.image.alt': 'QR code',

    'form.profile.title': 'Alterar Senha',
    'form.profile.password.old': 'Senha antiga',
    'form.profile.password.old.placeholder': 'Insira a senha antiga',
    'form.profile.password.new': 'Nova senha',
    'form.profile.password.new.placeholder': 'Entre com uma nova senha',
    'form.profile.password.confirm': 'Confirmar',
    'form.profile.password.confirm.placeholder': 'Entre com a senha novamente',

    'tab.customers': 'Organizações',
    'tab.common.applications': 'Aplicações compartilhadas',

    'tab.devices': 'Dispositivos',
    'tab.applications': 'Aplicativos',
    'tab.configurations': 'Configurações',
    'tab.files': 'Arquivos',
    'tab.default.design': 'Design padrão',
    'tab.common.settings': 'Visualização da tabela de dispositivos',
    'tab.users': 'Usuários',
    'tab.groups': 'Grupos',
    'tab.language': 'Idioma e outras configurações',
    'tab.license': 'Licença',
    'tab.hints': 'Dicas',
    'tab.plugins': 'Plugins',
    
    'tab.configeditor.common.settings': 'Configurações padrão',
    'tab.configeditor.design.settings': 'Configurações de Design',
    'tab.configeditor.applications': 'Aplicativos',
    'tab.configeditor.mdm.settings': 'Configurações de MDM',
    'tab.configeditor.app.settings': 'Configurações de aplicações',
    'tab.configeditor.files': 'Arquivos',

    'search.placeholder.file': 'Pesquise por arquivo',
    'search.placeholder.configuration': 'Pesquise por configuração',
    'search.placeholder.customer': 'Pesquise por uma organização',
    'search.placeholder.application': 'Pesquise por uma aplicação',
    'search.placeholder.application.setting': 'Pesquise uma configuração de aplicativo',
    'search.placeholder.device': 'Pesquisa por um dispositivo',
    'search.placeholder.address': 'Pesquisa de endereço',
    'search.placeholder.point': 'Pesquisa de site',
    'search.placeholder.message': 'Pesquisa de mensagem',
    'search.placeholder': 'Buscar ...',
    'search.placeholder.from': 'De ...',
    'search.placeholder.to': 'Para ...',
    'search.placeholder.user': 'Insira o nome do usuário',

    'table.heading.customer.name': 'Nome',
    'table.heading.customer.desc': 'Descrição',
    'table.heading.customer.registration.time': 'Registrado',
    'table.heading.customer.last.login.time': 'Último login',
    'table.heading.customer.actions': 'Ações',
    'table.heading.customer.type': 'Tipo',
    'table.heading.customer.expiry.time': 'Expiração',
    'table.heading.customer.device.limit': 'Limite',
    'table.heading.customer.status': 'Status',

    'customer.new': 'Novo',
    'customer.active': 'Ativo',
    'customer.need.followup': 'Necessita acompanhamento',
    'customer.followup.sent': 'Acompanhamento enviado',
    'customer.internal.test': 'Teste interno',
    'customer.developer': 'Desenvolvedor',
    'customer.difficult': 'Dificuldade',
    'customer.pause': 'Pausa',
    'customer.denial': 'Negação',
    'customer.client': 'Cliente',

    'table.heading.configuration.name': 'Nome',
    'table.heading.configuration.desc': 'Descrição',
    'table.heading.configuration.actions': 'Ações',

    'table.heading.application.setting.app.pkg': 'ID do pacote',
    'table.heading.application.setting.app.name': 'Nome da Aplicação',
    'table.heading.application.setting.name': 'Atributo',
    'table.heading.application.setting.value': 'Valor',
    'table.heading.application.setting.comment': 'Comentário',
    'table.heading.application.setting.lastUpdate': 'Data de criação',

    'table.heading.file.url': 'URL',
    'table.heading.file.devicepath': 'Caminho no dispositivo',
    'table.heading.file.description': 'Descrição do arquivo',
    'table.heading.file.action': 'Ação',
    'table.heading.file.lastUpdate': 'Data de criação',
    
    'table.heading.application.pkg': 'ID do pacote',
    'table.heading.application.name': 'Nome da Aplicação',
    'table.heading.application.version': 'Versão',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Ícone',
    'table.heading.application.actions': 'Ações',
    'table.heading.application.order': 'Order',

    'table.heading.device.status': 'Status',
    'table.heading.device.date': 'Data',
    'table.heading.device.device.number': 'Número do dispositivo',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Número do telefone',
    'table.heading.device.phone.model': 'Modelo do telefone',
    'table.heading.device.status.permissions': 'Status de permissão',
    'table.heading.device.status.installation': 'Status de instalação',
    'table.heading.device.status.files': 'Status dos arquivos',
    'table.heading.device.configuration': 'Configuração',
    'table.heading.device.desc': 'Descrição',
    'table.heading.device.group': 'Grupo',
    'table.heading.device.launcher.version': 'Versão do lançador',
    'table.heading.device.battery.level': 'Nível de bateria',
    'table.heading.device.default.launcher': 'Definir como padrão',
    'table.heading.device.actions': 'Ações',

    'table.heading.group.name': 'Nome',
    'table.heading.group.actions': 'Ações',

    'table.heading.file.name': 'Nome do arquivo',
    'table.heading.file.path': 'Caminho',
    'table.heading.file.address': 'Endereço',
    'table.heading.file.actions': 'Ações',

    'table.heading.users.login': 'Login',
    'table.heading.users.name': 'Nome',
    'table.heading.users.role': 'Funções',
    'table.heading.users.actions': 'Ações',

    'table.heading.common.apps.customer': 'Organização',
    'table.heading.common.apps.pkg': 'ID do Pacote',
    'table.heading.common.apps.name': 'Nome da Aplicação',
    'table.heading.common.apps.version': 'Verão',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Ícone',
    'table.heading.common.apps.actions': 'Ações',

    'notfound.devices': 'Não há dispositivos para mostrar.',
    'notfound.files':' A lista de arquivos está vazia.',
    'notfound.configurations': 'Nenhuma configuração foi encontrada.',
    'notfound.customers': 'Organizações não encontradas.',
    'notfound.common.apps': 'Não há aplicações para mostrar.',
    'notfound.applications': 'Aplicações não encontradas',
    'notfound.groups':' Grupos não encontrados. Tente uma consulta diferente.',
    'notfound.users':' Usuários não encontrados. Tente uma consulta diferente.',
    'notfound.apps.for.display': 'Não há aplicações para mostrar.',
    'notfound.app.versions.for.display': 'Não há versões para mostrar.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    'menu.about': 'Sobre',
    'menu.profile': 'Perfil',
    'menu.panel.master': 'Painel Master',
    'menu.panel.main': 'Painel principal',
    'menu.logout': 'Deslogar',
    'menu.functions': 'Funções',
    'menu.settings': 'Configurações',
    'menu.show.hints': 'Mostrar dicas',

    'plugin.name.not.specified': '<< O nome da função não foi especificado >>',

    'breadcrumb.devices': 'Dispositivos',
    'breadcrumb.applications': 'Aplicativos',
    'breadcrumb.configurations': 'Configurações',
    'breadcrumb.files': 'Arquivos',
    'breadcrumb.default.design': 'Design por padrão',
    'breadcrumb.common.settings': 'Visualização da tabela de dispositivos',
    'breadcrumb.language.settings': 'Idioma e outras configurações',
    'breadcrumb.license.settings': 'Licença',
    'breadcrumb.users': 'Usuários',
    'breadcrumb.groups': 'Grupos',
    'breadcrumb.hints': 'Dicas',
    'breadcrumb.plugins': 'Plugins',
    'breadcrumb.config.details': 'Detalhes',
    'breadcrumb.application.versions': 'Versões',

    'app.name': 'Headwind MDM',
    'app.vendor.name':"h-mdm.com",
    'app.vendor.link':"https://h-mdm.com",
    'app.description': 'é o sistema de gerenciamento de dispositivos móveis de código aberto',
    'app.title': 'Painel Web ${appName}',

    'box.show.my.apps.only': 'Mostrar apenas minhas aplicações',
    'configuration.app.version.upgrade.message': 'Versão instalada ${installedVersion}, versão disponível ${latestVersion}',

    'about.line.1': 'Painel de controle ${appName}',
    'about.line.2': 'Iniciador empresarial para Android',
    'about.line.3': 'Versão ${versionNumber}',
    'about.line.4': 'Plugins Instalador',

    'common.app.clarification': 'Essa aplicação é pública e não está disponível para edição. Para adicionar outra versão deste app, por favor, entre em contato com o administrador.',

    'qrcode.help.line1': 'Para configurar o dispositivo Android (verão 7 ou posterior) em um modo gerenciado (corporativo):',
    'qrcode.help.line2': 'Redefina o dispositivo para as configurações de fábrica',
    'qrcode.help.line3': 'Toque 7 vezes em qualquer lugar da tela inicial (você deve entrar em modo oculto de leitura de QR code)',
    'qrcode.help.line4': 'Siga as instruções do dispositivo: aceite os termos, conecte-se ao Wi-Fi, escaneie este QR code',
    'qrcode.help.line5': 'O QR code talvez contenha o ID do dispositivo para ${appName} (então você não precisa inserí-lo em um dispositivo mobile). Para incorporar o ID do dispositivo ao QR code, insira o ID do dispositivo nesta tela e clique "Renovar".',

    'form.configuration.app.version.select.select.title': 'Selecione a versão para instalar',
    'form.configuration.app.version.select.version.check.off': 'Desabilitar verificação de versão',
    'form.configuration.app.version.select.upgrade.warning': 'Atualizar aplicativo "${v1}" para versão "${v3}" para configuração "${v2}"?',
    'form.configuration.app.version.select.downgrade.warning': 'Downgrade de versão DELETA TODAS AS APLICAÇÕES em todos os dispositivos! Fazer downgrade da aplicação da versão "${v1}" para a versão "${v2}"? ',

    'hint.step.1': 'Clique aqui para iniciar o a inscrição do dispositivo',
    'hint.step.2': 'Clique aqui para abrir o QR code',
    'hint.step.3': 'Clique aqui para ver como abrir o  QR code scanner no dispositivo',
    'hint.step.4': 'Encontre um ID de dispositivo disponível na aba Dispositivos». Clique em «Renovar» para incluir  no QR code.',

    'ie.browser.notice.1': 'Infelizmente, o Internet Explorer não é compatível.',
    'ie.browser.notice.2': 'Browser recomendado para o ${appName} - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a>.',

    'form.resolved.duplicate.pkg.text1': 'O ID "${pkg}" do pacote já é usado pelos aplicativos listados abaixo.',
    'form.resolved.duplicate.pkg.text2': 'Você deseja adicionar uma nova aplicação ou uma nova versão de uma aplicação existente?',
    'form.resolved.duplicate.pkg.text3': 'Nova versão para',
    'form.resolved.duplicate.pkg.text4': 'O ID "${pkg}" do pacote já é usado pelos aplicativos ${apps}',
    'form.resolved.duplicate.pkg.text5': 'Você tem certeza que deseja alterar o ID do pacote?',

    'tooltip.usage.byconfigurations': 'Usado por configurações',
    'tooltip.usage.byapps': 'Usado por aplicações',
    'tooltip.usage.byicons': 'Usado por ícones',

    'form.devices.label.params.more': 'Mais parâmetros',
    'form.devices.label.params.less': 'Menos parâmetros',
    'form.devices.label.installation.status': 'Status de instalação',
    "format.devices.date.createTime": "dd/MM/yyyy HH:mm:ss",
    "format.devices.date.datePicker": "dd-MM-yyyy",

    'form.devices.selection.install.status.default': 'Status da instalação ...',
    'form.devices.selection.install.status.all': 'Tudo',
    'form.devices.selection.install.status.success': 'Sucesso',
    'form.devices.selection.install.status.version.mismatch': 'Incompatibilidade de versão',
    'form.devices.selection.install.status.failure': 'Falha',
    'form.devices.selection.imei.changed': 'IMEI alterado recentemente',

    'search.placeholder.launcher.version': 'Versão do lançador',
    'error.date.range.invalid': 'Intervalo de data inválido',

    'customer.type.demo': 'Demonstração',
    'customer.type.small': 'Profissional',
    'customer.type.corporate': 'Empresarial',
    'customer.type.master': 'Primário',

    'customer.type.options.all': 'Todos os tipos',
    'customer.status.options.all': 'Todos os status',

    'account.expiring': 'Sua conta irá expirar em ${days} dias. Por favor, contate o vendedor para renovar sua conta.',
    'account.expired.short': 'Sua conta expirou!',
    'account.expired': 'Sua conta expirou. Por favor, contate o vendedor para renovar sua conta.',
    'device.limit.achieved': 'Não é possível adicionar um dispositivo, por quel você atingiu seu limite. Por favor, remova algum dispositivo ou contate o vendedor para extender seu limite de dispositivos.',

    'yes': 'sim',
    'no': 'não'
};
