if (! document.localization) document.localization = [];

document.localization ['tr_TR'] = {
	'login.username': 'Kullanıcı adı veya e-posta',
	'login.username.placeholder': 'Kullanıcı adınızı veya e-postanızı girin',
	'login.password': 'Şifre:',
	'login.password.placeholder': 'Şifre girin',
	'login.submit': 'Giriş yap',
	'login.password.incorrect': 'Geçersiz kullanıcı adı veya şifre',
	'login.password.recovery': 'Şifrenizi mi unuttunuz?',
	'recovery.password': 'Şifreyi kurtar',
	'recovery.password.success': 'Şifre kurtarma talimatları e-postanıza gönderildi',
	'login.no.account': 'Hesabınız yok mu?',
	'login.signup': 'Kaydol',

	'signup.title': 'Başlayın',
	'signup.email': 'E-posta adresiniz',
	'signup.email.placeholder': 'Geçerli bir e-posta adresi girin',
	'signup.email.invalid': 'Geçerli bir e-posta adresi girin',
	'signup.terms.agree': 'Kabul ediyorum',
	'signup.terms.terms': 'Şartlar ve koşullar',
	'signup.submit': 'Kaydolun',
	'signup.progress': 'Kaydolunuyor...',
	'signup.email.used': 'Bu e-postaya sahip bir müşteri zaten kayıtlı',
	'signup.name.used': 'Bu kullanıcı adına sahip bir müşteri zaten kayıtlı',
	'signup.complete': 'Kaydolduğunuz için teşekkür ederiz!',
	'signup.email.check': 'Lütfen e-postanızı kontrol edin ve tamamlamak için bağlantıyı takip edin kayıt!',
	'signup.complete.title': '${appName} hesabınız neredeyse hazır!',
	'signup.ready.title': '${appName} hesabınız hazır!',
	'signup.customer.id': 'Kullanıcı adı',
	'signup.customer.id.placeholder': 'Yalnızca harf ve rakam kullanın',
	'signup.customer.id.invalid': 'Lütfen yalnızca 6 veya daha fazla karakter, harf ve rakam kullanın',
	'signup.first.name': 'Ad',
	'signup.first.name.placeholder': 'Adınız (zorunlu)',
	'signup.last.name': 'Soyadı',
	'signup.last.name.placeholder': 'Soyadınız (zorunlu)',
	'signup.company': 'Şirket adı',
	'signup.company.placeholder': 'İşletmenizin adı (isteğe bağlı)',
	'signup.description': 'MDM\'yi nasıl kullanacaksınız?',
	'signup.description.placeholder': 'Bu, ekibimizin size yardımcı olmasına yardımcı olacaktır',
	'signup.password': 'Şifre',
	'signup.password.repeat': 'Şifreyi tekrarlayın',
	'signup.password.placeholder': '6+ karakter',
	'signup.password.short': 'Lütfen en az 6 karakter girin',
	'signup.password.not.match': 'Şifreler match',
	'signup.finalized.title': 'Hesabınız hazır!',
	'signup.finalized.description': 'Kısa bir süre içinde, yararlı talimatlar içeren e-postayı almalısınız. Lütfen bu e-postayı inceleyin ve kullanıcı adınız ve şifrenizle web paneline giriş yapın.',
	'signup.token.invalid.title': 'Jeton geçersiz veya zaten kullanılmış',
	'signup.token.invalid.description': 'Lütfen yeni bir hesap oluşturmak için kaydolmayı tekrar deneyin!',

	'header.label.username': 'Kullanıcı adı',

	'summary.devices.status': 'Cihaz durumu',
	'summary.devices.active': 'Aktif',
	'summary.devices.idle': 'Boşta',
	'summary.devices.offline': 'Çevrimdışı',
	'summary.devices.enrollment': 'Kayıt özeti',
	'summary.devices.enrolled.total': 'Toplam kayıtlı',
	'summary.devices.enrolled.earlier': 'Daha erken kaydoldu',
	'summary.devices.enrolled.monthly': 'Son 30 gün',
	'summary.devices.installation.status': 'Uygulama durumu',
	'summary.devices.installation.completed': 'Tamamlandı',
	'summary.devices.version.mismatch': 'Sürüm uyumsuzluğu',
	'summary.devices.installation.failed': 'Yükleme başarısız oldu',
	'summary.devices.enrolled.lastyear': 'Son 12 ay',

	'devices.group.options.all': 'Tüm gruplar',
	'devices.configuration.options.all': 'Tüm yapılandırmalar',
	'devices.permissions.all': 'Tüm izinler verildi',
	'devices.permissions.not.as.device.admin': '- Uygulama bir cihaz yöneticisi olarak yüklenmedi',
	'devices.permissions.window.overlap.prohibited': '- Diğer pencerelerin üzerine bindirme yapılamıyor',
	'devices.permissions.history.access.prohibited': '- Kullanım geçmişine erişim yapılandırılmadı',
	'devices.unknown': 'Bilinmiyor',
	'devices.model.unknown': 'Bilinmiyor',
	'devices.date.unknown': 'bilinmiyor',
	'devices.date.format': 'dd/MM/yy HH:mm',
	'devices.app.installed': '- ${applicationName}: Yüklendi.',
	'devices.app.not.installed': '- ${applicationName}: Yüklenmedi.',
	'devices.app.version.available': ', kullanılabilir ${applicationVersion}',
	'devices.app.installed.and.version.available': '- ${applicationName}: yüklendi ${applicationInstalledVersion}, kullanılabilir ${applicationVersionAvailable}',
	'devices.app.needs.removal': '${applicationVersion}, kaldırma gerekli',
	'devices.no.data': 'Cihaz veri iletmedi',
	'devices.settings.conformance.broken': 'Ayarlarla uyumsuzluk: (${serverData})',
	'devices.file.installed': '- ${file}: kuruldu',
	'devices.file.not.installed': '- ${file}: kurulmadı.',
	'devices.file.lastUpdate.differs': '- ${file}: değişiklik süresinde fark ${diff} dakika',

	'button.apply': 'Uygula',
	'button.gps.on': 'GPS\'i Etkinleştir',
	'button.wifi.on': 'Wi-Fi\'yi Etkinleştir',
	'button.notify.update': 'Güncellemede bildir',
	'button.app.settings': 'Uygulama ayarları',
	'button.ok': 'Tamam',
	'button.help': 'Yardım',
	'button.new.app': 'Yeni uygulama',
	'button.new.app.version': 'Yeni sürüm',
	'button.upgrade': 'Yükseltme',
	'button.renew.config': 'Cihazlarda güncelleme',
	'button.common': 'Ortak uygulama',
	'button.close': 'Kapat',
	'button.yes': 'Evet',
	'button.cancel': 'İptal',
	'button.save': 'Kaydet',
	'button.save.and.close': 'Kaydet ve kapat',
	'button.more': 'Daha fazla ...',
	'button.cleanup': 'Temizle',
	'button.add': 'Ekle',
	'button.add.icon': 'Yeni Simge',
	'button.search': 'Ara',
	'button.export': 'Dışa Aktar',
	'button.change': 'Düzenle',
	'button.copy': 'Kopyala',
	'button.qrcode': 'QR kodu',
	'button.application': 'Uygulama',
	'button.change.password': 'Şifreyi değiştir',
	'button.set.configuration': 'Yapılandırmayı ayarla',
	'button.set.group': 'Grubu ayarla',
	'button.group.action': 'Grup eylemi',
	'button.delete': 'Sil',
	'button.login': 'Giriş yap',
	'button.renew.code': 'Yenile',
	'button.configurations': 'Yapılandırmalar',
	'button.set.configurations': 'Yapılandırmaları Belirle',
	'button.edit.versions': 'Sürümler',
	'button.edit': 'Düzenle',
	'button.change.common.app': 'Paylaşılan Uygulamayı Düzenle',
	'button.delete.common.app': 'Paylaşılan Uygulamayı Sil',
	'button.turn.common.app': 'Ortak Yap',
	'button.hints.enable': 'Araç ipuçlarını göster',
	'button.hints.disable': 'Araç ipuçlarını gizle',
	'button.show.password': 'Şifreyi göster',
	'button.hide.password': 'Şifreyi gizle',

	'question.impersonate.user': 'Uygulamaya "${customerName}" kuruluşunun yöneticisi olarak giriş yapılsın mı?',
	'question.change.user': 'Uygulamaya "${userName}" kullanıcısı olarak giriş yapılsın mı?',
	'question.delete.file': '"${fileName}" dosyası silinsin mi?',
	'question.delete.customer': '"${customerName}" kuruluşu silinsin mi?',
	'question.delete.user': '"${username}" kullanıcısı silinsin mi?',
	'question.delete.application': '"${applicationName}" uygulaması silinsin mi?',
	'question.delete.application.version': '"${applicationVersion}" sürümü silinsin mi?',
	'question.delete.configuration': 'Yapılandırma silinsin mi? "${configurationName}"?',
	'question.delete.group': '"${groupName}" grubu silinsin mi?',
	'question.delete.role': '"${roleName}" rolü silinsin mi?',
    'question.delete.icon': '"${iconName}" simgesi silinsin mi?',
	'question.delete.device.bulk': 'Seçili cihazlar silinsin mi?',
	'question.delete.device': '"${deviceNumber}" numaralı cihaz silinsin mi?',
	'question.exit.without.saving': 'Değişiklikler kaydedilmedi. Neyse bu sayfadan ayrılalım mı?',
	'question.turn2common.application': '"${applicationName}" uygulamasını paylaşalım mı?',
	'question.app.upgrade': '"${v1}" uygulamasını "${v2}" yapılandırması için en son sürüme güncelleyelim mi?',

	'error.application.setting.empty.app': 'Uygulamayı belirt',
	'error.application.setting.empty.name': 'Bir ad girin',
	'error.application.setting.empty.value': 'Bir değer belirtin',

	'error.icon.dimension.invalid': 'Simge kare olmalı',
	'error.icon.empty.name': 'Simgenin adını girin',
	'error.icon.empty.file': 'Simge dosyasını yükle',
	'error.application.version.pkg.mismatch': 'Dosyanın paket kimliği (${actual}) uygulamaya (${expected}) uymuyor',
	'error.empty.user': 'Bir kullanıcı seçin',
	'error.empty.user.name': 'Kullanıcı adını girin',
	'error.empty.user.login': 'Kullanıcı oturum açma bilgilerini girin',
	'error.empty.user.role': 'Bir kullanıcı rolü seçin',
	'error.empty.password': 'Yeni parola girin',
	'error.empty.password.confirm': 'Parola onayını girin',
	'error.user.not.found': 'Kullanıcı bulunamadı',
	'error.email.not.configured': 'E-posta yapılandırılmadı',
	'error.email.not.found': 'Kullanıcı e-postası ayarlanmadı',
	'error.empty.group.name': 'Grup adını girin',
	'error.empty.configuration': 'Yapılandırmayı belirtin',
	'error.empty.configuration.name': 'Yapılandırma adını girin',
	'error.empty.configuration.password': 'Şifreyi girin',
	'error.empty.configuration.contentApp': 'İçerik uygulaması belirtilmedi',
	'error.empty.group': 'Bir veya daha fazla gruba bir cihaz ekleyin',
    'error.invalid.character': 'Aygıt numarası / ? & sembollerini içeremez',
	'error.invalid.configuration.mainApp': 'MDM ayarlarında yanlış ana uygulama kullanılıyor',
	'error.invalid.configuration.contentApp': 'MDM ayarlarında geçersiz içerik uygulaması kullanılıyor',
	'error.mismatch.password': 'Şifre ve şifre onayı eşleşmelidir',
	'error.empty.customer.name': 'Şifreyi girin kuruluşun adı',
	'error.empty.customer.prefix': 'Cihaz numarası önekini girin',
	'error.empty.customer.device.configuration': 'Cihaz yapılandırmasını seçin',
	'error.empty.customer.duplicate.prefix': 'Önek zaten kullanımda',
	'error.duplicate.customer.name': 'Girilen ada sahip kuruluş zaten var. Farklı bir ad deneyin.',
	'error.duplicate.group.name': 'Girilen ada sahip grup zaten var. Farklı bir ad deneyin.',
	'error.duplicate.configuration.name': 'Girilen ada sahip yapılandırma zaten var. Farklı bir ad deneyin.',
	'error.duplicate.device.number': 'Bu numaraya sahip bir cihaz zaten mevcut',
	'error.internal.server': 'Dahili sunucu hatası',
	'error.permission.denied': 'Yürütme hakkı yok',
	'error.request.failure': 'İstek başarısız',
	'error.configuration.device.use': 'Bu yapılandırma silinemez, cihazlarda kullanılıyor. Önce "Cihazlar"a gidin, bu yapılandırmayı kullanan cihazları bulun ve ayarlarını değiştirin.',
	'error.invalid.system.update.time': 'Geçersiz yükleme aralığı',
	'error.size.limit.exceeded': 'Depolama sınırı aşıldı',

	'error.configuration.file.empty.name': 'Bir dosya adı girin',
	'error.configuration.file.empty.desc': 'Bir dosya açıklaması belirtin',
	'error.configuration.file.empty.path': 'Cihazdaki yolu belirtin',
    'error.configuration.file.empty.file': 'Lütfen bir dosya yükleyin',
    'error.configuration.file.empty.url': 'Lütfen dosya URL\'sini belirtin',

	'error.notfound.device': 'Cihaz bulunamadı',
	'error.duplicate.device': 'Aynı numaraya sahip bir cihaz zaten mevcut',
	'error.duplicate.login': 'Böyle bir oturum açma zaten kullanılıyor',
	'error.duplicate.email': 'Bu e-postaya sahip bir kullanıcı zaten var',
	'error.duplicate.group': 'Aynı ada sahip bir grup zaten var',
	'error.duplicate.application': 'Bu paket kimliğine ve sürümüne sahip bir uygulama zaten var',
	'error.recent.application.version.exists': 'Daha yeni bir uygulama sürümü var',
	'error.common.application.access.prohibited': 'Ortak uygulamaların yönetimi yalnızca Süper Yönetici tarafından yapılabilir',
	'error.application.config.reference.exists': 'Uygulama yapılandırmalarda kullanılıyor ve silinemiyor',
	'error.application.version.deletion.prohibited': 'Sürüm benzersiz veya yapılandırmalarda kullanılıyor ve silinemiyor',
	'error.duplicate.file': 'Aynı ada sahip bir dosya zaten var',
	'error.used.file': 'Bu dosya kullanılıyor',
	'error.version.exists': 'Bu uygulamanın aynı sürümü zaten var',
	'error.duplicate.configuration': 'Bu ada sahip bir yapılandırma zaten var',
	'error.duplicate.role.name': 'Aynı ada sahip bir rol zaten var',
	'error.empty.role.name': 'Lütfen rol adını belirtin',
    'error.duplicate.icon.name': 'Aynı ada sahip bir simge zaten mevcut',
	'error.notfound.customer.admin': 'Yönetici hesabı bulunamadı',
	'error.apk.file.required': '.apk veya .xapk uzantılı dosyayı seçin',
	'error.apk.parse': 'Dosya ayrıştırılırken bir hata oluştu',
	'error.package.not.match': 'Paket kimliği eşleşmiyor',
	'error.empty.app.name': 'Uygulama adını girin',
	'error.empty.app.pkg': 'Paket kimliğini girin',
	'error.empty.app.url': 'URL\'yi girin',
	'error.empty.app.iconText': 'Simge metnini girin',
	'error.empty.app.version': 'Uygulamanın sürümünü girin',
	'error.notempty.group': 'Bu grup bir veya daha fazla cihazı içerir. Bunu kaldıramazsınız.',
	'error.file.empty': 'Yeni bir dosya yükle',
	'error.file.deletion': 'Sunucudaki dosyayı silerken hata oluştu',
	'error.file.save': 'Sunucuya dosya kaydedilirken hata oluştu',
	'error.password.wrong': 'Geçersiz parola',
	'error.password.empty': 'Parola belirtilmemiş',
	'error.password.weak': 'Zayıf parola kalitesi',
	'error.params.missing': 'Eksik parametreler:',
	'error.empty.push.options': 'Lütfen Push bildirimleri seçeneklerini seçin',
	'error.app.name.exists': 'Bu adda başka bir uygulama zaten var. Lütfen benzersiz bir ad belirtin.',

	'table.filtering.check.all': 'Tümünü Seç',
	'table.filtering.uncheck.all': 'Tümünü İptal Et',
	'table.filtering.suffix.configuration': 'yapılandırmalar',
	'table.filtering.suffix.group': 'gruplar',
	'table.filtering.suffix.permission': 'izinler',
	'table.filtering.no.selected.configuration': 'Hiçbir yapılandırma seçilmedi',
	'table.filtering.no.selected.group': 'Hiçbir grup seçilmedi',
	'table.filtering.no.selected.permission': 'Hiçbir izin seçilmedi',

	'success.admin.created': 'Yönetici hesabı oluşturuldu:\n ${adminCredentials}',
	'success.uploading.file': 'Dosya sunucuya yükleniyor ...',
	'success.loading.devices': 'Cihaz listesi yükleniyor ...',
	'success.loading.customer': 'Müşteri ayrıntıları yükleniyor ...',
	'success.file.uploaded': 'Dosya başarıyla yüklendi.',
	'success.file.uploaded.need.save': 'Dosya başarıyla yüklendi. Bağıl yolu girin ve "Kaydet"e tıklayın.',
	'success.settings.design.saved': 'Tasarım ayarları başarıyla kaydedildi',
	'success.settings.common.saved': 'Aygıt tablosu ayarları başarıyla kaydedildi',
	'success.settings.saved': 'Ayarlar başarıyla kaydedildi',
	'success.settings.apiKey.saved': 'API anahtarı başarıyla kaydedildi',
	'success.settings.hints.enabled': 'İpuçları etkinleştirildi',
	'success.settings.hints.disabled': 'İpuçları devre dışı bırakıldı',
	'success.configuration.saved': 'Yapılandırma başarıyla kaydedildi',
	'success.operation.completed': 'İşlem başarıyla tamamlandı',
	'success.plugins.disabled': 'Ayarlar başarıyla kaydedildi',
	'success.config.update.notification': 'Yapılandırma güncelleme komutu cihazlara gönderildi',
	'success.config.update.device.app.settings.notification': 'Uygulama ayarlarını güncelleme komutu cihaza gönderildi.',

	'form.icon.title': 'Simge',
	'form.icon.name': 'Ad',
	'form.icon.file': 'Dosya',

	'configuration.add.warning': 'Boş bir yapılandırma oluşturmak istediğinizden emin misiniz? Tüm gerekli sistem uygulamalarını manuel olarak eklemeniz gerekecektir. Bunun yerine mevcut bir yapılandırmayı kopyalayıp değiştirmeyi düşünün.',
	'configuration.remove.warning': 'Son yapılandırmayı kaldırmak istediğinizden emin misiniz? Hangi sistem uygulamalarının gerekli olduğu bilgisini kaybedeceksiniz.',
	'form.configuration.title': 'Yapılandırma',
	'form.configuration.title.typical': 'Tipik yapılandırma',
	'form.configuration.settings.auto.update': 'Otomatik Güncelleme',
	'form.configuration.settings.system.update': 'Sistem Güncellemesi',
	'form.configuration.settings.system.update.default': 'Varsayılan',
	'form.configuration.settings.system.update.immediate': 'Hemen',
	'form.configuration.settings.system.update.scheduled': 'Planlanmış',
	'form.configuration.settings.system.update.postponed': 'Ertelendi',
	'form.configuration.settings.system.update.time': 'Kurulum süresi',
	'form.configuration.settings.system.update.time.from': 'başlangıç:',
	'form.configuration.settings.system.update.time.to': 'bitiş:',
	'form.configuration.settings.system.schedule.app.update': 'Uygulama güncellemesini zamanla',
	'form.configuration.settings.system.app.update.time': 'Uygulama güncelleme süresi',
	'form.configuration.settings.download.updates': 'İçeriği indir',
	'form.configuration.settings.download.updates.unlimited': 'Sınırsız',
	'form.configuration.settings.download.updates.limited': 'Mobil ağda 3 deneme',
	'form.configuration.settings.download.updates.wifi': 'Yazar Yalnızca WiFi',
	'form.configuration.settings.block.status.bar': 'Durum çubuğu kilidi',
	'form.configuration.settings.block.status.bar.hint': 'Bu ayar kullanım dışıdır ve Android 6 ve altı sürümlerde iyi çalışır. Daha yeni Android sürümlerinde durum çubuğunu kilitlemek için kiosk modunu (MDM ayarları) kullanın.',
	'form.configuration.settings.mdm.kiosk.mode': 'Kiosk modu',
	'form.configuration.settings.mdm.app.main': 'MDM uygulaması',
	'form.configuration.settings.mdm.component.event.receiver': 'Yönetici alıcı sınıfı',
	'form.configuration.settings.mdm.component.event.receiver.placeholder': 'com.hmdm.launcher.AdminReceiver olmalı',
	'form.configuration.settings.mdm.component.wifi.ssid': 'WiFi SSID',
	'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'Kayıt WiFi SSID - manuel olarak girmek için boş bırakın',
	'form.configuration.settings.mdm.component.wifi.password': 'WiFi şifresi',
	'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Kayıt WiFi şifresi - manuel olarak girmek için boş bırakın',
	'form.configuration.settings.mdm.component.wifi.security': 'WiFi güvenlik türü',
	'form.configuration.settings.mdm.component.wifi.notice': 'Uyarı: bu WiFi ayarları yalnızca ilk kayda uygulanır!',
	'form.configuration.settings.mdm.component.server.url': 'Yeni sunucu URL\'si',
	'form.configuration.settings.mdm.component.server.url.placeholder': 'Yeni bir MDM sunucusuna geçiş için kullanılır',
	'form.configuration.settings.mdm.app.content': 'İçerik uygulaması',
	'form.configuration.settings.mdm.kiosk.home': 'Ana Sayfa düğmesini etkinleştir',
	'form.configuration.settings.mdm.kiosk.recents': 'Son Aramalar düğmesini etkinleştir',
	'form.configuration.settings.mdm.kiosk.notifications': 'Bildirimleri etkinleştir',
	'form.configuration.settings.mdm.kiosk.system.info': 'Durum çubuğu bilgisini etkinleştir',
	'form.configuration.settings.mdm.kiosk.keyguard': 'Ekran kilidini etkinleştir',
	'form.configuration.settings.mdm.kiosk.lock.buttons': 'Güç düğmesini kilitle',
	'form.configuration.settings.mdm.mobile.enrollment': 'Mobil veri kullanarak kaydol',
	'form.configuration.settings.mdm.encrypt.device': 'Cihaz depolama alanını şifrele',
	'form.configuration.settings.mdm.lock.safe.settings': 'Güvenli ayarları kilitle (WiFi, GPS, vb.)',
	'form.configuration.settings.mdm.permissive': 'İzinli (kilitsiz) mod',
	'form.configuration.settings.mdm.kiosk.exit': 'Kiosk çıkış düğmesi',
	'form.configuration.settings.mdm.allowed.classes': 'İzin verilen etkinlikler',
	'form.configuration.settings.mdm.allowed.classes.placeholder': 'Virgülle ayrılmış sınıflar, örneğin: com.android.settings.homepage.SettingsHomepageActivity',
	'form.configuration.settings.mdm.restrictions': 'Kısıtlamalar',
	'form.configuration.settings.mdm.restrictions.placeholder': 'MDM kısıtlamaları, virgülle ayrılmış, örn.: no_sms,no_outgoing_calls,no_usb_file_transfer',
	'form.configuration.settings.mdm.misc': 'Diğer QR kodu girişleri',
	'form.configuration.settings.mdm.misc.placeholder': 'virgülle ayrılmış girişler, örn.:\n"android.app.extra.PROVISIONING_LOCALE": "de_DE"',
	'form.configuration.settings.mdm.qrcode.url': 'QR kodu URL\'si',
	'form.configuration.settings.mdm.hint': 'Ana uygulamayı ve bileşeni seçin',
	'form.configuration.apps.search.label': 'Ara:',
	'form.configuration.apps.sort.label': 'Sırala:',
	'form.configuration.apps.sort.byname': 'Ada göre',
	'form.configuration.apps.sort.bypkg': 'Kimliğe göre',
	'form.configuration.apps.no.apk': 'yok',
	'form.configuration.apps.show.systeam.apps': 'Sistem Uygulamalarını Göster',
	'form.configuration.apps.action.select': '(seç)',
	'form.configuration.apps.action.install': 'Yükle',
	'form.configuration.apps.action.prohibit': 'Engelle',
	'form.configuration.apps.action.not.install': 'Yükleme',
	'form.configuration.apps.action.delete': 'Sil',
	'form.configuration.apps.action.permit': 'İzin Ver',
	'form.configuration.apps.label.inherit': 'Miras Alındı',
	'form.configuration.apps.label.show': 'Göster',
	'form.configuration.apps.label.not.show': 'Gizle',
	'form.configuration.apps.edit.details': 'Ek parametreler',
	'form.configuration.apps.keycode': 'Anahtar kodu',
	'form.configuration.apps.bottom': 'Alt satırda görüntüle',
	'form.configuration.apps.long.tap': 'Uzun dokunma ayarları açar',
	'form.configuration.apps.hint': 'İpucu: Uygulamayı yapılandırmadan çıkarmak için "Engelle" veya "Yükleme" eylemini seçin.',
	'form.configuration.settings.design.use.default': 'Varsayılan tasarımı kullan',
	'form.configuration.settings.design.color.background': 'Arka Plan Rengi',
	'form.configuration.settings.design.color.background.placeholder': 'Bir renk seçin',
	'form.configuration.settings.design.color.app.names': 'Uygulama Adları Rengi',
	'form.configuration.settings.design.color.app.names.placeholder': 'Bir renk seçin',
	'form.configuration.settings.design.background.image.url': 'Arka plan görüntüsünün URL\'si',
	'form.configuration.settings.design.background.image.url.placeholder': 'Arka plan görüntüsünün URL\'sini girin',
	'form.configuration.settings.design.icon': 'Simge boyutu',
	'form.configuration.settings.design.icon.small': 'Küçük',
	'form.configuration.settings.design.icon.medium': 'Ortalama (+ %20)',
	'form.configuration.settings.design.icon.large': 'Büyük (+ %40)',
	'form.configuration.settings.design.desktop.header': 'Masaüstü başlığı',
	'form.configuration.settings.design.desktop.header.no': 'Hayır',
	'form.configuration.settings.design.desktop.header.deviceid': 'Cihaz Kimliği',
	'form.configuration.settings.design.desktop.header.description': 'Açıklama',
	'form.configuration.settings.design.desktop.header.custom': 'Özel şablon',
	'form.configuration.settings.design.desktop.header.hint': 'Bu parametrenin cihazlara gönderildiğinden emin olun (Ayarlar - Genel ve dil ayarları)',
	'form.configuration.settings.design.desktop.header.template': 'Şablonu girin',
	'form.configuration.settings.design.desktop.header.template.placeholder': 'Değişkenleri kullanın',
	'form.configuration.settings.design.display.status': 'Saati ve pil durumunu görüntüleyin',
	'form.configuration.settings.design.upload': 'Yükle',
	'form.configuration.settings.common.name': 'Ad',
	'form.configuration.settings.common.name.placeholder': 'Yapılandırma adını girin',
	'form.configuration.settings.common.desc': 'Açıklama',
	'form.configuration.settings.common.desc.placeholder': 'Yapılandırma açıklamasını girin',
	'form.configuration.settings.common.admin.pwd': 'Kilidi açma şifresi',
	'form.configuration.settings.common.admin.pwd.placeholder': 'Cihazın kilidini açma şifresini girin',
	'form.configuration.settings.common.gps': 'GPS',
	'form.configuration.settings.common.gps.any': 'Herhangi biri',
	'form.configuration.settings.common.gps.off': 'Devre Dışı',
	'form.configuration.settings.common.gps.on': 'Etkin',
	'form.configuration.settings.common.bluetooth': 'Bluetooth',
	'form.configuration.settings.common.wifi': 'Wi-Fi',
	'form.configuration.settings.common.mobile.data': 'Mobil veri',
	'form.configuration.settings.common.usb.storage': 'USB depolamayı engelle',
	'form.configuration.settings.common.brightness': 'Parlaklığı yönet',
	'form.configuration.settings.common.brightness.none': 'Yok',
	'form.configuration.settings.common.brightness.auto': 'Otomatik',
	'form.configuration.settings.common.brightness.manual': 'Değer',
	'form.configuration.settings.common.brightness.value': 'Ekran parlaklığı',
	'form.configuration.settings.common.timeout': 'Ekran zaman aşımını yönet',
	'form.configuration.settings.common.timeout.value': 'Ekran zaman aşımı (s)',
	'form.configuration.settings.common.volume.block': 'Sesi kilitle',
	'form.configuration.settings.common.volume.manage': 'Sesi yönet',
	'form.configuration.settings.common.volume.value': 'Ses',
	'form.configuration.settings.common.timezone.mode': 'Saat dilimini yönet',
	'form.configuration.settings.common.timezone.mode.default': 'Yönetme',
	'form.configuration.settings.common.timezone.mode.auto': 'Otomatik',
	'form.configuration.settings.common.timezone.mode.manual': 'Manuel',
	'form.configuration.settings.common.timezone': 'Saat dilimi',
	'form.configuration.settings.common.timezone.placeholder': 'örn. America/Los_Angeles',
	'form.configuration.settings.common.timezone.link': 'Saat dilimlerinin listesi',
	'form.configuration.settings.common.no.network.warning': 'UYARI! Tüm bağlantı kanallarını kapatmayın, aksi takdirde cihazları artık yönetemezsiniz!',
	'form.configuration.settings.common.autostart.foreground': 'Ön planda uygulamaları otomatik başlat',
	'form.configuration.settings.request.updates': 'Konum Takibi',
	'form.configuration.settings.request.updates.donottrack': 'Etkin izleme yok (üçüncü taraf uygulama konum verilerini kullanın)',
	'form.configuration.settings.request.updates.gps': 'GPS ile konumu takip et',
	'form.configuration.settings.request.updates.wifi': 'Wi-Fi ile konumu takip et (Google hizmetleri etkinleştirilmiş olmalıdır)',
	'form.configuration.settings.request.updates.prompt.gps': 'GPS ile konumu takip etmek için GPS\'i etkinleştirmeniz gerekir',
	'form.configuration.settings.request.updates.prompt.wifi': 'Konumu Wi-Fi ile izlemek için Wi-Fi\'yi etkinleştirmeniz gerekir',
	'form.configuration.settings.revoke.location.permission': 'Konum izni yok',
	'form.configuration.settings.revoke.location.permission.hint': 'Ayarlanırsa, konum izni MDM aracısına verilmez ve cihaz konumunu izleyemez',
	'form.configuration.settings.apps.permissions': 'Diğer uygulamalar için izinler',
	'form.configuration.settings.apps.permissions.grant': 'Tüm izinleri otomatik olarak ver',
	'form.configuration.settings.apps.permissions.ask.location': 'Tümünü otomatik olarak ver, kullanıcıdan konum izni iste',
	'form.configuration.settings.apps.permissions.deny.location': 'Tümünü otomatik olarak ver, konum iznini verme',
	'form.configuration.settings.apps.permissions.ask.all': 'Kullanıcıdan tüm izinleri iste',
	'form.configuration.settings.push.options' : 'Bildirimleri gönder',
	'form.configuration.settings.push.options.mqtt.worker' : 'MQTT protokolü (pil tasarrufu)',
	'form.configuration.settings.push.options.mqtt.alarm' : 'MQTT protokolü',
	'form.configuration.settings.push.options.polling' : 'HTTP yoklaması',
	'form.configuration.settings.push.options.mqtt.worker.hint' : 'Cihaz aktif olduğunda anında Push mesajları iletir. Ancak uyku modunda mesajlar birkaç saate kadar gecikebilir. Bu seçeneği bağımsız cihazlarda kullanmayın. MQTT, TCP 31000 portunu kullanır, güvenlik duvarınızda etkinleştirin.',
	'form.configuration.settings.push.options.mqtt.alarm.hint' : 'MQTT, minimum kaynak tüketen hafif bir protokoldür. MQTT, TCP 31000 portunu kullanır, güvenlik duvarınızda etkinleştirin.',
	'form.configuration.settings.push.options.polling.hint' : 'Uzun yoklama, daha fazla sunucu kaynağı tüketebilen bir HTTP bağlantısını sürdürür. HTTP(S) dışında herhangi bir TCP portu gerektirmez.',
	'form.configuration.settings.push.options.keepalive' : 'Canlı Tutma süresi',
	'form.configuration.settings.minute.1' : '1 dakika',
	'form.configuration.settings.minutes.2' : '2 dakika',
	'form.configuration.settings.minutes.3' : '3 dakika',
	'form.configuration.settings.minutes.5' : '5 dakika',
	'form.configuration.settings.minutes.10' : '10 dakika',
	'form.configuration.settings.minutes.15' : '15 dakika',
	'form.configuration.settings.password.mode' : 'Parola gereksinimleri',
	'form.configuration.settings.password.mode.any' : 'Hiçbiri',
	'form.configuration.settings.password.mode.present' : 'Şifre sunar',
	'form.configuration.settings.password.mode.easy' : 'Kolay (en az 6 sembol)',
	'form.configuration.settings.password.mode.moderate' : 'Orta (8+ sembol, harf ve rakam)',
	'form.configuration.settings.password.mode.strong' : 'Güçlü (8+, büyük ve küçük harf, rakam, işaret)',
	'form.configuration.settings.show.wifi': 'Bağlantı hatasında WiFi ayarları',
	'form.configuration.settings.use.default.launcher': 'Arka plan modu',
	'form.configuration.settings.use.default.launcher.hint': 'Sistem başlatıcısını değiştirmeyin, yalnızca arka planda MDM hizmetlerini çalıştırın. Kiosk moduyla önerilmez.',
	'form.configuration.settings.disable.screenshots': 'Ekran görüntüsünü devre dışı bırak',
	'form.configuration.settings.orientation': 'Yönlendirmeyi kilitle',
	'form.configuration.settings.orientation.none': 'Kilitleme',
	'form.configuration.settings.orientation.portrait': 'Dikey',
	'form.configuration.settings.orientation.landscape': 'Manzara',
	'form.configuration.settings.files.default.path': 'Bir cihazdaki varsayılan yol',
	'form.configuration.files.search.label': 'Ara:',
	'form.configuration.files.action.upload': 'Yükle',
	'form.configuration.files.action.remove': 'Kaldır',
	'form.configuration.files.variables': 'Değişken içeriği',
	'form.configuration.files.variables.hint': 'DEVICE_NUMBER, IMEI, CUSTOM* dizeleri değerleriyle değiştirilecek',

	'form.configuration.file.name': 'Dosya adı',
    'form.configuration.file.select': 'Bir dosya seçin',
    'form.configuration.file.create': '(yeni bir dosya oluştur)',
	'form.configuration.file.description': 'Dosya açıklaması',
	'form.configuration.file.description.placeholder': 'İsteğe bağlı, kolaylığınız için',
	'form.configuration.file.path': 'Cihazdaki yol',
	'form.configuration.file.path.placeholder': 'Örneğin bir sürücüye giden yolu hariç tutma /my-app/image.jpg',
	'form.configuration.file.url': 'URL',
	'form.configuration.file.url.placeholder': 'Sadece bir dosya harici bir kaynakta barındırılıyorsa',
	'form.configuration.file.file': 'Dosya',
	'form.configuration.file.action': 'Eylem',
	'form.configuration.file.action.prompt.1': 'Yükle',
	'form.configuration.file.action.prompt.2': 'Kaldır',
	'form.configuration.file.remove.prompt.1': 'Bu dosya artık cihazlarla senkronize edilmeyecek',
	'form.configuration.file.remove.prompt.2': 'Dosyayı sunucudan kaldır',

	'form.password.title': 'Şifreyi Değiştir',
	'form.password.label.user': 'Kullanıcı',
	'form.password.label.password.new': 'Yeni şifre',
	'form.password.label.password.new.placeholder': 'Yeni bir şifre girin',
	'form.password.label.password.confirm': 'Doğrula',
	'form.password.label.password.confirm.placeholder': 'Yeni şifreyi tekrar girin',
	'form.password.length': 'Minimum uzunluk: ${length}. ',

	'form.application.type': 'Tür',
	'form.application.type.option.web': 'Web sayfası',
	'form.application.type.option.app': 'Uygulama',
	'form.application.type.option.intent': 'Sistem eylemi',
	'form.application.intent': 'Eylem',
	'form.application.intent.placeholder': 'Bir eylem seçin',
	'form.application.url.hint': 'Yerel dosyalara ve klasörlere bağlantılar oluşturmak için file:///storage/emulated/0/... kullanın',
	'form.application.pkg': 'Paket Kimliği',
	'form.application.from.file': 'dosyadan belirlenir',
	'form.application.pkg.title': 'Paket Kimliği, yüklediğinizde otomatik olarak belirlenir APK dosyası. Elle girilen paket kimliği yalnızca sistem uygulamaları için gereklidir.',
	'form.application.pkg.placeholder': 'Örneğin, com.android.camera',
	'form.application.disabled.arch': 'Sürüm-belirli',
	'form.application.disabled.arch.title': 'Farklı CPU mimarileri için APK\'lar eklemek için "Ekle"ye tıklayın veya uygulama sürümleri listesini açın',
	'form.application.arch': 'Yerel kod',
	'form.application.arch.title': 'Bazı uygulamalar belirli CPU mimarileri için optimize edilmiş kod içerir. Bu durumda, iki APK yüklemeniz gerekir (armeabi-v7a ve arm64-v8a mimarileri için)',
	'form.application.arch.universal': 'Hiçbiri (evrensel APK)',
	'form.application.arch.armeabi': 'armeabi-v7a için yerel kod',
	'form.application.arch.arm64': 'arm64-v8a için yerel kod',
	'form.application.arch.no.split': 'Evrensel APK',
	'form.application.arch.split': 'APK\'yi böl',
	'form.application.arch.warning': 'Bu APK yalnızca ${arch} için optimize edilmiştir ve tüm cihazlarda çalışmayabilir. Başka bir CPU mimarisi için optimize edilmiş başka bir APK yüklemeniz önerilir. Bu APK\'yi tüm cihazlarda kullanmak için "Evrensel APK"yı seçin.',
	'form.application.arch.success': 'Bu uygulama her iki CPU mimarisi için de APK\'ler içeriyor',
	'form.application.version.exists': 'Bu sürüm için APK zaten mevcut',
	'form.application.url.armeabi': 'armeabi-v7a için URL',
	'form.application.url.arm64': 'arm64-v8a için URL',
	'form.application.name': 'Uygulama Adı',
	'form.application.name.title': 'Uygulama adını listede göreceksiniz. Benzersiz ve bilgilendirici adlar kullanmanızı öneririz.',
	'form.application.name.placeholder': 'Örneğin, Kamera (Android)',
	'form.application.version': 'Sürüm',
	'form.application.version.placeholder': 'Önceden yüklenmiş uygulamalar için 0',
	'form.application.version.title': 'APK dosyasını yüklediğinizde paket sürümü otomatik olarak belirlenir. Sistem uygulamaları için 0 olarak ayarlayın.',
	'form.application.version.code': 'Sürüm Kodu',
	'form.application.version.code.exists': 'Aynı koda sahip bir sürüm zaten mevcut. Lütfen bu sorunu uygulama geliştiricilerine bildirin.',
	'form.application.system': 'Önceden yüklenmiş uygulama',
	'form.application.system.title': 'Sistem uygulamaları bir cihaza önceden yüklenir ve URL veya dosya gerektirmez. Bu bayrağı yalnızca belirli bir sistem paketini etkinleştirmeniz gerekiyorsa ayarlayın.',
	'form.application.run.after.install': 'Yüklemeden sonra çalıştır',
	'form.application.run.after.install.title': 'Arka plan hizmetleri olan uygulamaların en az bir kez ön planda başlatılması gerekir.',
	'form.application.run.at.boot': 'Önyüklemede çalıştır',
	'form.application.run.at.boot.title': 'Önyüklemeden sonra uygulamayı ön planda çalıştırmanız gerekiyorsa bu bayrağı ayarlayın. Bu bayrak arka plan işlemlerini etkilemez.',
	'form.application.url': 'URL',
	'form.application.url.title': 'URL yalnızca uygulamanız harici bir kaynakta barındırılıyorsa yazılmalıdır. Aşağıdaki alanı kullanarak bir APK dosyası yüklemeniz önerilir.',
	'form.application.url.disabled': 'URL her sürüm için ayarlanır. URL\'yi değiştirmek için bu pencereyi kapatın ve "Sürümler" simgesine tıklayın.',
	'form.application.file': 'Dosya',
	'form.application.auto.update': 'Otomatik Güncelleme',
	'form.application.auto.update.title': 'Uygulamanın yüklendiği tüm yapılandırmaları güncellemek için bu bayrağı ayarlayın. Yalnızca uygulamanın %100 kararlı olduğundan eminseniz kullanın.',
	'form.application.showLabel': 'Simgeyi Göster',
	'form.application.showLabel.title': 'Bu bayrak, uygulama simgesinin başlatıcıda görüntülenip görüntülenmeyeceğini belirtir. Bu seçenek yapılandırmada geçersiz kılınabilir.',
	'form.application.use.kiosk': 'Kiosk Tarayıcısında Aç',
	'form.application.use.kiosk.title': 'Adresi değiştirme olanağı olmadan Kiosk Tarayıcısında bir web sayfası açmak istiyorsanız bu bayrağı ayarlayın',
	'form.application.iconText': 'Simge Metni',
	'form.application.iconText.placeholder': '(varsayılan)',
	'form.application.versions.title': 'Uygulama sürümleri',
	'form.application.icon': 'Simge',
	'form.application.icon.default': '(varsayılan)',
	'form.application.icon.add': 'Simge ekle',

	'form.application.setting.app': 'Uygulama',
	'form.application.setting.app.placeholder': 'Bir uygulama seçin',
	'form.application.setting.name': 'Öznitelik',
	'form.application.setting.value': 'Değer',
	'form.application.setting.comment': 'Yorum',
	'form.application.setting.type': 'Tür',
	'form.application.setting.readonly': 'Cihazda değişmez',
		
	'form.application.configurations.app': 'Uygulama',
	'form.application.configurations.configs': 'Yapılandırmalar',

	'form.configuration.copy.new.name': 'Yeni ad',
	'form.configuration.copy.new.name.placeholder': 'Yeni yapılandırma adını girin',

	'form.customer.name': 'Müşteri Kimliği',
	'form.customer.name.placeholder': 'Oturum açmak için kullanılan kuruluş tanımlayıcısı',
	'form.customer.admin.name': 'Yönetici adı',
	'form.customer.firstname.placeholder': 'Ad',
	'form.customer.lastname.placeholder': 'Soyadı',
	'form.customer.language': 'Dil',
	'form.customer.language.placeholder': 'İngilizce veya iki küçük harf için boş',
	'form.customer.apiKey': 'API anahtarı',
	'form.customer.apiKey.placeholder': 'API anahtarını girin',
	'form.customer.prefix': 'Önek',
	'form.customer.prefix.placeholder': 'Cihaz numarası önekini girin',
	'form.customer.device.configuration': 'Cihaz yapılandırması',
	'form.customer.desc': 'Açıklama',
	'form.customer.desc.placeholder': 'Kuruluşun açıklamasını girin',
	'form.customer.copy.configuration': 'Yapılandırmaları kopyala',
	'form.customer.copy.design': 'Tasarımı kopyala',
	'form.customer.type': 'Müşteri type',
	'form.customer.status': 'Müşteri durumu',
	'form.customer.expiry.time': 'Son kullanma tarihi',
	'form.customer.device.limit': 'Cihaz sınırı',
	'form.customer.size.limit': 'Depolama sınırı',
	'form.customer.size.limit.placeholder': 'Boyut (Mb)',

	'form.device.number': 'Sayı',
	'form.device.number.locked': 'Önceki numara değişikliği tamamlanmadığı için numara değiştirilemiyor.',
	'form.device.migration.warning': 'Cihaz numarası değiştirilecek. Cihazın açık ve çevrimiçi olduğundan emin olun.',
	'form.device.number.hint': 'Özel karakterler kullanmayın',
	'form.device.desc': 'Açıklama',
	'form.device.groups': 'Gruplar',
	'form.device.config': 'Yapılandırma',
	'form.device.imei': 'IMEI',
	'form.device.phone.number': 'Telefon Numarası',

	'form.update.device.config': 'Yapılandırma',
	'form.update.device.action': 'Grup eylemi',
	'form.device.set.group': 'Gruplara ekle',
	'form.device.clear.group': 'Gruplardan kaldır',

	'form.file.file': 'Dosya',
    'form.file.name': 'Dosya adı',
    'form.file.description': 'Açıklama (isteğe bağlı)',
    'form.file.external': 'Harici',
    'form.file.external.title': 'Dosyayı yüklemek yerine, harici bir kaynaktaki URL\'yi belirtebilirsiniz',
    'form.file.external.url': 'URL',
    'form.file.external.url.placeholder': 'Harici bir kaynaktaki dosya URL\'si',
    'form.file.path': 'Sunucudaki yol',
    'form.file.device.path': 'Cihazdaki yol',
    'form.file.device.path.placeholder': '/storage/emulated/0\'a göre yol',
    'form.file.deleted': 'SİLİNDİ',
    'form.file.copy.link': 'Bağlantıyı kopyala: ${link}',
    'form.file.configurations.file': 'Dosya',
    'form.file.configurations.configs': 'Yapılandırmalar',
    'form.file.configurations.upload': 'Yükle',
	'form.file.path.placeholder': 'Örneğin "/files/" gibi bir göreli yol girin',
	'form.file.available': 'Kullanılabilir alan: ${space} Mb',

	'form.file.apps.name': 'Uygulama Adı',
	'form.file.apps.pkg': 'Paket Kimliği',
	'form.file.apps.version': 'Sürüm',

	'form.group.name': 'Ad',
	'form.group.name.placeholder': 'Grubun adını girin',

	'form.role.name': 'Ad',
	'form.role.name.placeholder': 'Rolün adını girin',
	'form.role.permissions': 'İzinler',

	'form.user.login': 'Giriş',
	'form.user.login.placeholder': 'Kullanıcı girişini girin',
	'form.user.name': 'Ad',
	'form.user.name.placeholder': 'Ad ve soyad',
	'form.user.email': 'E-posta',
	'form.user.email.placeholder': 'E-postayı girin',
	'form.user.role': 'Rol',
	'form.user.all.devices.available': 'Tüm cihazlar kullanılabilir',
	'form.user.available.groups': 'Kullanılabilir cihaz grupları',
	'form.user.all.configs.available': 'Tüm yapılandırmalar kullanılabilir',
	'form.user.available.configs': 'Kullanılabilir yapılandırmalar',
	'form.user.password.new': 'Yeni Parola',
	'form.user.password': 'Parola',
	'form.user.password.new.placeholder': 'Yeni bir parola girin',
	'form.user.password.confirm': 'Doğrula',
	'form.user.password.confirm.placeholder': 'Yeni parolayı tekrar girin',

	'form.settings.hints.title': 'İpuçları',

	'form.settings.plugins.title': 'Kullanılan Eklentiler',

	'form.settings.common.title': 'Aygıt Tablosu Görünümü',
	'form.settings.common.visible.columns': '"Aygıtlar" tablosundaki görünür sütunlar',
	'form.settings.common.status': 'Durum',
	'form.settings.common.role': 'Kullanıcı rolü',
	'form.settings.common.date': 'Son çevrimiçi tarih',
	'form.settings.common.device.number': 'Aygıt numarası',
	'form.settings.common.imei': 'IMEI',
	'form.settings.common.phone.number': 'Telefon Numarası',
	'form.settings.common.phone.model': 'Telefon Modeli',
	'form.settings.common.status.permissions': 'İzin Durumu',
	'form.settings.common.status.installation': 'Yükleme Durumu',
	'form.settings.common.status.files': 'Dosya Durumu',
	'form.settings.common.config': 'Yapılandırma',
	'form.settings.common.desc': 'Açıklama',
	'form.settings.common.group': 'Grup',
	'form.settings.common.launcher.version': 'Başlatıcı sürümü',
	'form.settings.common.battery.level': 'Pil seviyesi',
	'form.settings.common.default.launcher': 'Arkaplan',
	'form.settings.common.mdm.mode': 'MDM modu',
	'form.settings.common.kiosk.mode': 'Kiosk modu',
	'form.settings.common.android.version': 'Android sürümü',
	'form.settings.common.enrollment.date': 'Kayıt tarihi',
	'form.settings.common.serial': 'Seri numarası',
	'form.settings.common.publicip': 'IP adresi',

	'form.settings.design.title': 'Varsayılan Tasarım',
	'form.settings.design.color.font': 'Arka Plan Rengi',
	'form.settings.design.color.font.placeholder': 'Bir renk seçin',
	'form.settings.design.color.app.names': 'Uygulama Adları Rengi',
	'form.settings.design.color.app.names.placeholder': 'Bir renk seçin',
	'form.settings.design.url.background.image': 'Arka plan görüntüsünün URL\'si',
	'form.settings.design.url.background.image.placeholder': 'Arka plan görüntüsü URL\'sini girin',
	'form.settings.design.size.icon': 'Simge boyutu',
	'form.settings.design.size.icon.small': 'Küçük',
	'form.settings.design.size.icon.medium': 'Ortalama (+ %20)',
	'form.settings.design.size.icon.large': 'Büyük (+ %40)',
	'form.settings.design.desktop.header': 'Masaüstü başlığı',
	'form.settings.design.desktop.header.no': 'Hayır',
	'form.settings.design.desktop.header.device.id': 'Aygıt kimliği',

	'form.settings.lang.title': 'Dil ayarları',
	'form.settings.lang.use.default': 'Varsayılan dili kullan',
	'form.settings.lang.use': 'Dili kullan',
	'form.settings.lang.en': 'English',
	'form.settings.lang.pt': 'Português',
	'form.settings.lang.ru': 'Русский',
	'form.settings.lang.fr': 'Français',
	'form.settings.lang.ar': 'عربي',
	'form.settings.lang.es': 'Español',
	'form.settings.lang.de': 'Deutsch',
	'form.settings.lang.cn': '繁体中文',
	'form.settings.lang.tw': '繁體中文',
	'form.settings.lang.ja': '日本',
	'form.settings.lang.tr': 'Türkçe',
    'form.settings.lang.it': 'Italiano',

	'form.settings.misc.title': 'Çeşitli ayarlar',
	'form.settings.misc.phone.format': 'Telefon numarası biçimi',
	'form.settings.misc.phone.format.placeholder': '+9 (999) 999-99-99',
	'form.settings.misc.custom.property.name.1': 'Özel özellik #1',
	'form.settings.misc.custom.property.name.2': 'Özel özellik #2',
	'form.settings.misc.custom.property.name.3': 'Özel özellik #3',
	'form.settings.misc.custom.property.multiline': 'Çok satırlı',
	'form.settings.misc.custom.property.send': 'Cihaza gönder',
	'form.settings.misc.custom.property.name.placeholder': 'Özel bir özellik için ad girin',
	'form.settings.misc.create.new.devices': 'İlk erişimde cihaz ekle',
	'form.settings.misc.new.device.config': 'Yeni cihaz yapılandırması',
	'form.settings.misc.new.device.group': 'Yeni cihaz grubu',
	'form.settings.misc.send.description': 'Açıklamayı cihazlara gönder',
	'form.settings.misc.password.length': 'Minimum parola uzunluğu',
	'form.settings.misc.password.strength': 'Parola gücü',
	'form.settings.misc.password.none': 'Belirtilmemiş (herhangi bir karakter)',
	'form.settings.misc.password.alphanumeric': 'Küçük ve büyük harfler, rakamlar',
	'form.settings.misc.password.specialchar': 'Küçük ve büyük harfler, rakamlar, özel karakterler',
	'form.settings.misc.password.reset': 'Kullanıcı şifreyi sıfırlamalı',
	'form.settings.misc.idle.logout': 'Boştayken oturumu kapat',
	'form.settings.misc.idle.logout.never': 'Asla',
	'form.settings.misc.idle.logout.1': '5 dakika',
	'form.settings.misc.idle.logout.2': '10 dakika',
	'form.settings.misc.idle.logout.3': '30 dakika',
	'form.settings.misc.idle.logout.4': '1 saat',
	'form.settings.security.title': 'Güvenlik ayarları',

	'idle.logout.message': 'Etkin olmadığınız için ${sec} saniye içinde oturumunuz kapatılacak',
	'idle.logout.resume': 'Buradayım!',

	'form.settings.groups.title': 'Gruplar',
	'form.settings.groups.search.placeholder': 'Grup araması',

	'form.settings.users.title': 'Kullanıcılar',
	'form.settings.users.search.placeholder': 'Kullanıcı ara',

	'form.settings.roles.title': 'Kullanıcı rolleri',

    'form.settings.icons.title': 'Simgeler',
    'form.settings.icons.search.placeholder': 'Simgeleri ara',

	'form.qr.device.number': 'Cihaz numarası',
	'form.qr.auto.create': 'Var değilse cihaz listesine ekle',
	'form.qr.number.use': 'Cihaz numarası ataması',
	'form.qr.number.use.request': 'Kullanıcı değeri',
	'form.qr.number.use.imei': 'IMEI',
	'form.qr.number.use.serial': 'Seri numarası',
	'form.qr.number.hint': 'Otomatik cihaz numarası atamasını etkinleştirmek için cihaz numarasını temizle',
	'form.qr.groups': 'Gruplara ekle',
	'form.qr.button.json': 'JSON al',
	'form.qr.device.number.placeholder': 'Cihaz kimliğini girin ...',
	'form.qr.code.image.alt': 'QR kodu',

	'form.password.reset.title': 'Lütfen yeni bir parola ayarlayın',
	'form.password.reset.invalid': 'Üzgünüz, bu parola sıfırlama bağlantısı geçersiz',
	'form.password.reset.submit': 'Parola belirle',

	'form.two.factor.auth.title': 'İki faktörlü kimlik doğrulama',
	'form.two.factor.auth.hint': 'Kaydınızı tamamlamak için lütfen mobil cihazınıza Authenticator uygulamasını yükleyin, QR kodunu tarayın, doğrulama kodunu oluşturun ve girin.',
	'form.two.factor.auth.code.invalid': 'Doğrulama kodu geçersiz!',
	'form.two.factor.auth.code': 'Doğrulama kodu',
	'form.two.factor.auth.code.hint': 'Kimlik doğrulama uygulamasından 6 haneli kod',
	'form.two.factor.auth.code.error': 'Kod 6 haneli bir sayı olmalıdır',
	'form.two.factor.auth.verify': 'Doğrula',
	'form.two.factor.auth.settings.hint': 'İki faktörlü kimlik doğrulamayı ayarlamak için lütfen mobil cihazınıza Kimlik Doğrulayıcı uygulamasını yükleyin, QR kodunu tarayın, doğrulama kodunu oluşturun ve girin.',
	'form.two.factor.auth.set': 'İki faktörlü kimlik doğrulama açık',
	'form.two.factor.auth.reset': 'İki faktörlü kimlik doğrulama kapalı',
	'form.two.factor.auth.off.confirm': 'İki faktörlü kimlik doğrulamayı kapatmak istiyor musunuz? Tekrar açtıktan sonra tüm kimlik doğrulayıcılar geçersiz hale gelecektir.',

	'form.profile.title': 'Şifreyi değiştir',
	'form.profile.password.old': 'Eski Şifre',
	'form.profile.password.old.placeholder': 'Eski şifreyi gir',
	'form.profile.password.new': 'Yeni Şifre',
	'form.profile.password.new.placeholder': 'Yeni bir şifre gir',
	'form.profile.password.confirm': 'Doğrula',
	'form.profile.password.confirm.placeholder': 'Yeni şifreyi tekrar gir',

	'tab.customers': 'Kuruluşlar',
	'tab.common.applications': 'Paylaşılan Uygulamalar',

	'tab.devices': 'Aygıtlar',
	'tab.applications': 'Uygulamalar',
	'tab.configurations': 'Yapılandırmalar',
	'tab.files': 'Dosyalar',
	'tab.default.design': 'Varsayılan Tasarım',
	'tab.common.settings': 'Aygıt Tablo Görünümü',
	'tab.users': 'Kullanıcılar',
	'tab.roles': 'Roller',
	'tab.groups': 'Gruplar',
    'tab.icons': 'Simgeler',
	'tab.language': 'Genel ve dil ayarları',
	'tab.license': 'Lisans',
	'tab.hints': 'İpuçları',
	'tab.plugins': 'Eklentiler',

	'tab.configeditor.common.settings': 'Ortak ayarlar',
	'tab.configeditor.design.settings': 'Tasarım Ayarları',
	'tab.configeditor.applications': 'Uygulamalar',
	'tab.configeditor.mdm.settings': 'MDM Ayarları',
	'tab.configeditor.app.settings': 'Uygulama Ayarları',
	'tab.configeditor.files': 'Dosyalar',

	'search.placeholder.file': 'dosya ara',
	'search.placeholder.configuration': 'Yapılandırma ara',
	'search.placeholder.customer': 'Bir kuruluş ara',
	'search.placeholder.application': 'Bir uygulama ara',
	'search.placeholder.application.setting': 'Bir uygulama ayarı ara',
	'search.placeholder.device': 'Bir cihaz ara',
	'search.placeholder.address': 'Adres araması',
	'search.placeholder.point': 'Site araması',
	'search.placeholder.message': 'Mesaj araması',
	'search.placeholder': 'Ara ...',
	'search.placeholder.from': 'Nereden ...',
	'search.placeholder.to': 'Nereye ...',
	'search.placeholder.user': 'Kullanıcı adını yazın',

	'table.heading.customer.name': 'Ad',
	'table.heading.customer.desc': 'Açıklama',
	'table.heading.customer.registration.time': 'Kayıtlı',
	'table.heading.customer.last.login.time': 'Son giriş',
	'table.heading.customer.actions': 'Eylemler',
	'table.heading.customer.type': 'Tür',
	'table.heading.customer.expiry.time': 'Sona Eriyor',
	'table.heading.customer.device.limit': 'Sınır',
	'table.heading.customer.status': 'Durum',

	'customer.new': 'Yeni',
	'customer.active': 'Etkin',
	'customer.need.followup': 'Takip gerekiyor',
	'customer.followup.sent': 'Takip gönderildi',
	'customer.internal.test': 'Dahili test',
	'customer.developer': 'Geliştirici',
	'customer.difficult': 'Zor',
	'customer.pause': 'Duraklat',
	'customer.inactive': 'Oturum açma yok',
	'customer.abandon': 'Terk et',
	'customer.onpremise': 'Şirket içi deneme',
	'customer.denial': 'Reddetme',
	'customer.client': 'İstemci',

	'table.heading.configuration.name': 'Ad',
	'table.heading.configuration.desc': 'Açıklama',
	'table.heading.configuration.actions': 'Eylemler',

	'table.heading.application.setting.app.pkg': 'Paket Kimliği',
	'table.heading.application.setting.app.name': 'Uygulama Adı',
	'table.heading.application.setting.name': 'Öznitelik',
	'table.heading.application.setting.value': 'Değer',
	'table.heading.application.setting.comment': 'Yorum',
	'table.heading.application.setting.lastUpdate': 'Oluşturma Tarihi',

	'table.heading.file.url': 'URL',
	'table.heading.file.devicepath': 'Aygıttaki yol',
	'table.heading.file.description': 'Dosya açıklaması',
	'table.heading.file.action': 'Eylem',
	'table.heading.file.lastUpdate': 'Oluşturma tarihi',
		
	'table.heading.application.pkg': 'Paket Kimliği',
	'table.heading.application.name': 'Uygulama Adı',
	'table.heading.application.version': 'Sürüm',
	'table.heading.application.url': 'URL',
	'table.heading.application.label': 'Simge',
	'table.heading.application.actions': 'Eylemler',
	'table.heading.application.order': 'Sıra',

	'table.heading.device.status': 'Durum',
	'table.heading.device.date': 'Tarih',
	'table.heading.device.device.number': 'Cihaz Numarası',
	'table.heading.device.imei': 'IMEI',
	'table.heading.device.phone.number': 'Telefon Numarası',
	'table.heading.device.phone.model': 'Telefon Modeli',
	'table.heading.device.status.permissions': 'İzin Durumu',
	'table.heading.device.status.installation': 'Kurulum Durumu',
	'table.heading.device.status.files': 'Dosya durumu',
	'table.heading.device.configuration': 'Yapılandırma',
	'table.heading.device.desc': 'Açıklama',
	'table.heading.device.group': 'Grup',
	'table.heading.device.launcher.version': 'Başlatıcı sürümü',
	'table.heading.device.battery.level': 'Pil seviyesi',
	'table.heading.device.default.launcher': 'Arkaplan',
	'table.heading.device.mdm.mode': 'MDM modu',
	'table.heading.device.kiosk.mode': 'Kiosk modu',
	'table.heading.device.android.version': 'Android sürümü',
	'table.heading.device.enrollment.date': 'Kayıtlı',
	'table.heading.device.serial': 'Seri numarası',
	'table.heading.device.publicip': 'IP adresi',
	'table.heading.device.actions': 'Eylemler',

	'table.heading.group.name': 'Ad',
	'table.heading.group.actions': 'Eylemler',

	'table.heading.role.name': 'Ad',
	'table.heading.role.actions': 'Eylemler',

	'table.heading.file.name': 'Dosya adı',
    'table.heading.file.comment': 'Açıklama',
    'table.heading.file.device.path': 'Cihazdaki yol',
    'table.heading.file.update.time': 'Güncellendi',
    'table.heading.file.external': 'Harici',
    'table.heading.file.variable': 'Değişken',
    'table.heading.file.remove': 'Kaldır',
    'table.heading.file.remove.hint': 'Dosyanın cihaz depolama alanından kaldırılmasını zorlar',
    'table.heading.file.path': 'Yol',
	'table.heading.file.address': 'Adres',
	'table.heading.file.size': 'Boyut',
	'table.heading.file.actions': 'Eylemler',

	'table.heading.users.login': 'Giriş',
	'table.heading.users.name': 'Ad',
	'table.heading.users.role': 'Rol',
	'table.heading.users.actions': 'Eylemler',

	'table.heading.common.apps.customer': 'Kuruluş',
	'table.heading.common.apps.pkg': 'Paket Kimliği',
	'table.heading.common.apps.name': 'Uygulama Adı',
	'table.heading.common.apps.version': 'Sürüm',
	'table.heading.common.apps.url': 'URL',
	'table.heading.common.apps.label': 'Simge',
	'table.heading.common.apps.actions': 'Eylemler',

	'notfound.devices': 'Görüntülenecek cihaz yok.',
	'notfound.files': 'Dosya listesi boş.',
	'notfound.configurations': 'Hiçbir yapılandırma bulunamadı.',
	'notfound.customers': 'Kuruluş bulunamadı.',
	'notfound.common.apps': 'Görüntülenecek uygulama yok.',
	'notfound.applications': 'Uygulamalar found',
	'notfound.groups':' Grup bulunamadı. Farklı bir sorgu deneyin.',
	'notfound.users':' Kullanıcılar bulunamadı. Farklı bir sorgu deneyin.',
	'notfound.apps.for.display': 'Görüntülenecek uygulama yok.',
	'notfound.app.versions.for.display': 'Görüntülenecek sürüm yok.',
	'notfound.roles':'Rol listesi boş.',
    'notfound.icons':'Simge listesi boş.',

	'format.date.header': 'HH:mm dd/MM/yyyy',

	'menu.about': 'Hakkında',
	'menu.profile': 'Profil',
	'menu.panel.master': 'Ana Panel',
	'menu.panel.main': 'Ana panel',
	'menu.logout': 'Çıkış yap',
	'menu.functions': 'İşlevler',
	'menu.settings': 'Ayarlar',
	'menu.show.hints': 'İpuçlarını göster',

	'plugin.name.not.specified': '<< İşlev adı belirtilmedi >>',

	'breadcrumb.summary': 'Özet',
	'breadcrumb.devices': 'Cihazlar',
	'breadcrumb.applications': 'Uygulamalar',
	'breadcrumb.configurations': 'Yapılandırmalar',
	'breadcrumb.files': 'Dosyalar',
	'breadcrumb.default.design': 'Varsayılan olarak tasarım',
	'breadcrumb.common.settings': 'Aygıt Tablo Görünümü',
	'breadcrumb.language.settings': 'Dil ve Diğer Ayarlar',
	'breadcrumb.license.settings': 'Lisans',
	'breadcrumb.users': 'Kullanıcılar',
	'breadcrumb.groups': 'Gruplar',
	'breadcrumb.hints': 'İpuçları',
	'breadcrumb.plugins': 'Eklentiler',
	'breadcrumb.config.details': 'Ayrıntılar',
	'breadcrumb.application.versions': 'Sürümler',

	'app.name': 'Headwind MDM',
	'app.vendor.name':"h-mdm.com",
	'app.vendor.link':"https://h-mdm.com",
	'app.description': 'açık kaynaklı bir mobil cihaz yönetim sistemidir',
	'app.title': '${appName} Web Paneli',

	'box.show.my.apps.only': 'Yalnızca uygulamalarımı görüntüle',
	'configuration.app.version.upgrade.message': 'Yüklü sürüm ${installedVersion}, mevcut sürüm ${latestVersion}',

	'about.line.1': '${appName} kontrol paneli',
	'about.line.2': 'Android için Enterprise başlatıcısı',
	'about.line.3': 'Sürüm ${versionNumber}',
	'about.line.4': 'Yüklü eklentiler',

	'common.app.clarification': 'Bu uygulama herkese açıktır ve düzenlemeye açık değildir. Bu uygulamanın başka bir sürümünü eklemek için lütfen yöneticiyle iletişime geçin.',

	'qrcode.help.line1': 'Android cihazı (sürüm 7 veya üzeri) yönetilen (kurumsal) modda ayarlamak için:',
	'qrcode.help.line2': 'Cihazı fabrika ayarlarına sıfırla',
	'qrcode.help.line3': 'Başlangıç ekranının herhangi bir yerine 7 kez dokunun (gizli bir QR kodu tarama moduna girmelisiniz)',
	'qrcode.help.line4': 'Cihaz talimatlarını izleyin: şartları kabul edin, Wi-Fi\'ye bağlanın, bu QR kodunu tarayın',
	'qrcode.help.line5': 'QR kodu ${appName} için cihaz kimliğini içerebilir (bu nedenle mobil cihazda girmenize gerek yoktur). Cihaz kimliğini QR koduna yerleştirmek için, bu ekranda cihaz kimliğini girin ve "Yenile"ye tıklayın.',

	'form.configuration.app.version.select.select.title': 'Yüklenecek sürümü seçin',
	'form.configuration.app.version.select.version.check.off': 'Sürüm denetimini devre dışı bırak',
	'form.configuration.app.version.select.upgrade.warning': '"${v1}" uygulamasını "${v2}" yapılandırması için "${v3}" sürümüne yükseltin mi?',
	'form.configuration.app.version.select.downgrade.warning': 'Sürümü düşürün TÜM BU UYGULAMALARI tüm cihazlardan SİLİN! "${v1}" uygulama sürümünü "${v2}" sürümüne düşürün mü? ',

	'hint.step.1': 'Cihaz kaydını başlatmak için buraya tıklayın',
	'hint.step.2': 'QR kodunu açmak için buraya tıklayın',
	'hint.step.3': 'Cihazda QR kodu tarayıcısının nasıl açılacağını görmek için buraya tıklayın',
	'hint.step.4': '«Cihazlar» sekmesinde kullanılabilir bir cihaz kimliği bulun. QR koduna eklemek için «Yenile»ye tıklayın.',

	'ie.browser.notice.1': 'Ne yazık ki Internet Explorer desteklenmiyor.',
	'ie.browser.notice.2': '${appName} - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a>\'u kullanmak için önerilen tarayıcı.',

	'form.resolved.duplicate.pkg.text1': 'Paket Kimliği "${pkg}" aşağıda listelenen uygulamalar tarafından zaten kullanılıyor.',
	'form.resolved.duplicate.pkg.text2': 'Yeni bir uygulama mı yoksa mevcut bir uygulamanın yeni bir sürümünü mü eklemek istiyorsunuz?',
	'form.resolved.duplicate.pkg.text3': 'Yeni sürüm',
	'form.resolved.duplicate.pkg.text4': 'Paket Kimliği "${pkg}" zaten ${apps} uygulamaları tarafından kullanılıyor',
	'form.resolved.duplicate.pkg.text5': 'Paket kimliğini değiştirmek istediğinizden emin misiniz?',

	'tooltip.usage.byconfigurations': 'Yapılandırmalar tarafından kullanılıyor',
	'tooltip.usage.byapps': 'Uygulamalar tarafından kullanılıyor',
	'tooltip.usage.byicons': 'Simgeler tarafından kullanılıyor',

	'form.devices.label.params.more': 'Daha fazla parametre',
	'form.devices.label.params.less': 'Daha az parametre',
	'form.devices.label.installation.status': 'Kurulum durumu',
	'format.devices.date.createTime': 'dd/MM/yyyy HH:mm:ss',
	'format.devices.date.datePicker': 'dd-MM-yyyy',
	'form.devices.fast.search': 'Numaraya göre hızlı arama',

	'form.devices.selection.install.status.default': 'Kurulum durumu ...',
	'form.devices.selection.install.status.all': 'Tümü',
	'form.devices.selection.install.status.success': 'Başarılı',
	'form.devices.selection.install.status.version.mismatch': 'Sürüm Uyuşmazlığı',
	'form.devices.selection.install.status.failure': 'Başarısız',
	'form.devices.selection.imei.changed': 'IMEI yakın zamanda değiştirildi',

	'search.placeholder.launcher.version': 'Başlatıcı Sürümü',
	'error.date.range.invalid': 'Geçersiz tarih interval',

	'form.selection.status.any': 'Herhangi bir değer',
	'form.selection.status.all': 'Tümü',
	'form.selection.status.yes': 'Evet',
	'form.selection.status.no': 'Hayır',

	'form.devices.selection.status': 'Durum ...',
	'form.devices.selection.online': 'Çevrimiçi',
	'form.devices.selection.offline': 'Çevrimdışı',
	'form.devices.selection.number': 'Bir sayı girin',

	'form.devices.selection.online.status.custom': 'Zaman girin',
	'form.devices.selection.online.status.1': '15 dakika',
	'form.devices.selection.online.status.2': '30 dakika',
	'form.devices.selection.online.status.3': '1 saat',
	'form.devices.selection.online.status.4': '2 saat',
	'form.devices.selection.online.status.5': '6 saat',
	'form.devices.selection.online.status.6': '1 gün',
	'form.devices.selection.online.status.7': '2 gün',
	'form.devices.selection.online.status.8': '3 gün',
	'form.devices.selection.online.status.9': '1 hafta',
	'form.devices.selection.online.status.10': '1 ay',

	'form.devices.selection.online.status.label': 'dakika(lar)',
	'form.devices.status.ago': 'önce',
	'form.devices.status.minutes': 'd',
	'form.devices.status.hours': 'h',
	'form.devices.status.days': 'g',
	'form.devices.status.weeks': 'hafta(lar)',
	'form.devices.status.months': 'paz',
	'form.devices.status.years': 'yıl(lar)',

	'customer.type.demo': 'Demo',
	'customer.type.small': 'Profesyonel',
	'customer.type.corporate': 'Kurumsal',
	'customer.type.master': 'Birincil',

	'customer.type.options.all': 'Tüm tipler',
	'customer.status.options.all': 'Tüm durumlar',

	'account.expiring': 'Hesabınız ${days} gün içinde sona erecek. Lütfen hesabınızı yenilemek için satıcıyla iletişime geçin.',
	'account.expired.short': 'Hesabınızın süresi doldu!',
	'account.expired': 'Hesabınızın süresi doldu. Lütfen hesabınızı yenilemek için satıcıyla iletişime geçin.',
	'device.limit.achieved': 'Limitinize ulaştığınız için cihaz ekleyemiyorsunuz. Lütfen bazı cihazları kaldırın veya cihaz sınırınızı uzatmak için satıcıyla iletişime geçin.',

	'menu.updates': 'Güncellemeleri kontrol edin',
	'updates.title': 'Güncellemeler',
	'updates.disabled.custom': 'Özel sürüm, lütfen manuel olarak güncelleyin',
	'updates.disabled.not_master': 'Barındırma sağlayıcısından güncelleme yapmasını isteyin',
	'updates.disabled.multiple': 'Birden fazla uygulama sürümü, lütfen manuel olarak güncelleyin',
	'updates.disabled.error': 'Dahili sunucu hatası',
	'updates.disabled.download': 'Güncelleme indirilirken hata oluştu',
	'updates.application': 'Uygulama',
	'updates.current.version': 'Geçerli sürüm',
	'updates.available.version': 'Mevcut sürüm',
	'updates.downloaded': 'İndirildi',
	'updates.auto.update': 'Mobil uygulamaları otomatik olarak güncelle (üretimde dikkatli kullan!)',
	'updates.enable.stats': 'Sistem performansını iyileştirmek için kullanım istatistiklerini servis sağlayıcıya gönder',
	'updates.get': 'Güncellemeleri al',
	'updates.checking': 'Güncellemeler kontrol ediliyor...',
	'updates.getting': 'Güncellemeler alınıyor...',
	'updates.success': 'Güncelleme tamamlandı',
	'updates.web.hint': 'Web uygulaması güncellemesini tamamlamak için SSH konsolunda "/opt/hmdm/update-web-app.sh" kabuk betiğini çalıştırın',

	'manual.title': 'Headwind MDM kurulum kılavuzu',
	'manual.domain': 'Alan adı',
	'manual.domain.placeholder': 'Headwind MDM örneğinizin alan adı',
	'manual.key': 'Destek anahtarı',
	'manual.key.placeholder': 'XXXX-XXXX-XXXX-XXXX',
	'manual.submit': 'Kılavuzları al',
	'manual.key.invalid': 'Anahtar geçerli değil!',
	'manual.option.select': '(Lütfen kılavuzu seçin)',
	'manual.option.0': 'Headwind MDM\'nin yeni bir örneğini kur',
	'manual.option.1': 'Headwind MDM Topluluğunu yükselt',
	'manual.option.2': 'Headwind Remote ve URL Filtreleme eklentilerini kur',
	'manual.option.3': 'Headwind Remote\'un yeni bir örneğini kur',
	'manual.license.premium': 'Premium',
	'manual.license.enterprise': 'Enterprise',

	'permission.edit_device_app_settings': 'Cihaza özgü uygulama ayarlarını yönet',
	'permission.plugins_customer_access_management': 'Kullanılabilir eklentileri yönet',
	'permission.plugin_audit_access': 'Denetim günlüğünü görüntüle',
	'permission.plugin_contacts_access': 'Kişileri yönet',
	'permission.plugin_deviceexport_access': 'Cihazları dışa aktar',
	'permission.plugin_deviceimport_access': 'Cihazları içe aktar',
	'permission.plugin_deviceinfo_access': 'Cihazın ayrıntılı bilgilerini görüntüle',
	'permission.plugin_devicelocations_access': 'Cihazları haritada görüntüle',
	'permission.plugin_devicelocations_settings_access': 'Harita eklentisini yapılandır',
	'permission.plugin_devicelog_access': 'Cihaz günlüklerini görüntüle',
	'permission.plugin_devicereset_access': 'Cihazları sıfırla ve yeniden başlat',
	'permission.plugin_licensing_access': 'Lisansa erişim (kullanım dışı)',
	'permission.plugin_messaging_send': 'Mesaj gönder',
	'permission.plugin_messaging_delete': 'Gönderilen mesajları sil',
	'permission.plugin_photo_remove_photo': 'Fotoğrafları sil',
	'permission.settings': 'Ayarları yönet',
	'permission.configurations': 'Yapılandırmaları görüntüle',
	'permission.edit_devices': 'Cihaz bilgilerini düzenle',
	'permission.edit_device_desc': 'Cihaz açıklamasını düzenle',
    'permission.enroll_devices': 'Cihazları QR koduyla kaydedin',
	'permission.plugin_apuppet_access': 'Uzaktan kumanda',
	'permission.plugin_knox_access': 'Knox eklentisi',
	'permission.add_config': 'Yapılandırmaları ekle',
	'permission.copy_config': 'Yinelenen yapılandırmalar',
	'permission.plugin_openvpn_access': 'OpenVPN eklentisi',
	'permission.plugin_photo_access': 'Fotoğraf eklentisi',
	'permission.push_api': 'Push API\'sine erişim',
	'permission.plugin_urlfilter_access': 'URL filtreleme',
	'permission.plugin_push_send': 'Push mesajları gönder',
	'permission.plugin_push_delete': 'Push mesajlarını sil',
	'permission.get_updates': 'Şunları kontrol et güncellemeler',
	'permission.plugin_xtra_access': 'Premium sürüm talebi',
	'permission.applications': 'Uygulamaları görüntüle',
	'permission.edit_applications': 'Uygulamaları yönet',
	'permission.edit_application_versions': 'Uygulama sürümlerini yönet',
	'permission.files': 'Dosyaları görüntüle',
	'permission.edit_files': 'Dosyaları yönet',

	'yes': 'yes',
	'no': 'no'
};
