if (! document.localization) document.localization = [];

document.localization ['vi_VN'] = {
    'login.username': 'Tên đăng nhập hoặc email',
    'login.username.placeholder': 'Nhập tên đăng nhập hoặc email',
    'login.password': 'Mật khẩu:',
    'login.password.placeholder': 'Nhập mật khẩu',
    'login.submit': 'Đăng nhập',
    'login.password.incorrect': 'Tên đăng nhập hoặc mật khẩu không hợp lệ',
    'login.password.recovery': 'Quên mật khẩu?',
    'recovery.password': 'Khôi phục mật khẩu',
    'recovery.password.success': 'Hướng dẫn khôi phục mật khẩu đã được gửi tới email của bạn',
    'login.no.account': 'Chưa có tài khoản?',
    'login.signup': 'Đăng ký',
    'signup.title': 'Bắt đầu',
    'signup.email': 'Địa chỉ email của bạn',
    'signup.email.placeholder': 'Nhập một địa chỉ email hợp lệ',
    'signup.email.invalid': 'Vui lòng nhập một địa chỉ email hợp lệ',
    'signup.terms.agree': 'Tôi đồng ý với',
    'signup.terms.terms': 'điều khoản và điều kiện',
    'signup.submit': 'Đăng ký',
    'signup.progress': 'Đang đăng ký...',
    'signup.email.used': 'Đã có khách hàng đăng ký với email này',
    'signup.name.used': 'Đã có khách hàng đăng ký với tên đăng nhập này',
    'signup.complete': 'Cảm ơn bạn đã đăng ký!',
    'signup.email.check': 'Vui lòng kiểm tra email và làm theo liên kết để hoàn tất đăng ký!',
    'signup.complete.title': 'Tài khoản của bạn tại ${appName} gần như đã sẵn sàng!',
    'signup.ready.title': 'Tài khoản của bạn tại ${appName} đã sẵn sàng!',
    'signup.customer.id': 'Tên đăng nhập',
    'signup.customer.id.placeholder': 'Chỉ dùng chữ và số',
    'signup.customer.id.invalid': 'Vui lòng dùng 6 ký tự trở lên, chỉ gồm chữ và số',
    'signup.first.name': 'Tên',
    'signup.first.name.placeholder': 'Tên của bạn (bắt buộc)',
    'signup.last.name': 'Họ',
    'signup.last.name.placeholder': 'Họ của bạn (bắt buộc)',
    'signup.company': 'Tên công ty',
    'signup.company.placeholder': 'Tên doanh nghiệp của bạn (không bắt buộc)',
    'signup.description': 'Bạn sẽ sử dụng MDM như thế nào?',
    'signup.description.placeholder': 'Điều này sẽ giúp đội ngũ của chúng tôi hỗ trợ bạn',
    'signup.password': 'Mật khẩu',
    'signup.password.repeat': 'Nhập lại mật khẩu',
    'signup.password.placeholder': '6+ ký tự',
    'signup.password.short': 'Vui lòng nhập ít nhất 6 ký tự',
    'signup.password.not.match': 'Mật khẩu không khớp',
    'signup.finalized.title': 'Tài khoản của bạn đã sẵn sàng!',
    'signup.finalized.description': 'Trong thời gian ngắn, bạn sẽ nhận được email chứa hướng dẫn hữu ích. Vui lòng kiểm tra email này và đăng nhập vào bảng điều khiển web bằng tên đăng nhập và mật khẩu.',
    'signup.token.invalid.title': 'Mã token không hợp lệ hoặc đã được sử dụng',
    'signup.token.invalid.description': 'Vui lòng thử đăng ký lại để tạo tài khoản mới!',
    'header.label.username': 'Tên đăng nhập',
    'summary.devices.status': 'Trạng thái thiết bị',
    'summary.devices.active': 'Đang hoạt động',
    'summary.devices.idle': 'Nhàn rỗi',
    'summary.devices.offline': 'Ngoại tuyến',
    'summary.devices.enrollment': 'Tóm tắt đăng ký',
    'summary.devices.enrolled.total': 'Tổng đã đăng ký',
    'summary.devices.enrolled.earlier': 'Đã đăng ký trước đó',
    'summary.devices.enrolled.monthly': '30 ngày qua',
    'summary.devices.installation.status': 'Trạng thái ứng dụng',
    'summary.devices.installation.completed': 'Hoàn tất',
    'summary.devices.version.mismatch': 'Phiên bản không khớp',
    'summary.devices.installation.failed': 'Cài đặt thất bại',
    'summary.devices.enrolled.lastyear': '12 tháng qua',
    'devices.group.options.all': 'Tất cả nhóm',
    'devices.configuration.options.all': 'Tất cả cấu hình',
    'devices.permissions.all': 'Tất cả quyền đã được cấp',
    'devices.permissions.not.as.device.admin': '- Ứng dụng chưa được cài đặt như quản trị viên thiết bị',
    'devices.permissions.window.overlap.prohibited': '- Không cho phép phủ cửa sổ lên các cửa sổ khác',
    'devices.permissions.history.access.prohibited': '- Truy cập lịch sử sử dụng chưa được cấu hình',
    'devices.unknown': 'Không xác định',
    'devices.model.unknown': 'Không xác định',
    'devices.date.unknown': 'không xác định',
    'devices.date.format': 'dd/MM/yy HH:mm',
    'devices.app.installed': '- ${applicationName}: Đã cài đặt.',
    'devices.app.not.installed': '- ${applicationName}: Chưa cài đặt.',
    'devices.app.version.available': ', có sẵn ${applicationVersion}',
    'devices.app.installed.and.version.available': '- ${applicationName}: đã cài ${applicationInstalledVersion}, có sẵn ${applicationVersionAvailable}',
    'devices.app.needs.removal': '${applicationVersion}, cần gỡ bỏ',
    'devices.no.data': 'Thiết bị chưa truyền dữ liệu',
    'devices.settings.conformance.broken': 'Không khớp với cài đặt: (${serverData})',
    'devices.file.installed': '- ${file}: đã cài đặt',
    'devices.file.not.installed': '- ${file}: chưa cài đặt.',
    'devices.file.lastUpdate.differs': '- ${file}: khác thời gian chỉnh sửa ${diff} phút',
    'button.apply': 'Áp dụng',
    'button.gps.on': 'Bật GPS',
    'button.wifi.on': 'Bật Wi-Fi',
    'button.notify.update': 'Thông báo khi có cập nhật',
    'button.app.settings': 'Cài đặt ứng dụng',
    'button.ok': 'OK',
    'button.help': 'Trợ giúp',
    'button.new.app': 'Ứng dụng mới',
    'button.new.app.version': 'Phiên bản mới',
    'button.upgrade': 'Nâng cấp',
    'button.renew.config': 'Cập nhật trên thiết bị',
    'button.common': 'Ứng dụng chung',
    'button.close': 'Đóng',
    'button.yes': 'Có',
    'button.cancel': 'Hủy',
    'button.save': 'Lưu',
    'button.save.and.close': 'Lưu và đóng',
    'button.more': 'Thêm ...',
    'button.cleanup': 'Xóa',
    'button.add': 'Thêm',
    'button.add.icon': 'Biểu tượng mới',
    'button.search': 'Tìm kiếm',
    'button.export': 'Xuất',
    'button.change': 'Sửa',
    'button.copy': 'Sao chép',
    'button.qrcode': 'Mã QR',
    'button.application': 'Ứng dụng',
    'button.change.password': 'Đổi mật khẩu',
    'button.set.configuration': 'Đặt cấu hình',
    'button.set.group': 'Đặt nhóm',
    'button.group.action': 'Thao tác nhóm',
    'button.delete': 'Xóa',
    'button.login': 'Đăng nhập',
    'button.renew.code': 'Làm mới',
    'button.configurations': 'Cấu hình',
    'button.set.configurations': 'Chỉ định cấu hình',
    'button.edit.versions': 'Phiên bản',
    'button.edit': 'Sửa',
    'button.change.common.app': 'Chỉnh sửa ứng dụng chia sẻ',
    'button.delete.common.app': 'Xóa ứng dụng chia sẻ',
    'button.turn.common.app': 'Đặt thành ứng dụng chung',
    'button.hints.enable': 'Hiện gợi ý',
    'button.hints.disable': 'Ẩn gợi ý',
    'button.show.password': 'Hiện mật khẩu',
    'button.hide.password': 'Ẩn mật khẩu',
    'question.impersonate.user': 'Đăng nhập vào ứng dụng với tư cách quản trị viên của tổ chức \'${customerName}\'?',
    'question.change.user': 'Đăng nhập vào ứng dụng với tư cách người dùng \'${userName}\'?',
    'question.delete.file': 'Xóa tệp \'${fileName}\'?',
    'question.delete.customer': 'Xóa tổ chức \'${customerName}\'?',
    'question.delete.user': 'Xóa người dùng \'${username}\'?',
    'question.delete.application': 'Xóa ứng dụng \'${applicationName}\'?',
    'question.delete.application.version': 'Xóa phiên bản \'${applicationVersion}\'?',
    'question.delete.configuration': 'Xóa cấu hình \'${configurationName}\'?',
    'question.delete.group': 'Xóa nhóm \'${groupName}\'?',
    'question.delete.role': 'Xóa vai trò \'${roleName}\'?',
    'question.delete.icon': 'Xóa biểu tượng \'${iconName}\'?',
    'question.delete.device.bulk': 'Xóa các thiết bị được chọn?',
    'question.delete.device': 'Xóa thiết bị có số \'${deviceNumber}\'?',
    'question.exit.without.saving': 'Các thay đổi chưa được lưu. Bạn vẫn muốn rời khỏi trang này?',
    'question.turn2common.application': 'Chia sẻ ứng dụng \'${applicationName}\'?',
    'question.app.upgrade': 'Cập nhật ứng dụng \'${v1}\' lên phiên bản mới nhất cho cấu hình \'${v2}\'?',

    'error.application.setting.empty.app': 'Chỉ định ứng dụng',
    'error.application.setting.empty.name': 'Nhập tên',
    'error.application.setting.empty.value': 'Chỉ định giá trị',
    'error.icon.dimension.invalid': 'Biểu tượng phải là hình vuông',
    'error.icon.empty.name': 'Nhập tên biểu tượng',
    'error.icon.empty.file': 'Tải lên tệp biểu tượng',
    'error.application.version.pkg.mismatch': 'ID gói của tệp (${actual}) không tương ứng với ứng dụng (${expected})',
    'error.empty.user': 'Chọn người dùng',
    'error.empty.user.name': 'Điền tên người dùng',
    'error.empty.user.login': 'Điền tên đăng nhập người dùng',
    'error.empty.user.role': 'Chọn vai trò người dùng',
    'error.empty.password': 'Nhập mật khẩu mới',
    'error.empty.password.confirm': 'Nhập xác nhận mật khẩu',
    'error.user.not.found': 'Không tìm thấy người dùng',
    'error.email.not.configured': 'Email chưa được cấu hình',
    'error.email.not.found': 'Email người dùng chưa được thiết lập',
    'error.empty.group.name': 'Điền tên nhóm',
    'error.empty.configuration': 'Chỉ định cấu hình',
    'error.empty.configuration.name': 'Điền tên cấu hình',
    'error.empty.configuration.password': 'Điền mật khẩu',
    'error.empty.configuration.contentApp': 'Chưa chỉ định ứng dụng nội dung',
    'error.empty.group': 'Thêm một hoặc nhiều thiết bị vào nhóm',
    'error.invalid.character': 'Số thiết bị không được chứa ký tự / ? &',
    'error.invalid.configuration.mainApp': 'Trong cài đặt MDM, ứng dụng chính được chọn không đúng',
    'error.invalid.configuration.contentApp': 'Ứng dụng nội dung trong cài đặt MDM không hợp lệ',
    'error.mismatch.password': 'Mật khẩu và xác nhận mật khẩu phải khớp',
    'error.empty.customer.name': 'Điền tên tổ chức',
    'error.empty.customer.prefix': 'Điền tiền tố số thiết bị',
    'error.empty.customer.device.configuration': 'Chọn cấu hình thiết bị',
    'error.empty.customer.duplicate.prefix': 'Tiền tố đã được sử dụng',
    'error.duplicate.customer.name': 'Tổ chức với tên này đã tồn tại. Hãy thử tên khác.',
    'error.duplicate.group.name': 'Nhóm với tên này đã tồn tại. Hãy thử tên khác.',
    'error.duplicate.configuration.name': 'Cấu hình với tên này đã tồn tại. Hãy thử tên khác.',
    'error.duplicate.device.number': 'Đã tồn tại thiết bị với số này',
    'error.internal.server': 'Lỗi máy chủ nội bộ',
    'error.permission.denied': 'Không có quyền thực hiện',
    'error.request.failure': 'Yêu cầu thất bại',
    'error.configuration.device.use': 'Không thể xóa cấu hình này vì nó đang được sử dụng trên thiết bị. Trước hết vào \'Devices\', tìm các thiết bị đang dùng cấu hình này và thay đổi cài đặt của chúng.',
    'error.invalid.system.update.time': 'Khoảng thời gian cài đặt không hợp lệ',
    'error.size.limit.exceeded': 'Vượt quá giới hạn lưu trữ',
    'error.configuration.file.empty.name': 'Nhập tên tệp',
    'error.configuration.file.empty.desc': 'Chỉ định mô tả tệp',
    'error.configuration.file.empty.path': 'Chỉ định đường dẫn trên thiết bị',
    'error.configuration.file.empty.file': 'Vui lòng tải lên tệp',
    'error.configuration.file.empty.url': 'Vui lòng chỉ định URL của tệp',
    'error.notfound.device': 'Không tìm thấy thiết bị',
    'error.duplicate.device': 'Đã tồn tại thiết bị với cùng số',
    'error.duplicate.login': 'Tên đăng nhập này đã được sử dụng',
    'error.duplicate.email': 'Đã tồn tại người dùng với email này',
    'error.duplicate.group': 'Đã tồn tại nhóm với tên này',
    'error.duplicate.application': 'Đã tồn tại ứng dụng với ID gói và phiên bản này',
    'error.recent.application.version.exists': 'Đã tồn tại phiên bản ứng dụng mới hơn',
    'error.common.application.access.prohibited': 'Quản lý các ứng dụng chung chỉ được phép bởi Siêu-Quản trị viên',
    'error.application.config.reference.exists': 'Ứng dụng đang được sử dụng trong cấu hình và không thể xóa',
    'error.application.version.deletion.prohibited': 'Phiên bản là duy nhất hoặc đang được sử dụng trong cấu hình và không thể xóa',
    'error.duplicate.file': 'Đã tồn tại tệp với cùng tên',
    'error.used.file': 'Tệp này đang được sử dụng',
    'error.version.exists': 'Đã tồn tại phiên bản tương tự của ứng dụng',
    'error.duplicate.configuration': 'Đã tồn tại cấu hình với tên này',
    'error.duplicate.role.name': 'Đã tồn tại vai trò với tên này',
    'error.empty.role.name': 'Vui lòng chỉ định tên vai trò',
    'error.duplicate.icon.name': 'Đã tồn tại biểu tượng với tên này',
    'error.notfound.customer.admin': 'Không tìm thấy tài khoản quản trị viên',
    'error.apk.file.required': 'Chọn tệp có phần mở rộng .apk hoặc .xapk',
    'error.apk.parse': 'Đã xảy ra lỗi khi phân tích tệp',
    'error.package.not.match': 'ID gói không khớp',
    'error.empty.app.name': 'Nhập tên ứng dụng',
    'error.empty.app.pkg': 'Nhập ID gói',
    'error.empty.app.url': 'Nhập URL',
    'error.empty.app.iconText': 'Nhập văn bản cho biểu tượng',
    'error.empty.app.version': 'Nhập phiên bản ứng dụng',
    'error.notempty.group': 'Nhóm này có một hoặc nhiều thiết bị. Bạn không thể xóa nó.',
    'error.file.empty': 'Tải lên tệp mới',
    'error.file.deletion': 'Lỗi khi xóa tệp trên máy chủ',
    'error.file.save': 'Lỗi khi lưu tệp trên máy chủ',
    'error.password.wrong': 'Mật khẩu không hợp lệ',
    'error.password.empty': 'Chưa chỉ định mật khẩu',
    'error.password.weak': 'Mật khẩu yếu',
    'error.params.missing': 'Thiếu tham số:',
    'error.empty.push.options': 'Vui lòng chọn tùy chọn Push',
    'error.app.name.exists': 'Đã tồn tại ứng dụng khác với tên này. Vui lòng chọn tên duy nhất.',
    'table.filtering.check.all': 'Chọn tất cả',
    'table.filtering.uncheck.all': 'Bỏ chọn tất cả',
    'table.filtering.suffix.configuration': 'cấu hình',
    'table.filtering.suffix.group': 'nhóm',
    'table.filtering.suffix.permission': 'quyền',
    'table.filtering.no.selected.configuration': 'Chưa chọn cấu hình nào',
    'table.filtering.no.selected.group': 'Chưa chọn nhóm nào',
    'table.filtering.no.selected.permission': 'Chưa chọn quyền nào',

    'success.admin.created': 'Tài khoản quản trị viên đã được tạo:\n ${adminCredentials}',
    'success.uploading.file': 'Tệp đang được tải lên máy chủ ...',
    'success.loading.devices': 'Đang tải danh sách thiết bị ...',
    'success.loading.customer': 'Đang tải chi tiết khách hàng ...',
    'success.file.uploaded': 'Tệp đã tải lên thành công.',
    'success.file.uploaded.need.save': 'Tệp đã tải lên thành công. Nhập đường dẫn tương đối và nhấn \'Lưu\'.',
    'success.settings.design.saved': 'Đã lưu cài đặt thiết kế thành công',
    'success.settings.common.saved': 'Đã lưu cài đặt bảng thiết bị thành công',
    'success.settings.saved': 'Đã lưu cài đặt thành công',
    'success.settings.apiKey.saved': 'Đã lưu khóa API thành công',
    'success.settings.hints.enabled': 'Đã bật gợi ý',
    'success.settings.hints.disabled': 'Đã tắt gợi ý',
    'success.configuration.saved': 'Đã lưu cấu hình thành công',
    'success.operation.completed': 'Thao tác hoàn tất thành công',
    'success.plugins.disabled': 'Đã lưu cài đặt thành công',
    'success.config.update.notification': 'Lệnh cập nhật cấu hình đã được gửi tới thiết bị',
    'success.config.update.device.app.settings.notification': 'Lệnh cập nhật cài đặt ứng dụng đã được gửi tới thiết bị.',

    'form.icon.title': 'Biểu tượng',
    'form.icon.name': 'Tên',
    'form.icon.file': 'Tệp',

    'configuration.add.warning': 'Bạn có chắc muốn tạo một cấu hình trống? Bạn sẽ cần thêm thủ công tất cả ứng dụng hệ thống cần thiết. Hãy cân nhắc sao chép và chỉnh sửa từ một cấu hình có sẵn.',
    'configuration.remove.warning': 'Bạn có chắc muốn xóa cấu hình cuối cùng? Bạn sẽ mất thông tin về các ứng dụng hệ thống cần thiết.',

    'form.configuration.title': 'Cấu hình',
    'form.configuration.title.typical': 'Cấu hình điển hình',

    'form.configuration.settings.auto.update': 'Tự động cập nhật',
    'form.configuration.settings.system.update': 'Cập nhật hệ thống',
    'form.configuration.settings.system.update.default': 'Mặc định',
    'form.configuration.settings.system.update.immediate': 'Ngay lập tức',
    'form.configuration.settings.system.update.scheduled': 'Lên lịch',
    'form.configuration.settings.system.update.postponed': 'Hoãn lại',
    'form.configuration.settings.system.update.time': 'Thời gian cài đặt',
    'form.configuration.settings.system.update.time.from': 'từ:',
    'form.configuration.settings.system.update.time.to': 'đến:',
    'form.configuration.settings.system.schedule.app.update': 'Lên lịch cập nhật ứng dụng',
    'form.configuration.settings.system.app.update.time': 'Thời gian cập nhật ứng dụng',

    'form.configuration.settings.download.updates': 'Tải nội dung',
    'form.configuration.settings.download.updates.unlimited': 'Không giới hạn',
    'form.configuration.settings.download.updates.limited': '3 lần thử trong mạng di động',
    'form.configuration.settings.download.updates.wifi': 'Chỉ qua Wi-Fi',

    'form.configuration.settings.block.status.bar': 'Khóa thanh trạng thái',
    'form.configuration.settings.block.status.bar.hint': 'Thiết lập này đã lỗi thời và chỉ hoạt động tốt trên Android 6 trở xuống. Để khóa thanh trạng thái trên các phiên bản Android mới hơn, hãy dùng chế độ kiosk (cài đặt MDM).',

    'form.configuration.settings.mdm.kiosk.mode': 'Chế độ kiosk',
    'form.configuration.settings.mdm.app.main': 'Ứng dụng MDM',
    'form.configuration.settings.mdm.component.event.receiver': 'Lớp nhận sự kiện quản trị',
    'form.configuration.settings.mdm.component.event.receiver.placeholder': 'Phải là com.hmdm.launcher.AdminReceiver',
    'form.configuration.settings.mdm.component.wifi.ssid': 'SSID WiFi',
    'form.configuration.settings.mdm.component.wifi.ssid.placeholder': 'SSID WiFi để đăng ký – để trống để nhập thủ công',
    'form.configuration.settings.mdm.component.wifi.password': 'Mật khẩu WiFi',
    'form.configuration.settings.mdm.component.wifi.password.placeholder': 'Mật khẩu WiFi để đăng ký – để trống để nhập thủ công',
    'form.configuration.settings.mdm.component.wifi.security': 'Loại bảo mật WiFi',
    'form.configuration.settings.mdm.component.wifi.notice': 'Lưu ý: các cài đặt WiFi này chỉ áp dụng cho lần đăng ký ban đầu!',
    'form.configuration.settings.mdm.component.server.url': 'URL máy chủ mới',
    'form.configuration.settings.mdm.component.server.url.placeholder': 'Dùng để di chuyển sang máy chủ MDM mới',
    'form.configuration.settings.mdm.app.content': 'Ứng dụng nội dung',

    'form.configuration.settings.mdm.kiosk.home': 'Bật nút Trang chủ',
    'form.configuration.settings.mdm.kiosk.recents': 'Bật nút Gần đây',
    'form.configuration.settings.mdm.kiosk.notifications': 'Bật thông báo',
    'form.configuration.settings.mdm.kiosk.system.info': 'Bật thông tin thanh trạng thái',
    'form.configuration.settings.mdm.kiosk.keyguard': 'Bật khóa màn hình',
    'form.configuration.settings.mdm.kiosk.lock.buttons': 'Khóa nút Nguồn',

    'form.configuration.settings.mdm.mobile.enrollment': 'Đăng ký bằng dữ liệu di động',
    'form.configuration.settings.mdm.encrypt.device': 'Mã hóa bộ nhớ thiết bị',
    'form.configuration.settings.mdm.lock.safe.settings': 'Khóa cài đặt an toàn (WiFi, GPS, ...)',
    'form.configuration.settings.mdm.permissive': 'Chế độ mở (không khóa)',
    'form.configuration.settings.mdm.kiosk.exit': 'Nút thoát chế độ kiosk',
    'form.configuration.settings.mdm.kiosk.screen': 'Màn hình luôn bật',
    'form.configuration.settings.mdm.allowed.classes': 'Hoạt động được phép',
    'form.configuration.settings.mdm.allowed.classes.placeholder': 'Các lớp cách nhau bằng dấu phẩy, ví dụ: com.android.settings.homepage.SettingsHomepageActivity',
    'form.configuration.settings.mdm.restrictions': 'Giới hạn',
    'form.configuration.settings.mdm.restrictions.placeholder': 'Giới hạn MDM, cách nhau bằng dấu phẩy, ví dụ: no_sms,no_outgoing_calls,no_usb_file_transfer',
    'form.configuration.settings.mdm.launcher': 'Ghi đè URL trình khởi chạy',
    'form.configuration.settings.mdm.launcher.placeholder': 'URL trình khởi chạy thay thế để đăng ký trong các mạng kín',
    'form.configuration.settings.mdm.misc': 'Các mục QR code khác',
    'form.configuration.settings.mdm.misc.placeholder': 'Các mục cách nhau bằng dấu phẩy, ví dụ:\n\'android.app.extra.PROVISIONING_LOCALE\': \'de_DE\'',
    'form.configuration.settings.mdm.qrcode.url': 'URL mã QR',
    'form.configuration.settings.mdm.hint': 'Chọn ứng dụng chính và thành phần',

    'form.configuration.apps.search.label': 'Tìm:',
    'form.configuration.apps.sort.label': 'Sắp xếp:',
    'form.configuration.apps.sort.byname': 'Theo tên',
    'form.configuration.apps.sort.bypkg': 'Theo ID',
    'form.configuration.apps.no.apk': 'không có',
    'form.configuration.apps.show.systeam.apps': 'Hiển thị Ứng dụng Hệ thống',
    'form.configuration.apps.action.select': '(chọn)',
    'form.configuration.apps.action.install': 'Cài đặt',
    'form.configuration.apps.action.prohibit': 'Chặn',
    'form.configuration.apps.action.not.install': 'Không cài',
    'form.configuration.apps.action.delete': 'Xóa',
    'form.configuration.apps.action.permit': 'Cho phép',
    'form.configuration.apps.label.inherit': 'Kế thừa',
    'form.configuration.apps.label.show': 'Hiện',
    'form.configuration.apps.label.not.show': 'Ẩn',
    'form.configuration.apps.edit.details': 'Tham số bổ sung',
    'form.configuration.apps.keycode': 'Mã phím',
    'form.configuration.apps.bottom': 'Hiển thị ở hàng dưới',
    'form.configuration.apps.long.tap': 'Nhấn giữ mở cài đặt',
    'form.configuration.apps.hint': 'Gợi ý: để bỏ liên kết ứng dụng khỏi cấu hình, chọn hành động \'Chặn\' hoặc \'Không cài\'.',

    'form.configuration.settings.design.use.default': 'Dùng thiết kế mặc định',
    'form.configuration.settings.design.color.background': 'Màu nền',
    'form.configuration.settings.design.color.background.placeholder': 'Chọn màu',
    'form.configuration.settings.design.color.app.names': 'Màu tên ứng dụng',
    'form.configuration.settings.design.color.app.names.placeholder': 'Chọn màu',
    'form.configuration.settings.design.background.image.url': 'URL ảnh nền',
    'form.configuration.settings.design.background.image.url.placeholder': 'Nhập URL ảnh nền',
    'form.configuration.settings.design.icon': 'Kích thước biểu tượng',
    'form.configuration.settings.design.icon.small': 'Nhỏ',
    'form.configuration.settings.design.icon.medium': 'Trung bình (+20%)',
    'form.configuration.settings.design.icon.large': 'Lớn (+40%)',
    'form.configuration.settings.design.desktop.header': 'Tiêu đề desktop',
    'form.configuration.settings.design.desktop.header.no': 'Không',
    'form.configuration.settings.design.desktop.header.deviceid': 'Device ID',
    'form.configuration.settings.design.desktop.header.description': 'Mô tả',
    'form.configuration.settings.design.desktop.header.custom': 'Mẫu tùy chỉnh',
    'form.configuration.settings.design.desktop.header.hint': 'Đảm bảo tham số này được gửi tới thiết bị (Cài đặt - Chung và ngôn ngữ)',
    'form.configuration.settings.design.desktop.header.template': 'Nhập mẫu',
    'form.configuration.settings.design.desktop.header.template.placeholder': 'Dùng biến',

    'form.configuration.settings.design.display.status': 'Hiển thị thời gian và trạng thái pin',
    'form.configuration.settings.design.upload': 'Tải lên',
    'form.configuration.settings.common.name': 'Tên',
    'form.configuration.settings.common.name.placeholder': 'Nhập tên cấu hình',
    'form.configuration.settings.common.desc': 'Mô tả',
    'form.configuration.settings.common.desc.placeholder': 'Nhập mô tả cấu hình',
    'form.configuration.settings.common.admin.pwd': 'Mật khẩu mở khóa',
    'form.configuration.settings.common.admin.pwd.placeholder': 'Nhập mật khẩu mở khóa thiết bị',
    'form.configuration.settings.common.gps': 'GPS',
    'form.configuration.settings.common.gps.any': 'Bất kỳ',
    'form.configuration.settings.common.gps.off': 'Tắt',
    'form.configuration.settings.common.gps.on': 'Bật',
    'form.configuration.settings.common.bluetooth': 'Bluetooth',
    'form.configuration.settings.common.wifi': 'Wi-Fi',
    'form.configuration.settings.common.mobile.data': 'Dữ liệu di động',
    'form.configuration.settings.common.usb.storage': 'Chặn USB storage',
    'form.configuration.settings.common.brightness': 'Quản lý độ sáng',
    'form.configuration.settings.common.brightness.none': 'Không',
    'form.configuration.settings.common.brightness.auto': 'Tự động',
    'form.configuration.settings.common.brightness.manual': 'Giá trị',
    'form.configuration.settings.common.brightness.value': 'Độ sáng màn hình',
    'form.configuration.settings.common.timeout': 'Quản lý thời gian chờ màn hình',
    'form.configuration.settings.common.timeout.value': 'Thời gian chờ màn hình (s)',
    'form.configuration.settings.common.volume.block': 'Khóa âm lượng',
    'form.configuration.settings.common.volume.manage': 'Quản lý âm lượng',
    'form.configuration.settings.common.volume.value': 'Âm lượng',
    'form.configuration.settings.common.timezone.mode': 'Quản lý múi giờ',
    'form.configuration.settings.common.timezone.mode.default': 'Không quản lý',
    'form.configuration.settings.common.timezone.mode.auto': 'Tự động',
    'form.configuration.settings.common.timezone.mode.manual': 'Thủ công',
    'form.configuration.settings.common.timezone': 'Múi giờ',
    'form.configuration.settings.common.timezone.placeholder': 'ví dụ: America/Los_Angeles',
    'form.configuration.settings.common.timezone.link': 'Danh sách múi giờ',

    'form.configuration.settings.common.no.network.warning': 'CẢNH BÁO! Không tắt tất cả kênh kết nối, nếu không bạn sẽ không thể quản lý thiết bị!',
    'form.configuration.settings.common.autostart.foreground': 'Tự khởi động ứng dụng ở foreground',
    'form.configuration.settings.request.updates': 'Theo dõi vị trí',
    'form.configuration.settings.request.updates.donottrack': 'Không theo dõi hoạt động (dùng dữ liệu vị trí từ app bên thứ ba)',
    'form.configuration.settings.request.updates.gps': 'Theo dõi vị trí bằng GPS',
    'form.configuration.settings.request.updates.wifi': 'Theo dõi vị trí bằng Wi-Fi (cần bật dịch vụ Google)',
    'form.configuration.settings.request.updates.prompt.gps': 'Để theo dõi bằng GPS, bạn cần bật GPS',
    'form.configuration.settings.request.updates.prompt.wifi': 'Để theo dõi bằng Wi-Fi, bạn cần bật Wi-Fi',

    'form.configuration.settings.revoke.location.permission': 'Không cấp quyền vị trí',
    'form.configuration.settings.revoke.location.permission.hint': 'Nếu được đặt, quyền vị trí sẽ không được cấp cho agent MDM và nó không thể theo dõi vị trí thiết bị',
    'form.configuration.settings.apps.permissions': 'Quyền cho ứng dụng khác',
    'form.configuration.settings.apps.permissions.grant': 'Tự cấp tất cả quyền',
    'form.configuration.settings.apps.permissions.ask.location': 'Tự cấp tất cả, hỏi người dùng về quyền vị trí',
    'form.configuration.settings.apps.permissions.deny.location': 'Tự cấp tất cả, không cấp quyền vị trí',
    'form.configuration.settings.apps.permissions.ask.all': 'Hỏi người dùng cho tất cả quyền',
    'form.configuration.settings.push.options': 'Thông báo đẩy (Push)',
    'form.configuration.settings.push.options.mqtt.worker': 'MQTT (tiết kiệm pin)',
    'form.configuration.settings.push.options.mqtt.alarm': 'MQTT',
    'form.configuration.settings.push.options.polling': 'HTTP polling',
    'form.configuration.settings.push.options.mqtt.worker.hint': 'Gửi tin tức ngay lập tức khi thiết bị hoạt động. Tin có thể bị trễ vài giờ ở chế độ ngủ. MQTT dùng TCP port 31000, bật port trên firewall.',
    'form.configuration.settings.push.options.mqtt.alarm.hint': 'MQTT là giao thức nhẹ, tiêu thụ ít tài nguyên. MQTT dùng TCP port 31000, bật port trên firewall.',
    'form.configuration.settings.push.options.polling.hint': 'Long polling giữ kết nối HTTP mở, có thể tốn tài nguyên server. Không yêu cầu port ngoài HTTP(S).',
    'form.configuration.settings.push.options.keepalive': 'Thời gian Keep-Alive',
    'form.configuration.settings.minute.1': '1 minute',
    'form.configuration.settings.minutes.2': '2 minutes',
    'form.configuration.settings.minutes.3': '3 minutes',
    'form.configuration.settings.minutes.5': '5 minutes',
    'form.configuration.settings.minutes.10': '10 minutes',
    'form.configuration.settings.minutes.15': '15 minutes',
    'form.configuration.settings.password.mode': 'Yêu cầu mật khẩu',
    'form.configuration.settings.password.mode.any': 'Không',
    'form.configuration.settings.password.mode.present': 'Yêu cầu mật khẩu có mặt',
    'form.configuration.settings.password.mode.easy': 'Dễ (ít nhất 6 ký tự)',
    'form.configuration.settings.password.mode.moderate': 'Trung bình (8+ ký tự, chữ và số)',
    'form.configuration.settings.password.mode.strong': 'Mạnh (8+, hoa/thường, chữ số, ký tự đặc biệt)',
    'form.configuration.settings.show.wifi': 'Hiển thị cài đặt Wi-Fi khi lỗi kết nối',
    'form.configuration.settings.use.default.launcher': 'Chế độ nền',
    'form.configuration.settings.use.default.launcher.hint': 'Không thay launcher hệ thống, chỉ chạy dịch vụ MDM nền. Không khuyến nghị dùng với chế độ kiosk.',
    'form.configuration.settings.disable.screenshots': 'Vô hiệu hóa chụp màn hình',
    'form.configuration.settings.orientation': 'Khóa hướng',
    'form.configuration.settings.orientation.none': 'Không khóa',
    'form.configuration.settings.orientation.portrait': 'Dọc',
    'form.configuration.settings.orientation.landscape': 'Ngang',
    'form.configuration.settings.files.default.path': 'Đường dẫn mặc định trên thiết bị',
    'form.configuration.files.search.label': 'Tìm:',
    'form.configuration.files.action.upload': 'Tải lên',
    'form.configuration.files.action.remove': 'Xóa',
    'form.configuration.files.variables': 'Nội dung biến',
    'form.configuration.files.variables.hint': 'Chuỗi DEVICE_NUMBER, IMEI, CUSTOM* sẽ được thay bằng giá trị tương ứng',

    'form.password.title': 'Đổi mật khẩu',
    'form.password.label.user': 'Người dùng',
    'form.password.label.password.new': 'Mật khẩu mới',
    'form.password.label.password.new.placeholder': 'Nhập mật khẩu mới',
    'form.password.label.password.confirm': 'Xác nhận mật khẩu',
    'form.password.label.password.confirm.placeholder': 'Nhập lại mật khẩu mới',

    'form.application.type': 'Loại',
    'form.application.type.option.web': 'Trang web',
    'form.application.type.option.app': 'Ứng dụng',
    'form.application.pkg': 'ID gói',
    'form.application.from.file': 'Lấy từ tệp',
    'form.application.pkg.title': 'ID gói duy nhất',
    
    'form.application.version': 'Phiên bản',
    'form.application.version.title': 'Số nguyên dương, số lớn hơn là phiên bản mới hơn',
    'form.application.system': 'Hệ thống',
    'form.application.system.title': 'Ứng dụng hệ thống không thể bị gỡ bỏ khỏi thiết bị',
    'form.application.run.after.install': 'Chạy sau khi cài đặt',
    'form.application.run.after.install.title': 'Ứng dụng sẽ chỉ chạy nếu được chỉ định trong cài đặt MDM launcher',
    'form.application.url': 'URL',
    'form.application.url.title': 'Nếu loại là Web',
    'form.application.file': 'Tệp',
    
    'form.application.use.kiosk': 'Chạy trong chế độ kiosk',
    'form.application.use.kiosk.title': 'Chạy trong WebView toàn màn hình',
    'form.application.iconText': 'Nhãn',
    
    'form.application.icon': 'Biểu tượng',
    'form.application.icon.default': 'Mặc định',
    'form.application.icon.add': 'Thêm biểu tượng',

    'form.customer.name': 'Tên',
    'form.customer.name.placeholder': 'Nhập tên tổ chức',
    'form.customer.desc': 'Mô tả',
    'form.customer.desc.placeholder': 'Nhập mô tả tổ chức',
    'form.customer.prefix': 'Tiền tố',
    'form.customer.prefix.placeholder': 'Nhập tiền tố số thiết bị',
    'form.customer.device.configuration': 'Cấu hình thiết bị',
    'form.customer.expiry.time': 'Ngày hết hạn',
    
    'form.customer.device.limit': 'Giới hạn số thiết bị',
    
    'form.customer.status': 'Trạng thái',
    
    'form.customer.type': 'Loại',
    
    'form.device.number': 'Số thiết bị',
    
    'form.device.desc': 'Mô tả',
    
    'form.device.imei': 'IMEI',
    'form.device.phone.number': 'Số điện thoại',

    'form.file.name': 'Tên',
    
    'form.file.path': 'Đường dẫn trên thiết bị',
    'form.file.path.placeholder': 'Ví dụ: /sdcard/app',
    
    'form.file.file': 'Tệp',
    
    'form.group.name': 'Tên',
    'form.group.name.placeholder': 'Nhập tên nhóm',
    
    'form.role.name': 'Tên',
    'form.role.name.placeholder': 'Nhập tên vai trò',
    
    'form.user.name': 'Tên',
    'form.user.name.placeholder': 'Nhập tên người dùng',
    'form.user.login': 'Tên đăng nhập',
    'form.user.login.placeholder': 'Nhập tên đăng nhập',
    'form.user.email': 'Email',
    'form.user.email.placeholder': 'Nhập email',
    'form.user.password.new': 'Mật khẩu mới',
    'form.user.password.new.placeholder': 'Nhập mật khẩu mới',
    'form.user.password.confirm': 'Xác nhận mật khẩu',
    'form.user.password.confirm.placeholder': 'Nhập lại mật khẩu mới',
    'form.user.role': 'Vai trò',        
    
    'search.placeholder': 'Nhập từ khóa để tìm kiếm...',    

    'form.configuration.file.name': 'Tên tệp',
    'form.configuration.file.select': 'Chọn tệp',
    'form.configuration.file.create': '(tạo một tệp mới)',
    'form.configuration.file.description': 'Mô tả tệp',
    'form.configuration.file.description.placeholder': 'Tùy chọn, để thuận tiện cho bạn',
    'form.configuration.file.path': 'Đường dẫn trên thiết bị',
    'form.configuration.file.path.placeholder': 'Không bao gồm đường dẫn tới ổ đĩa, ví dụ: /my-app/image.jpg',
    'form.configuration.file.url': 'URL',
    'form.configuration.file.url.placeholder': 'Nếu tệp chỉ được lưu trữ trên nguồn bên ngoài',
    'form.configuration.file.file': 'Tệp',
    'form.configuration.file.action': 'Hành động',
    'form.configuration.file.action.prompt.1': 'Tải lên',
    'form.configuration.file.action.prompt.2': 'Xóa',
    'form.configuration.file.remove.prompt.1': 'Tệp này sẽ không còn được đồng bộ với các thiết bị nữa',
    'form.configuration.file.remove.prompt.2': 'Xóa tệp khỏi máy chủ',

    'form.password.length': 'Độ dài tối thiểu: ${length}. ',

    'form.application.type.option.intent': 'Hành động hệ thống',
    'form.application.intent': 'Hành động',
    'form.application.intent.placeholder': 'Chọn một hành động',
    'form.application.url.hint': 'Sử dụng file:///storage/emulated/0/... để tạo liên kết tới tệp và thư mục cục bộ',

    'form.application.pkg.placeholder': 'Ví dụ: com.android.camera',
    'form.application.disabled.arch': 'Theo phiên bản',
    'form.application.disabled.arch.title': 'Để thêm APK cho các kiến trúc CPU khác nhau, nhấp "Add", hoặc mở danh sách phiên bản ứng dụng',
    'form.application.arch': 'Mã native',
    'form.application.arch.title': 'Một số ứng dụng chứa mã được tối ưu cho kiến trúc CPU cụ thể. Trong trường hợp này, bạn cần tải lên hai APK (cho armeabi-v7a và arm64-v8a).',
    'form.application.arch.universal': 'Không (APK universal)',
    'form.application.arch.armeabi': 'Mã native cho armeabi-v7a',
    'form.application.arch.arm64': 'Mã native cho arm64-v8a',
    'form.application.arch.no.split': 'APK universal',
    'form.application.arch.split': 'Split APK',
    'form.application.arch.warning': 'APK này chỉ được tối ưu cho ${arch} và có thể không hoạt động trên tất cả thiết bị. Nên tải lên một APK khác được tối ưu cho kiến trúc CPU khác. Để dùng APK này trên mọi thiết bị, chọn "Universal APK".',
    'form.application.arch.success': 'Ứng dụng này chứa APK cho cả hai kiến trúc CPU',
    'form.application.version.exists': 'APK cho phiên bản này đã tồn tại',
    'form.application.url.armeabi': 'URL cho armeabi-v7a',
    'form.application.url.arm64': 'URL cho arm64-v8a',
    'form.application.name': 'Tên ứng dụng',
    'form.application.name.title': 'Bạn sẽ thấy tên ứng dụng trong danh sách. Khuyến nghị sử dụng tên duy nhất và mang thông tin rõ ràng.',
    'form.application.name.placeholder': 'Ví dụ: Camera (Android)',

    'form.application.version.placeholder': '0 cho các ứng dụng cài sẵn',

    'form.application.version.code': 'Mã phiên bản',
    'form.application.version.code.exists': 'Đã tồn tại phiên bản có cùng mã. Vui lòng báo lỗi này cho nhà phát triển ứng dụng.',

    'form.application.run.at.boot': 'Chạy khi khởi động',
    'form.application.run.at.boot.title': 'Bật tùy chọn này nếu cần chạy ứng dụng ở foreground sau khi khởi động. Tùy chọn này không ảnh hưởng tới tiến trình nền.',

    'form.application.url.disabled': 'URL được thiết lập cho từng phiên bản. Để thay đổi URL, đóng cửa sổ này và nhấp biểu tượng "Versions".',

    'form.application.auto.update': 'Tự động cập nhật',
    'form.application.auto.update.title': 'Bật tùy chọn này để cập nhật tất cả cấu hình nơi ứng dụng đã được cài. Chỉ dùng khi bạn chắc chắn 100% ứng dụng ổn định.',
    'form.application.showLabel': 'Hiển thị biểu tượng',
    'form.application.showLabel.title': 'Tùy chọn này xác định có hiển thị biểu tượng ứng dụng trong launcher hay không. Có thể bị ghi đè trong cấu hình.',

    'form.application.iconText.placeholder': '(mặc định)',
    'form.application.versions.title': 'Các phiên bản của ứng dụng',

    'form.application.setting.app': 'Ứng dụng',
    'form.application.setting.app.placeholder': 'Chọn một ứng dụng',
    'form.application.setting.name': 'Thuộc tính',
    'form.application.setting.value': 'Giá trị',
    'form.application.setting.comment': 'Ghi chú',
    'form.application.setting.type': 'Loại',
    'form.application.setting.readonly': 'Không thay đổi trên thiết bị',
    
    'form.application.configurations.app': 'Ứng dụng',
    'form.application.configurations.configs': 'Cấu hình',

    'form.configuration.copy.new.name': 'Tên mới',
    'form.configuration.copy.new.name.placeholder': 'Nhập tên cấu hình mới',

    'form.customer.admin.name': 'Tên quản trị viên',
    'form.customer.firstname.placeholder': 'Tên',
    'form.customer.lastname.placeholder': 'Họ',
    'form.customer.language': 'Ngôn ngữ',
    'form.customer.language.placeholder': 'Để trống cho tiếng Anh hoặc nhập hai chữ cái viết thường',
    'form.customer.apiKey': 'Khóa API',
    'form.customer.apiKey.placeholder': 'Nhập khóa API',

    'form.customer.copy.configuration': 'Sao chép cấu hình',
    'form.customer.copy.design': 'Sao chép thiết kế',

    'form.customer.size.limit': 'Giới hạn lưu trữ',
    'form.customer.size.limit.placeholder': 'Dung lượng (Mb)',

    'form.device.number.locked': 'Không thể thay đổi số vì lần thay đổi trước chưa hoàn tất.',
    'form.device.migration.warning': 'Số thiết bị sẽ bị thay đổi. Đảm bảo thiết bị đang bật và trực tuyến.',
    'form.device.number.hint': 'Không sử dụng ký tự đặc biệt',

    'form.device.groups': 'Nhóm',
    'form.device.config': 'Cấu hình',

    'form.update.device.config': 'Cấu hình',
    'form.update.device.action': 'Thao tác nhóm',
    'form.device.set.group': 'Thêm vào nhóm',
    'form.device.clear.group': 'Xóa khỏi nhóm',

    'form.file.description': 'Mô tả (tùy chọn)',
    'form.file.external': 'Bên ngoài',
    'form.file.external.title': 'Thay vì tải lên tệp, bạn có thể chỉ định URL trên nguồn bên ngoài',
    'form.file.external.url': 'URL',
    'form.file.external.url.placeholder': 'URL tệp trên nguồn bên ngoài',

    'form.file.device.path': 'Đường dẫn trên thiết bị',
    'form.file.device.path.placeholder': 'Đường dẫn tương đối tới /storage/emulated/0',
    'form.file.deleted': 'ĐÃ XÓA',
    'form.file.copy.link': 'Sao chép liên kết: ${link}',
    'form.file.configurations.file': 'Tệp',
    'form.file.configurations.configs': 'Cấu hình',
    'form.file.configurations.upload': 'Tải lên',

    'form.file.available': 'Dung lượng khả dụng: ${space} Mb',

    'form.file.apps.name': 'Tên ứng dụng',
    'form.file.apps.pkg': 'ID gói',
    'form.file.apps.version': 'Phiên bản',

    'form.role.permissions': 'Quyền',

    'form.user.all.devices.available': 'Tất cả thiết bị có sẵn',
    'form.user.available.groups': 'Nhóm thiết bị có sẵn',
    'form.user.all.configs.available': 'Tất cả cấu hình có sẵn',
    'form.user.available.configs': 'Cấu hình có sẵn',

    'form.user.password': 'Mật khẩu',

    'form.settings.hints.title': 'Gợi ý',

    'form.settings.plugins.title': 'Plugin đã sử dụng',

    'form.settings.common.title': 'Hiển thị bảng Thiết bị',
    'form.settings.common.visible.columns': 'Các cột hiển thị trong bảng "Thiết bị"',
    'form.settings.common.status': 'Trạng thái',
    'form.settings.common.role': 'Vai trò người dùng',
    'form.settings.common.date': 'Ngày trực tuyến cuối',
    'form.settings.common.device.number': 'Số thiết bị',
    'form.settings.common.imei': 'IMEI',
    'form.settings.common.phone.number': 'Số điện thoại',
    'form.settings.common.phone.model': 'Mẫu điện thoại',
    'form.settings.common.status.permissions': 'Trạng thái quyền',
    'form.settings.common.status.installation': 'Trạng thái cài đặt',
    'form.settings.common.status.files': 'Trạng thái tệp',
    'form.settings.common.config': 'Cấu hình',
    'form.settings.common.desc': 'Mô tả',
    'form.settings.common.group': 'Nhóm',
    'form.settings.common.launcher.version': 'Phiên bản launcher',
    'form.settings.common.battery.level': 'Mức pin',
    'form.settings.common.default.launcher': 'Chế độ nền',
    'form.settings.common.mdm.mode': 'Chế độ MDM',
    'form.settings.common.kiosk.mode': 'Chế độ kiosk',
    'form.settings.common.android.version': 'Phiên bản Android',
    'form.settings.common.enrollment.date': 'Ngày đăng ký',
    'form.settings.common.serial': 'Số sê-ri',
    'form.settings.common.publicip': 'Địa chỉ IP',

    'form.settings.design.title': 'Thiết kế mặc định',
    'form.settings.design.color.font': 'Màu nền',
    'form.settings.design.color.font.placeholder': 'Chọn màu',
    'form.settings.design.color.app.names': 'Màu tên ứng dụng',
    'form.settings.design.color.app.names.placeholder': 'Chọn màu',
    'form.settings.design.url.background.image': 'URL của ảnh nền',
    'form.settings.design.url.background.image.placeholder': 'Nhập URL ảnh nền',
    'form.settings.design.size.icon': 'Kích thước biểu tượng',
    'form.settings.design.size.icon.small': 'Nhỏ',
    'form.settings.design.size.icon.medium': 'Trung bình (+20%)',
    'form.settings.design.size.icon.large': 'Lớn (+40%)',
    'form.settings.design.desktop.header': 'Tiêu đề desktop',
    'form.settings.design.desktop.header.no': 'Không',
    'form.settings.design.desktop.header.device.id': 'Device ID',

    'form.settings.lang.title': 'Cài đặt ngôn ngữ',
    'form.settings.lang.use.default': 'Dùng ngôn ngữ mặc định',
    'form.settings.lang.use': 'Dùng ngôn ngữ',
    'form.settings.lang.en': 'English',
    'form.settings.lang.pt': 'Português',
    'form.settings.lang.ru': 'Русский',
    'form.settings.lang.fr': 'Français',
    'form.settings.lang.ar': 'عربي',
    'form.settings.lang.es': 'Español',
    'form.settings.lang.de': 'Deutsch',
    'form.settings.lang.cn': '繁体中文',
    'form.settings.lang.tw': '繁體中文',
    'form.settings.lang.ja': '日本',
    'form.settings.lang.tr': 'Türkçe',
    'form.settings.lang.vi': 'Tiếng Việt',
    'form.settings.lang.it': 'Italiano',

    'form.settings.misc.title': 'Cài đặt khác',
    'form.settings.misc.phone.format': 'Định dạng số điện thoại',
    'form.settings.misc.phone.format.placeholder': '+9 (999) 999-99-99',
    'form.settings.misc.custom.property.name.1': 'Thuộc tính tùy chỉnh #1',
    'form.settings.misc.custom.property.name.2': 'Thuộc tính tùy chỉnh #2',
    'form.settings.misc.custom.property.name.3': 'Thuộc tính tùy chỉnh #3',
    'form.settings.misc.custom.property.multiline': 'Nhiều dòng',
    'form.settings.misc.custom.property.send': 'Gửi tới thiết bị',
    'form.settings.misc.custom.property.name.placeholder': 'Nhập tên cho thuộc tính tùy chỉnh',
    'form.settings.misc.create.new.devices': 'Thêm thiết bị khi truy cập lần đầu',
    'form.settings.misc.new.device.config': 'Cấu hình thiết bị mới',
    'form.settings.misc.new.device.group': 'Nhóm thiết bị mới',
    'form.settings.misc.send.description': 'Gửi mô tả tới thiết bị',
    'form.settings.misc.password.length': 'Độ dài mật khẩu tối thiểu',
    'form.settings.misc.password.strength': 'Độ mạnh mật khẩu',
    'form.settings.misc.password.none': 'Chưa chỉ định (bất kỳ ký tự nào)',
    'form.settings.misc.password.alphanumeric': 'Chữ hoa, chữ thường và chữ số',
    'form.settings.misc.password.specialchar': 'Chữ hoa, chữ thường, chữ số và ký tự đặc biệt',
    'form.settings.misc.password.reset': 'Người dùng nên đặt lại mật khẩu',
    'form.settings.misc.idle.logout': 'Đăng xuất khi không hoạt động',
    'form.settings.misc.idle.logout.never': 'Không bao giờ',
    'form.settings.misc.idle.logout.1': '5 phút',
    'form.settings.misc.idle.logout.2': '10 phút',
    'form.settings.misc.idle.logout.3': '30 phút',
    'form.settings.misc.idle.logout.4': '1 giờ',
    'form.settings.security.title': 'Cài đặt bảo mật',

    'idle.logout.message': 'Bạn sẽ bị đăng xuất sau ${sec} giây do không hoạt động',
    'idle.logout.resume': 'Tôi vẫn ở đây!',

    'form.settings.groups.title': 'Nhóm',
    'form.settings.groups.search.placeholder': 'Tìm nhóm',

    'form.settings.users.title': 'Người dùng',
    'form.settings.users.search.placeholder': 'Tìm người dùng',

    'form.settings.roles.title': 'Vai trò người dùng',

    'form.settings.icons.title': 'Biểu tượng',
    'form.settings.icons.search.placeholder': 'Tìm biểu tượng',

    'form.qr.device.number': 'Số thiết bị',
    'form.qr.auto.create': 'Thêm vào danh sách thiết bị nếu chưa tồn tại',
    'form.qr.number.use': 'Gán số thiết bị',
    'form.qr.number.use.request': 'Giá trị người dùng',
    'form.qr.number.use.imei': 'IMEI',
    'form.qr.number.use.serial': 'Số sê-ri',
    'form.qr.number.hint': 'Xóa số thiết bị để kích hoạt gán số tự động',
    'form.qr.groups': 'Thêm vào nhóm',
    'form.qr.button.json': 'Lấy JSON',
    'form.qr.device.number.placeholder': 'Nhập ID thiết bị ...',
    'form.qr.code.image.alt': 'Mã QR',

    'form.password.reset.title': 'Vui lòng đặt mật khẩu mới',
    'form.password.reset.invalid': 'Xin lỗi, liên kết đặt lại mật khẩu này không hợp lệ',
    'form.password.reset.submit': 'Đặt mật khẩu',

    'form.two.factor.auth.title': 'Xác thực hai yếu tố',
    'form.two.factor.auth.hint': 'Để hoàn tất đăng ký, hãy cài ứng dụng Authenticator trên điện thoại, quét mã QR, tạo và nhập mã xác thực.',
    'form.two.factor.auth.code.invalid': 'Mã xác thực không hợp lệ!',
    'form.two.factor.auth.code': 'Mã xác thực',
    'form.two.factor.auth.code.hint': 'Mã 6 chữ số từ ứng dụng Authenticator',
    'form.two.factor.auth.code.error': 'Mã phải là số 6 chữ số',
    'form.two.factor.auth.verify': 'Xác minh',
    'form.two.factor.auth.settings.hint': 'Để bật xác thực hai yếu tố, hãy cài ứng dụng Authenticator trên điện thoại, quét mã QR, tạo và nhập mã xác thực.',
    'form.two.factor.auth.set': 'Xác thực hai yếu tố đã được bật',
    'form.two.factor.auth.reset': 'Xác thực hai yếu tố đã bị tắt',
    'form.two.factor.auth.off.confirm': 'Bạn có muốn tắt xác thực hai yếu tố không? Sau khi bật lại, tất cả các Authenticator sẽ không còn hợp lệ.',

    'form.profile.title': 'Đổi mật khẩu',
    'form.profile.password.old': 'Mật khẩu cũ',
    'form.profile.password.old.placeholder': 'Nhập mật khẩu cũ',
    'form.profile.password.new': 'Mật khẩu mới',
    'form.profile.password.new.placeholder': 'Nhập mật khẩu mới',
    'form.profile.password.confirm': 'Xác nhận',
    'form.profile.password.confirm.placeholder': 'Nhập lại mật khẩu mới',

    'tab.customers': 'Tổ chức',
    'tab.common.applications': 'Ứng dụng chia sẻ',

    'tab.devices': 'Thiết bị',
    'tab.applications': 'Ứng dụng',
    'tab.configurations': 'Cấu hình',
    'tab.files': 'Tệp',
    'tab.default.design': 'Thiết kế mặc định',
    'tab.common.settings': 'Hiển thị bảng Thiết bị',
    'tab.users': 'Người dùng',
    'tab.roles': 'Vai trò',
    'tab.groups': 'Nhóm',
    'tab.icons': 'Biểu tượng',
    'tab.language': 'Cài đặt chung và ngôn ngữ',
    'tab.license': 'Giấy phép',
    'tab.hints': 'Gợi ý',
    'tab.plugins': 'Plugin',
    
    'tab.configeditor.common.settings': 'Cài đặt chung',
    'tab.configeditor.design.settings': 'Cài đặt thiết kế',
    'tab.configeditor.applications': 'Ứng dụng',
    'tab.configeditor.mdm.settings': 'Cài đặt MDM',
    'tab.configeditor.app.settings': 'Cài đặt ứng dụng',
    'tab.configeditor.files': 'Tệp',

    'search.placeholder.file': 'Tìm tệp',
    'search.placeholder.configuration': 'Tìm cấu hình',
    'search.placeholder.customer': 'Tìm tổ chức',
    'search.placeholder.application': 'Tìm ứng dụng',
    'search.placeholder.application.setting': 'Tìm cài đặt ứng dụng',
    'search.placeholder.device': 'Tìm thiết bị',
    'search.placeholder.address': 'Tìm địa chỉ',
    'search.placeholder.point': 'Tìm vị trí',
    'search.placeholder.message': 'Tìm tin nhắn',

    'search.placeholder.from': 'Từ ...',
    'search.placeholder.to': 'Đến ...',
    'search.placeholder.user': 'Nhập tên người dùng',

    'table.heading.customer.name': 'Tên',
    'table.heading.customer.desc': 'Mô tả',
    'table.heading.customer.registration.time': 'Đã đăng ký',
    'table.heading.customer.last.login.time': 'Đăng nhập lần cuối',
    'table.heading.customer.actions': 'Hành động',
    'table.heading.customer.type': 'Loại',
    'table.heading.customer.expiry.time': 'Hết hạn',
    'table.heading.customer.device.limit': 'Giới hạn',
    'table.heading.customer.status': 'Trạng thái',

    'customer.new': 'Mới',
    'customer.active': 'Đang hoạt động',
    'customer.need.followup': 'Cần theo dõi',
    'customer.followup.sent': 'Đã gửi nhắc',
    'customer.internal.test': 'Kiểm tra nội bộ',
    'customer.developer': 'Nhà phát triển',
    'customer.difficult': 'Khó',
    'customer.pause': 'Tạm dừng',
    'customer.inactive': 'Không đăng nhập',
    'customer.abandon': 'Bỏ',
    'customer.onpremise': 'Dùng thử On-premise',
    'customer.denial': 'Từ chối',
    'customer.client': 'Khách hàng',

    'table.heading.configuration.name': 'Tên',
    'table.heading.configuration.desc': 'Mô tả',
    'table.heading.configuration.actions': 'Hành động',

    'table.heading.application.setting.app.pkg': 'ID gói',
    'table.heading.application.setting.app.name': 'Tên ứng dụng',
    'table.heading.application.setting.name': 'Thuộc tính',
    'table.heading.application.setting.value': 'Giá trị',
    'table.heading.application.setting.comment': 'Ghi chú',
    'table.heading.application.setting.lastUpdate': 'Ngày tạo',

    'table.heading.file.url': 'URL',
    'table.heading.file.devicepath': 'Đường dẫn trên thiết bị',
    'table.heading.file.description': 'Mô tả tệp',
    'table.heading.file.action': 'Hành động',
    'table.heading.file.lastUpdate': 'Ngày tạo',
    
    'table.heading.application.pkg': 'ID gói',
    'table.heading.application.name': 'Tên ứng dụng',
    'table.heading.application.version': 'Phiên bản',
    'table.heading.application.url': 'URL',
    'table.heading.application.label': 'Biểu tượng',
    'table.heading.application.actions': 'Hành động',
    'table.heading.application.order': 'Thứ tự',

    'table.heading.device.status': 'Trạng thái',
    'table.heading.device.date': 'Ngày',
    'table.heading.device.device.number': 'Số thiết bị',
    'table.heading.device.imei': 'IMEI',
    'table.heading.device.phone.number': 'Số điện thoại',
    'table.heading.device.phone.model': 'Mẫu điện thoại',
    'table.heading.device.status.permissions': 'Trạng thái quyền',
    'table.heading.device.status.installation': 'Trạng thái cài đặt',
    'table.heading.device.status.files': 'Trạng thái tệp',
    'table.heading.device.configuration': 'Cấu hình',
    'table.heading.device.desc': 'Mô tả',
    'table.heading.device.group': 'Nhóm',
    'table.heading.device.launcher.version': 'Phiên bản launcher',
    'table.heading.device.battery.level': 'Mức pin',
    'table.heading.device.default.launcher': 'Chế độ nền',
    'table.heading.device.mdm.mode': 'Chế độ MDM',
    'table.heading.device.kiosk.mode': 'Chế độ kiosk',
    'table.heading.device.android.version': 'Phiên bản Android',
    'table.heading.device.enrollment.date': 'Đã đăng ký',
    'table.heading.device.serial': 'Số sê-ri',
    'table.heading.device.publicip': 'Địa chỉ IP',
    'table.heading.device.actions': 'Hành động',

    'table.heading.group.name': 'Tên',
    'table.heading.group.actions': 'Hành động',

    'table.heading.role.name': 'Tên',
    'table.heading.role.actions': 'Hành động',

    'table.heading.file.name': 'Tên tệp',
    'table.heading.file.comment': 'Mô tả',
    'table.heading.file.device.path': 'Đường dẫn trên thiết bị',
    'table.heading.file.update.time': 'Cập nhật lúc',
    'table.heading.file.external': 'Bên ngoài',
    'table.heading.file.variable': 'Biến',
    'table.heading.file.remove': 'Xóa',
    'table.heading.file.remove.hint': 'Buộc xóa tệp khỏi bộ nhớ thiết bị',
    'table.heading.file.path': 'Đường dẫn',
    'table.heading.file.address': 'Địa chỉ',
    'table.heading.file.size': 'Kích thước',
    'table.heading.file.actions': 'Hành động',

    'table.heading.users.login': 'Đăng nhập',
    'table.heading.users.name': 'Tên',
    'table.heading.users.role': 'Vai trò',
    'table.heading.users.actions': 'Hành động',

    'table.heading.common.apps.customer': 'Tổ chức',
    'table.heading.common.apps.pkg': 'ID gói',
    'table.heading.common.apps.name': 'Tên ứng dụng',
    'table.heading.common.apps.version': 'Phiên bản',
    'table.heading.common.apps.url': 'URL',
    'table.heading.common.apps.label': 'Biểu tượng',
    'table.heading.common.apps.actions': 'Hành động',

    'notfound.devices': 'Không có thiết bị để hiển thị.',
    'notfound.files':'Danh sách tệp rỗng.',
    'notfound.configurations': 'Không tìm thấy cấu hình.',
    'notfound.customers': 'Không tìm thấy tổ chức.',
    'notfound.common.apps': 'Không có ứng dụng để hiển thị.',
    'notfound.applications': 'Không tìm thấy ứng dụng',
    'notfound.groups':'Không tìm thấy nhóm. Thử truy vấn khác.',
    'notfound.users':'Không tìm thấy người dùng. Thử truy vấn khác.',
    'notfound.apps.for.display': 'Không có ứng dụng để hiển thị.',
    'notfound.app.versions.for.display': 'Không có phiên bản để hiển thị.',
    'notfound.roles':'Danh sách vai trò rỗng.',
    'notfound.icons':'Danh sách biểu tượng rỗng.',

    'format.date.header': 'HH:mm dd/MM/yyyy',

    'menu.about': 'Giới thiệu',
    'menu.profile': 'Hồ sơ',
    'menu.panel.master': 'Bảng chính (Master Panel)',
    'menu.panel.main': 'Bảng chính',
    'menu.logout': 'Đăng xuất',
    'menu.functions': 'Chức năng',
    'menu.settings': 'Cài đặt',
    'menu.show.hints': 'Hiển thị gợi ý',

    'plugin.name.not.specified': '<< Tên chức năng chưa được chỉ định >>',

    'breadcrumb.summary': 'Tổng quan',
    'breadcrumb.devices': 'Thiết bị',
    'breadcrumb.applications': 'Ứng dụng',
    'breadcrumb.configurations': 'Cấu hình',
    'breadcrumb.files': 'Tệp',
    'breadcrumb.default.design': 'Thiết kế mặc định',
    'breadcrumb.common.settings': 'Hiển thị bảng Thiết bị',
    'breadcrumb.language.settings': 'Ngôn ngữ và cài đặt khác',
    'breadcrumb.license.settings': 'Giấy phép',
    'breadcrumb.users': 'Người dùng',
    'breadcrumb.groups': 'Nhóm',
    'breadcrumb.hints': 'Gợi ý',
    'breadcrumb.plugins': 'Plugin',
    'breadcrumb.config.details': 'Chi tiết',
    'breadcrumb.application.versions': 'Phiên bản',

    'app.name': 'Headwind MDM',
    'app.vendor.name': "h-mdm.com",
    'app.vendor.link': "https://h-mdm.com",
    'app.description': 'là một hệ thống quản lý thiết bị di động mã nguồn mở',
    'app.title': 'Bảng ${appName} Web',

    'box.show.my.apps.only': 'Chỉ hiển thị ứng dụng của tôi',
    'configuration.app.version.upgrade.message': 'Đã cài ${installedVersion}, có phiên bản ${latestVersion}',

    'about.line.1': 'Bảng điều khiển ${appName}',
    'about.line.2': 'MDM mã nguồn mở cho Android',
    'about.line.3': 'Phiên bản ${versionNumber}',
    'about.line.4': 'Các plugin đã cài đặt',

    'common.app.clarification': 'Ứng dụng này công khai và không thể chỉnh sửa. Để thêm phiên bản khác của ứng dụng, vui lòng liên hệ quản trị viên.',

    'qrcode.help.line1': 'Để cấu hình thiết bị Android (phiên bản 7 trở lên) ở chế độ quản lý (corporate):',
    'qrcode.help.line2': 'Khôi phục thiết bị về cài đặt gốc',
    'qrcode.help.line3': 'Chạm 7 lần vào bất kỳ chỗ nào trên màn hình khởi động (bạn sẽ vào chế độ quét mã QR ẩn)',
    'qrcode.help.line4': 'Làm theo hướng dẫn trên thiết bị: chấp nhận điều khoản, kết nối Wi-Fi, quét mã QR này',
    'qrcode.help.line5': 'Mã QR có thể chứa ID thiết bị cho ${appName} (để bạn không phải nhập trên thiết bị). Để nhúng ID thiết bị vào mã QR, nhập ID thiết bị ở màn hình này và nhấn "Renew".',

    'form.configuration.app.version.select.select.title': 'Chọn phiên bản để cài',
    'form.configuration.app.version.select.version.check.off': 'Tắt kiểm tra phiên bản',
    'form.configuration.app.version.select.upgrade.warning': 'Nâng cấp ứng dụng "${v1}" lên phiên bản "${v3}" cho cấu hình "${v2}"?',
    'form.configuration.app.version.select.downgrade.warning': 'Hạ cấp phiên bản SẼ XÓA TẤT CẢ NHỮNG ỨNG DỤNG NÀY trên mọi thiết bị! Hạ phiên bản ứng dụng "${v1}" xuống "${v2}"? ',

    'hint.step.1': 'Nhấp vào đây để bắt đầu ghi danh thiết bị',
    'hint.step.2': 'Nhấp vào đây để mở mã QR',
    'hint.step.3': 'Nhấp vào đây để xem cách mở trình quét QR trên thiết bị',
    'hint.step.4': 'Tìm ID thiết bị có sẵn trong tab «Devices». Nhấp «Renew» để đưa vào mã QR.',

    'ie.browser.notice.1': 'Rất tiếc, Internet Explorer không được hỗ trợ.',
    'ie.browser.notice.2': 'Trình duyệt được khuyến nghị cho ${appName} - <a href="https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop">Chrome</a>.',

    'form.resolved.duplicate.pkg.text1': 'Package ID "${pkg}" đã được sử dụng bởi các ứng dụng được liệt kê bên dưới.',
    'form.resolved.duplicate.pkg.text2': 'Bạn muốn thêm ứng dụng mới hay thêm phiên bản mới cho ứng dụng hiện có?',
    'form.resolved.duplicate.pkg.text3': 'Phiên bản mới cho',
    'form.resolved.duplicate.pkg.text4': 'Package ID "${pkg}" đã được sử dụng bởi các ứng dụng ${apps}',
    'form.resolved.duplicate.pkg.text5': 'Bạn có chắc muốn thay đổi Package ID?',

    'tooltip.usage.byconfigurations': 'Được dùng bởi các cấu hình',
    'tooltip.usage.byapps': 'Được dùng bởi các ứng dụng',
    'tooltip.usage.byicons': 'Được dùng bởi các biểu tượng',

    'form.devices.label.params.more': 'Thêm tham số',
    'form.devices.label.params.less': 'Bớt tham số',
    'form.devices.label.installation.status': 'Trạng thái cài đặt',
    "format.devices.date.createTime": "dd/MM/yyyy HH:mm:ss",
    "format.devices.date.datePicker": "dd-MM-yyyy",
    'form.devices.fast.search': 'Tìm nhanh theo số',

    'form.devices.selection.install.status.default': 'Trạng thái cài đặt ...',
    'form.devices.selection.install.status.all': 'Tất cả',
    'form.devices.selection.install.status.success': 'Thành công',
    'form.devices.selection.install.status.version.mismatch': 'Không khớp phiên bản',
    'form.devices.selection.install.status.failure': 'Thất bại',
    'form.devices.selection.imei.changed': 'IMEI vừa thay đổi',

    'search.placeholder.launcher.version': 'Phiên bản Launcher',
    'error.date.range.invalid': 'Khoảng thời gian không hợp lệ',

    'form.selection.status.any': 'Bất kỳ giá trị nào',
    'form.selection.status.all': 'Tất cả',
    'form.selection.status.yes': 'Có',
    'form.selection.status.no': 'Không',

    'form.devices.selection.status': 'Trạng thái ...',
    'form.devices.selection.online': 'Trực tuyến',
    'form.devices.selection.offline': 'Ngoại tuyến',
    'form.devices.selection.number': 'Nhập số',

    'form.devices.selection.online.status.custom': 'Nhập thời gian',
    'form.devices.selection.online.status.1': '15 minutes',
    'form.devices.selection.online.status.2': '30 minutes',
    'form.devices.selection.online.status.3': '1 hour',
    'form.devices.selection.online.status.4': '2 hours',
    'form.devices.selection.online.status.5': '6 hours',
    'form.devices.selection.online.status.6': '1 day',
    'form.devices.selection.online.status.7': '2 days',
    'form.devices.selection.online.status.8': '3 days',
    'form.devices.selection.online.status.9': '1 week',
    'form.devices.selection.online.status.10': '1 month',

    'form.devices.selection.online.status.label': 'minute(s)',
    'form.devices.status.ago': 'trước',
    'form.devices.status.minutes': 'm',
    'form.devices.status.hours': 'h',
    'form.devices.status.days': 'd',
    'form.devices.status.weeks': 'week(s)',
    'form.devices.status.months': 'mon',
    'form.devices.status.years': 'year(s)',

    'customer.type.demo': 'Demo',
    'customer.type.small': 'Professional',
    'customer.type.corporate': 'Enterprise',
    'customer.type.master': 'Primary',

    'customer.type.options.all': 'Tất cả loại',
    'customer.status.options.all': 'Tất cả trạng thái',

    'account.expiring': 'Tài khoản của bạn sẽ hết hạn trong ${days} ngày. Vui lòng liên hệ người bán để gia hạn tài khoản.',
    'account.expired.short': 'Tài khoản của bạn đã hết hạn!',
    'account.expired': 'Tài khoản của bạn đã hết hạn. Vui lòng liên hệ người bán để gia hạn tài khoản.',
    'device.limit.achieved': 'Không thể thêm thiết bị vì bạn đã đạt giới hạn. Vui lòng xóa một số thiết bị hoặc liên hệ người bán để mở rộng giới hạn.',

    'menu.updates': 'Kiểm tra cập nhật',
    'updates.title': 'Cập nhật',
    'updates.disabled.custom': 'Phiên bản tùy chỉnh, vui lòng cập nhật thủ công',
    'updates.disabled.not_master': 'Yêu cầu nhà cung cấp hosting cập nhật',
    'updates.disabled.multiple': 'Nhiều phiên bản ứng dụng, vui lòng cập nhật thủ công',
    'updates.disabled.error': 'Lỗi máy chủ nội bộ',
    'updates.disabled.download': 'Lỗi khi tải cập nhật',
    'updates.application': 'Ứng dụng',
    'updates.current.version': 'Phiên bản hiện tại',
    'updates.available.version': 'Phiên bản có sẵn',
    'updates.downloaded': 'Đã tải về',
    'updates.auto.update': 'Tự động cập nhật ứng dụng di động (dùng thận trọng trong môi trường sản xuất!)',
    'updates.enable.stats': 'Gửi thống kê sử dụng cho nhà cung cấp để cải thiện hiệu năng',
    'updates.get': 'Lấy cập nhật',
    'updates.checking': 'Đang kiểm tra cập nhật...',
    'updates.getting': 'Đang lấy cập nhật...',
    'updates.success': 'Cập nhật hoàn tất',
    'updates.web.hint': 'Để hoàn tất cập nhật web app, chạy script "/opt/hmdm/update-web-app.sh" trên SSH console',

    'permission.edit_device_app_settings': 'Quản lý cài đặt ứng dụng theo thiết bị',
    'permission.plugins_customer_access_management': 'Quản lý plugin có sẵn',
    'permission.plugin_audit_access': 'Xem nhật ký kiểm toán',
    'permission.plugin_contacts_access': 'Quản lý danh bạ',
    'permission.plugin_deviceexport_access': 'Xuất thiết bị',
    'permission.plugin_deviceimport_access': 'Nhập thiết bị',
    'permission.plugin_deviceinfo_access': 'Xem thông tin chi tiết thiết bị',
    'permission.plugin_devicelocations_access': 'Xem thiết bị trên bản đồ',
    'permission.plugin_devicelocations_settings_access': 'Cấu hình plugin bản đồ',
    'permission.plugin_devicelog_access': 'Xem nhật ký thiết bị',
    'permission.plugin_devicereset_access': 'Reset và khởi động lại thiết bị',
    'permission.plugin_licensing_access': 'Truy cập giấy phép (không khuyến nghị)',
    'permission.plugin_messaging_send': 'Gửi tin nhắn',
    'permission.plugin_messaging_delete': 'Xóa tin nhắn đã gửi',
    'permission.plugin_photo_remove_photo': 'Xóa ảnh',
    'permission.settings': 'Quản lý cài đặt',
    'permission.configurations': 'Xem cấu hình',
    'permission.edit_devices': 'Sửa thông tin thiết bị',
    'permission.edit_device_desc': 'Sửa mô tả thiết bị',
    'permission.enroll_devices': 'Ghi danh thiết bị qua mã QR',
    'permission.plugin_apuppet_access': 'Điều khiển từ xa',
    'permission.plugin_knox_access': 'Plugin Knox',
    'permission.add_config': 'Thêm cấu hình',
    'permission.copy_config': 'Sao chép cấu hình',
    'permission.plugin_openvpn_access': 'Plugin OpenVPN',
    'permission.plugin_photo_access': 'Plugin ảnh',
    'permission.push_api': 'Truy cập Push API',
    'permission.plugin_urlfilter_access': 'Lọc URL',
    'permission.plugin_push_send': 'Gửi Push',
    'permission.plugin_push_delete': 'Xóa Push',
    'permission.get_updates': 'Kiểm tra cập nhật',
    'permission.plugin_xtra_access': 'Yêu cầu phiên bản Premium',
    'permission.applications': 'Xem ứng dụng',
    'permission.edit_applications': 'Quản lý ứng dụng',
    'permission.edit_application_versions': 'Quản lý phiên bản ứng dụng',
    'permission.files': 'Xem tệp',
    'permission.edit_files': 'Quản lý tệp',

    'yes': 'có',
    'no': 'không'
};
